In [93]:
import os
import json
import polars as pl

In [95]:
data_raw = "data_raw/segments"

In [97]:
os.makedirs(data_raw, exist_ok=True)

In [99]:
done = [x.replace('.json','') for x in os.listdir(data_raw)]

In [101]:
source_folders = os.listdir('downloads/segments')

In [103]:
source_folders

['2024-12-24',
 '2024-12-25',
 '2024-12-26',
 '2024-12-27',
 '2024-12-28',
 '2024-12-29',
 '2024-12-30',
 '2024-12-31',
 '2025-01-01',
 '2025-01-02',
 '2025-01-03',
 '2025-01-04',
 '2025-01-05',
 '2025-01-06',
 '2025-01-07']

In [105]:
for s in source_folders:
    if s not in done:
        print(s)
        day = []
        for f in os.listdir(f'downloads/segments/{s}'):
            time = f.split('_')[1].split('.')[0]
            with open(os.path.join(f'downloads/segments/{s}', f), 'r', encoding='utf-8') as file:
                segment = json.loads(file.read())
                segment['date'] = time
                day.append(segment)
        df = pl.DataFrame(day)
        df.write_parquet(os.path.join(data_raw, f'{s}.parquet'))
        with open(os.path.join(data_raw, f'{s}.json'), 'w+', encoding='utf-8') as export:
            export.write(json.dumps(day))

In [155]:
overview = df.group_by(["name","activity_type","country","city","distance","total_elevation_gain"]).agg(pl.col("effort_count").max()).sort("effort_count", descending=True)
overview

shape: (261, 7)
┌───────────────────┬───────────────┬────────────────┬──────────────────┬──────────┬──────────────────┬──────────────┐
│ name              ┆ activity_type ┆ country        ┆ city             ┆ distance ┆ total_elevation_ ┆ effort_count │
│ ---               ┆ ---           ┆ ---            ┆ ---              ┆ ---      ┆ gain             ┆ ---          │
│ str               ┆ str           ┆ str            ┆ str              ┆ f64      ┆ ---              ┆ i64          │
│                   ┆               ┆                ┆                  ┆          ┆ f64              ┆              │
╞═══════════════════╪═══════════════╪════════════════╪══════════════════╪══════════╪══════════════════╪══════════════╡
│ Richmond ITT1     ┆ Ride          ┆ United Kingdom ┆ London           ┆ 589.3    ┆ 7.2              ┆ 4625714      │
│ Box Hill 2.2k     ┆ Ride          ┆ United Kingdom ┆ Mole Valley      ┆ 2296.62  ┆ 119.1            ┆ 1415736      │
│                   ┆               ┆                ┆ District,        ┆          ┆                  ┆              │
│                   ┆               ┆                ┆ Surrey, …        ┆          ┆                  ┆              │
│ Die Eine Runde    ┆ Ride          ┆ Czech Republic ┆ Brno             ┆ 380.0    ┆ 0.0              ┆ 1089698      │
│ Overtake the      ┆ Run           ┆ United Kingdom ┆ London           ┆ 591.8    ┆ 2.2              ┆ 663772       │
│ Boris Bikes       ┆               ┆                ┆                  ┆          ┆                  ┆              │
│ Třebešín-dráha K  ┆ Ride          ┆ Czech Republic ┆ Prague           ┆ 347.2    ┆ 0.0              ┆ 402245       │
│ Alpe d'Huez       ┆ Ride          ┆ France         ┆ Le Bourg         ┆ 12024.9  ┆ 1047.3           ┆ 336375       │
│                   ┆               ┆                ┆ D'Oisans         ┆          ┆                  ┆              │
│ Sa Calobra - Coll ┆ Ride          ┆ Spain          ┆ Escorca          ┆ 9416.77  ┆ 659.8            ┆ 323413       │
│ dels Reis         ┆               ┆                ┆                  ┆          ┆                  ┆              │
│ Opičí Časovka,    ┆ Ride          ┆ Czech Republic ┆ Prague           ┆ 1390.1   ┆ 6.0              ┆ 323017       │
│ Podolská vodárn…  ┆               ┆                ┆                  ┆          ┆                  ┆              │
│ Prostějov kolo    ┆ Ride          ┆ Czech Republic ┆ Prostějov        ┆ 311.1    ┆ 0.0              ┆ 251263       │
│ dráha P           ┆               ┆                ┆                  ┆          ┆                  ┆              │
│ Koppenberg        ┆ Ride          ┆ Belgium        ┆ Oudenaarde       ┆ 556.595  ┆ 63.1             ┆ 245118       │
│ Mont Ventoux (par ┆ Ride          ┆ France         ┆ Bédoin           ┆ 20741.8  ┆ 1569.4           ┆ 242104       │
│ Bedoin)           ┆               ┆                ┆                  ┆          ┆                  ┆              │
│ Stelvio - Bormio  ┆ Ride          ┆ Italy          ┆ null             ┆ 2982.1   ┆ 5.4              ┆ 235604       │
│ Turn Downhill     ┆               ┆                ┆                  ┆          ┆                  ┆              │
│ Zweite hup u ZOO  ┆ Ride          ┆ Czechia        ┆ Praha-Troja      ┆ 314.1    ┆ 6.6              ┆ 234009       │
│ Zbraslav -        ┆ Ride          ┆ Czechia        ┆ Zbraslav         ┆ 2359.0   ┆ 5.7              ┆ 217003       │
│ Komořany          ┆               ┆                ┆                  ┆          ┆                  ┆              │
│ Stadion Na        ┆ Run           ┆ Czechia        ┆ Prague           ┆ 420.9    ┆ 0.0              ┆ 215805       │
│ Děkance           ┆               ┆                ┆                  ┆          ┆                  ┆              │
│ Lužánky rovinka   ┆ Run           ┆ Czechia        ┆ Brno-střed       ┆ 268.9    ┆ 3.8              ┆ 180145       │
│ Šlechtovka -      ┆ Run           ┆ Czechia        ┆ Praha 7          ┆ 225.4    ┆ 0.0              ┆ 156359       │
│ finální rovinka   ┆               ┆                ┆                  ┆          ┆                  ┆              │
│ time trial at     ┆ Ride          ┆ Czech Republic ┆ Brno             ┆ 1438.1   ┆ 20.6             ┆ 141864       │
│ Svratka           ┆               ┆                ┆                  ┆          ┆                  ┆              │
│ Passo Stelvio     ┆ Ride          ┆ Italy          ┆ null             ┆ 23600.3  ┆ 1840.3           ┆ 139224       │
│ Od posledního     ┆ Ride          ┆ Czechia        ┆ Bílovice nad     ┆ 827.8    ┆ 6.2              ┆ 124486       │
│ tunelu do Bílovi… ┆               ┆                ┆ Svitavou         ┆          ┆                  ┆              │
│ VUT horní dráha   ┆ Run           ┆ Czechia        ┆ Brno             ┆ 405.2    ┆ 0.0              ┆ 109048       │
│ 400m              ┆               ┆                ┆                  ┆          ┆                  ┆              │
│ Col du Tourmalet  ┆ Ride          ┆ France         ┆ Luz Saint        ┆ 18827.5  ┆ 1397.7           ┆ 99930        │
│ (par Luz-St-S…    ┆               ┆                ┆ Sauveur          ┆          ┆                  ┆              │
│ Vítkov up sprint  ┆ Run           ┆ Czechia        ┆ Prague           ┆ 118.2    ┆ 6.0              ┆ 86623        │
│ Pražačka 320      ┆ Run           ┆ Czechia        ┆ Prague           ┆ 343.3    ┆ 0.0              ┆ 75242        │
│ Viveros-Paseo     ┆ Run           ┆ Spain          ┆ Valencia         ┆ 1722.9   ┆ 18.0             ┆ 73160        │
│ alameda           ┆               ┆                ┆                  ┆          ┆                  ┆              │
│ TJ Sokol okruh    ┆ Run           ┆ Czech Republic ┆ Prague           ┆ 418.8    ┆ 5.7              ┆ 72849        │
│ Kolo na stadionu  ┆ Run           ┆ Czechia        ┆ Třebíč           ┆ 475.6    ┆ 6.2              ┆ 69590        │
│ v Třebíči         ┆               ┆                ┆                  ┆          ┆                  ┆              │
│ Srbsko - Hlásná   ┆ Ride          ┆ Czechia        ┆ Srbsko           ┆ 5736.1   ┆ 13.5             ┆ 61463        │
│ Třebáň            ┆               ┆                ┆                  ┆          ┆                  ┆              │
│ Stezka do Zlina   ┆ Ride          ┆ Czech Republic ┆ Zlin             ┆ 1368.28  ┆ 23.1348          ┆ 60477        │
│ Rokytka od myčky  ┆ Ride          ┆ Czechia        ┆ Praha 14         ┆ 1823.0   ┆ 4.0              ┆ 59027        │
│ Dráha Plzeň okruh ┆ Ride          ┆ Czechia        ┆ Pilsen           ┆ 361.9    ┆ 0.0              ┆ 54673        │
│ P                 ┆               ┆                ┆                  ┆          ┆                  ┆              │
│ Sptint pod Býčí   ┆ Ride          ┆ Czechia        ┆ Olomučany        ┆ 778.8    ┆ 0.0              ┆ 53348        │
│ skálou            ┆               ┆                ┆                  ┆          ┆                  ┆              │
│ 400 m - atletický ┆ Run           ┆ Czechia        ┆ Olomouc          ┆ 400.0    ┆ 2.9              ┆ 52422        │
│ okruh - Loko…     ┆               ┆                ┆                  ┆          ┆                  ┆              │
│ Hvězda flat       ┆ Run           ┆ Czech Republic ┆ Praha 6          ┆ 1001.15  ┆ 11.426           ┆ 49911        │
│ tenis 1K          ┆ Run           ┆ Czech Republic ┆ Brno             ┆ 1002.8   ┆ 0.0              ┆ 49023        │
│ Tyršák čtyřstofka ┆ Run           ┆ Czechia        ┆ Šumperk          ┆ 426.5    ┆ 3.1              ┆ 46670        │
│ Llanberis path    ┆ Hike          ┆ United Kingdom ┆ Caernarfon       ┆ 2417.5   ┆ 0.0              ┆ 45005        │
│ bottom section …  ┆               ┆                ┆                  ┆          ┆                  ┆              │
│ Od dubu ke Gizele ┆ Run           ┆ Czech Republic ┆ Prague           ┆ 385.7    ┆ 2.9              ┆ 44623        │
│ Revnicak Eve      ┆ Ride          ┆ Czechia        ┆ Řevnice          ┆ 5562.4   ┆ 287.8            ┆ 43497        │
│ Risova studanka - ┆ Ride          ┆ Czech Republic ┆ Brno             ┆ 2612.4   ┆ 138.5            ┆ 41396        │
│ od zavory         ┆               ┆                ┆                  ┆          ┆                  ┆              │
│ Most Legií (směr  ┆ Run           ┆ Czechia        ┆ Praha 1          ┆ 328.1    ┆ 2.08             ┆ 40265        │
│ Kampa)            ┆               ┆                ┆                  ┆          ┆                  ┆              │
│ Jiráskovo nábřeží ┆ Ride          ┆ Czechia        ┆ České Budějovice ┆ 1113.6   ┆ 9.7              ┆ 39669        │
│ k Husovce         ┆               ┆                ┆                  ┆          ┆                  ┆              │
│ Junglepark        ┆ Run           ┆ Czech Republic ┆ Brno             ┆ 367.37   ┆ 25.6568          ┆ 38087        │
│ 400m-Jičín        ┆ Run           ┆ Czechia        ┆ Jičín            ┆ 401.7    ┆ 3.2              ┆ 38024        │
│ Karlův most ONLY  ┆ Run           ┆ Czech Republic ┆ Prague           ┆ 289.0    ┆ 2.8              ┆ 37497        │
│ Stodůlecký -      ┆ Run           ┆ Czechia        ┆ Praha 13         ┆ 542.0    ┆ 0.0              ┆ 36839        │
│ Nepomucký rybník  ┆               ┆                ┆                  ┆          ┆                  ┆              │
│ Smetanovy reverse ┆ Run           ┆ Czechia        ┆ Olomouc          ┆ 639.7    ┆ 3.65364          ┆ 35550        │
│ Ještěd Finale     ┆ Ride          ┆ Czechia        ┆ Světlá pod       ┆ 763.9    ┆ 69.2             ┆ 35106        │
│ konec před kostk… ┆               ┆                ┆ Ještědem         ┆          ┆                  ┆              │
│ 400m              ┆ Run           ┆ Czechia        ┆ Pardubice V      ┆ 414.7    ┆ 0.0              ┆ 33533        │
│ Lužánky - Plochá  ┆ Run           ┆ Czech Republic ┆ Brno             ┆ 411.9    ┆ 0.0              ┆ 32808        │
│ dráha             ┆               ┆                ┆                  ┆          ┆                  ┆              │
│ Sedýlko - Praděd  ┆ Ride          ┆ Czech Republic ┆ Loučná Nad       ┆ 1210.1   ┆ 69.9             ┆ 31977        │
│ climb             ┆               ┆                ┆ Desnou           ┆          ┆                  ┆              │
│ Sprintík          ┆ Ride          ┆ Czech Republic ┆ Blansko          ┆ 3075.3   ┆ 222.0            ┆ 30470        │
│ křižovatka/skalní ┆               ┆                ┆                  ┆          ┆                  ┆              │
│ mlý…              ┆               ┆                ┆                  ┆          ┆                  ┆              │
│ Szpic Jested      ┆ Ride          ┆ Czechia        ┆ Liberec          ┆ 2926.9   ┆ 236.7            ┆ 30367        │
│ last 3 km ( od r… ┆               ┆                ┆                  ┆          ┆                  ┆              │
│ Muglinovská→Hradn ┆ Ride          ┆ Czechia        ┆ Ostrava          ┆ 2847.9   ┆ 46.4             ┆ 30174        │
│ í lávka (po p…    ┆               ┆                ┆                  ┆          ┆                  ┆              │
│ svadov—valtirov   ┆ Ride          ┆ Czechia        ┆ Ústí nad         ┆ 2883.8   ┆ 7.0              ┆ 27238        │
│                   ┆               ┆                ┆ Labem-Neštěmice  ┆          ┆                  ┆              │
│ Lysá hora - 5 km  ┆ Ride          ┆ Czech Republic ┆ Staré Hamry      ┆ 4951.0   ┆ 485.4            ┆ 26025        │
│ Údolí Svatý Jan   ┆ Ride          ┆ Czech Republic ┆ Beroun           ┆ 5730.4   ┆ 38.8             ┆ 24900        │
│ S&Ch20 Masarykův  ┆ Ride          ┆ Czechia        ┆ Ostrovačice      ┆ 5136.6   ┆ 78.0             ┆ 24520        │
│ okruh             ┆               ┆                ┆                  ┆          ┆                  ┆              │
│ Maslovice -       ┆ Ride          ┆ Czech Republic ┆ Máslovice        ┆ 5287.0   ┆ 33.8             ┆ 24504        │
│ Kralupy           ┆               ┆                ┆                  ┆          ┆                  ┆              │
│ Klinovec Top      ┆ Ride          ┆ Czechia        ┆ Jáchymov         ┆ 940.2    ┆ 58.0             ┆ 24427        │
│ Stezka nábřeží    ┆ Run           ┆ Czechia        ┆ Zlín             ┆ 588.5    ┆ 5.4              ┆ 23790        │
│ Stadion           ┆ Run           ┆ Czechia        ┆ Čelákovice       ┆ 403.4    ┆ 5.6              ┆ 23530        │
│ Čelákovice 400m   ┆               ┆                ┆                  ┆          ┆                  ┆              │
│ (II.)             ┆               ┆                ┆                  ┆          ┆                  ┆              │
│ Adamaov climb     ┆ Ride          ┆ Czechia        ┆ Adamov           ┆ 3599.6   ┆ 278.9            ┆ 22707        │
│ Juliska 400 m     ┆ Run           ┆ Czechia        ┆ Prague           ┆ 410.1    ┆ 10.8             ┆ 22164        │
│ Papezov - Prazmo  ┆ Ride          ┆ Czechia        ┆ Krásná           ┆ 7714.6   ┆ 13.2             ┆ 21245        │
│ Výstup na         ┆ Ride          ┆ Czechia        ┆ null             ┆ 1190.2   ┆ 65.2             ┆ 20481        │
│ Klínovec          ┆               ┆                ┆                  ┆          ┆                  ┆              │
│ Cyklostezka       ┆ Ride          ┆ Czechia        ┆ Hřensko          ┆ 1001.9   ┆ 27.9             ┆ 20268        │
│ sprint směr Děčín ┆               ┆                ┆                  ┆          ┆                  ┆              │
│ Malchor - Lysá    ┆ Hike          ┆ Czech Republic ┆ Krásná           ┆ 727.9    ┆ 120.2            ┆ 20112        │
│ Hora              ┆               ┆                ┆                  ┆          ┆                  ┆              │
│ Total brikule 🚀  ┆ Ride          ┆ Czechia        ┆ Staré Město      ┆ 572.0    ┆ 0.0              ┆ 19132        │
│ Cyklostezka       ┆ Ride          ┆ Czechia        ┆ Náchod           ┆ 3593.0   ┆ 11.5             ┆ 18864        │
│ Náchod -> Velké   ┆               ┆                ┆                  ┆          ┆                  ┆              │
│ Po…               ┆               ┆                ┆                  ┆          ┆                  ┆              │
│ 400 m (track num. ┆ Run           ┆ Czechia        ┆ Benešov          ┆ 406.8    ┆ 0.0              ┆ 18817        │
│ 2)                ┆               ┆                ┆                  ┆          ┆                  ┆              │
│ Podle Radbuzy     ┆ Ride          ┆ Czech Republic ┆ Pilsen           ┆ 2315.0   ┆ 15.8             ┆ 18400        │
│ Trinec-Tesin      ┆ Ride          ┆ Czechia        ┆ Třinec           ┆ 4677.3   ┆ 9.4              ┆ 17822        │
│ MH - Klaster      ┆ Ride          ┆ Czechia        ┆ Klášter Hradiště ┆ 1458.9   ┆ 4.8              ┆ 17589        │
│                   ┆               ┆                ┆ nad Jizerou      ┆          ┆                  ┆              │
│ Benedikt -        ┆ Run           ┆ Czechia        ┆ Most             ┆ 1995.5   ┆ 35.7             ┆ 16628        │
│ Parkoviště        ┆               ┆                ┆                  ┆          ┆                  ┆              │
│ stezka            ┆ Run           ┆ Czech Republic ┆ České Budějovice ┆ 1000.0   ┆ 6.4              ┆ 16045        │
│ Židlochovice ->   ┆ Ride          ┆ Czechia        ┆ Židlochovice     ┆ 12812.5  ┆ 20.4             ┆ 15945        │
│ Olympia           ┆               ┆                ┆                  ┆          ┆                  ┆              │
│ Do sedla Klínovce ┆ Ride          ┆ Czech Republic ┆ Loučná pod       ┆ 2782.7   ┆ 177.4            ┆ 15827        │
│ po silnici        ┆               ┆                ┆ Klínovcem        ┆          ┆                  ┆              │
│ Ovál ZŠ           ┆ Run           ┆ Czechia        ┆ Hradec Králové   ┆ 269.6    ┆ 0.0              ┆ 15633        │
│ Štefánikova       ┆               ┆                ┆                  ┆          ┆                  ┆              │
│ Tuhnice           ┆ Ride          ┆ Czech Republic ┆ Karlovy Vary     ┆ 2383.8   ┆ 0.0              ┆ 15542        │
│ most-Drahovice    ┆               ┆                ┆                  ┆          ┆                  ┆              │
│ most,st…          ┆               ┆                ┆                  ┆          ┆                  ┆              │
│ Mutěnka - z       ┆ Ride          ┆ Czechia        ┆ Kyjov            ┆ 3713.4   ┆ 0.0              ┆ 15204        │
│ Kyjova po odbočku ┆               ┆                ┆                  ┆          ┆                  ┆              │
│ …                 ┆               ┆                ┆                  ┆          ┆                  ┆              │
│ Šárka Valley      ┆ Run           ┆ Czechia        ┆ Praha 6          ┆ 976.5    ┆ 0.0              ┆ 15183        │
│ (short)           ┆               ┆                ┆                  ┆          ┆                  ┆              │
│ Kynšperský ATAK   ┆ Ride          ┆ Czechia        ┆ Kynšperk nad     ┆ 634.2    ┆ 0.0              ┆ 15182        │
│                   ┆               ┆                ┆ Ohří             ┆          ┆                  ┆              │
│ Decin - Bad       ┆ Ride          ┆ Czechia        ┆ Děčín            ┆ 18518.5  ┆ 28.0             ┆ 15069        │
│ Schandau Abzweig  ┆               ┆                ┆                  ┆          ┆                  ┆              │
│ R…                ┆               ┆                ┆                  ┆          ┆                  ┆              │
│ Track Domažlice   ┆ Run           ┆ Czechia        ┆ Domažlice        ┆ 397.4    ┆ 5.6              ┆ 14708        │
│ 400m - Sportovní  ┆ Run           ┆ Czechia        ┆ Jihlava          ┆ 394.1    ┆ 0.0              ┆ 14591        │
│ areál Na Stou…    ┆               ┆                ┆                  ┆          ┆                  ┆              │
│ Štvanická lávka   ┆ Run           ┆ Czechia        ┆ Prague           ┆ 277.5    ┆ 6.2              ┆ 14515        │
│ (do Karlína)      ┆               ┆                ┆                  ┆          ┆                  ┆              │
│ Zlaťák konec -    ┆ Ride          ┆ Czechia        ┆ Vítkovice        ┆ 507.3    ┆ 42.1             ┆ 14461        │
│ smrt              ┆               ┆                ┆                  ┆          ┆                  ┆              │
│ Transformator k   ┆ Hike          ┆ Czechia        ┆ Ostravice        ┆ 1537.0   ┆ 158.4            ┆ 14098        │
│ Butorance (u s…   ┆               ┆                ┆                  ┆          ┆                  ┆              │
│ Hradní lávka =>   ┆ Run           ┆ Czechia        ┆ Ostrava          ┆ 996.4    ┆ 22.7             ┆ 14046        │
│ Sýkorův most      ┆               ┆                ┆                  ┆          ┆                  ┆              │
│ k přehradě hop    ┆ Ride          ┆ Czech Republic ┆ Krásná Lípa      ┆ 315.9    ┆ 21.4             ┆ 13871        │
│ TJ Znojmo Lap     ┆ Run           ┆ Czechia        ┆ Znojmo           ┆ 404.6    ┆ 5.1              ┆ 13647        │
│ Park 1            ┆ Run           ┆ Czech Republic ┆ Ostrava          ┆ 718.9    ┆ 0.0              ┆ 13602        │
│ mezi mosty        ┆ Run           ┆ Czechia        ┆ Pardubice        ┆ 957.4    ┆ 6.2              ┆ 12921        │
│ Chrudim climb     ┆ Ride          ┆ Czech Republic ┆ Chrudim          ┆ 866.4    ┆ 16.6             ┆ 12612        │
│ Špindlerovka -    ┆ Ride          ┆ Czechia        ┆ Špindlerův Mlýn  ┆ 4162.3   ┆ 232.3            ┆ 12583        │
│ část II. (od Če…  ┆               ┆                ┆                  ┆          ┆                  ┆              │
│ Hostyn-od.zastavk ┆ Ride          ┆ Czech Republic ┆ Bystřice Pod     ┆ 5103.32  ┆ 340.8            ┆ 12560        │

In [157]:
pl.Config(tbl_rows=300)

In [187]:
last_date = df.select(pl.col('date')).max().item()
last_date = last_date.strftime("%Y-%m-%d")
last_date

'2025-01-07'

In [159]:
with pl.Config() as cfg:
    cfg.set_tbl_formatting('ASCII_MARKDOWN')
    overview_markdown = repr(overview)

In [161]:
overview_markdown

"shape: (261, 7)\n| name              | activity_type | country        | city             | distance | total_elevation_ | effort_count |\n| ---               | ---           | ---            | ---              | ---      | gain             | ---          |\n| str               | str           | str            | str              | f64      | ---              | i64          |\n|                   |               |                |                  |          | f64              |              |\n|-------------------|---------------|----------------|------------------|----------|------------------|--------------|\n| Richmond ITT1     | Ride          | United Kingdom | London           | 589.3    | 7.2              | 4625714      |\n| Box Hill 2.2k     | Ride          | United Kingdom | Mole Valley      | 2296.62  | 119.1            | 1415736      |\n|                   |               |                | District,        |          |                  |              |\n|                   |               |                | Surrey, …        |          |                  |              |\n| Die Eine Runde    | Ride          | Czech Republic | Brno             | 380.0    | 0.0              | 1089698      |\n| Overtake the      | Run           | United Kingdom | London           | 591.8    | 2.2              | 663772       |\n| Boris Bikes       |               |                |                  |          |                  |              |\n| Třebešín-dráha K  | Ride          | Czech Republic | Prague           | 347.2    | 0.0              | 402245       |\n| Alpe d'Huez       | Ride          | France         | Le Bourg         | 12024.9  | 1047.3           | 336375       |\n|                   |               |                | D'Oisans         |          |                  |              |\n| Sa Calobra - Coll | Ride          | Spain          | Escorca          | 9416.77  | 659.8            | 323413       |\n| dels Reis         |               |                |                  |          |                  |              |\n| Opičí Časovka,    | Ride          | Czech Republic | Prague           | 1390.1   | 6.0              | 323017       |\n| Podolská vodárn…  |               |                |                  |          |                  |              |\n| Prostějov kolo    | Ride          | Czech Republic | Prostějov        | 311.1    | 0.0              | 251263       |\n| dráha P           |               |                |                  |          |                  |              |\n| Koppenberg        | Ride          | Belgium        | Oudenaarde       | 556.595  | 63.1             | 245118       |\n| Mont Ventoux (par | Ride          | France         | Bédoin           | 20741.8  | 1569.4           | 242104       |\n| Bedoin)           |               |                |                  |          |                  |              |\n| Stelvio - Bormio  | Ride          | Italy          | null             | 2982.1   | 5.4              | 235604       |\n| Turn Downhill     |               |                |                  |          |                  |              |\n| Zweite hup u ZOO  | Ride          | Czechia        | Praha-Troja      | 314.1    | 6.6              | 234009       |\n| Zbraslav -        | Ride          | Czechia        | Zbraslav         | 2359.0   | 5.7              | 217003       |\n| Komořany          |               |                |                  |          |                  |              |\n| Stadion Na        | Run           | Czechia        | Prague           | 420.9    | 0.0              | 215805       |\n| Děkance           |               |                |                  |          |                  |              |\n| Lužánky rovinka   | Run           | Czechia        | Brno-střed       | 268.9    | 3.8              | 180145       |\n| Šlechtovka -      | Run           | Czechia        | Praha 7          | 225.4    | 0.0              | 156359       |\n| finální rovinka   |               |                |                  |          |                  |              |\n| time trial at     | Ride          | Czech Republic | Brno             | 1438.1   | 20.6             | 141864       |\n| Svratka           |               |                |                  |          |                  |              |\n| Passo Stelvio     | Ride          | Italy          | null             | 23600.3  | 1840.3           | 139224       |\n| Od posledního     | Ride          | Czechia        | Bílovice nad     | 827.8    | 6.2              | 124486       |\n| tunelu do Bílovi… |               |                | Svitavou         |          |                  |              |\n| VUT horní dráha   | Run           | Czechia        | Brno             | 405.2    | 0.0              | 109048       |\n| 400m              |               |                |                  |          |                  |              |\n| Col du Tourmalet  | Ride          | France         | Luz Saint        | 18827.5  | 1397.7           | 99930        |\n| (par Luz-St-S…    |               |                | Sauveur          |          |                  |              |\n| Vítkov up sprint  | Run           | Czechia        | Prague           | 118.2    | 6.0              | 86623        |\n| Pražačka 320      | Run           | Czechia        | Prague           | 343.3    | 0.0              | 75242        |\n| Viveros-Paseo     | Run           | Spain          | Valencia         | 1722.9   | 18.0             | 73160        |\n| alameda           |               |                |                  |          |                  |              |\n| TJ Sokol okruh    | Run           | Czech Republic | Prague           | 418.8    | 5.7              | 72849        |\n| Kolo na stadionu  | Run           | Czechia        | Třebíč           | 475.6    | 6.2              | 69590        |\n| v Třebíči         |               |                |                  |          |                  |              |\n| Srbsko - Hlásná   | Ride          | Czechia        | Srbsko           | 5736.1   | 13.5             | 61463        |\n| Třebáň            |               |                |                  |          |                  |              |\n| Stezka do Zlina   | Ride          | Czech Republic | Zlin             | 1368.28  | 23.1348          | 60477        |\n| Rokytka od myčky  | Ride          | Czechia        | Praha 14         | 1823.0   | 4.0              | 59027        |\n| Dráha Plzeň okruh | Ride          | Czechia        | Pilsen           | 361.9    | 0.0              | 54673        |\n| P                 |               |                |                  |          |                  |              |\n| Sptint pod Býčí   | Ride          | Czechia        | Olomučany        | 778.8    | 0.0              | 53348        |\n| skálou            |               |                |                  |          |                  |              |\n| 400 m - atletický | Run           | Czechia        | Olomouc          | 400.0    | 2.9              | 52422        |\n| okruh - Loko…     |               |                |                  |          |                  |              |\n| Hvězda flat       | Run           | Czech Republic | Praha 6          | 1001.15  | 11.426           | 49911        |\n| tenis 1K          | Run           | Czech Republic | Brno             | 1002.8   | 0.0              | 49023        |\n| Tyršák čtyřstofka | Run           | Czechia        | Šumperk          | 426.5    | 3.1              | 46670        |\n| Llanberis path    | Hike          | United Kingdom | Caernarfon       | 2417.5   | 0.0              | 45005        |\n| bottom section …  |               |                |                  |          |                  |              |\n| Od dubu ke Gizele | Run           | Czech Republic | Prague           | 385.7    | 2.9              | 44623        |\n| Revnicak Eve      | Ride          | Czechia        | Řevnice          | 5562.4   | 287.8            | 43497        |\n| Risova studanka - | Ride          | Czech Republic | Brno             | 2612.4   | 138.5            | 41396        |\n| od zavory         |               |                |                  |          |                  |              |\n| Most Legií (směr  | Run           | Czechia        | Praha 1          | 328.1    | 2.08             | 40265        |\n| Kampa)            |               |                |                  |          |                  |              |\n| Jiráskovo nábřeží | Ride          | Czechia        | České Budějovice | 1113.6   | 9.7              | 39669        |\n| k Husovce         |               |                |                  |          |                  |              |\n| Junglepark        | Run           | Czech Republic | Brno             | 367.37   | 25.6568          | 38087        |\n| 400m-Jičín        | Run           | Czechia        | Jičín            | 401.7    | 3.2              | 38024        |\n| Karlův most ONLY  | Run           | Czech Republic | Prague           | 289.0    | 2.8              | 37497        |\n| Stodůlecký -      | Run           | Czechia        | Praha 13         | 542.0    | 0.0              | 36839        |\n| Nepomucký rybník  |               |                |                  |          |                  |              |\n| Smetanovy reverse | Run           | Czechia        | Olomouc          | 639.7    | 3.65364          | 35550        |\n| Ještěd Finale     | Ride          | Czechia        | Světlá pod       | 763.9    | 69.2             | 35106        |\n| konec před kostk… |               |                | Ještědem         |          |                  |              |\n| 400m              | Run           | Czechia        | Pardubice V      | 414.7    | 0.0              | 33533        |\n| Lužánky - Plochá  | Run           | Czech Republic | Brno             | 411.9    | 0.0              | 32808        |\n| dráha             |               |                |                  |          |                  |              |\n| Sedýlko - Praděd  | Ride          | Czech Republic | Loučná Nad       | 1210.1   | 69.9             | 31977        |\n| climb             |               |                | Desnou           |          |                  |              |\n| Sprintík          | Ride          | Czech Republic | Blansko          | 3075.3   | 222.0            | 30470        |\n| křižovatka/skalní |               |                |                  |          |                  |              |\n| mlý…              |               |                |                  |          |                  |              |\n| Szpic Jested      | Ride          | Czechia        | Liberec          | 2926.9   | 236.7            | 30367        |\n| last 3 km ( od r… |               |                |                  |          |                  |              |\n| Muglinovská→Hradn | Ride          | Czechia        | Ostrava          | 2847.9   | 46.4             | 30174        |\n| í lávka (po p…    |               |                |                  |          |                  |              |\n| svadov—valtirov   | Ride          | Czechia        | Ústí nad         | 2883.8   | 7.0              | 27238        |\n|                   |               |                | Labem-Neštěmice  |          |                  |              |\n| Lysá hora - 5 km  | Ride          | Czech Republic | Staré Hamry      | 4951.0   | 485.4            | 26025        |\n| Údolí Svatý Jan   | Ride          | Czech Republic | Beroun           | 5730.4   | 38.8             | 24900        |\n| S&Ch20 Masarykův  | Ride          | Czechia        | Ostrovačice      | 5136.6   | 78.0             | 24520        |\n| okruh             |               |                |                  |          |                  |              |\n| Maslovice -       | Ride          | Czech Republic | Máslovice        | 5287.0   | 33.8             | 24504        |\n| Kralupy           |               |                |                  |          |                  |              |\n| Klinovec Top      | Ride          | Czechia        | Jáchymov         | 940.2    | 58.0             | 24427        |\n| Stezka nábřeží    | Run           | Czechia        | Zlín             | 588.5    | 5.4              | 23790        |\n| Stadion           | Run           | Czechia        | Čelákovice       | 403.4    | 5.6              | 23530        |\n| Čelákovice 400m   |               |                |                  |          |                  |              |\n| (II.)             |               |                |                  |          |                  |              |\n| Adamaov climb     | Ride          | Czechia        | Adamov           | 3599.6   | 278.9            | 22707        |\n| Juliska 400 m     | Run           | Czechia        | Prague           | 410.1    | 10.8             | 22164        |\n| Papezov - Prazmo  | Ride          | Czechia        | Krásná           | 7714.6   | 13.2             | 21245        |\n| Výstup na         | Ride          | Czechia        | null             | 1190.2   | 65.2             | 20481        |\n| Klínovec          |               |                |                  |          |                  |              |\n| Cyklostezka       | Ride          | Czechia        | Hřensko          | 1001.9   | 27.9             | 20268        |\n| sprint směr Děčín |               |                |                  |          |                  |              |\n| Malchor - Lysá    | Hike          | Czech Republic | Krásná           | 727.9    | 120.2            | 20112        |\n| Hora              |               |                |                  |          |                  |              |\n| Total brikule 🚀  | Ride          | Czechia        | Staré Město      | 572.0    | 0.0              | 19132        |\n| Cyklostezka       | Ride          | Czechia        | Náchod           | 3593.0   | 11.5             | 18864        |\n| Náchod -> Velké   |               |                |                  |          |                  |              |\n| Po…               |               |                |                  |          |                  |              |\n| 400 m (track num. | Run           | Czechia        | Benešov          | 406.8    | 0.0              | 18817        |\n| 2)                |               |                |                  |          |                  |              |\n| Podle Radbuzy     | Ride          | Czech Republic | Pilsen           | 2315.0   | 15.8             | 18400        |\n| Trinec-Tesin      | Ride          | Czechia        | Třinec           | 4677.3   | 9.4              | 17822        |\n| MH - Klaster      | Ride          | Czechia        | Klášter Hradiště | 1458.9   | 4.8              | 17589        |\n|                   |               |                | nad Jizerou      |          |                  |              |\n| Benedikt -        | Run           | Czechia        | Most             | 1995.5   | 35.7             | 16628        |\n| Parkoviště        |               |                |                  |          |                  |              |\n| stezka            | Run           | Czech Republic | České Budějovice | 1000.0   | 6.4              | 16045        |\n| Židlochovice ->   | Ride          | Czechia        | Židlochovice     | 12812.5  | 20.4             | 15945        |\n| Olympia           |               |                |                  |          |                  |              |\n| Do sedla Klínovce | Ride          | Czech Republic | Loučná pod       | 2782.7   | 177.4            | 15827        |\n| po silnici        |               |                | Klínovcem        |          |                  |              |\n| Ovál ZŠ           | Run           | Czechia        | Hradec Králové   | 269.6    | 0.0              | 15633        |\n| Štefánikova       |               |                |                  |          |                  |              |\n| Tuhnice           | Ride          | Czech Republic | Karlovy Vary     | 2383.8   | 0.0              | 15542        |\n| most-Drahovice    |               |                |                  |          |                  |              |\n| most,st…          |               |                |                  |          |                  |              |\n| Mutěnka - z       | Ride          | Czechia        | Kyjov            | 3713.4   | 0.0              | 15204        |\n| Kyjova po odbočku |               |                |                  |          |                  |              |\n| …                 |               |                |                  |          |                  |              |\n| Šárka Valley      | Run           | Czechia        | Praha 6          | 976.5    | 0.0              | 15183        |\n| (short)           |               |                |                  |          |                  |              |\n| Kynšperský ATAK   | Ride          | Czechia        | Kynšperk nad     | 634.2    | 0.0              | 15182        |\n|                   |               |                | Ohří             |          |                  |              |\n| Decin - Bad       | Ride          | Czechia        | Děčín            | 18518.5  | 28.0             | 15069        |\n| Schandau Abzweig  |               |                |                  |          |                  |              |\n| R…                |               |                |                  |          |                  |              |\n| Track Domažlice   | Run           | Czechia        | Domažlice        | 397.4    | 5.6              | 14708        |\n| 400m - Sportovní  | Run           | Czechia        | Jihlava          | 394.1    | 0.0              | 14591        |\n| areál Na Stou…    |               |                |                  |          |                  |              |\n| Štvanická lávka   | Run           | Czechia        | Prague           | 277.5    | 6.2              | 14515        |\n| (do Karlína)      |               |                |                  |          |                  |              |\n| Zlaťák konec -    | Ride          | Czechia        | Vítkovice        | 507.3    | 42.1             | 14461        |\n| smrt              |               |                |                  |          |                  |              |\n| Transformator k   | Hike          | Czechia        | Ostravice        | 1537.0   | 158.4            | 14098        |\n| Butorance (u s…   |               |                |                  |          |                  |              |\n| Hradní lávka =>   | Run           | Czechia        | Ostrava          | 996.4    | 22.7             | 14046        |\n| Sýkorův most      |               |                |                  |          |                  |              |\n| k přehradě hop    | Ride          | Czech Republic | Krásná Lípa      | 315.9    | 21.4             | 13871        |\n| TJ Znojmo Lap     | Run           | Czechia        | Znojmo           | 404.6    | 5.1              | 13647        |\n| Park 1            | Run           | Czech Republic | Ostrava          | 718.9    | 0.0              | 13602        |\n| mezi mosty        | Run           | Czechia        | Pardubice        | 957.4    | 6.2              | 12921        |\n| Chrudim climb     | Ride          | Czech Republic | Chrudim          | 866.4    | 16.6             | 12612        |\n| Špindlerovka -    | Ride          | Czechia        | Špindlerův Mlýn  | 4162.3   | 232.3            | 12583        |\n| část II. (od Če…  |               |                |                  |          |                  |              |\n| Hostyn-od.zastavk | Ride          | Czech Republic | Bystřice Pod     | 5103.32  | 340.8            | 12560        |\n| y.po.znacku.P     |               |                | Hostýnem

In [189]:
with open('README.md', "w+", encoding="utf8") as readme:
    content = readme.read()
    content = content.split("## Poslední aktualizace")[0] 
    readme.write(f"""{content}\n\n## Poslední aktualizace\n\n{last_date}\n\n##Sledované segmenty\n\n" {overview_markdown}""")

In [193]:
df = pl.read_parquet('data_raw/segments/*.parquet')

In [83]:
import math

def haversine_distance(lat1, lon1, lat2, lon2):
    """
    Calculate the great-circle distance between two points on Earth.
    Returns distance in kilometers.
    """
    R = 6371  # Earth's radius in kilometers

    # Convert latitude and longitude to radians
    lat1, lon1, lat2, lon2 = map(math.radians, [lat1, lon1, lat2, lon2])
    
    # Differences in coordinates
    dlat = lat2 - lat1
    dlon = lon2 - lon1
    
    # Haversine formula
    a = math.sin(dlat/2)**2 + math.cos(lat1) * math.cos(lat2) * math.sin(dlon/2)**2
    c = 2 * math.asin(math.sqrt(a))
    
    return R * c

calculate_distance = lambda row: haversine_distance(
    row['souradnice_zacatek'][1],  # latitude1
    row['souradnice_zacatek'][0],  # longitude1
    row['souradnice_konec'][1],    # latitude2
    row['souradnice_konec'][0]     # longitude2
)

In [203]:
df = df.with_columns(pl.struct(['start_latlng','end_latlng']) \
       .map_elements(lambda x: haversine_distance(x['start_latlng'][0], x['start_latlng'][1], x['end_latlng'][0], x['end_latlng'][1])).alias('start_to_finish_distance'))

sys:1: MapWithoutReturnDtypeWarning: Calling `map_elements` without specifying `return_dtype` can lead to unpredictable results. Specify `return_dtype` to silence this warning.
sys:1: MapWithoutReturnDtypeWarning: Calling `map_elements` without specifying `return_dtype` can lead to unpredictable results. Specify `return_dtype` to silence this warning.
sys:1: MapWithoutReturnDtypeWarning: Calling `map_elements` without specifying `return_dtype` can lead to unpredictable results. Specify `return_dtype` to silence this warning.
sys:1: MapWithoutReturnDtypeWarning: Calling `map_elements` without specifying `return_dtype` can lead to unpredictable results. Specify `return_dtype` to silence this warning.
sys:1: MapWithoutReturnDtypeWarning: Calling `map_elements` without specifying `return_dtype` can lead to unpredictable results. Specify `return_dtype` to silence this warning.
sys:1: MapWithoutReturnDtypeWarning: Calling `map_elements` without specifying `return_dtype` can lead to unpredictable results. Specify `return_dtype` to silence this warning.
sys:1: MapWithoutReturnDtypeWarning: Calling `map_elements` without specifying `return_dtype` can lead to unpredictable results. Specify `return_dtype` to silence this warning.
sys:1: MapWithoutReturnDtypeWarning: Calling `map_elements` without specifying `return_dtype` can lead to unpredictable results. Specify `return_dtype` to silence this warning.
sys:1: MapWithoutReturnDtypeWarning: Calling `map_elements` without specifying `return_dtype` can lead to unpredictable results. Specify `return_dtype` to silence this warning.
sys:1: MapWithoutReturnDtypeWarning: Calling `map_elements` without specifying `return_dtype` can lead to unpredictable results. Specify `return_dtype` to silence this warning.
sys:1: MapWithoutReturnDtypeWarning: Calling `map_elements` without specifying `return_dtype` can lead to unpredictable results. Specify `return_dtype` to silence this warning.
sys:1: MapWithoutReturnDtypeWarning: Calling `map_elements` without specifying `return_dtype` can lead to unpredictable results. Specify `return_dtype` to silence this warning.
sys:1: MapWithoutReturnDtypeWarning: Calling `map_elements` without specifying `return_dtype` can lead to unpredictable results. Specify `return_dtype` to silence this warning.
sys:1: MapWithoutReturnDtypeWarning: Calling `map_elements` without specifying `return_dtype` can lead to unpredictable results. Specify `return_dtype` to silence this warning.
sys:1: MapWithoutReturnDtypeWarning: Calling `map_elements` without specifying `return_dtype` can lead to unpredictable results. Specify `return_dtype` to silence this warning.

In [209]:
df.group_by('name').agg(pl.col('start_to_finish_distance').max()).sort('start_to_finish_distance')

shape: (261, 2)
┌─────────────────────────────────┬──────────────────────────┐
│ name                            ┆ start_to_finish_distance │
│ ---                             ┆ ---                      │
│ str                             ┆ f64                      │
╞═════════════════════════════════╪══════════════════════════╡
│ Prostějov kolo dráha P          ┆ 0.000451                 │
│ 400 metrů, 44 120 diváků        ┆ 0.00052                  │
│ Pražačka 320                    ┆ 0.000925                 │
│ 400m-Jičín                      ┆ 0.001068                 │
│ Track Domažlice                 ┆ 0.001114                 │
│ Benedikt - Parkoviště           ┆ 0.001136                 │
│ Lužánky - Plochá dráha          ┆ 0.001678                 │
│ Tatran Třemošná                 ┆ 0.002124                 │
│ Die Eine Runde                  ┆ 0.002446                 │
│ Tyršák čtyřstofka               ┆ 0.002828                 │
│ Juliska 400 m                   ┆ 0.00286                  │
│ Dráha Plzeň okruh P             ┆ 0.003295                 │
│ 400m                            ┆ 0.003456                 │
│ 400 m - atletický okruh - Loko… ┆ 0.003459                 │
│ TJ Znojmo Lap                   ┆ 0.003705                 │
│ Stadion - 400 m                 ┆ 0.004469                 │
│ Ovál ZŠ Štefánikova             ┆ 0.004506                 │
│ Vojenský ovál 400M              ┆ 0.005436                 │
│ Giro di Tyrš                    ┆ 0.005763                 │
│ Velodrom 1kolo                  ┆ 0.005807                 │
│ Stadion Na Děkance              ┆ 0.006087                 │
│ Hradiště - čtyřstovka           ┆ 0.006289                 │
│ Stadion Čelákovice 400m (II.)   ┆ 0.006626                 │
│ 400m - Sportovní areál Na Stou… ┆ 0.007687                 │
│ Kolo na stadionu v Třebíči      ┆ 0.008266                 │
│ Třebešín-dráha K                ┆ 0.008769                 │
│ Brno Circuit                    ┆ 0.008877                 │
│ TJ Sokol okruh                  ┆ 0.009342                 │
│ VUT horní dráha 400m            ┆ 0.011266                 │
│ 400 m (track num. 2)            ┆ 0.015573                 │
│ S&Ch20 Masarykův okruh          ┆ 0.108713                 │
│ Vítkov up sprint                ┆ 0.117786                 │
│ Ještěd Finale konec před kostk… ┆ 0.191607                 │
│ Šlechtovka - finální rovinka    ┆ 0.222849                 │
│ Říp po žluté na vyhlídku        ┆ 0.238278                 │
│ Lužánky rovinka                 ┆ 0.260571                 │
│ Štvanická lávka (do Karlína)    ┆ 0.273856                 │
│ Karlův most ONLY                ┆ 0.283976                 │
│ Lysa hora - jizni sjezdovka     ┆ 0.284577                 │
│ Junglepark                      ┆ 0.298243                 │
│ Zlaťák konec - smrt             ┆ 0.299145                 │
│ Od lávky k lávce                ┆ 0.300839                 │
│ k přehradě hop                  ┆ 0.305337                 │
│ Zweite hup u ZOO                ┆ 0.308372                 │
│ Berounka sprint                 ┆ 0.311891                 │
│ Koupaliště sprint               ┆ 0.320015                 │
│ Od letňáku ke starému vchodu Z… ┆ 0.325029                 │
│ Most Legií (směr Kampa)         ┆ 0.326026                 │
│ panelka k bráně ˇerchova        ┆ 0.347137                 │
│ Segment                         ┆ 0.352854                 │
│ Svaty kopecek up                ┆ 0.352871                 │
│ LS - Park Boost                 ┆ 0.356353                 │
│ Od dubu ke Gizele               ┆ 0.370526                 │
│ Pavlov - Dívčí hrad climb       ┆ 0.377718                 │
│ Špindlerův Mlýn - Školní        ┆ 0.377897                 │
│ Stojka na Pancíř                ┆ 0.380638                 │
│ Stoupání na Templštejn          ┆ 0.382315                 │
│ Dneboh - Drábské Světničky      ┆ 0.389104                 │
│ Od křižovatky do Strání po vys… ┆ 0.392663                 │
│ Šup do parku                    ┆ 0.41346                  │
│ Zrucskej smrtak                 ┆ 0.425948                 │
│ Kolem stadionu                  ┆ 0.428665                 │
│ Obří hřeben - stoupák           ┆ 0.428891                 │
│ Rybnik                          ┆ 0.435598                 │
│ Lacinův kámen - Velká Skála     ┆ 0.446428                 │
│ hurá na Říp                     ┆ 0.491352                 │
│ Bludička-Opavice                ┆ 0.498226                 │
│ Luby end                        ┆ 0.501828                 │
│ Kynšperský ATAK                 ┆ 0.504788                 │
│ Ostaš                           ┆ 0.524418                 │
│ Stodůlecký - Nepomucký rybník   ┆ 0.529274                 │
│ Cyklostezka Stará huť-Dobříš    ┆ 0.545813                 │
│ Od Sanusu ke gymplu             ┆ 0.546075                 │
│ Valy                            ┆ 0.548886                 │
│ Total brikule 🚀                ┆ 0.551812                 │
│ Koppenberg                      ┆ 0.556162                 │
│ Hadí stezka (Svatobor)          ┆ 0.55617                  │
│ Pisek podel reky I              ┆ 0.567831                 │
│ Malchor - Lysá Hora             ┆ 0.568227                 │
│ Stezka nábřeží                  ┆ 0.577385                 │
│ Richmond ITT1                   ┆ 0.586404                 │
│ podél Podměstského rybníku      ┆ 0.590267                 │
│ Overtake the Boris Bikes        ┆ 0.590378                 │
│ Hadí stezka na Svatobor 🐍      ┆ 0.599233                 │
│ kopec na hrad                   ┆ 0.622104                 │
│ Snezka po schodech              ┆ 0.628409                 │
│ Harusák Climb                   ┆ 0.630145                 │
│ Smetanovy reverse               ┆ 0.631364                 │
│ plný kule z kolína              ┆ 0.644586                 │
│ Od posledního tunelu do Bílovi… ┆ 0.647058                 │
│ Opavice od zatáčky              ┆ 0.65315                  │
│ do Srní                         ┆ 0.653693                 │
│ Sedýlko - Praděd climb          ┆ 0.660889                 │
│ Final climb ke srubu na Deštno… ┆ 0.664013                 │
│ Okruhy Ochozou - Výběh na Haru… ┆ 0.664321                 │
│ JestedSkyrace - last uphill - … ┆ 0.688361                 │
│ Park 1                          ┆ 0.699398                 │
│ Tři prameny - Pravčická brána   ┆ 0.71009                  │
│ Sptint pod Býčí skálou          ┆ 0.711671                 │
│ Z Doubravky k Josefu            ┆ 0.724318                 │
│ Panelovka-Tichá 800m            ┆ 0.728498                 │
│ Rovinka od kruháče k bazénu     ┆ 0.729701                 │
│ Most - Most -> Břeclav          ┆ 0.747653                 │
│ Kopec pod Barborou              ┆ 0.755735                 │
│ U Jordánu do kopce              ┆ 0.759626                 │
│ Kopeček - od kruháče k bazilic… ┆ 0.765906                 │
│ Ku řopíku                       ┆ 0.772301                 │
│ Klinovec Top                    ┆ 0.774628                 │
│ rovinka kolem Sázavy:Plynovod-… ┆ 0.792908                 │
│ Krkonošská                      ┆ 0.794997                 │
│ Kuželna - Splav 800m            ┆ 0.802088                 │
│ Pod rozhlednu Babi lom          ┆ 0.803972                 │
│ Výstup na Klínovec              ┆ 0.808138                 │
│ segment z Tábora                ┆ 0.81795                  │
│ Šárka Valley (short)            ┆ 0.82043                  │
│ Interval                        ┆ 0.822266                 │
│ Tygří výzva, sklon 32% :)       ┆ 0.837959                 │
│ Chrudim climb                   ┆ 0.838854                 │
│ Rovinka Beranov                 ┆ 0.841521                 │
│ od hráze až na konec přehrady … ┆ 0.85032                  │
│ Třebíč - Stařeč po cyklostezce… ┆ 0.855554                 │
│ Solan last km                   ┆ 0.855722                 │
│ Gránické údolí - Central Part … ┆ 0.859017                 │
│ Benešovský brdek                ┆ 0.864204                 │
│ VR #11 finish                   ┆ 0.867632                 │
│ stezka                          ┆ 0.891633                 │
│ mezi mosty                      ┆ 0.894894                 │
│ Zig-zag na Šerák                ┆ 0.897097                 │
│ Okolo Bobrůvky Tři Studně - Ko… ┆ 0.908767                 │
│ Hlavní třídou nahoru            ┆ 0.918741                 │
│ BL Boletice - rovinka na hřebe… ┆ 0.946919                 │
│ tenis 1K                        ┆ 0.951894                 │
│ Hradní lávka => Sýkorův most    ┆ 0.958195                 │
│ Šantovka - Kojeňák              ┆ 0.985026                 │
│ Klobouky Viadukt                ┆ 0.98949                  │
│ Javorník finish od Pinduly      ┆ 0.994732                 │
│ Hvězda flat                     ┆ 0.995211                 │
│ Cyklostezka sprint směr Děčín   ┆ 1.000775                 │
│ Jiráskovo nábřeží k Husovce     ┆ 1.009863                 │
│ Ondřejník sedlo - Ondřejník vr… ┆ 1.011512                 │
│ Debř-Michalovice ☠              ┆ 1.013208                 │
│ Ciclo Via BNL -> K              ┆ 1.022516                 │
│ Mezi zábranama (proti proudu)   ┆ 1.039421                 │
│ Tuhnická lávka -Chebský most    ┆ 1.053672                 │
│ Výpřež - Ještěd (po červené)    ┆ 1.079444                 │
│ Šumbera pom. odb. - vysílač Há… ┆ 1.084656                 │
│ Pláně - Černý vrch              ┆ 1.100427                 │
│ Box Hill 2.2k                   ┆ 1.118491                 │
│ Javorový od stanice lanovky     ┆ 1.129113                 │
│ Kleť k vysílači - finále        ┆ 1.165982                 │
│ Labe_po asfaltu                 ┆ 1.188158                 │
│ Adamaov climb                   ┆ 1.192579                 │
│ Nábřeží                         ┆ 1.209947                 │
│ Transformator k Butorance (u s… ┆ 1.223649                 │
│ MH - Klaster                    ┆ 1.227082                 │
│ Dlouhá míle                     ┆ 1.251162                 │
│ Stezka do Zlina                 ┆ 1.265858                 │
│ Eurovie - nadjezd Rosice        ┆ 1.294441                 │
│ time trial at Svratka           ┆ 1.300465                 │
│ Richtrovy boudy - Výrovka       ┆ 1.301531                 │
│ Šobes - sjezd                   ┆ 1.302735                 │
│ #ULhalf - Strekovske Nabrezi    ┆ 1.320007                 │
│ 15% Stoupák Bártlovka->Paliční… ┆ 1.336884                 │
│ Červená podél Zlaté stoky do T… ┆ 1.34756                  │
│ Szpic Jested  last 3 km ( od r… ┆ 1.348759                 │
│ Špindlerovka - část II. (od Če… ┆ 1.360618                 │
│ Kraličák Skyrace - 2. kopec     ┆ 1.378572                 │
│ Opičí Časovka, Podolská vodárn… ┆ 1.379737                 │
│ Výrovka - Modré Sedlo           ┆ 1.406808                 │
│ Szlak czerwony, Schronisko Nad… ┆ 1.42071                  │
│ Opavska down 1/2                ┆ 1.43704                  │
│ Ježánky(Visalaje) - Bílý Kříž … ┆ 1.445806                 │
│ Bunč climb                      ┆ 1.459622                 │
│ podle Labe do Týnce             ┆ 1.492337                 │
│ Pod Homoli Climb                ┆ 1.515183                 │
│ Borůvková hora part II          ┆ 1.532247                 │
│ Viveros-Paseo alameda           ┆ 1.534193                 │
│ Ořešník                         ┆ 1.538323                 │
│ Sprint Páteček - Santos         ┆ 1.55548                  │
│ 611 - Mstetice                  ┆ 1.564022                 │
│ Le Grande Classico              ┆ 1.565898                 │
│ Od bývalé sáňkařské dráhy po m… ┆ 1.625815                 │
│ Luisino údolí - Velká Deštná    ┆ 1.654443                 │
│ Nová cyklopěšina z Peřiny do H… ┆ 1.66117                  │
│ Lípy (směrem do Jičína)         ┆ 1.710386                 │
│ Kočičí žleb - Ríšova studánka   ┆ 1.739759                 │
│ Kleť                            ┆ 1.740747                 │
│ stupani k vetr. mlynu Kuzelov   ┆ 1.802967                 │
│ Podle Radbuzy                   ┆ 1.806575                 │
│ Dom Śląski Up Hill              ┆ 1.811384                 │
│ Rokytka od myčky                ┆ 1.812742                 │
│ Kaufland - Popendorf            ┆ 1.85194                  │
│ Daskabát flat                   ┆ 1.853476                 │
│ Stelvio - Bormio Turn Downhill  ┆ 1.86659                  │
│ Posázavskou k odbočce před sch… ┆ 1.866937                 │
│ Neklid -> Klínovec              ┆ 1.876033                 │
│ Kozí hřbety - Luční bouda       ┆ 1.941582                 │
│ Železniční most => Jez Vítkovi… ┆ 2.095085                 │
│ Sprintík křižovatka/skalní mlý… ┆ 2.099472                 │
│ Starý Kolín - Svatá Kateřina    ┆ 2.125519                 │
│ most - Loket                    ┆ 2.137918                 │
│ Tuhnice most-Drahovice most,st… ┆ 2.155936                 │
│ Ručičky - Krakonošova snídaně … ┆ 2.221249                 │
│ Llanberis path bottom section … ┆ 2.235309                 │
│ Zbraslav - Komořany             ┆ 2.258969                 │
│ Dářská rašeliniště              ┆ 2.310261                 │
│ Do sedla Klínovce po silnici    ┆ 2.318996                 │
│ Po červené na Předěl            ┆ 2.368748                 │
│ Modrava - Tříjezerní slať       ┆ 2.384002                 │
│ Nová cyklostezka do Bosche  2   ┆ 2.439248                 │
│ Hostyn-od.zastavky.po.znacku.P  ┆ 2.482275                 │
│ Červená voda - Suchý vrch       ┆ 2.488056                 │
│ Pod Vilemínkou - Kralický Sněž… ┆ 2.492542                 │
│ Risova studanka - od zavory     ┆ 2.507177                 │
│ Sněžník od Děčína (po červené)  ┆ 2.528634                 │
│ Videlské sedlo-Švýcárna         ┆ 2.537729                 │
│ Muglinovská→Hradní lávka (po p… ┆ 2.660781                 │
│ Podél tratě do Úval             ┆ 2.686688                 │
│ svadov—valtirov                 ┆ 2.730017                 │
│ Sa Calobra - Coll dels Reis     ┆ 2.744107                 │
│ Luční bouda - Sněžka            ┆ 2.930938                 │
│ Pustevny - Radhošť              ┆ 2.961814                 │
│ Tříjezerní slať - Rokyta        ┆ 2.982105                 │
│ Cyklostezka Náchod -> Velké Po… ┆ 3.006125                 │
│ Černý důl konec Hoffmanky       ┆ 3.035668                 │
│ Plácky-soutok                   ┆ 3.064199                 │
│ Ruda -> Gerlovka                ┆ 3.126234                 │
│ Nové Lesy-Dvůr Králové          ┆ 3.134655                 │
│ Lysá hora - 5 km                ┆ 3.229545                 │
│ Sjezd Blatno-Březenec           ┆ 3.246378                 │
│ Alpe d'Huez                     ┆ 3.422275                 │
│ Revnicak Eve                    ┆ 3.429182                 │
│ Mutěnka - z Kyjova po odbočku … ┆ 3.458919                 │
│ Pec - Sněžka (přes Obřák)       ┆ 3.497416                 │
│ Lednice - Bulhary               ┆ 3.535302                 │
│ Údolí Svatý Jan                 ┆ 3.618147                 │
│ Sedmička, Lipno {               ┆ 3.651891                 │
│ Vlevo dole jezero Most          ┆ 3.698485                 │
│ Karlov - k Velkému kotli        ┆ 3.747321                 │
│ Jesenice-Blatno DH              ┆ 3.801644                 │
│ Soláň-Tanečnica                 ┆ 3.812561                 │
│ Čerťák - Ručičky (po modré)     ┆ 3.867048                 │
│ Máchovo kritérium - přes bory … ┆ 4.153776                 │
│ Trinec-Tesin                    ┆ 4.360789                 │
│ Srbsko - Hlásná Třebáň          ┆ 4.557374                 │
│ Maslovice - Kralupy             ┆ 4.687004                 │
│ Hrad Vevěří - Hráz              ┆ 4.790162                 │
│ Kvilda Bučina                   ┆ 5.008856                 │
│ Dlouhe Strane od Loucnej        ┆ 5.176626                 │
│ Bečva - Pustevny Uphill         ┆ 5.410356                 │
│ Hoštejn-Zábřeh                  ┆ 5.760825                 │
│ Papezov - Prazmo                ┆ 6.992833                 │
│ 2012 Pikes Peak Hill Climb      ┆ 9.013389                 │
│ Mont Ventoux (par Bedoin)       ┆ 9.156079                 │
│ Židlochovice -> Olympia         ┆ 9.643392                 │
│ Kerhartice-Choceň               ┆ 10.13598                 │
│ Podél dálnice                   ┆ 10.644463                │
│ Col du Tourmalet (par Luz-St-S… ┆ 12.706239                │
│ Passo Stelvio                   ┆ 13.390809                │
│ Decin - Bad Schandau Abzweig R… ┆ 14.292023                │
│ Hilo to Mauna Kea               ┆ 41.397707                │
└─────────────────────────────────┴──────────────────────────┘

In [195]:
df.with_columns(
   pl.struct(["start_latlng", "end_latlng"]).map(lambda x: haversine_distance(x["start_latlng"][0], x["start_latlng"][1], x["end_latlng"][0], x["end_latlng"][1])).alias("start_to_finish")
)

AttributeError: 'Expr' object has no attribute 'map'

In [91]:
df.with_columns(
    pl.map_elements(lambda x, y: calculate_distance(x, y), pl.col("start_latlng"), pl.col("end_latlng")).alias("start_to_finish")
)

AttributeError: module 'polars' has no attribute 'map_elements'

In [ ]:
df.with_columns(pl.struct(['start_latlng','end_latlng']) \
       .map_elements(lambda x: func(x['col_1'], x['col_2'])).alias('col_3'))

In [51]:
import datetime

In [52]:
df

shape: (6_640, 31)
┌──────────┬──────────────┬──────────────┬──────────────┬───┬──────────────┬──────────────┬─────────────┬────────────┐
│ id       ┆ resource_sta ┆ name         ┆ activity_typ ┆ … ┆ athlete_segm ┆ xoms         ┆ local_legen ┆ date       │
│ ---      ┆ te           ┆ ---          ┆ e            ┆   ┆ ent_stats    ┆ ---          ┆ d           ┆ ---        │
│ i64      ┆ ---          ┆ str          ┆ ---          ┆   ┆ ---          ┆ struct[4]    ┆ ---         ┆ str        │
│          ┆ i64          ┆              ┆ str          ┆   ┆ struct[6]    ┆              ┆ struct[7]   ┆            │
╞══════════╪══════════════╪══════════════╪══════════════╪═══╪══════════════╪══════════════╪═════════════╪════════════╡
│ 10186045 ┆ 3            ┆ Opičí        ┆ Ride         ┆ … ┆ {null,null,n ┆ {"1:33","2:0 ┆ {27344262," ┆ 1735077907 │
│          ┆              ┆ Časovka,     ┆              ┆   ┆ ull,null,nul ┆ 6","1:33",{" ┆ Petr Duřt", ┆            │
│          ┆              ┆ Podolská     ┆              ┆   ┆ l,0}         ┆ strava…      ┆ "https:/…   ┆            │
│          ┆              ┆ vodárn…      ┆              ┆   ┆              ┆              ┆             ┆            │
│ 10356069 ┆ 3            ┆ Kvilda       ┆ Ride         ┆ … ┆ {null,null,n ┆ {"10:47","13 ┆ {3478016,"T ┆ 1735077732 │
│          ┆              ┆ Bučina       ┆              ┆   ┆ ull,null,nul ┆ :11","10:47" ┆ yrel Fuchs" ┆            │
│          ┆              ┆              ┆              ┆   ┆ l,0}         ┆ ,{"str…      ┆ ,"https:…   ┆            │
│ 10356069 ┆ 3            ┆ Kvilda       ┆ Ride         ┆ … ┆ {null,null,n ┆ {"10:47","13 ┆ {3478016,"T ┆ 1735077914 │
│          ┆              ┆ Bučina       ┆              ┆   ┆ ull,null,nul ┆ :11","10:47" ┆ yrel Fuchs" ┆            │
│          ┆              ┆              ┆              ┆   ┆ l,0}         ┆ ,{"str…      ┆ ,"https:…   ┆            │
│ 11378514 ┆ 3            ┆ Park 1       ┆ Run          ┆ … ┆ {null,null,n ┆ {"2:15","2:1 ┆ {130038451, ┆ 1735077910 │
│          ┆              ┆              ┆              ┆   ┆ ull,null,nul ┆ 7","2:15",{" ┆ "Simona Tom ┆            │
│          ┆              ┆              ┆              ┆   ┆ l,0}         ┆ strava…      ┆ ášková",…   ┆            │
│ 11490813 ┆ 3            ┆ Interval     ┆ Run          ┆ … ┆ {230,"2024-0 ┆ {"2:45","3:2 ┆ {125532676, ┆ 1735077912 │
│          ┆              ┆              ┆              ┆   ┆ 4-24","only_ ┆ 9","2:45",{" ┆ "Filip Kraj ┆            │
│          ┆              ┆              ┆              ┆   ┆ me",11…      ┆ strava…      ┆ car","ht…   ┆            │
│ …        ┆ …            ┆ …            ┆ …            ┆ … ┆ …            ┆ …            ┆ …           ┆ …          │
│ 9125491  ┆ 3            ┆ Daskabát     ┆ Ride         ┆ … ┆ {null,null,n ┆ {"1:57","2:1 ┆ {120848052, ┆ 1736238151 │
│          ┆              ┆ flat         ┆              ┆   ┆ ull,null,nul ┆ 6","1:57",{" ┆ "Bretislav  ┆            │
│          ┆              ┆              ┆              ┆   ┆ l,0}         ┆ strava…      ┆ Pipal","…   ┆            │
│ 9153928  ┆ 3            ┆ Sprintík kři ┆ Ride         ┆ … ┆ {null,null,n ┆ {"4:08","5:0 ┆ {1225614,"  ┆ 1736237116 │
│          ┆              ┆ žovatka/skal ┆              ┆   ┆ ull,null,nul ┆ 6","4:08",{" ┆ 🔺£3️⃣💲 £🔺 ┆            │
│          ┆              ┆ ní mlý…      ┆              ┆   ┆ l,0}         ┆ strava…      ┆ K♉✝️🔺","ht ┆            │
│          ┆              ┆              ┆              ┆   ┆              ┆              ┆ t…          ┆            │
│ 9433317  ┆ 3            ┆ Třebešín-drá ┆ Ride         ┆ … ┆ {null,null,n ┆ {"17s","20s" ┆ {5959748,"H ┆ 1736238124 │
│          ┆              ┆ ha K         ┆              ┆   ┆ ull,null,nul ┆ ,"17s",{"str ┆ onza Kolář" ┆            │
│          ┆              ┆              ┆              ┆   ┆ l,0}         ┆ ava://…      ┆ ,"https:…   ┆            │
│ 9458674  ┆ 3            ┆ Zrucskej     ┆ Ride         ┆ … ┆ {null,null,n ┆ {"1:25","2:2 ┆ {149193634, ┆ 1736237139 │
│          ┆              ┆ smrtak       ┆              ┆   ┆ ull,null,nul ┆ 9","1:25",{" ┆ "Reno Ginte ┆            │
│          ┆              ┆              ┆              ┆   ┆ l,0}         ┆ strava…      ┆ r","http…   ┆            │
│ 9959344  ┆ 3            ┆ time trial   ┆ Ride         ┆ … ┆ {181,"2024-0 ┆ {"1:25","2:1 ┆ {118182015, ┆ 1736238127 │
│          ┆              ┆ at Svratka   ┆              ┆   ┆ 9-08","every ┆ 7","1:25",{" ┆ "Petr Stříb ┆            │
│          ┆              ┆              ┆              ┆   ┆ one",1…      ┆ strava…      ┆ ný","htt…   ┆            │
└──────────┴──────────────┴──────────────┴──────────────┴───┴──────────────┴──────────────┴─────────────┴────────────┘

In [53]:
df.with_columns(
    (pl.col("date").cast(pl.Int64))
)

shape: (6_640, 31)
┌──────────┬──────────────┬──────────────┬──────────────┬───┬──────────────┬──────────────┬─────────────┬────────────┐
│ id       ┆ resource_sta ┆ name         ┆ activity_typ ┆ … ┆ athlete_segm ┆ xoms         ┆ local_legen ┆ date       │
│ ---      ┆ te           ┆ ---          ┆ e            ┆   ┆ ent_stats    ┆ ---          ┆ d           ┆ ---        │
│ i64      ┆ ---          ┆ str          ┆ ---          ┆   ┆ ---          ┆ struct[4]    ┆ ---         ┆ i64        │
│          ┆ i64          ┆              ┆ str          ┆   ┆ struct[6]    ┆              ┆ struct[7]   ┆            │
╞══════════╪══════════════╪══════════════╪══════════════╪═══╪══════════════╪══════════════╪═════════════╪════════════╡
│ 10186045 ┆ 3            ┆ Opičí        ┆ Ride         ┆ … ┆ {null,null,n ┆ {"1:33","2:0 ┆ {27344262," ┆ 1735077907 │
│          ┆              ┆ Časovka,     ┆              ┆   ┆ ull,null,nul ┆ 6","1:33",{" ┆ Petr Duřt", ┆            │
│          ┆              ┆ Podolská     ┆              ┆   ┆ l,0}         ┆ strava…      ┆ "https:/…   ┆            │
│          ┆              ┆ vodárn…      ┆              ┆   ┆              ┆              ┆             ┆            │
│ 10356069 ┆ 3            ┆ Kvilda       ┆ Ride         ┆ … ┆ {null,null,n ┆ {"10:47","13 ┆ {3478016,"T ┆ 1735077732 │
│          ┆              ┆ Bučina       ┆              ┆   ┆ ull,null,nul ┆ :11","10:47" ┆ yrel Fuchs" ┆            │
│          ┆              ┆              ┆              ┆   ┆ l,0}         ┆ ,{"str…      ┆ ,"https:…   ┆            │
│ 10356069 ┆ 3            ┆ Kvilda       ┆ Ride         ┆ … ┆ {null,null,n ┆ {"10:47","13 ┆ {3478016,"T ┆ 1735077914 │
│          ┆              ┆ Bučina       ┆              ┆   ┆ ull,null,nul ┆ :11","10:47" ┆ yrel Fuchs" ┆            │
│          ┆              ┆              ┆              ┆   ┆ l,0}         ┆ ,{"str…      ┆ ,"https:…   ┆            │
│ 11378514 ┆ 3            ┆ Park 1       ┆ Run          ┆ … ┆ {null,null,n ┆ {"2:15","2:1 ┆ {130038451, ┆ 1735077910 │
│          ┆              ┆              ┆              ┆   ┆ ull,null,nul ┆ 7","2:15",{" ┆ "Simona Tom ┆            │
│          ┆              ┆              ┆              ┆   ┆ l,0}         ┆ strava…      ┆ ášková",…   ┆            │
│ 11490813 ┆ 3            ┆ Interval     ┆ Run          ┆ … ┆ {230,"2024-0 ┆ {"2:45","3:2 ┆ {125532676, ┆ 1735077912 │
│          ┆              ┆              ┆              ┆   ┆ 4-24","only_ ┆ 9","2:45",{" ┆ "Filip Kraj ┆            │
│          ┆              ┆              ┆              ┆   ┆ me",11…      ┆ strava…      ┆ car","ht…   ┆            │
│ …        ┆ …            ┆ …            ┆ …            ┆ … ┆ …            ┆ …            ┆ …           ┆ …          │
│ 9125491  ┆ 3            ┆ Daskabát     ┆ Ride         ┆ … ┆ {null,null,n ┆ {"1:57","2:1 ┆ {120848052, ┆ 1736238151 │
│          ┆              ┆ flat         ┆              ┆   ┆ ull,null,nul ┆ 6","1:57",{" ┆ "Bretislav  ┆            │
│          ┆              ┆              ┆              ┆   ┆ l,0}         ┆ strava…      ┆ Pipal","…   ┆            │
│ 9153928  ┆ 3            ┆ Sprintík kři ┆ Ride         ┆ … ┆ {null,null,n ┆ {"4:08","5:0 ┆ {1225614,"  ┆ 1736237116 │
│          ┆              ┆ žovatka/skal ┆              ┆   ┆ ull,null,nul ┆ 6","4:08",{" ┆ 🔺£3️⃣💲 £🔺 ┆            │
│          ┆              ┆ ní mlý…      ┆              ┆   ┆ l,0}         ┆ strava…      ┆ K♉✝️🔺","ht ┆            │
│          ┆              ┆              ┆              ┆   ┆              ┆              ┆ t…          ┆            │
│ 9433317  ┆ 3            ┆ Třebešín-drá ┆ Ride         ┆ … ┆ {null,null,n ┆ {"17s","20s" ┆ {5959748,"H ┆ 1736238124 │
│          ┆              ┆ ha K         ┆              ┆   ┆ ull,null,nul ┆ ,"17s",{"str ┆ onza Kolář" ┆            │
│          ┆              ┆              ┆              ┆   ┆ l,0}         ┆ ava://…      ┆ ,"https:…   ┆            │
│ 9458674  ┆ 3            ┆ Zrucskej     ┆ Ride         ┆ … ┆ {null,null,n ┆ {"1:25","2:2 ┆ {149193634, ┆ 1736237139 │
│          ┆              ┆ smrtak       ┆              ┆   ┆ ull,null,nul ┆ 9","1:25",{" ┆ "Reno Ginte ┆            │
│          ┆              ┆              ┆              ┆   ┆ l,0}         ┆ strava…      ┆ r","http…   ┆            │
│ 9959344  ┆ 3            ┆ time trial   ┆ Ride         ┆ … ┆ {181,"2024-0 ┆ {"1:25","2:1 ┆ {118182015, ┆ 1736238127 │
│          ┆              ┆ at Svratka   ┆              ┆   ┆ 9-08","every ┆ 7","1:25",{" ┆ "Petr Stříb ┆            │
│          ┆              ┆              ┆              ┆   ┆ one",1…      ┆ strava…      ┆ ný","htt…   ┆            │
└──────────┴──────────────┴──────────────┴──────────────┴───┴──────────────┴──────────────┴─────────────┴────────────┘

In [54]:
df = df.with_columns(
    (pl.col("date").cast(pl.Int64) * 1000000).cast(pl.Datetime(time_zone='CET'))
)

In [55]:
df.sort("date").group_by_dynamic("date", every="1d").agg(pl.col("effort_count").sum())

shape: (15, 2)
┌─────────────────────────┬──────────────┐
│ date                    ┆ effort_count │
│ ---                     ┆ ---          │
│ datetime[μs, CET]       ┆ i64          │
╞═════════════════════════╪══════════════╡
│ 2024-12-24 00:00:00 CET ┆ 1902247      │
│ 2024-12-25 00:00:00 CET ┆ 7384499      │
│ 2024-12-26 00:00:00 CET ┆ 10513226     │
│ 2024-12-27 00:00:00 CET ┆ 18965770     │
│ 2024-12-28 00:00:00 CET ┆ 29467674     │
│ …                       ┆ …            │
│ 2025-01-03 00:00:00 CET ┆ 29497016     │
│ 2025-01-04 00:00:00 CET ┆ 29502458     │
│ 2025-01-05 00:00:00 CET ┆ 29507482     │
│ 2025-01-06 00:00:00 CET ┆ 29510895     │
│ 2025-01-07 00:00:00 CET ┆ 14756680     │
└─────────────────────────┴──────────────┘

In [56]:
df.filter(pl.col('date').dt.hour() == 23).sort("date").group_by_dynamic("date", every="1d").agg(pl.col("effort_count").sum())

shape: (14, 2)
┌─────────────────────────┬──────────────┐
│ date                    ┆ effort_count │
│ ---                     ┆ ---          │
│ datetime[μs, CET]       ┆ i64          │
╞═════════════════════════╪══════════════╡
│ 2024-12-24 00:00:00 CET ┆ 1902247      │
│ 2024-12-25 00:00:00 CET ┆ 5124263      │
│ 2024-12-26 00:00:00 CET ┆ 3811608      │
│ 2024-12-27 00:00:00 CET ┆ 14698890     │
│ 2024-12-28 00:00:00 CET ┆ 14734637     │
│ …                       ┆ …            │
│ 2025-01-02 00:00:00 CET ┆ 14747390     │
│ 2025-01-03 00:00:00 CET ┆ 14749551     │
│ 2025-01-04 00:00:00 CET ┆ 14752780     │
│ 2025-01-05 00:00:00 CET ┆ 14754528     │
│ 2025-01-06 00:00:00 CET ┆ 14756258     │
└─────────────────────────┴──────────────┘

In [57]:
df.filter(pl.col("city") == "Brno").filter(pl.col('total_elevation_gain') > 5).filter(pl.col('date').dt.hour() == 23).sort("date").group_by_dynamic("date", every="1d").agg(pl.col("effort_count").sum())

shape: (14, 2)
┌─────────────────────────┬──────────────┐
│ date                    ┆ effort_count │
│ ---                     ┆ ---          │
│ datetime[μs, CET]       ┆ i64          │
╞═════════════════════════╪══════════════╡
│ 2024-12-24 00:00:00 CET ┆ 220886       │
│ 2024-12-25 00:00:00 CET ┆ 443249       │
│ 2024-12-26 00:00:00 CET ┆ 221568       │
│ 2024-12-27 00:00:00 CET ┆ 221618       │
│ 2024-12-28 00:00:00 CET ┆ 221597       │
│ …                       ┆ …            │
│ 2025-01-02 00:00:00 CET ┆ 221819       │
│ 2025-01-03 00:00:00 CET ┆ 221836       │
│ 2025-01-04 00:00:00 CET ┆ 221901       │
│ 2025-01-05 00:00:00 CET ┆ 221935       │
│ 2025-01-06 00:00:00 CET ┆ 221954       │
└─────────────────────────┴──────────────┘

In [58]:
df.filter(pl.col("city") == "Brno").filter(pl.col('date').dt.hour() == 23).sort("date").group_by_dynamic("date", every="1d").agg(pl.col("effort_count").sum())

shape: (14, 2)
┌─────────────────────────┬──────────────┐
│ date                    ┆ effort_count │
│ ---                     ┆ ---          │
│ datetime[μs, CET]       ┆ i64          │
╞═════════════════════════╪══════════════╡
│ 2024-12-24 00:00:00 CET ┆ 269552       │
│ 2024-12-25 00:00:00 CET ┆ 491939       │
│ 2024-12-26 00:00:00 CET ┆ 411880       │
│ 2024-12-27 00:00:00 CET ┆ 1500485      │
│ 2024-12-28 00:00:00 CET ┆ 1500683      │
│ …                       ┆ …            │
│ 2025-01-02 00:00:00 CET ┆ 1501565      │
│ 2025-01-03 00:00:00 CET ┆ 1501616      │
│ 2025-01-04 00:00:00 CET ┆ 1501873      │
│ 2025-01-05 00:00:00 CET ┆ 1502051      │
│ 2025-01-06 00:00:00 CET ┆ 1502528      │
└─────────────────────────┴──────────────┘

In [59]:
df.filter(pl.col("name") == "Risova studanka - od zavory").filter(pl.col('date').dt.hour() == 23).sort("date").group_by_dynamic("date", every="1d").agg(pl.col("effort_count").sum())

shape: (14, 2)
┌─────────────────────────┬──────────────┐
│ date                    ┆ effort_count │
│ ---                     ┆ ---          │
│ datetime[μs, CET]       ┆ i64          │
╞═════════════════════════╪══════════════╡
│ 2024-12-24 00:00:00 CET ┆ 41326        │
│ 2024-12-25 00:00:00 CET ┆ 82656        │
│ 2024-12-26 00:00:00 CET ┆ 41336        │
│ 2024-12-27 00:00:00 CET ┆ 41351        │
│ 2024-12-28 00:00:00 CET ┆ 41360        │
│ …                       ┆ …            │
│ 2025-01-02 00:00:00 CET ┆ 41388        │
│ 2025-01-03 00:00:00 CET ┆ 41389        │
│ 2025-01-04 00:00:00 CET ┆ 41392        │
│ 2025-01-05 00:00:00 CET ┆ 41396        │
│ 2025-01-06 00:00:00 CET ┆ 41396        │
└─────────────────────────┴──────────────┘

In [60]:
df.filter(pl.col("name") == "tenis 1K").filter(pl.col('date').dt.hour() == 23).sort("date").group_by_dynamic("date", every="1d").agg(pl.col("effort_count").sum())

shape: (14, 2)
┌─────────────────────────┬──────────────┐
│ date                    ┆ effort_count │
│ ---                     ┆ ---          │
│ datetime[μs, CET]       ┆ i64          │
╞═════════════════════════╪══════════════╡
│ 2024-12-24 00:00:00 CET ┆ 48666        │
│ 2024-12-25 00:00:00 CET ┆ 48690        │
│ 2024-12-26 00:00:00 CET ┆ 48725        │
│ 2024-12-27 00:00:00 CET ┆ 48738        │
│ 2024-12-28 00:00:00 CET ┆ 48761        │
│ …                       ┆ …            │
│ 2025-01-02 00:00:00 CET ┆ 48898        │
│ 2025-01-03 00:00:00 CET ┆ 48917        │
│ 2025-01-04 00:00:00 CET ┆ 48945        │
│ 2025-01-05 00:00:00 CET ┆ 48994        │
│ 2025-01-06 00:00:00 CET ┆ 49020        │
└─────────────────────────┴──────────────┘

In [61]:
df.filter(pl.col("city") == "Brno")

shape: (239, 31)
┌──────────┬──────────────┬──────────────┬──────────────┬───┬──────────────┬─────────────┬─────────────┬─────────────┐
│ id       ┆ resource_sta ┆ name         ┆ activity_typ ┆ … ┆ athlete_segm ┆ xoms        ┆ local_legen ┆ date        │
│ ---      ┆ te           ┆ ---          ┆ e            ┆   ┆ ent_stats    ┆ ---         ┆ d           ┆ ---         │
│ i64      ┆ ---          ┆ str          ┆ ---          ┆   ┆ ---          ┆ struct[4]   ┆ ---         ┆ datetime[μs │
│          ┆ i64          ┆              ┆ str          ┆   ┆ struct[6]    ┆             ┆ struct[7]   ┆ , CET]      │
╞══════════╪══════════════╪══════════════╪══════════════╪═══╪══════════════╪═════════════╪═════════════╪═════════════╡
│ 2645185  ┆ 3            ┆ Junglepark   ┆ Run          ┆ … ┆ {98,"2023-03 ┆ {"1:03","1: ┆ {134435067, ┆ 2024-12-24  │
│          ┆              ┆              ┆              ┆   ┆ -27","everyo ┆ 16","1:03", ┆ "Peter Feck ┆ 23:05:13    │
│          ┆              ┆              ┆              ┆   ┆ ne",87…      ┆ {"strava…   ┆ anic","h…   ┆ CET         │
│ 7116683  ┆ 3            ┆ Risova       ┆ Ride         ┆ … ┆ {603,"2024-0 ┆ {"5:46","7: ┆ {6149474,"R ┆ 2024-12-24  │
│          ┆              ┆ studanka -   ┆              ┆   ┆ 9-08","every ┆ 18","5:46", ┆ obert Šmíd" ┆ 23:05:01    │
│          ┆              ┆ od zavory    ┆              ┆   ┆ one",1…      ┆ {"strava…   ┆ ,"https:…   ┆ CET         │
│ 8716919  ┆ 3            ┆ tenis 1K     ┆ Run          ┆ … ┆ {220,"2022-1 ┆ {"2:53","3: ┆ {31296919," ┆ 2024-12-24  │
│          ┆              ┆              ┆              ┆   ┆ 1-30","every ┆ 28","2:53", ┆ Jan Pavelka ┆ 23:05:07    │
│          ┆              ┆              ┆              ┆   ┆ one",8…      ┆ {"strava…   ┆ ","https…   ┆ CET         │
│ 9959344  ┆ 3            ┆ time trial   ┆ Ride         ┆ … ┆ {181,"2024-0 ┆ {"1:25","2: ┆ {118182015, ┆ 2024-12-24  │
│          ┆              ┆ at Svratka   ┆              ┆   ┆ 9-08","every ┆ 17","1:25", ┆ "Petr Stříb ┆ 23:05:08    │
│          ┆              ┆              ┆              ┆   ┆ one",1…      ┆ {"strava…   ┆ ný","htt…   ┆ CET         │
│ 2645185  ┆ 3            ┆ Junglepark   ┆ Run          ┆ … ┆ {98,"2023-03 ┆ {"1:03","1: ┆ {134435067, ┆ 2024-12-25  │
│          ┆              ┆              ┆              ┆   ┆ -27","everyo ┆ 16","1:03", ┆ "Peter Feck ┆ 09:05:02    │
│          ┆              ┆              ┆              ┆   ┆ ne",87…      ┆ {"strava…   ┆ anic","h…   ┆ CET         │
│ …        ┆ …            ┆ …            ┆ …            ┆ … ┆ …            ┆ …           ┆ …           ┆ …           │
│ 36737042 ┆ 3            ┆ Kočičí žleb  ┆ Hike         ┆ … ┆ {null,null,n ┆ {"6:46","16 ┆ {32488360," ┆ 2025-01-07  │
│          ┆              ┆ - Ríšova     ┆              ┆   ┆ ull,null,nul ┆ :23","6:46" ┆ Lukáš Rosík ┆ 09:05:17    │
│          ┆              ┆ studánka     ┆              ┆   ┆ l,0}         ┆ ,{"strav…   ┆ ","https…   ┆ CET         │
│ 7064976  ┆ 3            ┆ Die Eine     ┆ Ride         ┆ … ┆ {null,null,n ┆ {"18s","18s ┆ {19684938," ┆ 2025-01-07  │
│          ┆              ┆ Runde        ┆              ┆   ┆ ull,null,nul ┆ ","18s",{"s ┆ eda 000","h ┆ 09:05:28    │
│          ┆              ┆              ┆              ┆   ┆ l,0}         ┆ trava://…   ┆ ttps://d…   ┆ CET         │
│ 7116683  ┆ 3            ┆ Risova       ┆ Ride         ┆ … ┆ {603,"2024-0 ┆ {"5:46","7: ┆ {6149474,"R ┆ 2025-01-07  │
│          ┆              ┆ studanka -   ┆              ┆   ┆ 9-08","every ┆ 18","5:46", ┆ obert Šmíd" ┆ 09:22:14    │
│          ┆              ┆ od zavory    ┆              ┆   ┆ one",1…      ┆ {"strava…   ┆ ,"https:…   ┆ CET         │
│ 8716919  ┆ 3            ┆ tenis 1K     ┆ Run          ┆ … ┆ {220,"2022-1 ┆ {"2:53","3: ┆ {31296919," ┆ 2025-01-07  │
│          ┆              ┆              ┆              ┆   ┆ 1-30","every ┆ 28","2:53", ┆ Jan Pavelka ┆ 09:05:14    │
│          ┆              ┆              ┆              ┆   ┆ one",8…      ┆ {"strava…   ┆ ","https…   ┆ CET         │
│ 9959344  ┆ 3            ┆ time trial   ┆ Ride         ┆ … ┆ {181,"2024-0 ┆ {"1:25","2: ┆ {118182015, ┆ 2025-01-07  │
│          ┆              ┆ at Svratka   ┆              ┆   ┆ 9-08","every ┆ 17","1:25", ┆ "Petr Stříb ┆ 09:22:07    │
│          ┆              ┆              ┆              ┆   ┆ one",1…      ┆ {"strava…   ┆ ný","htt…   ┆ CET         │
└──────────┴──────────────┴──────────────┴──────────────┴───┴──────────────┴─────────────┴─────────────┴─────────────┘