In [22]:
import os
import urllib.request

In [23]:
url = "https://opendata.chmi.cz/meteorology/climate/historical_csv/data/daily/temperature/dly-0-203-0-11514-T.csv"
output_dir = "data_raw"

# Extract the filename from the end of the URL
filename = "klementinum_teplota_" + url.split("/")[-1]
file_path = os.path.join(output_dir, filename)

# Create the 'data_raw' directory if it doesn't already exist
os.makedirs(output_dir, exist_ok=True)

print(f"Downloading {filename}...")

# Download and save the file
try:
    urllib.request.urlretrieve(url, file_path)
    print(f"Success! File saved to: {file_path}")
except Exception as e:
    print(f"An error occurred during download: {e}")

Downloading klementinum_teplota_dly-0-203-0-11514-T.csv...
Success! File saved to: data_raw\klementinum_teplota_dly-0-203-0-11514-T.csv

In [24]:
url = "https://opendata.chmi.cz/meteorology/climate/historical_csv/data/daily/humidity/dly-0-203-0-11514-H.csv"
output_dir = "data_raw"

# Extract the filename from the end of the URL
filename = "klementinum_vlhkost_" + url.split("/")[-1]
file_path = os.path.join(output_dir, filename)

# Create the 'data_raw' directory if it doesn't already exist
os.makedirs(output_dir, exist_ok=True)

print(f"Downloading {filename}...")

# Download and save the file
try:
    urllib.request.urlretrieve(url, file_path)
    print(f"Success! File saved to: {file_path}")
except Exception as e:
    print(f"An error occurred during download: {e}")

Downloading klementinum_vlhkost_dly-0-203-0-11514-H.csv...
Success! File saved to: data_raw\klementinum_vlhkost_dly-0-203-0-11514-H.csv

In [25]:
url = "https://opendata.chmi.cz/meteorology/climate/historical_csv/data/daily/sunshine/dly-0-203-0-11514-SSV.csv"
output_dir = "data_raw"

# Extract the filename from the end of the URL
filename = "klementinum_slunecni_svit_" + url.split("/")[-1]
file_path = os.path.join(output_dir, filename)

# Create the 'data_raw' directory if it doesn't already exist
os.makedirs(output_dir, exist_ok=True)

print(f"Downloading {filename}...")

# Download and save the file
try:
    urllib.request.urlretrieve(url, file_path)
    print(f"Success! File saved to: {file_path}")
except Exception as e:
    print(f"An error occurred during download: {e}")

Downloading klementinum_slunecni_svit_dly-0-203-0-11514-SSV.csv...
Success! File saved to: data_raw\klementinum_slunecni_svit_dly-0-203-0-11514-SSV.csv

In [26]:
url = "https://opendata.chmi.cz/meteorology/climate/historical_csv/data/daily/precipitation/dly-0-203-0-11514-SRA.csv"
output_dir = "data_raw"

# Extract the filename from the end of the URL
filename = "klementinum_srazky_" + url.split("/")[-1]
file_path = os.path.join(output_dir, filename)

# Create the 'data_raw' directory if it doesn't already exist
os.makedirs(output_dir, exist_ok=True)

print(f"Downloading {filename}...")

# Download and save the file
try:
    urllib.request.urlretrieve(url, file_path)
    print(f"Success! File saved to: {file_path}")
except Exception as e:
    print(f"An error occurred during download: {e}")

Downloading klementinum_srazky_dly-0-203-0-11514-SRA.csv...
Success! File saved to: data_raw\klementinum_srazky_dly-0-203-0-11514-SRA.csv

In [27]:
url = "https://opendata.chmi.cz/meteorology/climate/historical_csv/data/daily/snow/dly-0-203-0-11514-SCEdif.csv"
output_dir = "data_raw"

# Extract the filename from the end of the URL
filename = "klementinum_snih_" + url.split("/")[-1]
file_path = os.path.join(output_dir, filename)

# Create the 'data_raw' directory if it doesn't already exist
os.makedirs(output_dir, exist_ok=True)

print(f"Downloading {filename}...")

# Download and save the file
try:
    urllib.request.urlretrieve(url, file_path)
    print(f"Success! File saved to: {file_path}")
except Exception as e:
    print(f"An error occurred during download: {e}")

Downloading klementinum_snih_dly-0-203-0-11514-SCEdif.csv...
Success! File saved to: data_raw\klementinum_snih_dly-0-203-0-11514-SCEdif.csv

In [28]:
import polars as pl

In [29]:
pl.read_csv("data_raw/klementinum_snih_dly-0-203-0-11514-SCEdif.csv")

shape: (44_560, 8)
┌───────────────┬─────────┬──────────┬───────────────────┬───────┬──────┬─────────┬──────┐
│ STATION       ┆ ELEMENT ┆ TIMEFUNC ┆ DT                ┆ VALUE ┆ FLAG ┆ QUALITY ┆      │
│ ---           ┆ ---     ┆ ---      ┆ ---               ┆ ---   ┆ ---  ┆ ---     ┆ ---  │
│ str           ┆ str     ┆ str      ┆ str               ┆ str   ┆ str  ┆ f64     ┆ str  │
╞═══════════════╪═════════╪══════════╪═══════════════════╪═══════╪══════╪═════════╪══════╡
│ 0-203-0-11514 ┆ SCEdif  ┆ 06:00    ┆ 1901-01-01T06:00Z ┆ null  ┆ null ┆ 4.0     ┆ null │
│ 0-203-0-11514 ┆ SCEdif  ┆ 06:00    ┆ 1901-01-02T06:00Z ┆ null  ┆ null ┆ 4.0     ┆ null │
│ 0-203-0-11514 ┆ SCEdif  ┆ 06:00    ┆ 1901-01-03T06:00Z ┆ null  ┆ null ┆ 4.0     ┆ null │
│ 0-203-0-11514 ┆ SCEdif  ┆ 06:00    ┆ 1901-01-04T06:00Z ┆ null  ┆ null ┆ 4.0     ┆ null │
│ 0-203-0-11514 ┆ SCEdif  ┆ 06:00    ┆ 1901-01-05T06:00Z ┆ null  ┆ null ┆ 4.0     ┆ null │
│ …             ┆ …       ┆ …        ┆ …                 ┆ …     ┆ …    ┆ …       ┆ …    │
│ 0-203-0-11514 ┆ SCEdif  ┆ 06:00    ┆ 2022-12-27T06:00Z ┆ 0.0   ┆ null ┆ 0.0     ┆ null │
│ 0-203-0-11514 ┆ SCEdif  ┆ 06:00    ┆ 2022-12-28T06:00Z ┆ 0.0   ┆ null ┆ 0.0     ┆ null │
│ 0-203-0-11514 ┆ SCEdif  ┆ 06:00    ┆ 2022-12-29T06:00Z ┆ 0.0   ┆ null ┆ 0.0     ┆ null │
│ 0-203-0-11514 ┆ SCEdif  ┆ 06:00    ┆ 2022-12-30T06:00Z ┆ 0.0   ┆ null ┆ 0.0     ┆ null │
│ 0-203-0-11514 ┆ SCEdif  ┆ 06:00    ┆ 2022-12-31T06:00Z ┆ 0.0   ┆ null ┆ 0.0     ┆ null │
└───────────────┴─────────┴──────────┴───────────────────┴───────┴──────┴─────────┴──────┘

In [33]:
pl.concat(
    [
     #    pl.read_csv("data_raw/klementinum_snih_dly-0-203-0-11514-SNO.csv").with_columns(pl.col("DT").str.slice(0,10).str.to_date()).with_columns(pl.lit("snih").alias("co")),
        pl.read_csv("data_raw/klementinum_srazky_dly-0-203-0-11514-SRA.csv").with_columns(pl.col("DT").str.slice(0,10).str.to_date()).with_columns(pl.lit("srazky").alias("co")),
        pl.read_csv("data_raw/klementinum_slunecni_svit_dly-0-203-0-11514-SSV.csv").with_columns(pl.col("DT").str.slice(0,10).str.to_date()).with_columns(pl.lit("slunecni_svit").alias("co")),
        pl.read_csv("data_raw/klementinum_teplota_dly-0-203-0-11514-T.csv").with_columns(pl.col("DT").str.slice(0,10).str.to_date()).with_columns(pl.lit("teplota").alias("co")),
        pl.read_csv("data_raw/klementinum_vlhkost_dly-0-203-0-11514-H.csv").with_columns(pl.col("DT").str.slice(0,10).str.to_date()).with_columns(pl.lit("vlhkost").alias("co"))
    ]
)

shape: (737_309, 9)
┌───────────────┬─────────┬──────────┬────────────┬───┬──────┬─────────┬──────┬─────────┐
│ STATION       ┆ ELEMENT ┆ TIMEFUNC ┆ DT         ┆ … ┆ FLAG ┆ QUALITY ┆      ┆ co      │
│ ---           ┆ ---     ┆ ---      ┆ ---        ┆   ┆ ---  ┆ ---     ┆ ---  ┆ ---     │
│ str           ┆ str     ┆ str      ┆ date       ┆   ┆ str  ┆ f64     ┆ str  ┆ str     │
╞═══════════════╪═════════╪══════════╪════════════╪═══╪══════╪═════════╪══════╪═════════╡
│ 0-203-0-11514 ┆ SRA     ┆ 06:00    ┆ 1804-05-01 ┆ … ┆ null ┆ 0.0     ┆ null ┆ srazky  │
│ 0-203-0-11514 ┆ SRA     ┆ 06:00    ┆ 1804-05-02 ┆ … ┆ null ┆ 0.0     ┆ null ┆ srazky  │
│ 0-203-0-11514 ┆ SRA     ┆ 06:00    ┆ 1804-05-03 ┆ … ┆ null ┆ 0.0     ┆ null ┆ srazky  │
│ 0-203-0-11514 ┆ SRA     ┆ 06:00    ┆ 1804-05-04 ┆ … ┆ null ┆ 0.0     ┆ null ┆ srazky  │
│ 0-203-0-11514 ┆ SRA     ┆ 06:00    ┆ 1804-05-05 ┆ … ┆ null ┆ 0.0     ┆ null ┆ srazky  │
│ …             ┆ …       ┆ …        ┆ …          ┆ … ┆ …    ┆ …       ┆ …    ┆ …       │
│ 0-203-0-11514 ┆ H       ┆ 20:00    ┆ 2025-12-27 ┆ … ┆ null ┆ 0.0     ┆ null ┆ vlhkost │
│ 0-203-0-11514 ┆ H       ┆ 20:00    ┆ 2025-12-28 ┆ … ┆ null ┆ 0.0     ┆ null ┆ vlhkost │
│ 0-203-0-11514 ┆ H       ┆ 20:00    ┆ 2025-12-29 ┆ … ┆ null ┆ 0.0     ┆ null ┆ vlhkost │
│ 0-203-0-11514 ┆ H       ┆ 20:00    ┆ 2025-12-30 ┆ … ┆ null ┆ 0.0     ┆ null ┆ vlhkost │
│ 0-203-0-11514 ┆ H       ┆ 20:00    ┆ 2025-12-31 ┆ … ┆ null ┆ 0.0     ┆ null ┆ vlhkost │
└───────────────┴─────────┴──────────┴────────────┴───┴──────┴─────────┴──────┴─────────┘

In [37]:
pl.concat(
    [
  #      pl.read_csv("data_raw/klementinum_snih_dly-0-203-0-11514-SNO.csv").with_columns(pl.col("DT").str.slice(0,10).str.to_date()).with_columns(pl.lit("snih").alias("co")),
        pl.read_csv("data_raw/klementinum_srazky_dly-0-203-0-11514-SRA.csv").with_columns(pl.col("DT").str.slice(0,10).str.to_date()).with_columns(pl.lit("srazky").alias("co")),
        pl.read_csv("data_raw/klementinum_slunecni_svit_dly-0-203-0-11514-SSV.csv").with_columns(pl.col("DT").str.slice(0,10).str.to_date()).with_columns(pl.lit("slunecni_svit").alias("co")),
        pl.read_csv("data_raw/klementinum_teplota_dly-0-203-0-11514-T.csv").with_columns(pl.col("DT").str.slice(0,10).str.to_date()).with_columns(pl.lit("teplota").alias("co")),
        pl.read_csv("data_raw/klementinum_vlhkost_dly-0-203-0-11514-H.csv").with_columns(pl.col("DT").str.slice(0,10).str.to_date()).with_columns(pl.lit("vlhkost").alias("co"))
    ]
).filter(
    pl.col('DT').dt.year() >= 2024
).write_parquet(
    os.path.join('data','pocasi_klementinum.parquet')
)