In [1]:
import os
import json

In [5]:
data_raw = "data_raw/segments"

In [7]:
os.makedirs(data_raw, exist_ok=True)

In [17]:
done = [x.replace('.json','') for x in os.listdir(data_raw)]

In [13]:
source_folders = os.listdir('downloads/segments')

In [15]:
source_folders

['2024-12-24',
 '2024-12-25',
 '2024-12-26',
 '2024-12-27',
 '2024-12-28',
 '2024-12-29',
 '2024-12-30',
 '2024-12-31']

In [137]:
for s in source_folders:
    if s not in done:
        print(s)
        day = []
        for f in os.listdir(f'downloads/segments/{s}'):
            time = f.split('_')[1].split('.')[0]
            with open(os.path.join(f'downloads/segments/{s}', f), 'r', encoding='utf-8') as file:
                segment = json.loads(file.read())
                segment['date'] = time
                day.append(segment)
        df = pl.DataFrame(day)
        df.write_parquet(os.path.join(data_raw, f'{s}.parquet'))
        with open(os.path.join(data_raw, f'{s}.json'), 'w+', encoding='utf-8') as export:
            export.write(json.dumps(day))

2024-12-24
2024-12-25
2024-12-26
2024-12-27
2024-12-28
2024-12-29
2024-12-30
2024-12-31

In [20]:
import polars as pl

In [139]:
df = pl.read_parquet(os.path.join('data_raw/segments','*.parquet'))

In [59]:
import datetime

In [141]:
df

shape: (3_247, 31)
┌──────────┬───────────────┬──────────────┬──────────────┬───┬──────────────┬──────────────┬──────────────┬────────────┐
│ id       ┆ resource_stat ┆ name         ┆ activity_typ ┆ … ┆ athlete_segm ┆ xoms         ┆ local_legend ┆ date       │
│ ---      ┆ e             ┆ ---          ┆ e            ┆   ┆ ent_stats    ┆ ---          ┆ ---          ┆ ---        │
│ i64      ┆ ---           ┆ str          ┆ ---          ┆   ┆ ---          ┆ struct[4]    ┆ struct[7]    ┆ str        │
│          ┆ i64           ┆              ┆ str          ┆   ┆ struct[6]    ┆              ┆              ┆            │
╞══════════╪═══════════════╪══════════════╪══════════════╪═══╪══════════════╪══════════════╪══════════════╪════════════╡
│ 10186045 ┆ 3             ┆ Opičí        ┆ Ride         ┆ … ┆ {null,null,n ┆ {"1:33","2:0 ┆ {27344262,"P ┆ 1735077907 │
│          ┆               ┆ Časovka,     ┆              ┆   ┆ ull,null,nul ┆ 6","1:33",{" ┆ etr Duřt","h ┆            │
│          ┆               ┆ Podolská     ┆              ┆   ┆ l,0}         ┆ strava…      ┆ ttps:/…      ┆            │
│          ┆               ┆ vodárn…      ┆              ┆   ┆              ┆              ┆              ┆            │
│ 10356069 ┆ 3             ┆ Kvilda       ┆ Ride         ┆ … ┆ {null,null,n ┆ {"10:47","13 ┆ {3478016,"Ty ┆ 1735077732 │
│          ┆               ┆ Bučina       ┆              ┆   ┆ ull,null,nul ┆ :11","10:47" ┆ rel Fuchs"," ┆            │
│          ┆               ┆              ┆              ┆   ┆ l,0}         ┆ ,{"str…      ┆ https:…      ┆            │
│ 10356069 ┆ 3             ┆ Kvilda       ┆ Ride         ┆ … ┆ {null,null,n ┆ {"10:47","13 ┆ {3478016,"Ty ┆ 1735077914 │
│          ┆               ┆ Bučina       ┆              ┆   ┆ ull,null,nul ┆ :11","10:47" ┆ rel Fuchs"," ┆            │
│          ┆               ┆              ┆              ┆   ┆ l,0}         ┆ ,{"str…      ┆ https:…      ┆            │
│ 11378514 ┆ 3             ┆ Park 1       ┆ Run          ┆ … ┆ {null,null,n ┆ {"2:15","2:1 ┆ {130038451," ┆ 1735077910 │
│          ┆               ┆              ┆              ┆   ┆ ull,null,nul ┆ 7","2:15",{" ┆ Simona       ┆            │
│          ┆               ┆              ┆              ┆   ┆ l,0}         ┆ strava…      ┆ Tomášková",… ┆            │
│ 11490813 ┆ 3             ┆ Interval     ┆ Run          ┆ … ┆ {230,"2024-0 ┆ {"2:45","3:2 ┆ {125532676," ┆ 1735077912 │
│          ┆               ┆              ┆              ┆   ┆ 4-24","only_ ┆ 9","2:45",{" ┆ Filip Krajca ┆            │
│          ┆               ┆              ┆              ┆   ┆ me",11…      ┆ strava…      ┆ r","ht…      ┆            │
│ …        ┆ …             ┆ …            ┆ …            ┆ … ┆ …            ┆ …            ┆ …            ┆ …          │
│ 9125491  ┆ 3             ┆ Daskabát     ┆ Ride         ┆ … ┆ {null,null,n ┆ {"1:57","2:1 ┆ {120848052," ┆ 1735683716 │
│          ┆               ┆ flat         ┆              ┆   ┆ ull,null,nul ┆ 6","1:57",{" ┆ Bretislav    ┆            │
│          ┆               ┆              ┆              ┆   ┆ l,0}         ┆ strava…      ┆ Pipal","…    ┆            │
│ 9153928  ┆ 3             ┆ Sprintík kři ┆ Ride         ┆ … ┆ {null,null,n ┆ {"4:08","5:0 ┆ {1225614,"🔺 ┆ 1735682734 │
│          ┆               ┆ žovatka/skal ┆              ┆   ┆ ull,null,nul ┆ 6","4:08",{" ┆ £3️⃣💲 £🔺K♉ ┆            │
│          ┆               ┆ ní mlý…      ┆              ┆   ┆ l,0}         ┆ strava…      ┆ ✝️🔺","htt…  ┆            │
│ 9433317  ┆ 3             ┆ Třebešín-drá ┆ Ride         ┆ … ┆ {null,null,n ┆ {"17s","20s" ┆ {5959748,"Ho ┆ 1735682718 │
│          ┆               ┆ ha K         ┆              ┆   ┆ ull,null,nul ┆ ,"17s",{"str ┆ nza Kolář"," ┆            │
│          ┆               ┆              ┆              ┆   ┆ l,0}         ┆ ava://…      ┆ https:…      ┆            │
│ 9458674  ┆ 3             ┆ Zrucskej     ┆ Ride         ┆ … ┆ {null,null,n ┆ {"1:25","2:2 ┆ {149193634," ┆ 1735682705 │
│          ┆               ┆ smrtak       ┆              ┆   ┆ ull,null,nul ┆ 9","1:25",{" ┆ Reno Ginter" ┆            │
│          ┆               ┆              ┆              ┆   ┆ l,0}         ┆ strava…      ┆ ,"http…      ┆            │
│ 9959344  ┆ 3             ┆ time trial   ┆ Ride         ┆ … ┆ {181,"2024-0 ┆ {"1:25","2:1 ┆ {118182015," ┆ 1735684696 │
│          ┆               ┆ at Svratka   ┆              ┆   ┆ 9-08","every ┆ 7","1:25",{" ┆ Petr Stříbný ┆            │
│          ┆               ┆              ┆              ┆   ┆ one",1…      ┆ strava…      ┆ ","htt…      ┆            │
└──────────┴───────────────┴──────────────┴──────────────┴───┴──────────────┴──────────────┴──────────────┴────────────┘

In [131]:
df.with_columns(
    (pl.col("date").cast(pl.Int64))
)

shape: (522, 31)
┌──────────┬───────────────┬──────────────┬──────────────┬───┬──────────────┬──────────────┬──────────────┬────────────┐
│ id       ┆ resource_stat ┆ name         ┆ activity_typ ┆ … ┆ athlete_segm ┆ xoms         ┆ local_legend ┆ date       │
│ ---      ┆ e             ┆ ---          ┆ e            ┆   ┆ ent_stats    ┆ ---          ┆ ---          ┆ ---        │
│ i64      ┆ ---           ┆ str          ┆ ---          ┆   ┆ ---          ┆ struct[4]    ┆ struct[7]    ┆ i64        │
│          ┆ i64           ┆              ┆ str          ┆   ┆ struct[6]    ┆              ┆              ┆            │
╞══════════╪═══════════════╪══════════════╪══════════════╪═══╪══════════════╪══════════════╪══════════════╪════════════╡
│ 10101984 ┆ 3             ┆ podle Labe   ┆ Ride         ┆ … ┆ {null,null,n ┆ {"3:19","4:3 ┆ null         ┆ 1735545911 │
│          ┆               ┆ do Týnce     ┆              ┆   ┆ ull,null,nul ┆ 0","3:19",{" ┆              ┆            │
│          ┆               ┆              ┆              ┆   ┆ l,0}         ┆ strava…      ┆              ┆            │
│ 10101984 ┆ 3             ┆ podle Labe   ┆ Ride         ┆ … ┆ {null,null,n ┆ {"3:19","4:3 ┆ null         ┆ 1735596308 │
│          ┆               ┆ do Týnce     ┆              ┆   ┆ ull,null,nul ┆ 0","3:19",{" ┆              ┆            │
│          ┆               ┆              ┆              ┆   ┆ l,0}         ┆ strava…      ┆              ┆            │
│ 10147129 ┆ 3             ┆ TJ Sokol     ┆ Run          ┆ … ┆ {null,null,n ┆ {"1:07","1:2 ┆ {43165816,"E ┆ 1735547892 │
│          ┆               ┆ okruh        ┆              ┆   ┆ ull,null,nul ┆ 2","1:07",{" ┆ duard Stančí ┆            │
│          ┆               ┆              ┆              ┆   ┆ l,0}         ┆ strava…      ┆ k","ht…      ┆            │
│ 10147129 ┆ 3             ┆ TJ Sokol     ┆ Run          ┆ … ┆ {null,null,n ┆ {"1:07","1:2 ┆ {43165816,"E ┆ 1735597329 │
│          ┆               ┆ okruh        ┆              ┆   ┆ ull,null,nul ┆ 2","1:07",{" ┆ duard Stančí ┆            │
│          ┆               ┆              ┆              ┆   ┆ l,0}         ┆ strava…      ┆ k","ht…      ┆            │
│ 10186045 ┆ 3             ┆ Opičí        ┆ Ride         ┆ … ┆ {null,null,n ┆ {"1:33","2:0 ┆ {27344262,"P ┆ 1735545909 │
│          ┆               ┆ Časovka,     ┆              ┆   ┆ ull,null,nul ┆ 6","1:33",{" ┆ etr Duřt","h ┆            │
│          ┆               ┆ Podolská     ┆              ┆   ┆ l,0}         ┆ strava…      ┆ ttps:/…      ┆            │
│          ┆               ┆ vodárn…      ┆              ┆   ┆              ┆              ┆              ┆            │
│ …        ┆ …             ┆ …            ┆ …            ┆ … ┆ …            ┆ …            ┆ …            ┆ …          │
│ 9433317  ┆ 3             ┆ Třebešín-drá ┆ Ride         ┆ … ┆ {null,null,n ┆ {"17s","20s" ┆ {5959748,"Ho ┆ 1735597316 │
│          ┆               ┆ ha K         ┆              ┆   ┆ ull,null,nul ┆ ,"17s",{"str ┆ nza Kolář"," ┆            │
│          ┆               ┆              ┆              ┆   ┆ l,0}         ┆ ava://…      ┆ https:…      ┆            │
│ 9458674  ┆ 3             ┆ Zrucskej     ┆ Ride         ┆ … ┆ {null,null,n ┆ {"1:25","2:2 ┆ {149193634," ┆ 1735546897 │
│          ┆               ┆ smrtak       ┆              ┆   ┆ ull,null,nul ┆ 9","1:25",{" ┆ Reno Ginter" ┆            │
│          ┆               ┆              ┆              ┆   ┆ l,0}         ┆ strava…      ┆ ,"http…      ┆            │
│ 9458674  ┆ 3             ┆ Zrucskej     ┆ Ride         ┆ … ┆ {null,null,n ┆ {"1:25","2:2 ┆ {149193634," ┆ 1735597309 │
│          ┆               ┆ smrtak       ┆              ┆   ┆ ull,null,nul ┆ 9","1:25",{" ┆ Reno Ginter" ┆            │
│          ┆               ┆              ┆              ┆   ┆ l,0}         ┆ strava…      ┆ ,"http…      ┆            │
│ 9959344  ┆ 3             ┆ time trial   ┆ Ride         ┆ … ┆ {181,"2024-0 ┆ {"1:25","2:1 ┆ {118182015," ┆ 1735547902 │
│          ┆               ┆ at Svratka   ┆              ┆   ┆ 9-08","every ┆ 7","1:25",{" ┆ Petr Stříbný ┆            │
│          ┆               ┆              ┆              ┆   ┆ one",1…      ┆ strava…      ┆ ","htt…      ┆            │
│ 9959344  ┆ 3             ┆ time trial   ┆ Ride         ┆ … ┆ {181,"2024-0 ┆ {"1:25","2:1 ┆ {118182015," ┆ 1735596323 │
│          ┆               ┆ at Svratka   ┆              ┆   ┆ 9-08","every ┆ 7","1:25",{" ┆ Petr Stříbný ┆            │
│          ┆               ┆              ┆              ┆   ┆ one",1…      ┆ strava…      ┆ ","htt…      ┆            │
└──────────┴───────────────┴──────────────┴──────────────┴───┴──────────────┴──────────────┴──────────────┴────────────┘

In [143]:
df = df.with_columns(
    (pl.col("date").cast(pl.Int64) * 1000000).cast(pl.Datetime(time_zone='CET'))
)

In [145]:
df.sort("date").group_by_dynamic("date", every="1d").agg(pl.col("effort_count").sum())

shape: (8, 2)
┌─────────────────────────┬──────────────┐
│ date                    ┆ effort_count │
│ ---                     ┆ ---          │
│ datetime[μs, CET]       ┆ i64          │
╞═════════════════════════╪══════════════╡
│ 2024-12-24 00:00:00 CET ┆ 1902247      │
│ 2024-12-25 00:00:00 CET ┆ 7384499      │
│ 2024-12-26 00:00:00 CET ┆ 10513226     │
│ 2024-12-27 00:00:00 CET ┆ 18965770     │
│ 2024-12-28 00:00:00 CET ┆ 29467674     │
│ 2024-12-29 00:00:00 CET ┆ 29472133     │
│ 2024-12-30 00:00:00 CET ┆ 29478123     │
│ 2024-12-31 00:00:00 CET ┆ 14743554     │
└─────────────────────────┴──────────────┘

In [163]:
df.filter(pl.col('date').dt.hour() == 23).sort("date").group_by_dynamic("date", every="1d").agg(pl.col("effort_count").sum())

shape: (8, 2)
┌─────────────────────────┬──────────────┐
│ date                    ┆ effort_count │
│ ---                     ┆ ---          │
│ datetime[μs, CET]       ┆ i64          │
╞═════════════════════════╪══════════════╡
│ 2024-12-24 00:00:00 CET ┆ 1902247      │
│ 2024-12-25 00:00:00 CET ┆ 5124263      │
│ 2024-12-26 00:00:00 CET ┆ 3811608      │
│ 2024-12-27 00:00:00 CET ┆ 14698890     │
│ 2024-12-28 00:00:00 CET ┆ 14734637     │
│ 2024-12-29 00:00:00 CET ┆ 14737447     │
│ 2024-12-30 00:00:00 CET ┆ 14740613     │
│ 2024-12-31 00:00:00 CET ┆ 14743554     │
└─────────────────────────┴──────────────┘

NameError: name 'which' is not defined