In [1]:
import os
import polars as pl
import altair as alt

In [2]:
df = pl.read_parquet(os.path.join("data","segments.parquet"))

In [3]:
df.columns

['id',
 'name',
 'activity_type',
 'distance',
 'average_grade',
 'elevation_high',
 'elevation_low',
 'total_elevation_gain',
 'start_latlng',
 'end_latlng',
 'country',
 'state',
 'city',
 'effort_count',
 'athlete_count',
 'date',
 'start_to_finish_distance']

In [4]:
df.filter((pl.col("country") == "Czechia") & (pl.col('distance') > 500) & (pl.col('activity_type') == 'Ride')).select(pl.col('name')).unique().to_series().to_list()

['stupani k vetr. mlynu Kuzelov',
 'Dářská rašeliniště',
 'Lysá hora - 5 km',
 'S&Ch20 Masarykův okruh',
 'Final climb ke srubu na Deštnou',
 'Sprintík křižovatka/skalní mlýn',
 'Červená podél Zlaté stoky do Třeboně',
 'Sprint Páteček - Santos',
 'Novomlýnská 5: Věstonice-Strachotín',
 'Černý důl konec Hoffmanky',
 'Kynšperský ATAK',
 'podle Labe do Týnce',
 'time trial at Svratka',
 'Bunč climb',
 'Zbraslav - Komořany',
 'Z Lednice po silnici k odbocce na Janohrad',
 'Szpic Jested  last 3 km ( od rozc na Dub)',
 'Podle Radbuzy',
 'Risova studanka - od zavory',
 'Nová cyklostezka do Bosche  2',
 'Kopec pod Barborou',
 'Hostyn-od.zastavky.po.znacku.P',
 'Papezov - Prazmo',
 'Šantovka - Kojeňák',
 'Vlevo dole jezero Most',
 'Výstup na Klínovec',
 'svadov—valtirov',
 'Jiráskovo nábřeží k Husovce',
 'Srbsko - Hlásná Třebáň',
 'Zrucskej smrtak',
 'Chrudim climb',
 'Sedmička, Lipno {',
 'Máchovo kritérium - přes bory kolem vrchu Borný',
 'Rokytka od myčky',
 'Mutěnka - z Kyjova po odbočku na hraběcí',
 'Kerhartice-Choceň',
 'Autodrom Most',
 'Muglinovská→Hradní lávka (po pravém břehu)',
 'Bečva - Pustevny Uphill',
 'do Srní',
 'Nová cyklopěšina z Peřiny do HTčka',
 'Maslovice - Kralupy',
 'Cyklostezka Náchod -> Velké Poříčí',
 'Rovinka Beranov',
 'Solan last km',
 'Šobes - sjezd',
 'Okolo Bobrůvky Tři Studně - Koupaliště NMNM',
 'segment z Tábora',
 'Ještěd Finale konec před kostkami.',
 'Zlaťák konec - smrt',
 'MH - Klaster',
 'Cyklostezka sprint směr Děčín',
 'Krkonošská',
 'Tuhnice most-Drahovice most,stezka',
 'Opičí Časovka, Podolská vodárna - Dvorce',
 'Jesenice-Blatno DH',
 'Sjezd Blatno-Březenec',
 'most - Loket',
 'Revnicak Eve',
 'Starý Kolín - Svatá Kateřina',
 'Sedýlko - Praděd climb',
 'Podél dálnice',
 'Adamaov climb',
 'Od posledního tunelu do Bílovic',
 'Židlochovice -> Olympia',
 'Plácky-soutok',
 'Výrovka - Modré Sedlo',
 'Le Grande Classico',
 'Daskabát flat',
 'Decin - Bad Schandau Abzweig Radwg',
 'Od křižovatky do Strání po vysílač',
 '611 - Mstetice',
 'Sptint pod Býčí skálou',
 'Cyklostezka Stará huť-Dobříš',
 'Eurovie - nadjezd Rosice',
 'Benešovský brdek',
 'Pod Homoli Climb',
 'Špindlerovka - část II. (od Černýho potoka nahoru)',
 'Třebíč - Stařeč po cyklostezce (LS)',
 'Stezka do Zlina',
 'Červená voda - Suchý vrch',
 'Trinec-Tesin',
 'Total brikule 🚀',
 'Kvilda Bučina',
 'Kleť k vysílači - finále',
 'Ruda -> Gerlovka',
 'Klobouky Viadukt',
 'plný kule z kolína',
 'Klinovec Top',
 'Do sedla Klínovce po silnici',
 'Kaufland - Popendorf',
 'Dlouhe Strane od Loucnej',
 'Lednice - Bulhary',
 'Údolí Svatý Jan',
 'panelka k bráně ˇerchova']

In [5]:
def segment(nazev):
    segm = df.filter(pl.col('name') == nazev).group_by_dynamic("date", every="1d").agg(pl.col("effort_count").max())
    segm = segm.with_columns(pl.col("effort_count").diff().alias("daily_difference"))
    segm = segm.with_columns(pl.when(pl.col("daily_difference") < 0).then(None).otherwise(pl.col("daily_difference")).alias("daily_difference"))
    segm = segm.with_columns(pl.col("date").cast(str)).drop_nulls()
    print(segm)
    return alt.Chart(segm, width=800).mark_bar().encode(
        x='date:O',
        y='daily_difference:Q'
    )

In [6]:
segment("Židlochovice -> Olympia")

shape: (126, 3)
┌────────────────────────────┬──────────────┬──────────────────┐
│ date                       ┆ effort_count ┆ daily_difference │
│ ---                        ┆ ---          ┆ ---              │
│ str                        ┆ i64          ┆ i64              │
╞════════════════════════════╪══════════════╪══════════════════╡
│ 2024-12-25 00:00:00.000000 ┆ 15827        ┆ 13               │
│ 2024-12-26 00:00:00.000000 ┆ 15841        ┆ 14               │
│ 2024-12-27 00:00:00.000000 ┆ 15857        ┆ 16               │
│ 2024-12-28 00:00:00.000000 ┆ 15874        ┆ 17               │
│ 2024-12-29 00:00:00.000000 ┆ 15888        ┆ 14               │
│ …                          ┆ …            ┆ …                │
│ 2025-04-28 00:00:00.000000 ┆ 17899        ┆ 17               │
│ 2025-04-29 00:00:00.000000 ┆ 17922        ┆ 23               │
│ 2025-04-30 00:00:00.000000 ┆ 17950        ┆ 28               │
│ 2025-05-01 00:00:00.000000 ┆ 18050        ┆ 100              │
│ 2025-05-02 00:00:00.000000 ┆ 18096        ┆ 46               │
└────────────────────────────┴──────────────┴──────────────────┘

alt.Chart(...)

In [7]:
segment("Revnicak Eve")

shape: (116, 3)
┌────────────────────────────┬──────────────┬──────────────────┐
│ date                       ┆ effort_count ┆ daily_difference │
│ ---                        ┆ ---          ┆ ---              │
│ str                        ┆ i64          ┆ i64              │
╞════════════════════════════╪══════════════╪══════════════════╡
│ 2024-12-26 00:00:00.000000 ┆ 43467        ┆ 3                │
│ 2024-12-27 00:00:00.000000 ┆ 43469        ┆ 2                │
│ 2024-12-28 00:00:00.000000 ┆ 43471        ┆ 2                │
│ 2024-12-29 00:00:00.000000 ┆ 43478        ┆ 7                │
│ 2024-12-30 00:00:00.000000 ┆ 43481        ┆ 3                │
│ …                          ┆ …            ┆ …                │
│ 2025-04-28 00:00:00.000000 ┆ 44994        ┆ 28               │
│ 2025-04-29 00:00:00.000000 ┆ 45019        ┆ 25               │
│ 2025-04-30 00:00:00.000000 ┆ 45035        ┆ 16               │
│ 2025-05-01 00:00:00.000000 ┆ 45055        ┆ 20               │
│ 2025-05-02 00:00:00.000000 ┆ 45080        ┆ 25               │
└────────────────────────────┴──────────────┴──────────────────┘

alt.Chart(...)

In [8]:
segment("Sedmička, Lipno {")

shape: (113, 3)
┌────────────────────────────┬──────────────┬──────────────────┐
│ date                       ┆ effort_count ┆ daily_difference │
│ ---                        ┆ ---          ┆ ---              │
│ str                        ┆ i64          ┆ i64              │
╞════════════════════════════╪══════════════╪══════════════════╡
│ 2024-12-27 00:00:00.000000 ┆ 12542        ┆ 1                │
│ 2024-12-30 00:00:00.000000 ┆ 12540        ┆ 1                │
│ 2025-01-01 00:00:00.000000 ┆ 12538        ┆ 0                │
│ 2025-01-02 00:00:00.000000 ┆ 12539        ┆ 1                │
│ 2025-01-03 00:00:00.000000 ┆ 12539        ┆ 0                │
│ …                          ┆ …            ┆ …                │
│ 2025-04-28 00:00:00.000000 ┆ 12797        ┆ 2                │
│ 2025-04-29 00:00:00.000000 ┆ 12802        ┆ 5                │
│ 2025-04-30 00:00:00.000000 ┆ 12803        ┆ 1                │
│ 2025-05-01 00:00:00.000000 ┆ 12838        ┆ 35               │
│ 2025-05-02 00:00:00.000000 ┆ 12866        ┆ 28               │
└────────────────────────────┴──────────────┴──────────────────┘

alt.Chart(...)

In [9]:
segment("Solan last km")

shape: (123, 3)
┌────────────────────────────┬──────────────┬──────────────────┐
│ date                       ┆ effort_count ┆ daily_difference │
│ ---                        ┆ ---          ┆ ---              │
│ str                        ┆ i64          ┆ i64              │
╞════════════════════════════╪══════════════╪══════════════════╡
│ 2024-12-26 00:00:00.000000 ┆ 12355        ┆ 0                │
│ 2024-12-27 00:00:00.000000 ┆ 12358        ┆ 3                │
│ 2024-12-28 00:00:00.000000 ┆ 12358        ┆ 0                │
│ 2024-12-29 00:00:00.000000 ┆ 12358        ┆ 0                │
│ 2024-12-31 00:00:00.000000 ┆ 12356        ┆ 0                │
│ …                          ┆ …            ┆ …                │
│ 2025-04-28 00:00:00.000000 ┆ 12671        ┆ 4                │
│ 2025-04-29 00:00:00.000000 ┆ 12674        ┆ 3                │
│ 2025-04-30 00:00:00.000000 ┆ 12681        ┆ 7                │
│ 2025-05-01 00:00:00.000000 ┆ 12697        ┆ 16               │
│ 2025-05-02 00:00:00.000000 ┆ 12724        ┆ 27               │
└────────────────────────────┴──────────────┴──────────────────┘

alt.Chart(...)

In [10]:
segment("Richmond ITT1")

shape: (126, 3)
┌────────────────────────────┬──────────────┬──────────────────┐
│ date                       ┆ effort_count ┆ daily_difference │
│ ---                        ┆ ---          ┆ ---              │
│ str                        ┆ i64          ┆ i64              │
╞════════════════════════════╪══════════════╪══════════════════╡
│ 2024-12-28 00:00:00.000000 ┆ 4618619      ┆ 402              │
│ 2024-12-29 00:00:00.000000 ┆ 4619671      ┆ 1052             │
│ 2024-12-30 00:00:00.000000 ┆ 4621281      ┆ 1610             │
│ 2024-12-31 00:00:00.000000 ┆ 4622506      ┆ 1225             │
│ 2025-01-01 00:00:00.000000 ┆ 4622622      ┆ 116              │
│ …                          ┆ …            ┆ …                │
│ 2025-04-28 00:00:00.000000 ┆ 4779525      ┆ 1805             │
│ 2025-04-29 00:00:00.000000 ┆ 4781923      ┆ 2398             │
│ 2025-04-30 00:00:00.000000 ┆ 4784657      ┆ 2734             │
│ 2025-05-01 00:00:00.000000 ┆ 4787128      ┆ 2471             │
│ 2025-05-02 00:00:00.000000 ┆ 4789183      ┆ 2055             │
└────────────────────────────┴──────────────┴──────────────────┘

alt.Chart(...)

In [11]:
segment("U Jordánu do kopce")

shape: (127, 3)
┌────────────────────────────┬──────────────┬──────────────────┐
│ date                       ┆ effort_count ┆ daily_difference │
│ ---                        ┆ ---          ┆ ---              │
│ str                        ┆ i64          ┆ i64              │
╞════════════════════════════╪══════════════╪══════════════════╡
│ 2024-12-26 00:00:00.000000 ┆ 3562         ┆ 5                │
│ 2024-12-27 00:00:00.000000 ┆ 3562         ┆ 0                │
│ 2024-12-28 00:00:00.000000 ┆ 3565         ┆ 3                │
│ 2024-12-29 00:00:00.000000 ┆ 3565         ┆ 0                │
│ 2024-12-30 00:00:00.000000 ┆ 3568         ┆ 3                │
│ …                          ┆ …            ┆ …                │
│ 2025-04-28 00:00:00.000000 ┆ 3881         ┆ 4                │
│ 2025-04-29 00:00:00.000000 ┆ 3887         ┆ 6                │
│ 2025-04-30 00:00:00.000000 ┆ 3888         ┆ 1                │
│ 2025-05-01 00:00:00.000000 ┆ 3891         ┆ 3                │
│ 2025-05-02 00:00:00.000000 ┆ 3892         ┆ 1                │
└────────────────────────────┴──────────────┴──────────────────┘

alt.Chart(...)

In [12]:
segment('400 metrů, 44 120 diváků')

shape: (126, 3)
┌────────────────────────────┬──────────────┬──────────────────┐
│ date                       ┆ effort_count ┆ daily_difference │
│ ---                        ┆ ---          ┆ ---              │
│ str                        ┆ i64          ┆ i64              │
╞════════════════════════════╪══════════════╪══════════════════╡
│ 2024-12-26 00:00:00.000000 ┆ 4461         ┆ 0                │
│ 2024-12-27 00:00:00.000000 ┆ 4461         ┆ 0                │
│ 2024-12-28 00:00:00.000000 ┆ 4461         ┆ 0                │
│ 2024-12-29 00:00:00.000000 ┆ 4461         ┆ 0                │
│ 2024-12-30 00:00:00.000000 ┆ 4461         ┆ 0                │
│ …                          ┆ …            ┆ …                │
│ 2025-04-28 00:00:00.000000 ┆ 4655         ┆ 0                │
│ 2025-04-29 00:00:00.000000 ┆ 4655         ┆ 0                │
│ 2025-04-30 00:00:00.000000 ┆ 4655         ┆ 0                │
│ 2025-05-01 00:00:00.000000 ┆ 4655         ┆ 0                │
│ 2025-05-02 00:00:00.000000 ┆ 4655         ┆ 0                │
└────────────────────────────┴──────────────┴──────────────────┘

alt.Chart(...)

In [13]:
def weekly(segment):
    return df.filter(
        pl.col('name') == segment
    ).group_by_dynamic("date", every="1d").agg(
        pl.col("effort_count").max()
    ).with_columns(
        pl.col("effort_count").diff().alias("daily_difference")
    ).with_columns(
        pl.when(pl.col("daily_difference") < 0).then(None).otherwise(pl.col("daily_difference")).alias("daily_difference")
    ).drop_nulls(
    ).with_columns(
        pl.col("date").dt.weekday().alias("day")
    ).group_by("day").agg(pl.col("daily_difference").median()).sort(by="day")

In [14]:
def graf(tyden):
    return alt.Chart(tyden).mark_bar().encode(alt.X("day:N"), alt.Y("daily_difference:Q"))

In [15]:
graf(weekly("Track Domažlice"))

alt.Chart(...)

In [16]:
graf(weekly("Velká Deštná climb "))

alt.Chart(...)

In [17]:
graf(weekly("Židlochovice -> Olympia"))

alt.Chart(...)

In [18]:
graf(weekly("Od posledního tunelu do Bílovic"))

alt.Chart(...)

In [19]:
segment("Opičí Časovka, Podolská vodárna ")

shape: (0, 3)
┌──────┬──────────────┬──────────────────┐
│ date ┆ effort_count ┆ daily_difference │
│ ---  ┆ ---          ┆ ---              │
│ str  ┆ i64          ┆ i64              │
╞══════╪══════════════╪══════════════════╡
└──────┴──────────────┴──────────────────┘

alt.Chart(...)

In [20]:
graf(weekly("Opičí Časovka, Podolská vodárna"))

alt.Chart(...)

In [21]:
segment("Vítkov up sprint ")

shape: (0, 3)
┌──────┬──────────────┬──────────────────┐
│ date ┆ effort_count ┆ daily_difference │
│ ---  ┆ ---          ┆ ---              │
│ str  ┆ i64          ┆ i64              │
╞══════╪══════════════╪══════════════════╡
└──────┴──────────────┴──────────────────┘

alt.Chart(...)

In [22]:
df.filter(pl.col("name").str.contains("Vítkov up sprint"))

shape: (127, 17)
┌──────────┬───────────┬────────────────┬──────────┬───┬──────────────┬────────────────┬───────────────┬───────────────┐
│ id       ┆ name      ┆ activity_type  ┆ distance ┆ … ┆ effort_count ┆ athlete_count  ┆ date          ┆ start_to_fini │
│ ---      ┆ ---       ┆ ---            ┆ ---      ┆   ┆ ---          ┆ ---            ┆ ---           ┆ sh_distance   │
│ i64      ┆ str       ┆ str            ┆ f64      ┆   ┆ i64          ┆ i64            ┆ datetime[μs,  ┆ ---           │
│          ┆           ┆                ┆          ┆   ┆              ┆                ┆ CET]          ┆ f64           │
╞══════════╪═══════════╪════════════════╪══════════╪═══╪══════════════╪════════════════╪═══════════════╪═══════════════╡
│ 14214163 ┆ Vítkov up ┆ Run            ┆ 118.2    ┆ … ┆ 86417        ┆ 8588           ┆ 2024-12-27    ┆ 0.117786      │
│          ┆ sprint    ┆                ┆          ┆   ┆              ┆                ┆ 23:22:03 CET  ┆               │
│ 14214163 ┆ Vítkov up ┆ Run            ┆ 118.2    ┆ … ┆ 86426        ┆ 8589           ┆ 2024-12-28    ┆ 0.117786      │
│          ┆ sprint    ┆                ┆          ┆   ┆              ┆                ┆ 23:05:37 CET  ┆               │
│ 14214163 ┆ Vítkov up ┆ Run            ┆ 118.2    ┆ … ┆ 86438        ┆ 8592           ┆ 2024-12-29    ┆ 0.117786      │
│          ┆ sprint    ┆                ┆          ┆   ┆              ┆                ┆ 23:38:26 CET  ┆               │
│ 14214163 ┆ Vítkov up ┆ Run            ┆ 118.2    ┆ … ┆ 86458        ┆ 8598           ┆ 2024-12-30    ┆ 0.117786      │
│          ┆ sprint    ┆                ┆          ┆   ┆              ┆                ┆ 23:21:42 CET  ┆               │
│ 14214163 ┆ Vítkov up ┆ Run            ┆ 118.2    ┆ … ┆ 86473        ┆ 8600           ┆ 2024-12-31    ┆ 0.117786      │
│          ┆ sprint    ┆                ┆          ┆   ┆              ┆                ┆ 23:22:02 CET  ┆               │
│ …        ┆ …         ┆ …              ┆ …        ┆ … ┆ …            ┆ …              ┆ …             ┆ …             │
│ 14214163 ┆ Vítkov up ┆ Run            ┆ 118.2    ┆ … ┆ 89797        ┆ 9148           ┆ 2025-04-28    ┆ 0.117786      │
│          ┆ sprint    ┆                ┆          ┆   ┆              ┆                ┆ 23:22:04 CEST ┆               │
│ 14214163 ┆ Vítkov up ┆ Run            ┆ 118.2    ┆ … ┆ 89810        ┆ 9153           ┆ 2025-04-29    ┆ 0.117786      │
│          ┆ sprint    ┆                ┆          ┆   ┆              ┆                ┆ 23:22:01 CEST ┆               │
│ 14214163 ┆ Vítkov up ┆ Run            ┆ 118.2    ┆ … ┆ 89851        ┆ 9162           ┆ 2025-04-30    ┆ 0.117786      │
│          ┆ sprint    ┆                ┆          ┆   ┆              ┆                ┆ 23:05:26 CEST ┆               │
│ 14214163 ┆ Vítkov up ┆ Run            ┆ 118.2    ┆ … ┆ 89904        ┆ 9168           ┆ 2025-05-01    ┆ 0.117786      │
│          ┆ sprint    ┆                ┆          ┆   ┆              ┆                ┆ 23:05:26 CEST ┆               │
│ 14214163 ┆ Vítkov up ┆ Run            ┆ 118.2    ┆ … ┆ 89927        ┆ 9183           ┆ 2025-05-02    ┆ 0.117786      │
│          ┆ sprint    ┆                ┆          ┆   ┆              ┆                ┆ 23:05:22 CEST ┆               │
└──────────┴───────────┴────────────────┴──────────┴───┴──────────────┴────────────────┴───────────────┴───────────────┘

In [23]:
graf(weekly("Vítkov up sprint"))

alt.Chart(...)

In [24]:
segment("Risova studanka - od zavory")

shape: (125, 3)
┌────────────────────────────┬──────────────┬──────────────────┐
│ date                       ┆ effort_count ┆ daily_difference │
│ ---                        ┆ ---          ┆ ---              │
│ str                        ┆ i64          ┆ i64              │
╞════════════════════════════╪══════════════╪══════════════════╡
│ 2024-12-25 00:00:00.000000 ┆ 41328        ┆ 2                │
│ 2024-12-26 00:00:00.000000 ┆ 41336        ┆ 8                │
│ 2024-12-27 00:00:00.000000 ┆ 41351        ┆ 15               │
│ 2024-12-28 00:00:00.000000 ┆ 41360        ┆ 9                │
│ 2024-12-29 00:00:00.000000 ┆ 41365        ┆ 5                │
│ …                          ┆ …            ┆ …                │
│ 2025-04-28 00:00:00.000000 ┆ 42787        ┆ 31               │
│ 2025-04-29 00:00:00.000000 ┆ 42808        ┆ 21               │
│ 2025-04-30 00:00:00.000000 ┆ 42839        ┆ 31               │
│ 2025-05-01 00:00:00.000000 ┆ 42856        ┆ 17               │
│ 2025-05-02 00:00:00.000000 ┆ 42878        ┆ 22               │
└────────────────────────────┴──────────────┴──────────────────┘

alt.Chart(...)

In [25]:
segment("Sedýlko - Praděd climb")

shape: (101, 3)
┌────────────────────────────┬──────────────┬──────────────────┐
│ date                       ┆ effort_count ┆ daily_difference │
│ ---                        ┆ ---          ┆ ---              │
│ str                        ┆ i64          ┆ i64              │
╞════════════════════════════╪══════════════╪══════════════════╡
│ 2024-12-25 00:00:00.000000 ┆ 31962        ┆ 0                │
│ 2024-12-26 00:00:00.000000 ┆ 31964        ┆ 2                │
│ 2024-12-27 00:00:00.000000 ┆ 31969        ┆ 5                │
│ 2024-12-28 00:00:00.000000 ┆ 31976        ┆ 7                │
│ 2024-12-29 00:00:00.000000 ┆ 31977        ┆ 1                │
│ …                          ┆ …            ┆ …                │
│ 2025-04-28 00:00:00.000000 ┆ 32110        ┆ 5                │
│ 2025-04-29 00:00:00.000000 ┆ 32111        ┆ 1                │
│ 2025-04-30 00:00:00.000000 ┆ 32119        ┆ 8                │
│ 2025-05-01 00:00:00.000000 ┆ 32182        ┆ 63               │
│ 2025-05-02 00:00:00.000000 ┆ 32269        ┆ 87               │
└────────────────────────────┴──────────────┴──────────────────┘

alt.Chart(...)

In [26]:
segment("Malchor - Lysá Hora")

shape: (126, 3)
┌────────────────────────────┬──────────────┬──────────────────┐
│ date                       ┆ effort_count ┆ daily_difference │
│ ---                        ┆ ---          ┆ ---              │
│ str                        ┆ i64          ┆ i64              │
╞════════════════════════════╪══════════════╪══════════════════╡
│ 2024-12-26 00:00:00.000000 ┆ 19801        ┆ 47               │
│ 2024-12-27 00:00:00.000000 ┆ 19835        ┆ 34               │
│ 2024-12-28 00:00:00.000000 ┆ 19870        ┆ 35               │
│ 2024-12-29 00:00:00.000000 ┆ 19910        ┆ 40               │
│ 2024-12-30 00:00:00.000000 ┆ 19952        ┆ 42               │
│ …                          ┆ …            ┆ …                │
│ 2025-04-28 00:00:00.000000 ┆ 21357        ┆ 6                │
│ 2025-04-29 00:00:00.000000 ┆ 21370        ┆ 13               │
│ 2025-04-30 00:00:00.000000 ┆ 21390        ┆ 20               │
│ 2025-05-01 00:00:00.000000 ┆ 21427        ┆ 37               │
│ 2025-05-02 00:00:00.000000 ┆ 21460        ┆ 33               │
└────────────────────────────┴──────────────┴──────────────────┘

alt.Chart(...)

In [27]:
graf(weekly("Tyršák čtyřstofka"))

alt.Chart(...)

In [28]:
graf(weekly('Juliska 400 m'))

alt.Chart(...)

In [29]:
graf(weekly('Karlův most ONLY'))

alt.Chart(...)

In [30]:
segment("Ořešník")

shape: (120, 3)
┌────────────────────────────┬──────────────┬──────────────────┐
│ date                       ┆ effort_count ┆ daily_difference │
│ ---                        ┆ ---          ┆ ---              │
│ str                        ┆ i64          ┆ i64              │
╞════════════════════════════╪══════════════╪══════════════════╡
│ 2024-12-26 00:00:00.000000 ┆ 1105         ┆ 1                │
│ 2024-12-27 00:00:00.000000 ┆ 1105         ┆ 0                │
│ 2024-12-28 00:00:00.000000 ┆ 1106         ┆ 1                │
│ 2024-12-30 00:00:00.000000 ┆ 1105         ┆ 1                │
│ 2024-12-31 00:00:00.000000 ┆ 1106         ┆ 1                │
│ …                          ┆ …            ┆ …                │
│ 2025-04-27 00:00:00.000000 ┆ 1154         ┆ 0                │
│ 2025-04-29 00:00:00.000000 ┆ 1153         ┆ 0                │
│ 2025-04-30 00:00:00.000000 ┆ 1153         ┆ 0                │
│ 2025-05-01 00:00:00.000000 ┆ 1156         ┆ 3                │
│ 2025-05-02 00:00:00.000000 ┆ 1165         ┆ 9                │
└────────────────────────────┴──────────────┴──────────────────┘

alt.Chart(...)

In [31]:
df = pl.read_parquet("data_raw/segments/*.parquet")

df = df.with_columns(
    (pl.col("date").cast(pl.Int64) * 1000000).cast(pl.Datetime(time_zone='CET'))
)
df = df.filter(pl.col('date').dt.hour() > 22)
df = df.sort(by="date")

In [32]:
df.columns

['id',
 'resource_state',
 'name',
 'activity_type',
 'distance',
 'average_grade',
 'maximum_grade',
 'elevation_high',
 'elevation_low',
 'start_latlng',
 'end_latlng',
 'elevation_profile',
 'elevation_profiles',
 'climb_category',
 'city',
 'state',
 'country',
 'private',
 'hazardous',
 'starred',
 'created_at',
 'updated_at',
 'total_elevation_gain',
 'map',
 'effort_count',
 'athlete_count',
 'star_count',
 'athlete_segment_stats',
 'xoms',
 'local_legend',
 'date']

In [33]:
df.group_by_dynamic("date", by="name", every="1d").agg(pl.col("effort_count").max())

C:\Users\micha\AppData\Local\Temp\ipykernel_24864\3197359101.py:1: DeprecationWarning: The argument `by` for `DataFrame.group_by_dynamic` is deprecated. It has been renamed to `group_by`.
  df.group_by_dynamic("date", by="name", every="1d").agg(pl.col("effort_count").max())

shape: (35_813, 3)
┌──────────────────────────┬──────────────────────────┬──────────────┐
│ name                     ┆ date                     ┆ effort_count │
│ ---                      ┆ ---                      ┆ ---          │
│ str                      ┆ datetime[μs, CET]        ┆ i64          │
╞══════════════════════════╪══════════════════════════╪══════════════╡
│ Dlouhe Strane od Loucnej ┆ 2024-12-24 00:00:00 CET  ┆ 308          │
│ Dlouhe Strane od Loucnej ┆ 2024-12-25 00:00:00 CET  ┆ 308          │
│ Dlouhe Strane od Loucnej ┆ 2024-12-26 00:00:00 CET  ┆ 308          │
│ Dlouhe Strane od Loucnej ┆ 2024-12-27 00:00:00 CET  ┆ 308          │
│ Dlouhe Strane od Loucnej ┆ 2024-12-28 00:00:00 CET  ┆ 308          │
│ …                        ┆ …                        ┆ …            │
│ kolem kapličky           ┆ 2025-04-28 00:00:00 CEST ┆ 162          │
│ kolem kapličky           ┆ 2025-04-29 00:00:00 CEST ┆ 166          │
│ kolem kapličky           ┆ 2025-04-30 00:00:00 CEST ┆ 171          │
│ kolem kapličky           ┆ 2025-05-01 00:00:00 CEST ┆ 172          │
│ kolem kapličky           ┆ 2025-05-02 00:00:00 CEST ┆ 179          │
└──────────────────────────┴──────────────────────────┴──────────────┘

In [34]:
df

shape: (36_086, 31)
┌──────────┬──────────────┬──────────────┬──────────────┬───┬──────────────┬──────────────┬──────────────┬─────────────┐
│ id       ┆ resource_sta ┆ name         ┆ activity_typ ┆ … ┆ athlete_segm ┆ xoms         ┆ local_legend ┆ date        │
│ ---      ┆ te           ┆ ---          ┆ e            ┆   ┆ ent_stats    ┆ ---          ┆ ---          ┆ ---         │
│ i64      ┆ ---          ┆ str          ┆ ---          ┆   ┆ ---          ┆ struct[4]    ┆ struct[7]    ┆ datetime[μs │
│          ┆ i64          ┆              ┆ str          ┆   ┆ struct[6]    ┆              ┆              ┆ , CET]      │
╞══════════╪══════════════╪══════════════╪══════════════╪═══╪══════════════╪══════════════╪══════════════╪═════════════╡
│ 17521739 ┆ 3            ┆ Dlouhe       ┆ Ride         ┆ … ┆ {null,null,n ┆ {"43:55","1: ┆ {13919744,"K ┆ 2024-12-24  │
│          ┆              ┆ Strane od    ┆              ┆   ┆ ull,null,nul ┆ 00:24","43:5 ┆ amil Filipek ┆ 23:02:03    │
│          ┆              ┆ Loucnej      ┆              ┆   ┆ l,0}         ┆ 5",{"s…      ┆ ","htt…      ┆ CET         │
│ 8598488  ┆ 3            ┆ Lysa hora -  ┆ Run          ┆ … ┆ {null,null,n ┆ {"1:47","2:0 ┆ {109095258," ┆ 2024-12-24  │
│          ┆              ┆ jizni        ┆              ┆   ┆ ull,null,nul ┆ 0","1:47",{" ┆ Roman Gula", ┆ 23:02:11    │
│          ┆              ┆ sjezdovka    ┆              ┆   ┆ l,0}         ┆ strava…      ┆ "https…      ┆ CET         │
│ 10356069 ┆ 3            ┆ Kvilda       ┆ Ride         ┆ … ┆ {null,null,n ┆ {"10:47","13 ┆ {3478016,"Ty ┆ 2024-12-24  │
│          ┆              ┆ Bučina       ┆              ┆   ┆ ull,null,nul ┆ :11","10:47" ┆ rel Fuchs"," ┆ 23:02:12    │
│          ┆              ┆              ┆              ┆   ┆ l,0}         ┆ ,{"str…      ┆ https:…      ┆ CET         │
│ 13477973 ┆ 3            ┆ Od dubu ke   ┆ Run          ┆ … ┆ {130,"2022-0 ┆ {"1:04","1:1 ┆ {31102876,"E ┆ 2024-12-24  │
│          ┆              ┆ Gizele       ┆              ┆   ┆ 9-28","every ┆ 6","1:04",{" ┆ vžen Demčenk ┆ 23:02:12    │
│          ┆              ┆              ┆              ┆   ┆ one",7…      ┆ strava…      ┆ o","ht…      ┆ CET         │
│ 7116683  ┆ 3            ┆ Risova       ┆ Ride         ┆ … ┆ {603,"2024-0 ┆ {"5:46","7:1 ┆ {6149474,"Ro ┆ 2024-12-24  │
│          ┆              ┆ studanka -   ┆              ┆   ┆ 9-08","every ┆ 8","5:46",{" ┆ bert Šmíd"," ┆ 23:05:01    │
│          ┆              ┆ od zavory    ┆              ┆   ┆ one",1…      ┆ strava…      ┆ https:…      ┆ CET         │
│ …        ┆ …            ┆ …            ┆ …            ┆ … ┆ …            ┆ …            ┆ …            ┆ …           │
│ 13040645 ┆ 3            ┆ Karlův most  ┆ Run          ┆ … ┆ {76,"2022-03 ┆ {"38s","51s" ┆ {138377191," ┆ 2025-05-02  │
│          ┆              ┆ ONLY         ┆              ┆   ┆ -10","everyo ┆ ,"38s",{"str ┆ Katerina     ┆ 23:38:54    │
│          ┆              ┆              ┆              ┆   ┆ ne",68…      ┆ ava://…      ┆ Ticha","h…   ┆ CEST        │
│ 7868044  ┆ 3            ┆ Pod Homoli   ┆ Ride         ┆ … ┆ {null,null,n ┆ {"4:17","6:4 ┆ {70878305,"M ┆ 2025-05-02  │
│          ┆              ┆ Climb        ┆              ┆   ┆ ull,null,nul ┆ 9","4:17",{" ┆ atěj Mašina" ┆ 23:38:54    │
│          ┆              ┆              ┆              ┆   ┆ l,0}         ┆ strava…      ┆ ,"avat…      ┆ CEST        │
│ 31902128 ┆ 3            ┆ Podél tratě  ┆ Run          ┆ … ┆ {null,null,n ┆ {"10:59","12 ┆ {39625492,"L ┆ 2025-05-02  │
│          ┆              ┆ do Úval      ┆              ┆   ┆ ull,null,nul ┆ :11","10:59" ┆ enka Haramul ┆ 23:38:55    │
│          ┆              ┆              ┆              ┆   ┆ l,0}         ┆ ,{"str…      ┆ enka",…      ┆ CEST        │
│ 36886062 ┆ 3            ┆ Labe_po      ┆ Run          ┆ … ┆ {null,null,n ┆ {"3:24","5:0 ┆ {39868053,"V ┆ 2025-05-02  │
│          ┆              ┆ asfaltu      ┆              ┆   ┆ ull,null,nul ┆ 1","3:24",{" ┆ rata Kysilka ┆ 23:38:55    │
│          ┆              ┆              ┆              ┆   ┆ l,0}         ┆ strava…      ┆ ","htt…      ┆ CEST        │
│ 652851   ┆ 3            ┆ Alpe d'Huez  ┆ Ride         ┆ … ┆ {null,null,n ┆ {"35:56","42 ┆ {107830355," ┆ 2025-05-02  │
│          ┆              ┆              ┆              ┆   ┆ ull,null,nul ┆ :36","35:56" ┆ 玖 言","http ┆ 23:38:55    │
│          ┆              ┆              ┆              ┆   ┆ l,0}         ┆ ,{"str…      ┆ s://dgal…    ┆ CEST        │
└──────────┴──────────────┴──────────────┴──────────────┴───┴──────────────┴──────────────┴──────────────┴─────────────┘

In [35]:
segment('Lužánky rovinka')

shape: (125, 3)
┌────────────────────────────┬──────────────┬──────────────────┐
│ date                       ┆ effort_count ┆ daily_difference │
│ ---                        ┆ ---          ┆ ---              │
│ str                        ┆ i64          ┆ i64              │
╞════════════════════════════╪══════════════╪══════════════════╡
│ 2024-12-25 00:00:00.000000 ┆ 179488       ┆ 40               │
│ 2024-12-26 00:00:00.000000 ┆ 179527       ┆ 39               │
│ 2024-12-27 00:00:00.000000 ┆ 179560       ┆ 33               │
│ 2024-12-28 00:00:00.000000 ┆ 179584       ┆ 24               │
│ 2024-12-29 00:00:00.000000 ┆ 179626       ┆ 42               │
│ …                          ┆ …            ┆ …                │
│ 2025-04-28 00:00:00.000000 ┆ 190668       ┆ 267              │
│ 2025-04-29 00:00:00.000000 ┆ 190777       ┆ 109              │
│ 2025-04-30 00:00:00.000000 ┆ 190866       ┆ 89               │
│ 2025-05-01 00:00:00.000000 ┆ 190989       ┆ 123              │
│ 2025-05-02 00:00:00.000000 ┆ 191096       ┆ 107              │
└────────────────────────────┴──────────────┴──────────────────┘

alt.Chart(...)

In [36]:
segment('time trial at Svratka')

shape: (121, 3)
┌────────────────────────────┬──────────────┬──────────────────┐
│ date                       ┆ effort_count ┆ daily_difference │
│ ---                        ┆ ---          ┆ ---              │
│ str                        ┆ i64          ┆ i64              │
╞════════════════════════════╪══════════════╪══════════════════╡
│ 2024-12-25 00:00:00.000000 ┆ 141661       ┆ 24               │
│ 2024-12-26 00:00:00.000000 ┆ 141680       ┆ 19               │
│ 2024-12-27 00:00:00.000000 ┆ 141706       ┆ 26               │
│ 2024-12-28 00:00:00.000000 ┆ 141721       ┆ 15               │
│ 2024-12-29 00:00:00.000000 ┆ 141735       ┆ 14               │
│ …                          ┆ …            ┆ …                │
│ 2025-04-28 00:00:00.000000 ┆ 146013       ┆ 79               │
│ 2025-04-29 00:00:00.000000 ┆ 146092       ┆ 79               │
│ 2025-04-30 00:00:00.000000 ┆ 146190       ┆ 98               │
│ 2025-05-01 00:00:00.000000 ┆ 146279       ┆ 89               │
│ 2025-05-02 00:00:00.000000 ┆ 146371       ┆ 92               │
└────────────────────────────┴──────────────┴──────────────────┘

alt.Chart(...)

In [37]:
segment('Od posledního tunelu do Bílovic')

shape: (118, 3)
┌────────────────────────────┬──────────────┬──────────────────┐
│ date                       ┆ effort_count ┆ daily_difference │
│ ---                        ┆ ---          ┆ ---              │
│ str                        ┆ i64          ┆ i64              │
╞════════════════════════════╪══════════════╪══════════════════╡
│ 2024-12-26 00:00:00.000000 ┆ 124240       ┆ 14               │
│ 2024-12-27 00:00:00.000000 ┆ 124314       ┆ 74               │
│ 2024-12-29 00:00:00.000000 ┆ 124308       ┆ 18               │
│ 2024-12-30 00:00:00.000000 ┆ 124325       ┆ 17               │
│ 2024-12-31 00:00:00.000000 ┆ 124334       ┆ 9                │
│ …                          ┆ …            ┆ …                │
│ 2025-04-28 00:00:00.000000 ┆ 129516       ┆ 106              │
│ 2025-04-29 00:00:00.000000 ┆ 129634       ┆ 118              │
│ 2025-04-30 00:00:00.000000 ┆ 129730       ┆ 96               │
│ 2025-05-01 00:00:00.000000 ┆ 129820       ┆ 90               │
│ 2025-05-02 00:00:00.000000 ┆ 129931       ┆ 111              │
└────────────────────────────┴──────────────┴──────────────────┘

alt.Chart(...)

In [38]:
segment('Lužánky - Plochá dráha')

shape: (117, 3)
┌────────────────────────────┬──────────────┬──────────────────┐
│ date                       ┆ effort_count ┆ daily_difference │
│ ---                        ┆ ---          ┆ ---              │
│ str                        ┆ i64          ┆ i64              │
╞════════════════════════════╪══════════════╪══════════════════╡
│ 2024-12-27 00:00:00.000000 ┆ 32752        ┆ 2                │
│ 2024-12-29 00:00:00.000000 ┆ 32746        ┆ 0                │
│ 2024-12-30 00:00:00.000000 ┆ 32763        ┆ 17               │
│ 2024-12-31 00:00:00.000000 ┆ 32763        ┆ 0                │
│ 2025-01-02 00:00:00.000000 ┆ 32762        ┆ 5                │
│ …                          ┆ …            ┆ …                │
│ 2025-04-28 00:00:00.000000 ┆ 34304        ┆ 0                │
│ 2025-04-29 00:00:00.000000 ┆ 34304        ┆ 0                │
│ 2025-04-30 00:00:00.000000 ┆ 34309        ┆ 5                │
│ 2025-05-01 00:00:00.000000 ┆ 34407        ┆ 98               │
│ 2025-05-02 00:00:00.000000 ┆ 34446        ┆ 39               │
└────────────────────────────┴──────────────┴──────────────────┘

alt.Chart(...)

In [39]:
segment('Risova studanka - od zavory')

shape: (125, 3)
┌────────────────────────────┬──────────────┬──────────────────┐
│ date                       ┆ effort_count ┆ daily_difference │
│ ---                        ┆ ---          ┆ ---              │
│ str                        ┆ i64          ┆ i64              │
╞════════════════════════════╪══════════════╪══════════════════╡
│ 2024-12-25 00:00:00.000000 ┆ 41328        ┆ 2                │
│ 2024-12-26 00:00:00.000000 ┆ 41336        ┆ 8                │
│ 2024-12-27 00:00:00.000000 ┆ 41351        ┆ 15               │
│ 2024-12-28 00:00:00.000000 ┆ 41360        ┆ 9                │
│ 2024-12-29 00:00:00.000000 ┆ 41365        ┆ 5                │
│ …                          ┆ …            ┆ …                │
│ 2025-04-28 00:00:00.000000 ┆ 42787        ┆ 31               │
│ 2025-04-29 00:00:00.000000 ┆ 42808        ┆ 21               │
│ 2025-04-30 00:00:00.000000 ┆ 42839        ┆ 31               │
│ 2025-05-01 00:00:00.000000 ┆ 42856        ┆ 17               │
│ 2025-05-02 00:00:00.000000 ┆ 42878        ┆ 22               │
└────────────────────────────┴──────────────┴──────────────────┘

alt.Chart(...)

In [40]:
segment('Brno Circuit')

shape: (125, 3)
┌────────────────────────────┬──────────────┬──────────────────┐
│ date                       ┆ effort_count ┆ daily_difference │
│ ---                        ┆ ---          ┆ ---              │
│ str                        ┆ i64          ┆ i64              │
╞════════════════════════════╪══════════════╪══════════════════╡
│ 2024-12-28 00:00:00.000000 ┆ 880          ┆ 0                │
│ 2024-12-29 00:00:00.000000 ┆ 881          ┆ 1                │
│ 2024-12-30 00:00:00.000000 ┆ 881          ┆ 0                │
│ 2024-12-31 00:00:00.000000 ┆ 881          ┆ 0                │
│ 2025-01-01 00:00:00.000000 ┆ 881          ┆ 0                │
│ …                          ┆ …            ┆ …                │
│ 2025-04-27 00:00:00.000000 ┆ 892          ┆ 0                │
│ 2025-04-28 00:00:00.000000 ┆ 892          ┆ 0                │
│ 2025-04-29 00:00:00.000000 ┆ 892          ┆ 0                │
│ 2025-05-01 00:00:00.000000 ┆ 890          ┆ 0                │
│ 2025-05-02 00:00:00.000000 ┆ 890          ┆ 0                │
└────────────────────────────┴──────────────┴──────────────────┘

alt.Chart(...)

In [41]:
df.filter(pl.col('country').str.contains('Cze')).filter(pl.col('activity_type') == 'Run').group_by("name").agg(pl.col('effort_count').cast(int).max()).sort(by='effort_count',descending=True)

shape: (113, 2)
┌──────────────────────────────┬──────────────┐
│ name                         ┆ effort_count │
│ ---                          ┆ ---          │
│ str                          ┆ i64          │
╞══════════════════════════════╪══════════════╡
│ Stadion Na Děkance           ┆ 226958       │
│ Lužánky rovinka              ┆ 191096       │
│ Šlechtovka - finální rovinka ┆ 168165       │
│ VUT horní dráha 400m         ┆ 121701       │
│ Strahovská dráha             ┆ 107888       │
│ …                            ┆ …            │
│ Valy                         ┆ 302          │
│ Autodrom Most                ┆ 236          │
│ kolem kapličky               ┆ 179          │
│ BRNĚNSKÁ SA CALOBRA          ┆ 84           │
│ ČSFR RIP                     ┆ 27           │
└──────────────────────────────┴──────────────┘

In [42]:
set(pl.Series(df.filter((pl.col('activity_type') == 'Run') & (pl.col('city') == 'Ostrava')).select("name")).to_list())

{'Hradní lávka => Sýkorův most',
 'Opavska down 1/2',
 'Park 1',
 'Železniční most => Jez Vítkovice'}

In [43]:
segment('Pražačka 320')

shape: (113, 3)
┌────────────────────────────┬──────────────┬──────────────────┐
│ date                       ┆ effort_count ┆ daily_difference │
│ ---                        ┆ ---          ┆ ---              │
│ str                        ┆ i64          ┆ i64              │
╞════════════════════════════╪══════════════╪══════════════════╡
│ 2024-12-27 00:00:00.000000 ┆ 74840        ┆ 23               │
│ 2024-12-29 00:00:00.000000 ┆ 74919        ┆ 101              │
│ 2024-12-30 00:00:00.000000 ┆ 74938        ┆ 19               │
│ 2024-12-31 00:00:00.000000 ┆ 74961        ┆ 23               │
│ 2025-01-01 00:00:00.000000 ┆ 75036        ┆ 75               │
│ …                          ┆ …            ┆ …                │
│ 2025-04-26 00:00:00.000000 ┆ 79646        ┆ 158              │
│ 2025-04-27 00:00:00.000000 ┆ 79877        ┆ 231              │
│ 2025-04-28 00:00:00.000000 ┆ 80288        ┆ 411              │
│ 2025-04-30 00:00:00.000000 ┆ 80197        ┆ 192              │
│ 2025-05-02 00:00:00.000000 ┆ 80268        ┆ 72               │
└────────────────────────────┴──────────────┴──────────────────┘

alt.Chart(...)

In [44]:
segment('Park 1')

shape: (127, 3)
┌────────────────────────────┬──────────────┬──────────────────┐
│ date                       ┆ effort_count ┆ daily_difference │
│ ---                        ┆ ---          ┆ ---              │
│ str                        ┆ i64          ┆ i64              │
╞════════════════════════════╪══════════════╪══════════════════╡
│ 2024-12-25 00:00:00.000000 ┆ 13566        ┆ 6                │
│ 2024-12-26 00:00:00.000000 ┆ 13571        ┆ 5                │
│ 2024-12-27 00:00:00.000000 ┆ 13571        ┆ 0                │
│ 2024-12-28 00:00:00.000000 ┆ 13573        ┆ 2                │
│ 2024-12-29 00:00:00.000000 ┆ 13576        ┆ 3                │
│ …                          ┆ …            ┆ …                │
│ 2025-04-28 00:00:00.000000 ┆ 14745        ┆ 13               │
│ 2025-04-29 00:00:00.000000 ┆ 14757        ┆ 12               │
│ 2025-04-30 00:00:00.000000 ┆ 14768        ┆ 11               │
│ 2025-05-01 00:00:00.000000 ┆ 14777        ┆ 9                │
│ 2025-05-02 00:00:00.000000 ┆ 14782        ┆ 5                │
└────────────────────────────┴──────────────┴──────────────────┘

alt.Chart(...)

In [45]:
segment('Hradní lávka => Sýkorův most')

shape: (126, 3)
┌────────────────────────────┬──────────────┬──────────────────┐
│ date                       ┆ effort_count ┆ daily_difference │
│ ---                        ┆ ---          ┆ ---              │
│ str                        ┆ i64          ┆ i64              │
╞════════════════════════════╪══════════════╪══════════════════╡
│ 2024-12-26 00:00:00.000000 ┆ 13983        ┆ 6                │
│ 2024-12-27 00:00:00.000000 ┆ 13985        ┆ 2                │
│ 2024-12-28 00:00:00.000000 ┆ 13987        ┆ 2                │
│ 2024-12-29 00:00:00.000000 ┆ 13992        ┆ 5                │
│ 2024-12-30 00:00:00.000000 ┆ 13998        ┆ 6                │
│ …                          ┆ …            ┆ …                │
│ 2025-04-28 00:00:00.000000 ┆ 15039        ┆ 5                │
│ 2025-04-29 00:00:00.000000 ┆ 15054        ┆ 15               │
│ 2025-04-30 00:00:00.000000 ┆ 15058        ┆ 4                │
│ 2025-05-01 00:00:00.000000 ┆ 15073        ┆ 15               │
│ 2025-05-02 00:00:00.000000 ┆ 15086        ┆ 13               │
└────────────────────────────┴──────────────┴──────────────────┘

alt.Chart(...)

In [46]:
df.group_by_dynamic("date", by="name", every="1d").agg(pl.col("effort_count").max())

C:\Users\micha\AppData\Local\Temp\ipykernel_24864\3197359101.py:1: DeprecationWarning: The argument `by` for `DataFrame.group_by_dynamic` is deprecated. It has been renamed to `group_by`.
  df.group_by_dynamic("date", by="name", every="1d").agg(pl.col("effort_count").max())

shape: (35_813, 3)
┌──────────────────────────┬──────────────────────────┬──────────────┐
│ name                     ┆ date                     ┆ effort_count │
│ ---                      ┆ ---                      ┆ ---          │
│ str                      ┆ datetime[μs, CET]        ┆ i64          │
╞══════════════════════════╪══════════════════════════╪══════════════╡
│ Dlouhe Strane od Loucnej ┆ 2024-12-24 00:00:00 CET  ┆ 308          │
│ Dlouhe Strane od Loucnej ┆ 2024-12-25 00:00:00 CET  ┆ 308          │
│ Dlouhe Strane od Loucnej ┆ 2024-12-26 00:00:00 CET  ┆ 308          │
│ Dlouhe Strane od Loucnej ┆ 2024-12-27 00:00:00 CET  ┆ 308          │
│ Dlouhe Strane od Loucnej ┆ 2024-12-28 00:00:00 CET  ┆ 308          │
│ …                        ┆ …                        ┆ …            │
│ kolem kapličky           ┆ 2025-04-28 00:00:00 CEST ┆ 162          │
│ kolem kapličky           ┆ 2025-04-29 00:00:00 CEST ┆ 166          │
│ kolem kapličky           ┆ 2025-04-30 00:00:00 CEST ┆ 171          │
│ kolem kapličky           ┆ 2025-05-01 00:00:00 CEST ┆ 172          │
│ kolem kapličky           ┆ 2025-05-02 00:00:00 CEST ┆ 179          │
└──────────────────────────┴──────────────────────────┴──────────────┘