In [1]:
import os
import polars as pl
import altair as alt

In [2]:
df = pl.read_parquet(os.path.join("data","segments.parquet")).sort(by="date")

In [113]:
df.group_by_dynamic(index_column="date",every="1d").agg(pl.col("name").unique().len()).sort(by="date")

shape: (27, 2)
┌──────────────────────────┬──────┐
│ date                     ┆ name │
│ ---                      ┆ ---  │
│ datetime[μs, CET]        ┆ u32  │
╞══════════════════════════╪══════╡
│ 2024-12-24 00:00:00 CET  ┆ 41   │
│ 2024-12-25 00:00:00 CET  ┆ 145  │
│ 2024-12-26 00:00:00 CET  ┆ 196  │
│ 2024-12-27 00:00:00 CET  ┆ 259  │
│ 2024-12-28 00:00:00 CET  ┆ 261  │
│ …                        ┆ …    │
│ 2025-08-01 00:00:00 CEST ┆ 289  │
│ 2025-08-20 00:00:00 CEST ┆ 287  │
│ 2025-11-02 00:00:00 CET  ┆ 289  │
│ 2025-11-13 00:00:00 CET  ┆ 289  │
│ 2025-11-24 00:00:00 CET  ┆ 289  │
└──────────────────────────┴──────┘

In [3]:
df.filter(pl.col("name") == "Risova studanka - od zavory")

shape: (28, 17)
┌─────────┬───────────────┬───────────────┬──────────┬───┬──────────────┬───────────────┬───────────────┬──────────────┐
│ id      ┆ name          ┆ activity_type ┆ distance ┆ … ┆ effort_count ┆ athlete_count ┆ date          ┆ start_to_fin │
│ ---     ┆ ---           ┆ ---           ┆ ---      ┆   ┆ ---          ┆ ---           ┆ ---           ┆ ish_distance │
│ i64     ┆ str           ┆ str           ┆ f64      ┆   ┆ i64          ┆ i64           ┆ datetime[μs,  ┆ ---          │
│         ┆               ┆               ┆          ┆   ┆              ┆               ┆ CET]          ┆ f64          │
╞═════════╪═══════════════╪═══════════════╪══════════╪═══╪══════════════╪═══════════════╪═══════════════╪══════════════╡
│ 7116683 ┆ Risova        ┆ Ride          ┆ 2612.4   ┆ … ┆ 41326        ┆ 4626          ┆ 2024-12-24    ┆ 2.507177     │
│         ┆ studanka - od ┆               ┆          ┆   ┆              ┆               ┆ 23:05:01 CET  ┆              │
│         ┆ zavory        ┆               ┆          ┆   ┆              ┆               ┆               ┆              │
│ 7116683 ┆ Risova        ┆ Ride          ┆ 2612.4   ┆ … ┆ 41328        ┆ 4626          ┆ 2024-12-25    ┆ 2.507177     │
│         ┆ studanka - od ┆               ┆          ┆   ┆              ┆               ┆ 23:05:55 CET  ┆              │
│         ┆ zavory        ┆               ┆          ┆   ┆              ┆               ┆               ┆              │
│ 7116683 ┆ Risova        ┆ Ride          ┆ 2612.4   ┆ … ┆ 41328        ┆ 4626          ┆ 2024-12-25    ┆ 2.507177     │
│         ┆ studanka - od ┆               ┆          ┆   ┆              ┆               ┆ 23:35:42 CET  ┆              │
│         ┆ zavory        ┆               ┆          ┆   ┆              ┆               ┆               ┆              │
│ 7116683 ┆ Risova        ┆ Ride          ┆ 2612.4   ┆ … ┆ 41336        ┆ 4626          ┆ 2024-12-26    ┆ 2.507177     │
│         ┆ studanka - od ┆               ┆          ┆   ┆              ┆               ┆ 23:05:33 CET  ┆              │
│         ┆ zavory        ┆               ┆          ┆   ┆              ┆               ┆               ┆              │
│ 7116683 ┆ Risova        ┆ Ride          ┆ 2612.4   ┆ … ┆ 41351        ┆ 4626          ┆ 2024-12-27    ┆ 2.507177     │
│         ┆ studanka - od ┆               ┆          ┆   ┆              ┆               ┆ 23:38:33 CET  ┆              │
│         ┆ zavory        ┆               ┆          ┆   ┆              ┆               ┆               ┆              │
│ …       ┆ …             ┆ …             ┆ …        ┆ … ┆ …            ┆ …             ┆ …             ┆ …            │
│ 7116683 ┆ Risova        ┆ Ride          ┆ 2612.4   ┆ … ┆ 44933        ┆ 5147          ┆ 2025-08-01    ┆ 2.507177     │
│         ┆ studanka - od ┆               ┆          ┆   ┆              ┆               ┆ 23:21:58 CEST ┆              │
│         ┆ zavory        ┆               ┆          ┆   ┆              ┆               ┆               ┆              │
│ 7116683 ┆ Risova        ┆ Ride          ┆ 2612.4   ┆ … ┆ 45446        ┆ 5192          ┆ 2025-08-20    ┆ 2.507177     │
│         ┆ studanka - od ┆               ┆          ┆   ┆              ┆               ┆ 23:39:51 CEST ┆              │
│         ┆ zavory        ┆               ┆          ┆   ┆              ┆               ┆               ┆              │
│ 7116683 ┆ Risova        ┆ Ride          ┆ 2612.4   ┆ … ┆ 46776        ┆ 5337          ┆ 2025-11-02    ┆ 2.507177     │
│         ┆ studanka - od ┆               ┆          ┆   ┆              ┆               ┆ 23:05:18 CET  ┆              │
│         ┆ zavory        ┆               ┆          ┆   ┆              ┆               ┆               ┆              │
│ 7116683 ┆ Risova        ┆ Ride          ┆ 2612.4   ┆ … ┆ 46974        ┆ 5339          ┆ 2025-11-13    ┆ 2.507177     │
│         ┆ studanka - od ┆               ┆          ┆   ┆              ┆               ┆ 23:38:50 CET  ┆              │
│         ┆ zavory        ┆               ┆          ┆   ┆              ┆               ┆               ┆              │
│ 7116683 ┆ Risova        ┆ Ride          ┆ 2612.4   ┆ … ┆ 47028        ┆ 5345          ┆ 2025-11-24    ┆ 2.507177     │
│         ┆ studanka - od ┆               ┆          ┆   ┆              ┆               ┆ 23:06:15 CET  ┆              │
│         ┆ zavory        ┆               ┆          ┆   ┆              ┆               ┆               ┆              │
└─────────┴───────────────┴───────────────┴──────────┴───┴──────────────┴───────────────┴───────────────┴──────────────┘

In [4]:
df.columns

['id',
 'name',
 'activity_type',
 'distance',
 'average_grade',
 'elevation_high',
 'elevation_low',
 'total_elevation_gain',
 'start_latlng',
 'end_latlng',
 'country',
 'state',
 'city',
 'effort_count',
 'athlete_count',
 'date',
 'start_to_finish_distance']

In [5]:
df.filter((pl.col("country") == "Czechia") & (pl.col('distance') > 500) & (pl.col('activity_type') == 'Ride')).select(pl.col('name')).unique().to_series().to_list()

['Dlouhe Strane od Loucnej',
 'podle Labe do Týnce',
 'MH - Klaster',
 'Vlevo dole jezero Most',
 'Solan last km',
 'Podél dálnice',
 'Kvilda Bučina',
 'Nová cyklostezka do Bosche  2',
 'Total brikule 🚀',
 'Dářská rašeliniště',
 'Rokytka od myčky',
 'Bečva - Pustevny Uphill',
 'Kleť k vysílači - finále',
 'Stezka do Zlina',
 'Nová cyklopěšina z Peřiny do HTčka',
 'Zrucskej smrtak',
 'panelka k bráně ˇerchova',
 'Srbsko - Hlásná Třebáň',
 'Maslovice - Kralupy',
 'time trial at Svratka',
 'Autodrom Most',
 'Sedýlko - Praděd climb',
 'Tuhnice most-Drahovice most,stezka',
 'Zlaťák konec - smrt',
 'Sprintík křižovatka/skalní mlýn',
 'Židlochovice -> Olympia',
 'svadov—valtirov',
 'Cyklostezka sprint směr Děčín',
 'Papezov - Prazmo',
 'do Srní',
 'Jiráskovo nábřeží k Husovce',
 'Jesenice-Blatno DH',
 'Výstup na Klínovec',
 'Ještěd Finale konec před kostkami.',
 'Hostyn-od.zastavky.po.znacku.P',
 'Sedmička, Lipno {',
 'Benešovský brdek',
 'S&Ch20 Masarykův okruh',
 'Revnicak Eve',
 'plný kule z kolína',
 'Od křižovatky do Strání po vysílač',
 'Klobouky Viadukt',
 'Decin - Bad Schandau Abzweig Radwg',
 'Šantovka - Kojeňák',
 'Bunč climb',
 'Špindlerovka - část II. (od Černýho potoka nahoru)',
 'Cyklostezka Náchod -> Velké Poříčí',
 'Adamaov climb',
 '611 - Mstetice',
 'Máchovo kritérium - přes bory kolem vrchu Borný',
 'Mutěnka - z Kyjova po odbočku na hraběcí',
 'Z Lednice po silnici k odbocce na Janohrad',
 'Novomlýnská 5: Věstonice-Strachotín',
 'Do sedla Klínovce po silnici',
 'Lysá hora - 5 km',
 'Szpic Jested  last 3 km ( od rozc na Dub)',
 'Kerhartice-Choceň',
 'Muglinovská→Hradní lávka (po pravém břehu)',
 'Černý důl konec Hoffmanky',
 'Trinec-Tesin',
 'Údolí Svatý Jan',
 'most - Loket',
 'Daskabát flat',
 'Výrovka - Modré Sedlo',
 'Cyklostezka Stará huť-Dobříš',
 'Sptint pod Býčí skálou',
 'Okolo Bobrůvky Tři Studně - Koupaliště NMNM',
 'stupani k vetr. mlynu Kuzelov',
 'Třebíč - Stařeč po cyklostezce (LS)',
 'Červená voda - Suchý vrch',
 'Kynšperský ATAK',
 'Červená podél Zlaté stoky do Třeboně',
 'Kaufland - Popendorf',
 'Starý Kolín - Svatá Kateřina',
 'segment z Tábora',
 'Plácky-soutok',
 'Šobes - sjezd',
 'Opičí Časovka, Podolská vodárna - Dvorce',
 'Ruda -> Gerlovka',
 'Podle Radbuzy',
 'Zbraslav - Komořany',
 'Lednice - Bulhary',
 'Eurovie - nadjezd Rosice',
 'Rovinka Beranov',
 'Krkonošská',
 'Sjezd Blatno-Březenec',
 'Klinovec Top',
 'Od posledního tunelu do Bílovic',
 'Pod Homoli Climb',
 'Final climb ke srubu na Deštnou',
 'Sprint Páteček - Santos',
 'Le Grande Classico',
 'Chrudim climb',
 'Kopec pod Barborou',
 'Risova studanka - od zavory']

In [6]:
def segment(nazev):
    segm = df.filter(pl.col('name') == nazev).group_by_dynamic("date", every="1d").agg(pl.col("effort_count").max())
    segm = segm.with_columns(pl.col("effort_count").diff().alias("daily_difference"))
    segm = segm.with_columns(pl.when(pl.col("daily_difference") < 0).then(None).otherwise(pl.col("daily_difference")).alias("daily_difference"))
    segm = segm.with_columns(pl.col("date").cast(str)).drop_nulls()
    print(segm)
    return alt.Chart(segm, width=800).mark_bar().encode(
        x='date:O',
        y='daily_difference:Q'
    )

In [7]:
segment("Risova studanka - od zavory")

shape: (26, 3)
┌─────────────────────────────────┬──────────────┬──────────────────┐
│ date                            ┆ effort_count ┆ daily_difference │
│ ---                             ┆ ---          ┆ ---              │
│ str                             ┆ i64          ┆ i64              │
╞═════════════════════════════════╪══════════════╪══════════════════╡
│ 2024-12-25 00:00:00.000000+01:… ┆ 41328        ┆ 2                │
│ 2024-12-26 00:00:00.000000+01:… ┆ 41336        ┆ 8                │
│ 2024-12-27 00:00:00.000000+01:… ┆ 41351        ┆ 15               │
│ 2024-12-28 00:00:00.000000+01:… ┆ 41360        ┆ 9                │
│ 2024-12-29 00:00:00.000000+01:… ┆ 41365        ┆ 5                │
│ …                               ┆ …            ┆ …                │
│ 2025-08-01 00:00:00.000000+02:… ┆ 44933        ┆ 1435             │
│ 2025-08-20 00:00:00.000000+02:… ┆ 45446        ┆ 513              │
│ 2025-11-02 00:00:00.000000+01:… ┆ 46776        ┆ 1330             │
│ 2025-11-13 00:00:00.000000+01:… ┆ 46974        ┆ 198              │
│ 2025-11-24 00:00:00.000000+01:… ┆ 47028        ┆ 54               │
└─────────────────────────────────┴──────────────┴──────────────────┘

alt.Chart(...)

In [8]:
segment("Zweite hup u ZOO")

shape: (26, 3)
┌─────────────────────────────────┬──────────────┬──────────────────┐
│ date                            ┆ effort_count ┆ daily_difference │
│ ---                             ┆ ---          ┆ ---              │
│ str                             ┆ i64          ┆ i64              │
╞═════════════════════════════════╪══════════════╪══════════════════╡
│ 2024-12-25 00:00:00.000000+01:… ┆ 233387       ┆ 37               │
│ 2024-12-26 00:00:00.000000+01:… ┆ 233414       ┆ 27               │
│ 2024-12-27 00:00:00.000000+01:… ┆ 233427       ┆ 13               │
│ 2024-12-28 00:00:00.000000+01:… ┆ 233437       ┆ 10               │
│ 2024-12-29 00:00:00.000000+01:… ┆ 233460       ┆ 23               │
│ …                               ┆ …            ┆ …                │
│ 2025-08-01 00:00:00.000000+02:… ┆ 258361       ┆ 10943            │
│ 2025-08-20 00:00:00.000000+02:… ┆ 262525       ┆ 4164             │
│ 2025-11-02 00:00:00.000000+01:… ┆ 272926       ┆ 10401            │
│ 2025-11-13 00:00:00.000000+01:… ┆ 273613       ┆ 687              │
│ 2025-11-24 00:00:00.000000+01:… ┆ 273946       ┆ 333              │
└─────────────────────────────────┴──────────────┴──────────────────┘

alt.Chart(...)

In [9]:
segment("Junglepark")

shape: (25, 3)
┌─────────────────────────────────┬──────────────┬──────────────────┐
│ date                            ┆ effort_count ┆ daily_difference │
│ ---                             ┆ ---          ┆ ---              │
│ str                             ┆ i64          ┆ i64              │
╞═════════════════════════════════╪══════════════╪══════════════════╡
│ 2024-12-25 00:00:00.000000+01:… ┆ 37930        ┆ 7                │
│ 2024-12-26 00:00:00.000000+01:… ┆ 37944        ┆ 14               │
│ 2024-12-27 00:00:00.000000+01:… ┆ 37953        ┆ 9                │
│ 2024-12-29 00:00:00.000000+01:… ┆ 37925        ┆ 18               │
│ 2024-12-30 00:00:00.000000+01:… ┆ 37932        ┆ 7                │
│ …                               ┆ …            ┆ …                │
│ 2025-08-01 00:00:00.000000+02:… ┆ 42311        ┆ 1222             │
│ 2025-08-20 00:00:00.000000+02:… ┆ 42632        ┆ 321              │
│ 2025-11-02 00:00:00.000000+01:… ┆ 44147        ┆ 1515             │
│ 2025-11-13 00:00:00.000000+01:… ┆ 44215        ┆ 68               │
│ 2025-11-24 00:00:00.000000+01:… ┆ 44404        ┆ 189              │
└─────────────────────────────────┴──────────────┴──────────────────┘

alt.Chart(...)

In [10]:
segment("Revnicak Eve")

shape: (25, 3)
┌─────────────────────────────────┬──────────────┬──────────────────┐
│ date                            ┆ effort_count ┆ daily_difference │
│ ---                             ┆ ---          ┆ ---              │
│ str                             ┆ i64          ┆ i64              │
╞═════════════════════════════════╪══════════════╪══════════════════╡
│ 2024-12-26 00:00:00.000000+01:… ┆ 43467        ┆ 3                │
│ 2024-12-27 00:00:00.000000+01:… ┆ 43469        ┆ 2                │
│ 2024-12-28 00:00:00.000000+01:… ┆ 43471        ┆ 2                │
│ 2024-12-29 00:00:00.000000+01:… ┆ 43478        ┆ 7                │
│ 2024-12-30 00:00:00.000000+01:… ┆ 43481        ┆ 3                │
│ …                               ┆ …            ┆ …                │
│ 2025-08-01 00:00:00.000000+02:… ┆ 47424        ┆ 1737             │
│ 2025-08-20 00:00:00.000000+02:… ┆ 48011        ┆ 587              │
│ 2025-11-02 00:00:00.000000+01:… ┆ 49387        ┆ 1376             │
│ 2025-11-13 00:00:00.000000+01:… ┆ 49506        ┆ 119              │
│ 2025-11-24 00:00:00.000000+01:… ┆ 49555        ┆ 49               │
└─────────────────────────────────┴──────────────┴──────────────────┘

alt.Chart(...)

In [11]:
segment("Sedmička, Lipno {")

shape: (21, 3)
┌─────────────────────────────────┬──────────────┬──────────────────┐
│ date                            ┆ effort_count ┆ daily_difference │
│ ---                             ┆ ---          ┆ ---              │
│ str                             ┆ i64          ┆ i64              │
╞═════════════════════════════════╪══════════════╪══════════════════╡
│ 2024-12-27 00:00:00.000000+01:… ┆ 12542        ┆ 1                │
│ 2024-12-30 00:00:00.000000+01:… ┆ 12540        ┆ 1                │
│ 2025-01-01 00:00:00.000000+01:… ┆ 12538        ┆ 0                │
│ 2025-01-02 00:00:00.000000+01:… ┆ 12539        ┆ 1                │
│ 2025-01-03 00:00:00.000000+01:… ┆ 12539        ┆ 0                │
│ …                               ┆ …            ┆ …                │
│ 2025-08-01 00:00:00.000000+02:… ┆ 13985        ┆ 912              │
│ 2025-08-20 00:00:00.000000+02:… ┆ 14466        ┆ 481              │
│ 2025-11-02 00:00:00.000000+01:… ┆ 15065        ┆ 599              │
│ 2025-11-13 00:00:00.000000+01:… ┆ 15069        ┆ 4                │
│ 2025-11-24 00:00:00.000000+01:… ┆ 15084        ┆ 15               │
└─────────────────────────────────┴──────────────┴──────────────────┘

alt.Chart(...)

In [12]:
segment("Solan last km")

shape: (23, 3)
┌─────────────────────────────────┬──────────────┬──────────────────┐
│ date                            ┆ effort_count ┆ daily_difference │
│ ---                             ┆ ---          ┆ ---              │
│ str                             ┆ i64          ┆ i64              │
╞═════════════════════════════════╪══════════════╪══════════════════╡
│ 2024-12-26 00:00:00.000000+01:… ┆ 12355        ┆ 0                │
│ 2024-12-27 00:00:00.000000+01:… ┆ 12358        ┆ 3                │
│ 2024-12-28 00:00:00.000000+01:… ┆ 12358        ┆ 0                │
│ 2024-12-29 00:00:00.000000+01:… ┆ 12358        ┆ 0                │
│ 2024-12-31 00:00:00.000000+01:… ┆ 12356        ┆ 0                │
│ …                               ┆ …            ┆ …                │
│ 2025-08-01 00:00:00.000000+02:… ┆ 13272        ┆ 404              │
│ 2025-08-20 00:00:00.000000+02:… ┆ 13516        ┆ 244              │
│ 2025-11-02 00:00:00.000000+01:… ┆ 14006        ┆ 490              │
│ 2025-11-13 00:00:00.000000+01:… ┆ 14014        ┆ 8                │
│ 2025-11-24 00:00:00.000000+01:… ┆ 14024        ┆ 10               │
└─────────────────────────────────┴──────────────┴──────────────────┘

alt.Chart(...)

In [13]:
segment("Zweite hup u ZOO")

shape: (26, 3)
┌─────────────────────────────────┬──────────────┬──────────────────┐
│ date                            ┆ effort_count ┆ daily_difference │
│ ---                             ┆ ---          ┆ ---              │
│ str                             ┆ i64          ┆ i64              │
╞═════════════════════════════════╪══════════════╪══════════════════╡
│ 2024-12-25 00:00:00.000000+01:… ┆ 233387       ┆ 37               │
│ 2024-12-26 00:00:00.000000+01:… ┆ 233414       ┆ 27               │
│ 2024-12-27 00:00:00.000000+01:… ┆ 233427       ┆ 13               │
│ 2024-12-28 00:00:00.000000+01:… ┆ 233437       ┆ 10               │
│ 2024-12-29 00:00:00.000000+01:… ┆ 233460       ┆ 23               │
│ …                               ┆ …            ┆ …                │
│ 2025-08-01 00:00:00.000000+02:… ┆ 258361       ┆ 10943            │
│ 2025-08-20 00:00:00.000000+02:… ┆ 262525       ┆ 4164             │
│ 2025-11-02 00:00:00.000000+01:… ┆ 272926       ┆ 10401            │
│ 2025-11-13 00:00:00.000000+01:… ┆ 273613       ┆ 687              │
│ 2025-11-24 00:00:00.000000+01:… ┆ 273946       ┆ 333              │
└─────────────────────────────────┴──────────────┴──────────────────┘

alt.Chart(...)

In [14]:
segment("Do sedla Klínovce po silnici")

shape: (22, 3)
┌─────────────────────────────────┬──────────────┬──────────────────┐
│ date                            ┆ effort_count ┆ daily_difference │
│ ---                             ┆ ---          ┆ ---              │
│ str                             ┆ i64          ┆ i64              │
╞═════════════════════════════════╪══════════════╪══════════════════╡
│ 2024-12-27 00:00:00.000000+01:… ┆ 15821        ┆ 0                │
│ 2024-12-28 00:00:00.000000+01:… ┆ 15822        ┆ 1                │
│ 2024-12-29 00:00:00.000000+01:… ┆ 15822        ┆ 0                │
│ 2024-12-30 00:00:00.000000+01:… ┆ 15822        ┆ 0                │
│ 2024-12-31 00:00:00.000000+01:… ┆ 15824        ┆ 2                │
│ …                               ┆ …            ┆ …                │
│ 2025-05-29 00:00:00.000000+02:… ┆ 16279        ┆ 28               │
│ 2025-08-01 00:00:00.000000+02:… ┆ 17278        ┆ 999              │
│ 2025-08-20 00:00:00.000000+02:… ┆ 17606        ┆ 328              │
│ 2025-11-02 00:00:00.000000+01:… ┆ 18021        ┆ 415              │
│ 2025-11-13 00:00:00.000000+01:… ┆ 18027        ┆ 6                │
└─────────────────────────────────┴──────────────┴──────────────────┘

alt.Chart(...)

In [15]:
segment('400 metrů, 44 120 diváků')

shape: (24, 3)
┌─────────────────────────────────┬──────────────┬──────────────────┐
│ date                            ┆ effort_count ┆ daily_difference │
│ ---                             ┆ ---          ┆ ---              │
│ str                             ┆ i64          ┆ i64              │
╞═════════════════════════════════╪══════════════╪══════════════════╡
│ 2024-12-26 00:00:00.000000+01:… ┆ 4461         ┆ 0                │
│ 2024-12-27 00:00:00.000000+01:… ┆ 4461         ┆ 0                │
│ 2024-12-28 00:00:00.000000+01:… ┆ 4461         ┆ 0                │
│ 2024-12-29 00:00:00.000000+01:… ┆ 4461         ┆ 0                │
│ 2024-12-30 00:00:00.000000+01:… ┆ 4461         ┆ 0                │
│ …                               ┆ …            ┆ …                │
│ 2025-05-29 00:00:00.000000+02:… ┆ 4655         ┆ 0                │
│ 2025-08-01 00:00:00.000000+02:… ┆ 4658         ┆ 3                │
│ 2025-11-02 00:00:00.000000+01:… ┆ 4667         ┆ 15               │
│ 2025-11-13 00:00:00.000000+01:… ┆ 4667         ┆ 0                │
│ 2025-11-24 00:00:00.000000+01:… ┆ 4667         ┆ 0                │
└─────────────────────────────────┴──────────────┴──────────────────┘

alt.Chart(...)

In [16]:
def weekly(segment):
    return df.filter(
        pl.col('name') == segment
    ).group_by_dynamic("date", every="1d").agg(
        pl.col("effort_count").max()
    ).with_columns(
        pl.col("effort_count").diff().alias("daily_difference")
    ).with_columns(
        pl.when(pl.col("daily_difference") < 0).then(None).otherwise(pl.col("daily_difference")).alias("daily_difference")
    ).drop_nulls(
    ).with_columns(
        pl.col("date").dt.weekday().alias("day")
    ).group_by("day").agg(pl.col("daily_difference").median()).sort(by="day")

In [17]:
def graf(tyden):
    return alt.Chart(tyden).mark_bar().encode(alt.X("day:N"), alt.Y("daily_difference:Q"))

In [18]:
graf(weekly("Track Domažlice"))

alt.Chart(...)

In [19]:
graf(weekly("Velká Deštná climb "))

alt.Chart(...)

In [20]:
graf(weekly("Židlochovice -> Olympia"))

alt.Chart(...)

In [21]:
graf(weekly("Od posledního tunelu do Bílovic"))

alt.Chart(...)

In [22]:
segment("Opičí Časovka, Podolská vodárna")

shape: (0, 3)
┌──────┬──────────────┬──────────────────┐
│ date ┆ effort_count ┆ daily_difference │
│ ---  ┆ ---          ┆ ---              │
│ str  ┆ i64          ┆ i64              │
╞══════╪══════════════╪══════════════════╡
└──────┴──────────────┴──────────────────┘

alt.Chart(...)

In [23]:
graf(weekly("Opičí Časovka, Podolská vodárna"))

alt.Chart(...)

In [24]:
segment("Vítkov up sprint ")

shape: (0, 3)
┌──────┬──────────────┬──────────────────┐
│ date ┆ effort_count ┆ daily_difference │
│ ---  ┆ ---          ┆ ---              │
│ str  ┆ i64          ┆ i64              │
╞══════╪══════════════╪══════════════════╡
└──────┴──────────────┴──────────────────┘

alt.Chart(...)

In [25]:
df.filter(pl.col("name").str.contains("Vítkov up sprint"))

shape: (24, 17)
┌──────────┬───────────┬────────────────┬──────────┬───┬──────────────┬────────────────┬───────────────┬───────────────┐
│ id       ┆ name      ┆ activity_type  ┆ distance ┆ … ┆ effort_count ┆ athlete_count  ┆ date          ┆ start_to_fini │
│ ---      ┆ ---       ┆ ---            ┆ ---      ┆   ┆ ---          ┆ ---            ┆ ---           ┆ sh_distance   │
│ i64      ┆ str       ┆ str            ┆ f64      ┆   ┆ i64          ┆ i64            ┆ datetime[μs,  ┆ ---           │
│          ┆           ┆                ┆          ┆   ┆              ┆                ┆ CET]          ┆ f64           │
╞══════════╪═══════════╪════════════════╪══════════╪═══╪══════════════╪════════════════╪═══════════════╪═══════════════╡
│ 14214163 ┆ Vítkov up ┆ Run            ┆ 118.2    ┆ … ┆ 86417        ┆ 8588           ┆ 2024-12-27    ┆ 0.117786      │
│          ┆ sprint    ┆                ┆          ┆   ┆              ┆                ┆ 23:22:03 CET  ┆               │
│ 14214163 ┆ Vítkov up ┆ Run            ┆ 118.2    ┆ … ┆ 86426        ┆ 8589           ┆ 2024-12-28    ┆ 0.117786      │
│          ┆ sprint    ┆                ┆          ┆   ┆              ┆                ┆ 23:05:37 CET  ┆               │
│ 14214163 ┆ Vítkov up ┆ Run            ┆ 118.2    ┆ … ┆ 86438        ┆ 8592           ┆ 2024-12-29    ┆ 0.117786      │
│          ┆ sprint    ┆                ┆          ┆   ┆              ┆                ┆ 23:38:26 CET  ┆               │
│ 14214163 ┆ Vítkov up ┆ Run            ┆ 118.2    ┆ … ┆ 86458        ┆ 8598           ┆ 2024-12-30    ┆ 0.117786      │
│          ┆ sprint    ┆                ┆          ┆   ┆              ┆                ┆ 23:21:42 CET  ┆               │
│ 14214163 ┆ Vítkov up ┆ Run            ┆ 118.2    ┆ … ┆ 86473        ┆ 8600           ┆ 2024-12-31    ┆ 0.117786      │
│          ┆ sprint    ┆                ┆          ┆   ┆              ┆                ┆ 23:22:02 CET  ┆               │
│ …        ┆ …         ┆ …              ┆ …        ┆ … ┆ …            ┆ …              ┆ …             ┆ …             │
│ 14214163 ┆ Vítkov up ┆ Run            ┆ 118.2    ┆ … ┆ 93272        ┆ 9772           ┆ 2025-08-01    ┆ 0.117786      │
│          ┆ sprint    ┆                ┆          ┆   ┆              ┆                ┆ 23:05:46 CEST ┆               │
│ 14214163 ┆ Vítkov up ┆ Run            ┆ 118.2    ┆ … ┆ 94120        ┆ 9909           ┆ 2025-08-20    ┆ 0.117786      │
│          ┆ sprint    ┆                ┆          ┆   ┆              ┆                ┆ 23:06:34 CEST ┆               │
│ 14214163 ┆ Vítkov up ┆ Run            ┆ 118.2    ┆ … ┆ 97412        ┆ 10449          ┆ 2025-11-02    ┆ 0.117786      │
│          ┆ sprint    ┆                ┆          ┆   ┆              ┆                ┆ 23:39:06 CET  ┆               │
│ 14214163 ┆ Vítkov up ┆ Run            ┆ 118.2    ┆ … ┆ 97858        ┆ 10511          ┆ 2025-11-13    ┆ 0.117786      │
│          ┆ sprint    ┆                ┆          ┆   ┆              ┆                ┆ 23:22:09 CET  ┆               │
│ 14214163 ┆ Vítkov up ┆ Run            ┆ 118.2    ┆ … ┆ 98285        ┆ 10558          ┆ 2025-11-24    ┆ 0.117786      │
│          ┆ sprint    ┆                ┆          ┆   ┆              ┆                ┆ 23:22:25 CET  ┆               │
└──────────┴───────────┴────────────────┴──────────┴───┴──────────────┴────────────────┴───────────────┴───────────────┘

In [26]:
graf(weekly("Vítkov up sprint"))

alt.Chart(...)

In [27]:
segment("Risova studanka - od zavory")

shape: (26, 3)
┌─────────────────────────────────┬──────────────┬──────────────────┐
│ date                            ┆ effort_count ┆ daily_difference │
│ ---                             ┆ ---          ┆ ---              │
│ str                             ┆ i64          ┆ i64              │
╞═════════════════════════════════╪══════════════╪══════════════════╡
│ 2024-12-25 00:00:00.000000+01:… ┆ 41328        ┆ 2                │
│ 2024-12-26 00:00:00.000000+01:… ┆ 41336        ┆ 8                │
│ 2024-12-27 00:00:00.000000+01:… ┆ 41351        ┆ 15               │
│ 2024-12-28 00:00:00.000000+01:… ┆ 41360        ┆ 9                │
│ 2024-12-29 00:00:00.000000+01:… ┆ 41365        ┆ 5                │
│ …                               ┆ …            ┆ …                │
│ 2025-08-01 00:00:00.000000+02:… ┆ 44933        ┆ 1435             │
│ 2025-08-20 00:00:00.000000+02:… ┆ 45446        ┆ 513              │
│ 2025-11-02 00:00:00.000000+01:… ┆ 46776        ┆ 1330             │
│ 2025-11-13 00:00:00.000000+01:… ┆ 46974        ┆ 198              │
│ 2025-11-24 00:00:00.000000+01:… ┆ 47028        ┆ 54               │
└─────────────────────────────────┴──────────────┴──────────────────┘

alt.Chart(...)

In [28]:
segment("Sedýlko - Praděd climb")

shape: (19, 3)
┌─────────────────────────────────┬──────────────┬──────────────────┐
│ date                            ┆ effort_count ┆ daily_difference │
│ ---                             ┆ ---          ┆ ---              │
│ str                             ┆ i64          ┆ i64              │
╞═════════════════════════════════╪══════════════╪══════════════════╡
│ 2024-12-25 00:00:00.000000+01:… ┆ 31962        ┆ 0                │
│ 2024-12-26 00:00:00.000000+01:… ┆ 31964        ┆ 2                │
│ 2024-12-27 00:00:00.000000+01:… ┆ 31969        ┆ 5                │
│ 2024-12-28 00:00:00.000000+01:… ┆ 31976        ┆ 7                │
│ 2024-12-29 00:00:00.000000+01:… ┆ 31977        ┆ 1                │
│ …                               ┆ …            ┆ …                │
│ 2025-08-01 00:00:00.000000+02:… ┆ 34195        ┆ 1673             │
│ 2025-08-20 00:00:00.000000+02:… ┆ 35028        ┆ 833              │
│ 2025-11-02 00:00:00.000000+01:… ┆ 36047        ┆ 1019             │
│ 2025-11-13 00:00:00.000000+01:… ┆ 36091        ┆ 44               │
│ 2025-11-24 00:00:00.000000+01:… ┆ 36099        ┆ 8                │
└─────────────────────────────────┴──────────────┴──────────────────┘

alt.Chart(...)

In [29]:
segment("Malchor - Lysá Hora")

shape: (25, 3)
┌─────────────────────────────────┬──────────────┬──────────────────┐
│ date                            ┆ effort_count ┆ daily_difference │
│ ---                             ┆ ---          ┆ ---              │
│ str                             ┆ i64          ┆ i64              │
╞═════════════════════════════════╪══════════════╪══════════════════╡
│ 2024-12-26 00:00:00.000000+01:… ┆ 19801        ┆ 47               │
│ 2024-12-27 00:00:00.000000+01:… ┆ 19835        ┆ 34               │
│ 2024-12-28 00:00:00.000000+01:… ┆ 19870        ┆ 35               │
│ 2024-12-29 00:00:00.000000+01:… ┆ 19910        ┆ 40               │
│ 2024-12-30 00:00:00.000000+01:… ┆ 19952        ┆ 42               │
│ …                               ┆ …            ┆ …                │
│ 2025-08-01 00:00:00.000000+02:… ┆ 22451        ┆ 749              │
│ 2025-08-20 00:00:00.000000+02:… ┆ 22814        ┆ 363              │
│ 2025-11-02 00:00:00.000000+01:… ┆ 23820        ┆ 1006             │
│ 2025-11-13 00:00:00.000000+01:… ┆ 23959        ┆ 139              │
│ 2025-11-24 00:00:00.000000+01:… ┆ 24099        ┆ 140              │
└─────────────────────────────────┴──────────────┴──────────────────┘

alt.Chart(...)

In [30]:
graf(weekly("Tyršák čtyřstofka"))

alt.Chart(...)

In [31]:
graf(weekly('Juliska 400 m'))

alt.Chart(...)

In [32]:
graf(weekly('Karlův most ONLY'))

alt.Chart(...)

In [33]:
segment("Ořešník")

shape: (24, 3)
┌─────────────────────────────────┬──────────────┬──────────────────┐
│ date                            ┆ effort_count ┆ daily_difference │
│ ---                             ┆ ---          ┆ ---              │
│ str                             ┆ i64          ┆ i64              │
╞═════════════════════════════════╪══════════════╪══════════════════╡
│ 2024-12-26 00:00:00.000000+01:… ┆ 1105         ┆ 1                │
│ 2024-12-27 00:00:00.000000+01:… ┆ 1105         ┆ 0                │
│ 2024-12-28 00:00:00.000000+01:… ┆ 1106         ┆ 1                │
│ 2024-12-30 00:00:00.000000+01:… ┆ 1105         ┆ 1                │
│ 2024-12-31 00:00:00.000000+01:… ┆ 1106         ┆ 1                │
│ …                               ┆ …            ┆ …                │
│ 2025-08-01 00:00:00.000000+02:… ┆ 1255         ┆ 70               │
│ 2025-08-20 00:00:00.000000+02:… ┆ 1306         ┆ 51               │
│ 2025-11-02 00:00:00.000000+01:… ┆ 1392         ┆ 86               │
│ 2025-11-13 00:00:00.000000+01:… ┆ 1408         ┆ 16               │
│ 2025-11-24 00:00:00.000000+01:… ┆ 1415         ┆ 7                │
└─────────────────────────────────┴──────────────┴──────────────────┘

alt.Chart(...)

In [34]:
df = pl.read_parquet("data_raw/segments/*.parquet")

df = df.with_columns(
    (pl.col("date").cast(pl.Int64) * 1000000).cast(pl.Datetime(time_zone='CET'))
)
df = df.filter(pl.col('date').dt.hour() > 22)
df = df.sort(by="date")

In [35]:
df.columns

['id',
 'resource_state',
 'name',
 'activity_type',
 'distance',
 'average_grade',
 'maximum_grade',
 'elevation_high',
 'elevation_low',
 'start_latlng',
 'end_latlng',
 'elevation_profile',
 'elevation_profiles',
 'climb_category',
 'city',
 'state',
 'country',
 'private',
 'hazardous',
 'starred',
 'created_at',
 'updated_at',
 'total_elevation_gain',
 'map',
 'effort_count',
 'athlete_count',
 'star_count',
 'athlete_segment_stats',
 'xoms',
 'local_legend',
 'date']

In [36]:
df.group_by_dynamic("date", by="name", every="1d").agg(pl.col("effort_count").max())

C:\Users\micha\AppData\Local\Temp\ipykernel_36148\3197359101.py:1: DeprecationWarning: the argument `by` for `DataFrame.group_by_dynamic` is deprecated. It was renamed to `group_by` in version 0.20.14.
  df.group_by_dynamic("date", by="name", every="1d").agg(pl.col("effort_count").max())

shape: (6_946, 3)
┌─────────────────────────────────┬──────────────────────────┬──────────────┐
│ name                            ┆ date                     ┆ effort_count │
│ ---                             ┆ ---                      ┆ ---          │
│ str                             ┆ datetime[μs, CET]        ┆ i64          │
╞═════════════════════════════════╪══════════════════════════╪══════════════╡
│ 400m                            ┆ 2024-12-26 00:00:00 CET  ┆ 33521        │
│ 400m                            ┆ 2024-12-27 00:00:00 CET  ┆ 33521        │
│ 400m                            ┆ 2024-12-28 00:00:00 CET  ┆ 33518        │
│ 400m                            ┆ 2024-12-29 00:00:00 CET  ┆ 33518        │
│ 400m                            ┆ 2024-12-30 00:00:00 CET  ┆ 33518        │
│ …                               ┆ …                        ┆ …            │
│ Szlak czerwony, Schronisko Nad… ┆ 2025-08-01 00:00:00 CEST ┆ 10355        │
│ Szlak czerwony, Schronisko Nad… ┆ 2025-08-20 00:00:00 CEST ┆ 10837        │
│ Szlak czerwony, Schronisko Nad… ┆ 2025-11-02 00:00:00 CET  ┆ 11815        │
│ Szlak czerwony, Schronisko Nad… ┆ 2025-11-13 00:00:00 CET  ┆ 11974        │
│ Szlak czerwony, Schronisko Nad… ┆ 2025-11-24 00:00:00 CET  ┆ 12082        │
└─────────────────────────────────┴──────────────────────────┴──────────────┘

In [37]:
df

shape: (7_113, 31)
┌──────────┬──────────────┬──────────────┬──────────────┬───┬──────────────┬──────────────┬──────────────┬─────────────┐
│ id       ┆ resource_sta ┆ name         ┆ activity_typ ┆ … ┆ athlete_segm ┆ xoms         ┆ local_legend ┆ date        │
│ ---      ┆ te           ┆ ---          ┆ e            ┆   ┆ ent_stats    ┆ ---          ┆ ---          ┆ ---         │
│ i64      ┆ ---          ┆ str          ┆ ---          ┆   ┆ ---          ┆ struct[4]    ┆ struct[7]    ┆ datetime[μs │
│          ┆ i64          ┆              ┆ str          ┆   ┆ struct[6]    ┆              ┆              ┆ , CET]      │
╞══════════╪══════════════╪══════════════╪══════════════╪═══╪══════════════╪══════════════╪══════════════╪═════════════╡
│ 7116683  ┆ 3            ┆ Risova       ┆ Ride         ┆ … ┆ {603,"2024-0 ┆ {"5:46","7:1 ┆ {6149474,"Ro ┆ 2024-12-24  │
│          ┆              ┆ studanka -   ┆              ┆   ┆ 9-08","every ┆ 8","5:46",{" ┆ bert Šmíd"," ┆ 23:05:01    │
│          ┆              ┆ od zavory    ┆              ┆   ┆ one",1…      ┆ strava…      ┆ https:…      ┆ CET         │
│ 35697355 ┆ 3            ┆ Židlochovice ┆ Ride         ┆ … ┆ {null,null,n ┆ {"19:00","21 ┆ {66888801,"S ┆ 2024-12-24  │
│          ┆              ┆ -> Olympia   ┆              ┆   ┆ ull,null,nul ┆ :20","19:00" ┆ tanislav     ┆ 23:05:02    │
│          ┆              ┆              ┆              ┆   ┆ l,0}         ┆ ,{"str…      ┆ Núdzik","…   ┆ CET         │
│ 21800746 ┆ 3            ┆ Bečva -      ┆ Ride         ┆ … ┆ {null,null,n ┆ {"24:16","29 ┆ {102711780," ┆ 2024-12-24  │
│          ┆              ┆ Pustevny     ┆              ┆   ┆ ull,null,nul ┆ :31","24:16" ┆ Jiri Plandor ┆ 23:05:02    │
│          ┆              ┆ Uphill       ┆              ┆   ┆ l,0}         ┆ ,{"str…      ┆ ","htt…      ┆ CET         │
│ 25124999 ┆ 3            ┆ Tuhnická     ┆ Run          ┆ … ┆ {null,null,n ┆ {"3:22","4:1 ┆ {73935215,"B ┆ 2024-12-24  │
│          ┆              ┆ lávka        ┆              ┆   ┆ ull,null,nul ┆ 5","3:22",{" ┆ lanka Novotn ┆ 23:05:03    │
│          ┆              ┆ -Chebský     ┆              ┆   ┆ l,0}         ┆ strava…      ┆ a","ht…      ┆ CET         │
│          ┆              ┆ most         ┆              ┆   ┆              ┆              ┆              ┆             │
│ 28445365 ┆ 3            ┆ Šup do parku ┆ Run          ┆ … ┆ {null,null,n ┆ {"1:19","1:3 ┆ {21845495,"L ┆ 2024-12-24  │
│          ┆              ┆              ┆              ┆   ┆ ull,null,nul ┆ 1","1:19",{" ┆ ukáš Šteky", ┆ 23:05:03    │
│          ┆              ┆              ┆              ┆   ┆ l,0}         ┆ strava…      ┆ "https…      ┆ CET         │
│ …        ┆ …            ┆ …            ┆ …            ┆ … ┆ …            ┆ …            ┆ …            ┆ …           │
│ 35233870 ┆ 3            ┆ Luční bouda  ┆ Hike         ┆ … ┆ {null,null,n ┆ {"25:30","28 ┆ {3315241,"Mi ┆ 2025-11-24  │
│          ┆              ┆ - Sněžka     ┆              ┆   ┆ ull,null,nul ┆ :37","25:30" ┆ rek Pniok"," ┆ 23:39:38    │
│          ┆              ┆              ┆              ┆   ┆ l,0}         ┆ ,{"str…      ┆ https:…      ┆ CET         │
│ 10695168 ┆ 3            ┆ Výrovka -    ┆ Ride         ┆ … ┆ {null,null,n ┆ {"5:48","8:0 ┆ {46046723,"J ┆ 2025-11-24  │
│          ┆              ┆ Modré Sedlo  ┆              ┆   ┆ ull,null,nul ┆ 5","5:48",{" ┆ akub Dostál" ┆ 23:39:38    │
│          ┆              ┆              ┆              ┆   ┆ l,0}         ┆ strava…      ┆ ,"http…      ┆ CET         │
│ 22926612 ┆ 3            ┆ Soláň-Tanečn ┆ Hike         ┆ … ┆ {null,null,n ┆ {"28:07","34 ┆ {46436878,"P ┆ 2025-11-24  │
│          ┆              ┆ ica          ┆              ┆   ┆ ull,null,nul ┆ :59","28:07" ┆ avel Vičan", ┆ 23:39:39    │
│          ┆              ┆              ┆              ┆   ┆ l,0}         ┆ ,{"str…      ┆ "https…      ┆ CET         │
│ 31996953 ┆ 3            ┆ Hradiště -   ┆ Run          ┆ … ┆ {null,null,n ┆ {"53s","1:03 ┆ {146831386," ┆ 2025-11-24  │
│          ┆              ┆ čtyřstovka   ┆              ┆   ┆ ull,null,nul ┆ ","53s",{"st ┆ Martin       ┆ 23:39:39    │
│          ┆              ┆              ┆              ┆   ┆ l,0}         ┆ rava:/…      ┆ Šuster","ht… ┆ CET         │
│ 8962925  ┆ 3            ┆ Viveros-Pase ┆ Run          ┆ … ┆ {null,null,n ┆ {"4:46","5:3 ┆ {61843458,"A ┆ 2025-11-24  │
│          ┆              ┆ o alameda    ┆              ┆   ┆ ull,null,nul ┆ 5","4:41",{" ┆ lfredo       ┆ 23:39:40    │
│          ┆              ┆              ┆              ┆   ┆ l,0}         ┆ strava…      ┆ Pastor Gime… ┆ CET         │
└──────────┴──────────────┴──────────────┴──────────────┴───┴──────────────┴──────────────┴──────────────┴─────────────┘

In [38]:
segment('Lužánky rovinka')

shape: (26, 3)
┌─────────────────────────────────┬──────────────┬──────────────────┐
│ date                            ┆ effort_count ┆ daily_difference │
│ ---                             ┆ ---          ┆ ---              │
│ str                             ┆ i64          ┆ i64              │
╞═════════════════════════════════╪══════════════╪══════════════════╡
│ 2024-12-25 00:00:00.000000+01:… ┆ 179488       ┆ 40               │
│ 2024-12-26 00:00:00.000000+01:… ┆ 179527       ┆ 39               │
│ 2024-12-27 00:00:00.000000+01:… ┆ 179560       ┆ 33               │
│ 2024-12-28 00:00:00.000000+01:… ┆ 179584       ┆ 24               │
│ 2024-12-29 00:00:00.000000+01:… ┆ 179626       ┆ 42               │
│ …                               ┆ …            ┆ …                │
│ 2025-08-01 00:00:00.000000+02:… ┆ 199701       ┆ 5298             │
│ 2025-08-20 00:00:00.000000+02:… ┆ 201228       ┆ 1527             │
│ 2025-11-02 00:00:00.000000+01:… ┆ 208430       ┆ 7202             │
│ 2025-11-13 00:00:00.000000+01:… ┆ 209515       ┆ 1085             │
│ 2025-11-24 00:00:00.000000+01:… ┆ 210301       ┆ 786              │
└─────────────────────────────────┴──────────────┴──────────────────┘

alt.Chart(...)

In [39]:
segment('time trial at Svratka')

shape: (26, 3)
┌─────────────────────────────────┬──────────────┬──────────────────┐
│ date                            ┆ effort_count ┆ daily_difference │
│ ---                             ┆ ---          ┆ ---              │
│ str                             ┆ i64          ┆ i64              │
╞═════════════════════════════════╪══════════════╪══════════════════╡
│ 2024-12-25 00:00:00.000000+01:… ┆ 141661       ┆ 24               │
│ 2024-12-26 00:00:00.000000+01:… ┆ 141680       ┆ 19               │
│ 2024-12-27 00:00:00.000000+01:… ┆ 141706       ┆ 26               │
│ 2024-12-28 00:00:00.000000+01:… ┆ 141721       ┆ 15               │
│ 2024-12-29 00:00:00.000000+01:… ┆ 141735       ┆ 14               │
│ …                               ┆ …            ┆ …                │
│ 2025-08-01 00:00:00.000000+02:… ┆ 154143       ┆ 5683             │
│ 2025-08-20 00:00:00.000000+02:… ┆ 156036       ┆ 1893             │
│ 2025-11-02 00:00:00.000000+01:… ┆ 160798       ┆ 4762             │
│ 2025-11-13 00:00:00.000000+01:… ┆ 161102       ┆ 304              │
│ 2025-11-24 00:00:00.000000+01:… ┆ 161293       ┆ 191              │
└─────────────────────────────────┴──────────────┴──────────────────┘

alt.Chart(...)

In [40]:
segment('Od posledního tunelu do Bílovic')

shape: (24, 3)
┌─────────────────────────────────┬──────────────┬──────────────────┐
│ date                            ┆ effort_count ┆ daily_difference │
│ ---                             ┆ ---          ┆ ---              │
│ str                             ┆ i64          ┆ i64              │
╞═════════════════════════════════╪══════════════╪══════════════════╡
│ 2024-12-26 00:00:00.000000+01:… ┆ 124240       ┆ 14               │
│ 2024-12-27 00:00:00.000000+01:… ┆ 124314       ┆ 74               │
│ 2024-12-29 00:00:00.000000+01:… ┆ 124308       ┆ 18               │
│ 2024-12-30 00:00:00.000000+01:… ┆ 124325       ┆ 17               │
│ 2024-12-31 00:00:00.000000+01:… ┆ 124334       ┆ 9                │
│ …                               ┆ …            ┆ …                │
│ 2025-08-01 00:00:00.000000+02:… ┆ 138777       ┆ 6545             │
│ 2025-08-20 00:00:00.000000+02:… ┆ 140943       ┆ 2166             │
│ 2025-11-02 00:00:00.000000+01:… ┆ 145377       ┆ 4434             │
│ 2025-11-13 00:00:00.000000+01:… ┆ 145655       ┆ 278              │
│ 2025-11-24 00:00:00.000000+01:… ┆ 145810       ┆ 155              │
└─────────────────────────────────┴──────────────┴──────────────────┘

alt.Chart(...)

In [41]:
segment('Lužánky - Plochá dráha')

shape: (22, 3)
┌─────────────────────────────────┬──────────────┬──────────────────┐
│ date                            ┆ effort_count ┆ daily_difference │
│ ---                             ┆ ---          ┆ ---              │
│ str                             ┆ i64          ┆ i64              │
╞═════════════════════════════════╪══════════════╪══════════════════╡
│ 2024-12-27 00:00:00.000000+01:… ┆ 32752        ┆ 2                │
│ 2024-12-29 00:00:00.000000+01:… ┆ 32746        ┆ 0                │
│ 2024-12-30 00:00:00.000000+01:… ┆ 32763        ┆ 17               │
│ 2024-12-31 00:00:00.000000+01:… ┆ 32763        ┆ 0                │
│ 2025-01-02 00:00:00.000000+01:… ┆ 32762        ┆ 5                │
│ …                               ┆ …            ┆ …                │
│ 2025-08-01 00:00:00.000000+02:… ┆ 36420        ┆ 1505             │
│ 2025-08-20 00:00:00.000000+02:… ┆ 36926        ┆ 506              │
│ 2025-11-02 00:00:00.000000+01:… ┆ 39068        ┆ 2142             │
│ 2025-11-13 00:00:00.000000+01:… ┆ 39319        ┆ 251              │
│ 2025-11-24 00:00:00.000000+01:… ┆ 39439        ┆ 120              │
└─────────────────────────────────┴──────────────┴──────────────────┘

alt.Chart(...)

In [42]:
segment('Risova studanka - od zavory')

shape: (26, 3)
┌─────────────────────────────────┬──────────────┬──────────────────┐
│ date                            ┆ effort_count ┆ daily_difference │
│ ---                             ┆ ---          ┆ ---              │
│ str                             ┆ i64          ┆ i64              │
╞═════════════════════════════════╪══════════════╪══════════════════╡
│ 2024-12-25 00:00:00.000000+01:… ┆ 41328        ┆ 2                │
│ 2024-12-26 00:00:00.000000+01:… ┆ 41336        ┆ 8                │
│ 2024-12-27 00:00:00.000000+01:… ┆ 41351        ┆ 15               │
│ 2024-12-28 00:00:00.000000+01:… ┆ 41360        ┆ 9                │
│ 2024-12-29 00:00:00.000000+01:… ┆ 41365        ┆ 5                │
│ …                               ┆ …            ┆ …                │
│ 2025-08-01 00:00:00.000000+02:… ┆ 44933        ┆ 1435             │
│ 2025-08-20 00:00:00.000000+02:… ┆ 45446        ┆ 513              │
│ 2025-11-02 00:00:00.000000+01:… ┆ 46776        ┆ 1330             │
│ 2025-11-13 00:00:00.000000+01:… ┆ 46974        ┆ 198              │
│ 2025-11-24 00:00:00.000000+01:… ┆ 47028        ┆ 54               │
└─────────────────────────────────┴──────────────┴──────────────────┘

alt.Chart(...)

In [43]:
segment('Brno Circuit')

shape: (20, 3)
┌─────────────────────────────────┬──────────────┬──────────────────┐
│ date                            ┆ effort_count ┆ daily_difference │
│ ---                             ┆ ---          ┆ ---              │
│ str                             ┆ i64          ┆ i64              │
╞═════════════════════════════════╪══════════════╪══════════════════╡
│ 2024-12-28 00:00:00.000000+01:… ┆ 880          ┆ 0                │
│ 2024-12-29 00:00:00.000000+01:… ┆ 881          ┆ 1                │
│ 2024-12-30 00:00:00.000000+01:… ┆ 881          ┆ 0                │
│ 2024-12-31 00:00:00.000000+01:… ┆ 881          ┆ 0                │
│ 2025-01-01 00:00:00.000000+01:… ┆ 881          ┆ 0                │
│ …                               ┆ …            ┆ …                │
│ 2025-05-29 00:00:00.000000+02:… ┆ 877          ┆ 0                │
│ 2025-08-01 00:00:00.000000+02:… ┆ 902          ┆ 25               │
│ 2025-08-20 00:00:00.000000+02:… ┆ 903          ┆ 1                │
│ 2025-11-13 00:00:00.000000+01:… ┆ 922          ┆ 24               │
│ 2025-11-24 00:00:00.000000+01:… ┆ 958          ┆ 36               │
└─────────────────────────────────┴──────────────┴──────────────────┘

alt.Chart(...)

In [44]:
df.filter(pl.col('country').str.contains('Cze')).filter(pl.col('activity_type') == 'Run').group_by("name").agg(pl.col('effort_count').cast(int).max()).sort(by='effort_count',descending=True)

shape: (117, 2)
┌──────────────────────────────┬──────────────┐
│ name                         ┆ effort_count │
│ ---                          ┆ ---          │
│ str                          ┆ i64          │
╞══════════════════════════════╪══════════════╡
│ Stadion Na Děkance           ┆ 247615       │
│ Lužánky rovinka              ┆ 210301       │
│ Šlechtovka - finální rovinka ┆ 190114       │
│ VUT horní dráha 400m         ┆ 142892       │
│ Strahovská dráha             ┆ 118017       │
│ …                            ┆ …            │
│ Podél tratě do Úval          ┆ 379          │
│ Kraličák Skyrace - 2. kopec  ┆ 368          │
│ Valy                         ┆ 362          │
│ Autodrom Most                ┆ 281          │
│ ČSFR RIP                     ┆ 42           │
└──────────────────────────────┴──────────────┘

In [45]:
set(pl.Series(df.filter((pl.col('activity_type') == 'Run') & (pl.col('city') == 'Ostrava')).select("name")).to_list())

{'Hradní lávka => Sýkorův most',
 'Opavska down 1/2',
 'Park 1',
 'Železniční most => Jez Vítkovice'}

In [46]:
segment('Pražačka 320')

shape: (22, 3)
┌─────────────────────────────────┬──────────────┬──────────────────┐
│ date                            ┆ effort_count ┆ daily_difference │
│ ---                             ┆ ---          ┆ ---              │
│ str                             ┆ i64          ┆ i64              │
╞═════════════════════════════════╪══════════════╪══════════════════╡
│ 2024-12-27 00:00:00.000000+01:… ┆ 74840        ┆ 23               │
│ 2024-12-29 00:00:00.000000+01:… ┆ 74919        ┆ 101              │
│ 2024-12-30 00:00:00.000000+01:… ┆ 74938        ┆ 19               │
│ 2024-12-31 00:00:00.000000+01:… ┆ 74961        ┆ 23               │
│ 2025-01-01 00:00:00.000000+01:… ┆ 75036        ┆ 75               │
│ …                               ┆ …            ┆ …                │
│ 2025-08-01 00:00:00.000000+02:… ┆ 87822        ┆ 5411             │
│ 2025-08-20 00:00:00.000000+02:… ┆ 90075        ┆ 2253             │
│ 2025-11-02 00:00:00.000000+01:… ┆ 97501        ┆ 7426             │
│ 2025-11-13 00:00:00.000000+01:… ┆ 98896        ┆ 1395             │
│ 2025-11-24 00:00:00.000000+01:… ┆ 99974        ┆ 1078             │
└─────────────────────────────────┴──────────────┴──────────────────┘

alt.Chart(...)

In [47]:
segment("Pec - Sněžka (přes Obřák)")

shape: (25, 3)
┌─────────────────────────────────┬──────────────┬──────────────────┐
│ date                            ┆ effort_count ┆ daily_difference │
│ ---                             ┆ ---          ┆ ---              │
│ str                             ┆ i64          ┆ i64              │
╞═════════════════════════════════╪══════════════╪══════════════════╡
│ 2024-12-26 00:00:00.000000+01:… ┆ 3487         ┆ 1                │
│ 2024-12-27 00:00:00.000000+01:… ┆ 3491         ┆ 4                │
│ 2024-12-28 00:00:00.000000+01:… ┆ 3493         ┆ 2                │
│ 2024-12-29 00:00:00.000000+01:… ┆ 3501         ┆ 8                │
│ 2024-12-30 00:00:00.000000+01:… ┆ 3503         ┆ 2                │
│ …                               ┆ …            ┆ …                │
│ 2025-08-01 00:00:00.000000+02:… ┆ 4066         ┆ 301              │
│ 2025-08-20 00:00:00.000000+02:… ┆ 4217         ┆ 151              │
│ 2025-11-02 00:00:00.000000+01:… ┆ 4492         ┆ 275              │
│ 2025-11-13 00:00:00.000000+01:… ┆ 4525         ┆ 33               │
│ 2025-11-24 00:00:00.000000+01:… ┆ 4554         ┆ 29               │
└─────────────────────────────────┴──────────────┴──────────────────┘

alt.Chart(...)

In [48]:
segment('Park 1')

shape: (26, 3)
┌─────────────────────────────────┬──────────────┬──────────────────┐
│ date                            ┆ effort_count ┆ daily_difference │
│ ---                             ┆ ---          ┆ ---              │
│ str                             ┆ i64          ┆ i64              │
╞═════════════════════════════════╪══════════════╪══════════════════╡
│ 2024-12-25 00:00:00.000000+01:… ┆ 13566        ┆ 6                │
│ 2024-12-26 00:00:00.000000+01:… ┆ 13571        ┆ 5                │
│ 2024-12-27 00:00:00.000000+01:… ┆ 13571        ┆ 0                │
│ 2024-12-28 00:00:00.000000+01:… ┆ 13573        ┆ 2                │
│ 2024-12-29 00:00:00.000000+01:… ┆ 13576        ┆ 3                │
│ …                               ┆ …            ┆ …                │
│ 2025-08-01 00:00:00.000000+02:… ┆ 15562        ┆ 522              │
│ 2025-08-20 00:00:00.000000+02:… ┆ 15760        ┆ 198              │
│ 2025-11-02 00:00:00.000000+01:… ┆ 16253        ┆ 493              │
│ 2025-11-13 00:00:00.000000+01:… ┆ 16320        ┆ 67               │
│ 2025-11-24 00:00:00.000000+01:… ┆ 16349        ┆ 29               │
└─────────────────────────────────┴──────────────┴──────────────────┘

alt.Chart(...)

In [49]:
segment("Tuhnická lávka -Chebský most")

shape: (26, 3)
┌─────────────────────────────────┬──────────────┬──────────────────┐
│ date                            ┆ effort_count ┆ daily_difference │
│ ---                             ┆ ---          ┆ ---              │
│ str                             ┆ i64          ┆ i64              │
╞═════════════════════════════════╪══════════════╪══════════════════╡
│ 2024-12-25 00:00:00.000000+01:… ┆ 3902         ┆ 7                │
│ 2024-12-26 00:00:00.000000+01:… ┆ 3902         ┆ 0                │
│ 2024-12-27 00:00:00.000000+01:… ┆ 3907         ┆ 5                │
│ 2024-12-28 00:00:00.000000+01:… ┆ 3911         ┆ 4                │
│ 2024-12-29 00:00:00.000000+01:… ┆ 3913         ┆ 2                │
│ …                               ┆ …            ┆ …                │
│ 2025-08-01 00:00:00.000000+02:… ┆ 4659         ┆ 211              │
│ 2025-08-20 00:00:00.000000+02:… ┆ 4733         ┆ 74               │
│ 2025-11-02 00:00:00.000000+01:… ┆ 4988         ┆ 255              │
│ 2025-11-13 00:00:00.000000+01:… ┆ 5032         ┆ 44               │
│ 2025-11-24 00:00:00.000000+01:… ┆ 5059         ┆ 27               │
└─────────────────────────────────┴──────────────┴──────────────────┘

alt.Chart(...)

In [50]:
segment("START")

shape: (4, 3)
┌─────────────────────────────────┬──────────────┬──────────────────┐
│ date                            ┆ effort_count ┆ daily_difference │
│ ---                             ┆ ---          ┆ ---              │
│ str                             ┆ i64          ┆ i64              │
╞═════════════════════════════════╪══════════════╪══════════════════╡
│ 2025-08-20 00:00:00.000000+02:… ┆ 8823         ┆ 38               │
│ 2025-11-02 00:00:00.000000+01:… ┆ 8960         ┆ 137              │
│ 2025-11-13 00:00:00.000000+01:… ┆ 8969         ┆ 9                │
│ 2025-11-24 00:00:00.000000+01:… ┆ 8974         ┆ 5                │
└─────────────────────────────────┴──────────────┴──────────────────┘

alt.Chart(...)

In [51]:
segment('Hradní lávka => Sýkorův most')

shape: (25, 3)
┌─────────────────────────────────┬──────────────┬──────────────────┐
│ date                            ┆ effort_count ┆ daily_difference │
│ ---                             ┆ ---          ┆ ---              │
│ str                             ┆ i64          ┆ i64              │
╞═════════════════════════════════╪══════════════╪══════════════════╡
│ 2024-12-26 00:00:00.000000+01:… ┆ 13983        ┆ 6                │
│ 2024-12-27 00:00:00.000000+01:… ┆ 13985        ┆ 2                │
│ 2024-12-28 00:00:00.000000+01:… ┆ 13987        ┆ 2                │
│ 2024-12-29 00:00:00.000000+01:… ┆ 13992        ┆ 5                │
│ 2024-12-30 00:00:00.000000+01:… ┆ 13998        ┆ 6                │
│ …                               ┆ …            ┆ …                │
│ 2025-08-01 00:00:00.000000+02:… ┆ 15919        ┆ 515              │
│ 2025-08-20 00:00:00.000000+02:… ┆ 16126        ┆ 207              │
│ 2025-11-02 00:00:00.000000+01:… ┆ 16917        ┆ 791              │
│ 2025-11-13 00:00:00.000000+01:… ┆ 17040        ┆ 123              │
│ 2025-11-24 00:00:00.000000+01:… ┆ 17120        ┆ 80               │
└─────────────────────────────────┴──────────────┴──────────────────┘

alt.Chart(...)

In [52]:
df.group_by_dynamic("date", by="name", every="1d").agg(pl.col("effort_count").max())

C:\Users\micha\AppData\Local\Temp\ipykernel_36148\3197359101.py:1: DeprecationWarning: the argument `by` for `DataFrame.group_by_dynamic` is deprecated. It was renamed to `group_by` in version 0.20.14.
  df.group_by_dynamic("date", by="name", every="1d").agg(pl.col("effort_count").max())

shape: (6_946, 3)
┌─────────────────────────────────┬──────────────────────────┬──────────────┐
│ name                            ┆ date                     ┆ effort_count │
│ ---                             ┆ ---                      ┆ ---          │
│ str                             ┆ datetime[μs, CET]        ┆ i64          │
╞═════════════════════════════════╪══════════════════════════╪══════════════╡
│ 400m                            ┆ 2024-12-26 00:00:00 CET  ┆ 33521        │
│ 400m                            ┆ 2024-12-27 00:00:00 CET  ┆ 33521        │
│ 400m                            ┆ 2024-12-28 00:00:00 CET  ┆ 33518        │
│ 400m                            ┆ 2024-12-29 00:00:00 CET  ┆ 33518        │
│ 400m                            ┆ 2024-12-30 00:00:00 CET  ┆ 33518        │
│ …                               ┆ …                        ┆ …            │
│ Szlak czerwony, Schronisko Nad… ┆ 2025-08-01 00:00:00 CEST ┆ 10355        │
│ Szlak czerwony, Schronisko Nad… ┆ 2025-08-20 00:00:00 CEST ┆ 10837        │
│ Szlak czerwony, Schronisko Nad… ┆ 2025-11-02 00:00:00 CET  ┆ 11815        │
│ Szlak czerwony, Schronisko Nad… ┆ 2025-11-13 00:00:00 CET  ┆ 11974        │
│ Szlak czerwony, Schronisko Nad… ┆ 2025-11-24 00:00:00 CET  ┆ 12082        │
└─────────────────────────────────┴──────────────────────────┴──────────────┘