In [1]:
import os
import polars as pl
import altair as alt

In [2]:
df = pl.read_parquet(os.path.join("data","segments.parquet")).sort(by="date")

In [3]:
df.group_by_dynamic(index_column="date",every="1d").agg(pl.col("name").unique().len()).sort(by="date").tail(10)

shape: (10, 2)
┌─────────────────────────┬──────┐
│ date                    ┆ name │
│ ---                     ┆ ---  │
│ datetime[μs, CET]       ┆ u32  │
╞═════════════════════════╪══════╡
│ 2026-02-27 00:00:00 CET ┆ 289  │
│ 2026-02-28 00:00:00 CET ┆ 289  │
│ 2026-03-01 00:00:00 CET ┆ 289  │
│ 2026-03-02 00:00:00 CET ┆ 289  │
│ 2026-03-03 00:00:00 CET ┆ 288  │
│ 2026-03-04 00:00:00 CET ┆ 289  │
│ 2026-03-05 00:00:00 CET ┆ 289  │
│ 2026-03-06 00:00:00 CET ┆ 289  │
│ 2026-03-07 00:00:00 CET ┆ 289  │
│ 2026-03-08 00:00:00 CET ┆ 289  │
└─────────────────────────┴──────┘

In [4]:
", ".join(df.select(pl.col("name")).sort(by="name").unique().to_series().to_list())

"#ULhalf - Strekovske Nabrezi, 15% Stoupák Bártlovka->Paličník, 2012 Pikes Peak Hill Climb, 400 m (track num. 2), 400 m - atletický okruh - Lokomotiva, 400 metrů, 44 120 diváků, 400m, 400m - Sportovní areál Na Stoupách, 400m-Jičín, 400m-Liberec, 611 - Mstetice, Adamaov climb, Alpe d'Huez, Autodrom Most, BK-nabrezi, BKJ - podél Labe, BL Boletice - rovinka na hřebeni, BRNĚNSKÁ SA CALOBRA, Benedikt - Parkoviště, Benešovský brdek, Berounka sprint, Bečva - Pustevny Uphill, Bludička-Opavice, Borůvková hora part II, Box Hill 2.2k, Brno Circuit, Bunč climb, Chrudim climb, Ciclo Via BNL -> K, Col du Tourmalet (par Luz, versant ouest), Col du Tourmalet (par Luz-St-Sauveur), Cyklostezka Náchod -> Velké Poříčí, Cyklostezka Stará huť-Dobříš, Cyklostezka sprint směr Děčín, Daskabát flat, Debř-Michalovice ☠, Decin - Bad Schandau Abzweig Radwg, Die Eine Runde, Dlouhe Strane od Loucnej, Dlouhá míle, Dneboh - Drábské Světničky, Do sadů, Do sedla Klínovce po silnici, Dom Śląski Up Hill, Dráha Plzeň okruh P, Dářská rašeliniště, Eurovie - nadjezd Rosice, Final climb ke srubu na Deštnou, Giro di Tyrš, Gránické údolí - Central Part DOWN, Hadí stezka (Svatobor), Hadí stezka na Svatobor 🐍, Harusák Climb, Hilo to Mauna Kea, Hlavní třídou nahoru, Hostyn-od.zastavky.po.znacku.P, Hoštejn-Zábřeh, Hrad Vevěří - Hráz, Hradiště - čtyřstovka, Hradní lávka => Sýkorův most, Hvězda flat, Interval, Javorník finish od Pinduly, Javorový od stanice lanovky, Jelenka - Sněžka, Jesenice-Blatno DH, JestedSkyrace - last uphill - middle part, Ještěd Finale konec před kostkami., Ježánky(Visalaje) - Bílý Kříž (směr Visalaje), Jindrichohradecky 1/2 M petikilo, Jiráskovo nábřeží k Husovce, Juliska 400 m, Junglepark, Kampa South, Karlov - k Velkému kotli, Karlův most ONLY, Kaufland - Popendorf, Kerhartice-Choceň, Kleť, Kleť k vysílači - finále, Klinovec Top, Klobouky Viadukt, Kolem stadionu, Kolo na stadionu v Třebíči, Kopec nářku, Kopec pod Barborou, Kopeček - od kruháče k bazilice, Koppenberg, Koupaliště sprint, Kozí hřbety - Luční bouda, Kočičí žleb - Ríšova studánka, Kraličák Skyrace - 2. kopec, Krkonošská, Krásnohorské, Ku řopíku, Kuželna - Splav 800m, Kvilda Bučina, Kynšperský ATAK, LS - Park Boost, Labe_po asfaltu, Lacinův kámen - Velká Skála, Le Grande Classico, Lednice - Bulhary, Llanberis path bottom section to the road, Luby end, Luisino údolí - Velká Deštná, Luční bouda - Sněžka, Lužánky - Plochá dráha, Lužánky rovinka, Lysa hora - jizni sjezdovka, Lysá hora - 5 km, Lípy (směrem do Jičína), MH - Klaster, Malchor - Lysá Hora, Maslovice - Kralupy, Mestsky stadion Trutnov, Mezi zábranama (proti proudu), Modrava - Tříjezerní slať, Mont Ventoux (l'ascension mythique par Bédoin), Mont Ventoux (par Bedoin), Mont Ventoux (par Bédoin), Most - Most -> Břeclav, Most Legií (směr Kampa), Muglinovská→Hradní lávka (po pravém břehu), Mutěnka - z Kyjova po odbočku na hraběcí, Máchovo kritérium - přes bory kolem vrchu Borný, Neklid -> Klínovec, Novomlýnská 5: Věstonice-Strachotín, Nová cyklopěšina z Peřiny do HTčka, Nová cyklostezka do Bosche  2, Nové Lesy-Dvůr Králové, Nábřeží, Obří hřeben - stoupák, Od Sanusu ke gymplu, Od bývalé sáňkařské dráhy po modré na Ještěd, Od dubu ke Gizele, Od křižovatky do Strání po vysílač, Od letňáku ke starému vchodu ZOO, Od lávky k lávce, Od posledního tunelu do Bílovic, Okolo Bobrůvky Tři Studně - Koupaliště NMNM, Okruhy Ochozou - Výběh na Harusák (0,76 km / 105 m), Ondřejník sedlo - Ondřejník vrchol, Opavice od zatáčky, Opavska down 1/2, Opičí Časovka, Podolská vodárna - Dvorce, Ostaš, Overtake the Boris Bikes, Ovál ZŠ Štefánikova, Ořešník, Panelovka-Tichá 800m, Papezov - Prazmo, Park 1, Passo Stelvio, Pavlov - Dívčí hrad climb, Pec - Sněžka (přes Obřák), Pisek podel reky I, Plácky-soutok, Pláně - Černý vrch, Po červené na Předěl, Po Šutrované od Alexandrovy rozhledny na kopec, Pod Homoli Climb, Pod Vilemínkou - Kralický Sněžník (žlutá), Pod rozhlednu Babi lom, Podle Radbuzy, Podél dálnice, Podél tratě do Úval, Posázavskou k odbočce před schody, Pražačka 320, Pristaviste-Minaret, Prostějov kolo dráha P, Pustevny - Radhošť, Revnicak Eve, Richmond ITT1, Richtrovy boudy - Výrovka, Risova studanka - od zavory, Rokytka od myčky, Rovinka Beranov, Rovinka od kruháče k bazénu, Ruda -> Gerlovka, Rullerovo nábřeží, Ručičky - Krakonošova snídaně (po žluté), Rybnik, Růžohorky - Růžová hora, S&Ch20 Masarykův okruh, START, Sa Calobra - Coll dels Reis, Schody voda - Hostýn, Sedmička, Lipno {, Sedýlko - Praděd climb, Segment, Sjezd Blatno-Březenec, Slezanský ovál, Smetanovy reverse, Snezka po schodech, Sněžník od Děčína (po červené), Solan last km, Soláň-Tanečnica, Sprint Páteček - Santos, Sprintík křižovatka/skalní mlýn, Sptint pod Býčí skálou, Srbsko - Hlásná Třebáň, Stadion - 400 m, Stadion Na Děkance, Stadion Čelákovice 400m (II.), Starý Kolín - Svatá Kateřina, Stelvio - Bormio Turn Downhill, Stezka do Zlina, Stezka nábřeží, Stodůlecký - Nepomucký rybník, Stojka na Pancíř, Stoupání na Templštejn, Strahovská dráha, Svaty kopecek up, Szlak czerwony, Schronisko Nad Łomniczką - Dom Śląski, Szpic Jested  last 3 km ( od rozc na Dub), TJ Sokol okruh, TJ Znojmo Lap, Tatran Třemošná, Total brikule 🚀, Track Domažlice, Transformator k Butorance (u studanky), Trinec-Tesin, Tuhnice most-Drahovice most,stezka, Tuhnická lávka -Chebský most, Tygří výzva, sklon 32% :), Tyršák čtyřstofka, Třebešín-dráha K, Třebíč - Stařeč po cyklostezce (LS), Tři prameny - Pravčická brána, Tříjezerní slať - Rokyta, U Jordánu do kopce, VR #11 finish, VUT horní dráha 400m, Valy, Velká Deštná climb, Velodrom 1kolo, Videlské sedlo-Švýcárna, Viveros-Paseo alameda, Vlevo dole jezero Most, Vojenský ovál 400M, Vítkov up sprint, Výpřež - Ještěd (po červené), Výrovka - Modré Sedlo, Výstup na Klínovec, Z Doubravky k Josefu, Z Lednice po silnici k odbocce na Janohrad, Zatáčky Žabovřeská, Zbraslav - Komořany, Zig-zag na Šerák, Zlaťák konec - smrt, Zrucskej smrtak, Zweite hup u ZOO, do Srní, hurá na Říp, k přehradě hop, kolem kapličky, kopec na hrad, mezi mosty, most - Loket, od hráze až na konec přehrady - silnice, panelka k bráně ˇerchova, plný kule z kolína, po cyklostezce, podle Labe do Týnce, podél Podměstského rybníku, rovinka kolem Sázavy:Plynovod-křižovatka u Mostu, segment z Tábora, stezka, stupani k vetr. mlynu Kuzelov, svadov—valtirov, tenis 1K, time trial at Svratka, Údolí Svatý Jan, ČSFR RIP, Černý důl konec Hoffmanky, Červená podél Zlaté stoky do Třeboně, Červená voda - Suchý vrch, Čerťák - Ručičky (po modré), Čtyrák 800m, Říp po žluté na vyhlídku, Šantovka - Kojeňák, Šlechtovka - finální rovinka, Šobes - sjezd, Špindlerovka - část II. (od Černýho potoka nahoru), Špindlerův Mlýn - Školní, Štvanická lávka (do Karlína), Šumbera pom. odb. - vysílač Hády, Šup do parku, Šárka Valley (short), Železniční most => Jez Vítkovice, Židlochovice -> Olympia, 🟡 Kočičí žleb - Ríšova studánka, 🟡 Šumbera pom. odb. - vysílač Hády"

In [5]:
df.filter(pl.col("name") == "Risova studanka - od zavory")

shape: (421, 17)
┌─────────┬───────────────┬───────────────┬──────────┬───┬──────────────┬───────────────┬───────────────┬──────────────┐
│ id      ┆ name          ┆ activity_type ┆ distance ┆ … ┆ effort_count ┆ athlete_count ┆ date          ┆ start_to_fin │
│ ---     ┆ ---           ┆ ---           ┆ ---      ┆   ┆ ---          ┆ ---           ┆ ---           ┆ ish_distance │
│ i64     ┆ str           ┆ str           ┆ f64      ┆   ┆ i64          ┆ i64           ┆ datetime[μs,  ┆ ---          │
│         ┆               ┆               ┆          ┆   ┆              ┆               ┆ CET]          ┆ f64          │
╞═════════╪═══════════════╪═══════════════╪══════════╪═══╪══════════════╪═══════════════╪═══════════════╪══════════════╡
│ 7116683 ┆ Risova        ┆ Ride          ┆ 2612.4   ┆ … ┆ 41326        ┆ 4626          ┆ 2024-12-24    ┆ 2.507177     │
│         ┆ studanka - od ┆               ┆          ┆   ┆              ┆               ┆ 23:05:01 CET  ┆              │
│         ┆ zavory        ┆               ┆          ┆   ┆              ┆               ┆               ┆              │
│ 7116683 ┆ Risova        ┆ Ride          ┆ 2612.4   ┆ … ┆ 41328        ┆ 4626          ┆ 2024-12-25    ┆ 2.507177     │
│         ┆ studanka - od ┆               ┆          ┆   ┆              ┆               ┆ 23:05:55 CET  ┆              │
│         ┆ zavory        ┆               ┆          ┆   ┆              ┆               ┆               ┆              │
│ 7116683 ┆ Risova        ┆ Ride          ┆ 2612.4   ┆ … ┆ 41328        ┆ 4626          ┆ 2024-12-25    ┆ 2.507177     │
│         ┆ studanka - od ┆               ┆          ┆   ┆              ┆               ┆ 23:35:42 CET  ┆              │
│         ┆ zavory        ┆               ┆          ┆   ┆              ┆               ┆               ┆              │
│ 7116683 ┆ Risova        ┆ Ride          ┆ 2612.4   ┆ … ┆ 41336        ┆ 4626          ┆ 2024-12-26    ┆ 2.507177     │
│         ┆ studanka - od ┆               ┆          ┆   ┆              ┆               ┆ 23:05:33 CET  ┆              │
│         ┆ zavory        ┆               ┆          ┆   ┆              ┆               ┆               ┆              │
│ 7116683 ┆ Risova        ┆ Ride          ┆ 2612.4   ┆ … ┆ 41351        ┆ 4626          ┆ 2024-12-27    ┆ 2.507177     │
│         ┆ studanka - od ┆               ┆          ┆   ┆              ┆               ┆ 23:38:33 CET  ┆              │
│         ┆ zavory        ┆               ┆          ┆   ┆              ┆               ┆               ┆              │
│ …       ┆ …             ┆ …             ┆ …        ┆ … ┆ …            ┆ …             ┆ …             ┆ …            │
│ 7116683 ┆ Risova        ┆ Ride          ┆ 2612.4   ┆ … ┆ 47226        ┆ 5352          ┆ 2026-03-04    ┆ 2.507177     │
│         ┆ studanka - od ┆               ┆          ┆   ┆              ┆               ┆ 23:21:45 CET  ┆              │
│         ┆ zavory        ┆               ┆          ┆   ┆              ┆               ┆               ┆              │
│ 7116683 ┆ Risova        ┆ Ride          ┆ 2612.4   ┆ … ┆ 47249        ┆ 5352          ┆ 2026-03-05    ┆ 2.507177     │
│         ┆ studanka - od ┆               ┆          ┆   ┆              ┆               ┆ 23:39:06 CET  ┆              │
│         ┆ zavory        ┆               ┆          ┆   ┆              ┆               ┆               ┆              │
│ 7116683 ┆ Risova        ┆ Ride          ┆ 2612.4   ┆ … ┆ 47264        ┆ 5357          ┆ 2026-03-06    ┆ 2.507177     │
│         ┆ studanka - od ┆               ┆          ┆   ┆              ┆               ┆ 23:05:18 CET  ┆              │
│         ┆ zavory        ┆               ┆          ┆   ┆              ┆               ┆               ┆              │
│ 7116683 ┆ Risova        ┆ Ride          ┆ 2612.4   ┆ … ┆ 47287        ┆ 5361          ┆ 2026-03-07    ┆ 2.507177     │
│         ┆ studanka - od ┆               ┆          ┆   ┆              ┆               ┆ 23:38:45 CET  ┆              │
│         ┆ zavory        ┆               ┆          ┆   ┆              ┆               ┆               ┆              │
│ 7116683 ┆ Risova        ┆ Ride          ┆ 2612.4   ┆ … ┆ 47310        ┆ 5365          ┆ 2026-03-08    ┆ 2.507177     │
│         ┆ studanka - od ┆               ┆          ┆   ┆              ┆               ┆ 23:21:54 CET  ┆              │
│         ┆ zavory        ┆               ┆          ┆   ┆              ┆               ┆               ┆              │
└─────────┴───────────────┴───────────────┴──────────┴───┴──────────────┴───────────────┴───────────────┴──────────────┘

In [6]:
df.columns

['id',
 'name',
 'activity_type',
 'distance',
 'average_grade',
 'elevation_high',
 'elevation_low',
 'total_elevation_gain',
 'start_latlng',
 'end_latlng',
 'country',
 'state',
 'city',
 'effort_count',
 'athlete_count',
 'date',
 'start_to_finish_distance']

In [7]:
df.filter((pl.col("country") == "Czechia") & (pl.col('distance') > 500) & (pl.col('activity_type') == 'Ride')).select(pl.col('name')).unique().to_series().to_list()

['time trial at Svratka',
 'Sedmička, Lipno {',
 'Novomlýnská 5: Věstonice-Strachotín',
 'Jiráskovo nábřeží k Husovce',
 'Nová cyklostezka do Bosche  2',
 'Srbsko - Hlásná Třebáň',
 'Bečva - Pustevny Uphill',
 'Od křižovatky do Strání po vysílač',
 'Do sedla Klínovce po silnici',
 'Dlouhe Strane od Loucnej',
 'Údolí Svatý Jan',
 'Červená voda - Suchý vrch',
 'Od posledního tunelu do Bílovic',
 'Ještěd Finale konec před kostkami.',
 'Výstup na Klínovec',
 'Plácky-soutok',
 'Chrudim climb',
 'stupani k vetr. mlynu Kuzelov',
 'Cyklostezka Stará huť-Dobříš',
 'Papezov - Prazmo',
 'Sptint pod Býčí skálou',
 'Revnicak Eve',
 'Židlochovice -> Olympia',
 'Nová cyklopěšina z Peřiny do HTčka',
 'Maslovice - Kralupy',
 'Tuhnice most-Drahovice most,stezka',
 'Z Lednice po silnici k odbocce na Janohrad',
 'Cyklostezka sprint směr Děčín',
 'panelka k bráně ˇerchova',
 'Šobes - sjezd',
 'most - Loket',
 'Daskabát flat',
 'Klobouky Viadukt',
 'MH - Klaster',
 'Podél dálnice',
 'Adamaov climb',
 'Trinec-Tesin',
 'Kaufland - Popendorf',
 'podle Labe do Týnce',
 'Jesenice-Blatno DH',
 'Třebíč - Stařeč po cyklostezce (LS)',
 'Solan last km',
 'Hostyn-od.zastavky.po.znacku.P',
 'Vlevo dole jezero Most',
 'Starý Kolín - Svatá Kateřina',
 'Sprintík křižovatka/skalní mlýn',
 'Cyklostezka Náchod -> Velké Poříčí',
 'Ruda -> Gerlovka',
 'Benešovský brdek',
 'Kvilda Bučina',
 'Červená podél Zlaté stoky do Třeboně',
 'Zlaťák konec - smrt',
 'Le Grande Classico',
 'Risova studanka - od zavory',
 'Total brikule 🚀',
 'Špindlerovka - část II. (od Černýho potoka nahoru)',
 'Lysá hora - 5 km',
 'Eurovie - nadjezd Rosice',
 'Kerhartice-Choceň',
 'Sjezd Blatno-Březenec',
 'plný kule z kolína',
 'Szpic Jested  last 3 km ( od rozc na Dub)',
 'Dářská rašeliniště',
 'Kopec pod Barborou',
 'Sedýlko - Praděd climb',
 'segment z Tábora',
 'Sprint Páteček - Santos',
 'Mutěnka - z Kyjova po odbočku na hraběcí',
 'Autodrom Most',
 'Stezka do Zlina',
 'Krkonošská',
 'Pod Homoli Climb',
 'do Srní',
 'Muglinovská→Hradní lávka (po pravém břehu)',
 'Výrovka - Modré Sedlo',
 'Final climb ke srubu na Deštnou',
 'Černý důl konec Hoffmanky',
 'Kleť k vysílači - finále',
 'svadov—valtirov',
 'Rokytka od myčky',
 'Decin - Bad Schandau Abzweig Radwg',
 'Šantovka - Kojeňák',
 'Klinovec Top',
 'Zrucskej smrtak',
 'Opičí Časovka, Podolská vodárna - Dvorce',
 'Okolo Bobrůvky Tři Studně - Koupaliště NMNM',
 'Rovinka Beranov',
 'Lednice - Bulhary',
 'Zbraslav - Komořany',
 '611 - Mstetice',
 'Podle Radbuzy',
 'Kynšperský ATAK',
 'Máchovo kritérium - přes bory kolem vrchu Borný',
 'Bunč climb',
 'S&Ch20 Masarykův okruh']

In [8]:
def segment(nazev,every="d"):
    segm = df.filter(pl.col('name') == nazev).group_by_dynamic("date", every=f"1{every}").agg(pl.col("effort_count").max())
    segm = segm.with_columns(pl.col("effort_count").diff().alias("daily_difference"))
    segm = segm.with_columns(pl.when(pl.col("daily_difference") < 0).then(None).otherwise(pl.col("daily_difference")).alias("daily_difference"))
    segm = segm.with_columns(pl.col("date").cast(str)).drop_nulls()
    print(segm)
    return alt.Chart(segm, width=800).mark_bar().encode(
        x='date:O',
        y='daily_difference:Q'
    )

In [9]:
segment("Risova studanka - od zavory",every='m')

shape: (399, 3)
┌─────────────────────────────────┬──────────────┬──────────────────┐
│ date                            ┆ effort_count ┆ daily_difference │
│ ---                             ┆ ---          ┆ ---              │
│ str                             ┆ i64          ┆ i64              │
╞═════════════════════════════════╪══════════════╪══════════════════╡
│ 2024-12-25 23:05:00.000000+01:… ┆ 41328        ┆ 2                │
│ 2024-12-25 23:35:00.000000+01:… ┆ 41328        ┆ 0                │
│ 2024-12-26 23:05:00.000000+01:… ┆ 41336        ┆ 8                │
│ 2024-12-27 23:38:00.000000+01:… ┆ 41351        ┆ 15               │
│ 2024-12-28 23:05:00.000000+01:… ┆ 41360        ┆ 9                │
│ …                               ┆ …            ┆ …                │
│ 2026-03-04 23:21:00.000000+01:… ┆ 47226        ┆ 13               │
│ 2026-03-05 23:39:00.000000+01:… ┆ 47249        ┆ 23               │
│ 2026-03-06 23:05:00.000000+01:… ┆ 47264        ┆ 15               │
│ 2026-03-07 23:38:00.000000+01:… ┆ 47287        ┆ 23               │
│ 2026-03-08 23:21:00.000000+01:… ┆ 47310        ┆ 23               │
└─────────────────────────────────┴──────────────┴──────────────────┘

alt.Chart(...)

In [10]:
segment("Zweite hup u ZOO")

shape: (405, 3)
┌─────────────────────────────────┬──────────────┬──────────────────┐
│ date                            ┆ effort_count ┆ daily_difference │
│ ---                             ┆ ---          ┆ ---              │
│ str                             ┆ i64          ┆ i64              │
╞═════════════════════════════════╪══════════════╪══════════════════╡
│ 2024-12-25 00:00:00.000000+01:… ┆ 233387       ┆ 37               │
│ 2024-12-26 00:00:00.000000+01:… ┆ 233414       ┆ 27               │
│ 2024-12-27 00:00:00.000000+01:… ┆ 233427       ┆ 13               │
│ 2024-12-28 00:00:00.000000+01:… ┆ 233437       ┆ 10               │
│ 2024-12-29 00:00:00.000000+01:… ┆ 233460       ┆ 23               │
│ …                               ┆ …            ┆ …                │
│ 2026-03-04 00:00:00.000000+01:… ┆ 276899       ┆ 103              │
│ 2026-03-05 00:00:00.000000+01:… ┆ 277004       ┆ 105              │
│ 2026-03-06 00:00:00.000000+01:… ┆ 277133       ┆ 129              │
│ 2026-03-07 00:00:00.000000+01:… ┆ 277373       ┆ 240              │
│ 2026-03-08 00:00:00.000000+01:… ┆ 277554       ┆ 181              │
└─────────────────────────────────┴──────────────┴──────────────────┘

alt.Chart(...)

In [11]:
segment("Junglepark")

shape: (407, 3)
┌─────────────────────────────────┬──────────────┬──────────────────┐
│ date                            ┆ effort_count ┆ daily_difference │
│ ---                             ┆ ---          ┆ ---              │
│ str                             ┆ i64          ┆ i64              │
╞═════════════════════════════════╪══════════════╪══════════════════╡
│ 2024-12-25 00:00:00.000000+01:… ┆ 37930        ┆ 7                │
│ 2024-12-26 00:00:00.000000+01:… ┆ 37944        ┆ 14               │
│ 2024-12-27 00:00:00.000000+01:… ┆ 37953        ┆ 9                │
│ 2024-12-29 00:00:00.000000+01:… ┆ 37925        ┆ 18               │
│ 2024-12-30 00:00:00.000000+01:… ┆ 37932        ┆ 7                │
│ …                               ┆ …            ┆ …                │
│ 2026-03-04 00:00:00.000000+01:… ┆ 46159        ┆ 29               │
│ 2026-03-05 00:00:00.000000+01:… ┆ 46176        ┆ 17               │
│ 2026-03-06 00:00:00.000000+01:… ┆ 46196        ┆ 20               │
│ 2026-03-07 00:00:00.000000+01:… ┆ 46213        ┆ 17               │
│ 2026-03-08 00:00:00.000000+01:… ┆ 46234        ┆ 21               │
└─────────────────────────────────┴──────────────┴──────────────────┘

alt.Chart(...)

In [12]:
segment("Revnicak Eve")

shape: (384, 3)
┌─────────────────────────────────┬──────────────┬──────────────────┐
│ date                            ┆ effort_count ┆ daily_difference │
│ ---                             ┆ ---          ┆ ---              │
│ str                             ┆ i64          ┆ i64              │
╞═════════════════════════════════╪══════════════╪══════════════════╡
│ 2024-12-26 00:00:00.000000+01:… ┆ 43467        ┆ 3                │
│ 2024-12-27 00:00:00.000000+01:… ┆ 43469        ┆ 2                │
│ 2024-12-28 00:00:00.000000+01:… ┆ 43471        ┆ 2                │
│ 2024-12-29 00:00:00.000000+01:… ┆ 43478        ┆ 7                │
│ 2024-12-30 00:00:00.000000+01:… ┆ 43481        ┆ 3                │
│ …                               ┆ …            ┆ …                │
│ 2026-03-04 00:00:00.000000+01:… ┆ 49770        ┆ 31               │
│ 2026-03-05 00:00:00.000000+01:… ┆ 49781        ┆ 11               │
│ 2026-03-06 00:00:00.000000+01:… ┆ 49786        ┆ 5                │
│ 2026-03-07 00:00:00.000000+01:… ┆ 49837        ┆ 51               │
│ 2026-03-08 00:00:00.000000+01:… ┆ 49868        ┆ 31               │
└─────────────────────────────────┴──────────────┴──────────────────┘

alt.Chart(...)

In [13]:
segment("Sedmička, Lipno {")

shape: (366, 3)
┌─────────────────────────────────┬──────────────┬──────────────────┐
│ date                            ┆ effort_count ┆ daily_difference │
│ ---                             ┆ ---          ┆ ---              │
│ str                             ┆ i64          ┆ i64              │
╞═════════════════════════════════╪══════════════╪══════════════════╡
│ 2024-12-27 00:00:00.000000+01:… ┆ 12542        ┆ 1                │
│ 2024-12-30 00:00:00.000000+01:… ┆ 12540        ┆ 1                │
│ 2025-01-01 00:00:00.000000+01:… ┆ 12538        ┆ 0                │
│ 2025-01-02 00:00:00.000000+01:… ┆ 12539        ┆ 1                │
│ 2025-01-03 00:00:00.000000+01:… ┆ 12539        ┆ 0                │
│ …                               ┆ …            ┆ …                │
│ 2026-03-01 00:00:00.000000+01:… ┆ 15032        ┆ 0                │
│ 2026-03-03 00:00:00.000000+01:… ┆ 15031        ┆ 1                │
│ 2026-03-04 00:00:00.000000+01:… ┆ 15032        ┆ 1                │
│ 2026-03-07 00:00:00.000000+01:… ┆ 15030        ┆ 1                │
│ 2026-03-08 00:00:00.000000+01:… ┆ 15033        ┆ 3                │
└─────────────────────────────────┴──────────────┴──────────────────┘

alt.Chart(...)

In [14]:
segment("Solan last km")

shape: (397, 3)
┌─────────────────────────────────┬──────────────┬──────────────────┐
│ date                            ┆ effort_count ┆ daily_difference │
│ ---                             ┆ ---          ┆ ---              │
│ str                             ┆ i64          ┆ i64              │
╞═════════════════════════════════╪══════════════╪══════════════════╡
│ 2024-12-26 00:00:00.000000+01:… ┆ 12355        ┆ 0                │
│ 2024-12-27 00:00:00.000000+01:… ┆ 12358        ┆ 3                │
│ 2024-12-28 00:00:00.000000+01:… ┆ 12358        ┆ 0                │
│ 2024-12-29 00:00:00.000000+01:… ┆ 12358        ┆ 0                │
│ 2024-12-31 00:00:00.000000+01:… ┆ 12356        ┆ 0                │
│ …                               ┆ …            ┆ …                │
│ 2026-03-04 00:00:00.000000+01:… ┆ 14060        ┆ 0                │
│ 2026-03-05 00:00:00.000000+01:… ┆ 14061        ┆ 1                │
│ 2026-03-06 00:00:00.000000+01:… ┆ 14066        ┆ 5                │
│ 2026-03-07 00:00:00.000000+01:… ┆ 14075        ┆ 9                │
│ 2026-03-08 00:00:00.000000+01:… ┆ 14088        ┆ 13               │
└─────────────────────────────────┴──────────────┴──────────────────┘

alt.Chart(...)

In [15]:
segment("Zweite hup u ZOO")

shape: (405, 3)
┌─────────────────────────────────┬──────────────┬──────────────────┐
│ date                            ┆ effort_count ┆ daily_difference │
│ ---                             ┆ ---          ┆ ---              │
│ str                             ┆ i64          ┆ i64              │
╞═════════════════════════════════╪══════════════╪══════════════════╡
│ 2024-12-25 00:00:00.000000+01:… ┆ 233387       ┆ 37               │
│ 2024-12-26 00:00:00.000000+01:… ┆ 233414       ┆ 27               │
│ 2024-12-27 00:00:00.000000+01:… ┆ 233427       ┆ 13               │
│ 2024-12-28 00:00:00.000000+01:… ┆ 233437       ┆ 10               │
│ 2024-12-29 00:00:00.000000+01:… ┆ 233460       ┆ 23               │
│ …                               ┆ …            ┆ …                │
│ 2026-03-04 00:00:00.000000+01:… ┆ 276899       ┆ 103              │
│ 2026-03-05 00:00:00.000000+01:… ┆ 277004       ┆ 105              │
│ 2026-03-06 00:00:00.000000+01:… ┆ 277133       ┆ 129              │
│ 2026-03-07 00:00:00.000000+01:… ┆ 277373       ┆ 240              │
│ 2026-03-08 00:00:00.000000+01:… ┆ 277554       ┆ 181              │
└─────────────────────────────────┴──────────────┴──────────────────┘

alt.Chart(...)

In [16]:
segment("Do sedla Klínovce po silnici")

shape: (369, 3)
┌─────────────────────────────────┬──────────────┬──────────────────┐
│ date                            ┆ effort_count ┆ daily_difference │
│ ---                             ┆ ---          ┆ ---              │
│ str                             ┆ i64          ┆ i64              │
╞═════════════════════════════════╪══════════════╪══════════════════╡
│ 2024-12-27 00:00:00.000000+01:… ┆ 15821        ┆ 0                │
│ 2024-12-28 00:00:00.000000+01:… ┆ 15822        ┆ 1                │
│ 2024-12-29 00:00:00.000000+01:… ┆ 15822        ┆ 0                │
│ 2024-12-30 00:00:00.000000+01:… ┆ 15822        ┆ 0                │
│ 2024-12-31 00:00:00.000000+01:… ┆ 15824        ┆ 2                │
│ …                               ┆ …            ┆ …                │
│ 2026-03-04 00:00:00.000000+01:… ┆ 18050        ┆ 0                │
│ 2026-03-05 00:00:00.000000+01:… ┆ 18050        ┆ 0                │
│ 2026-03-06 00:00:00.000000+01:… ┆ 18054        ┆ 4                │
│ 2026-03-07 00:00:00.000000+01:… ┆ 18055        ┆ 1                │
│ 2026-03-08 00:00:00.000000+01:… ┆ 18056        ┆ 1                │
└─────────────────────────────────┴──────────────┴──────────────────┘

alt.Chart(...)

In [17]:
segment('400 metrů, 44 120 diváků')

shape: (415, 3)
┌─────────────────────────────────┬──────────────┬──────────────────┐
│ date                            ┆ effort_count ┆ daily_difference │
│ ---                             ┆ ---          ┆ ---              │
│ str                             ┆ i64          ┆ i64              │
╞═════════════════════════════════╪══════════════╪══════════════════╡
│ 2024-12-26 00:00:00.000000+01:… ┆ 4461         ┆ 0                │
│ 2024-12-27 00:00:00.000000+01:… ┆ 4461         ┆ 0                │
│ 2024-12-28 00:00:00.000000+01:… ┆ 4461         ┆ 0                │
│ 2024-12-29 00:00:00.000000+01:… ┆ 4461         ┆ 0                │
│ 2024-12-30 00:00:00.000000+01:… ┆ 4461         ┆ 0                │
│ …                               ┆ …            ┆ …                │
│ 2026-03-04 00:00:00.000000+01:… ┆ 4677         ┆ 0                │
│ 2026-03-05 00:00:00.000000+01:… ┆ 4677         ┆ 0                │
│ 2026-03-06 00:00:00.000000+01:… ┆ 4677         ┆ 0                │
│ 2026-03-07 00:00:00.000000+01:… ┆ 4677         ┆ 0                │
│ 2026-03-08 00:00:00.000000+01:… ┆ 4677         ┆ 0                │
└─────────────────────────────────┴──────────────┴──────────────────┘

alt.Chart(...)

In [18]:
def weekly(segment):
    return df.filter(
        pl.col('name') == segment
    ).group_by_dynamic("date", every="1d").agg(
        pl.col("effort_count").max()
    ).with_columns(
        pl.col("effort_count").diff().alias("daily_difference")
    ).with_columns(
        pl.when(pl.col("daily_difference") < 0).then(None).otherwise(pl.col("daily_difference")).alias("daily_difference")
    ).drop_nulls(
    ).with_columns(
        pl.col("date").dt.weekday().alias("day")
    ).group_by("day").agg(pl.col("daily_difference").median()).sort(by="day")

In [19]:
def graf(tyden):
    return alt.Chart(tyden).mark_bar().encode(alt.X("day:N"), alt.Y("daily_difference:Q"))

In [20]:
graf(weekly("Track Domažlice"))

alt.Chart(...)

In [21]:
graf(weekly("Velká Deštná climb "))

alt.Chart(...)

In [22]:
graf(weekly("Židlochovice -> Olympia"))

alt.Chart(...)

In [23]:
graf(weekly("Od posledního tunelu do Bílovic"))

alt.Chart(...)

In [24]:
segment("Opičí Časovka, Podolská vodárna")

shape: (0, 3)
┌──────┬──────────────┬──────────────────┐
│ date ┆ effort_count ┆ daily_difference │
│ ---  ┆ ---          ┆ ---              │
│ str  ┆ i64          ┆ i64              │
╞══════╪══════════════╪══════════════════╡
└──────┴──────────────┴──────────────────┘

alt.Chart(...)

In [25]:
graf(weekly("Opičí Časovka, Podolská vodárna"))

alt.Chart(...)

In [26]:
segment("Vítkov up sprint ")

shape: (0, 3)
┌──────┬──────────────┬──────────────────┐
│ date ┆ effort_count ┆ daily_difference │
│ ---  ┆ ---          ┆ ---              │
│ str  ┆ i64          ┆ i64              │
╞══════╪══════════════╪══════════════════╡
└──────┴──────────────┴──────────────────┘

alt.Chart(...)

In [27]:
df.filter(pl.col("name").str.contains("Vítkov up sprint"))

shape: (417, 17)
┌──────────┬───────────┬────────────────┬──────────┬───┬──────────────┬────────────────┬───────────────┬───────────────┐
│ id       ┆ name      ┆ activity_type  ┆ distance ┆ … ┆ effort_count ┆ athlete_count  ┆ date          ┆ start_to_fini │
│ ---      ┆ ---       ┆ ---            ┆ ---      ┆   ┆ ---          ┆ ---            ┆ ---           ┆ sh_distance   │
│ i64      ┆ str       ┆ str            ┆ f64      ┆   ┆ i64          ┆ i64            ┆ datetime[μs,  ┆ ---           │
│          ┆           ┆                ┆          ┆   ┆              ┆                ┆ CET]          ┆ f64           │
╞══════════╪═══════════╪════════════════╪══════════╪═══╪══════════════╪════════════════╪═══════════════╪═══════════════╡
│ 14214163 ┆ Vítkov up ┆ Run            ┆ 118.2    ┆ … ┆ 86417        ┆ 8588           ┆ 2024-12-27    ┆ 0.117786      │
│          ┆ sprint    ┆                ┆          ┆   ┆              ┆                ┆ 23:22:03 CET  ┆               │
│ 14214163 ┆ Vítkov up ┆ Run            ┆ 118.2    ┆ … ┆ 86426        ┆ 8589           ┆ 2024-12-28    ┆ 0.117786      │
│          ┆ sprint    ┆                ┆          ┆   ┆              ┆                ┆ 23:05:37 CET  ┆               │
│ 14214163 ┆ Vítkov up ┆ Run            ┆ 118.2    ┆ … ┆ 86438        ┆ 8592           ┆ 2024-12-29    ┆ 0.117786      │
│          ┆ sprint    ┆                ┆          ┆   ┆              ┆                ┆ 23:38:26 CET  ┆               │
│ 14214163 ┆ Vítkov up ┆ Run            ┆ 118.2    ┆ … ┆ 86458        ┆ 8598           ┆ 2024-12-30    ┆ 0.117786      │
│          ┆ sprint    ┆                ┆          ┆   ┆              ┆                ┆ 23:21:42 CET  ┆               │
│ 14214163 ┆ Vítkov up ┆ Run            ┆ 118.2    ┆ … ┆ 86473        ┆ 8600           ┆ 2024-12-31    ┆ 0.117786      │
│          ┆ sprint    ┆                ┆          ┆   ┆              ┆                ┆ 23:22:02 CET  ┆               │
│ …        ┆ …         ┆ …              ┆ …        ┆ … ┆ …            ┆ …              ┆ …             ┆ …             │
│ 14214163 ┆ Vítkov up ┆ Run            ┆ 118.2    ┆ … ┆ 102420       ┆ 10988          ┆ 2026-03-04    ┆ 0.117786      │
│          ┆ sprint    ┆                ┆          ┆   ┆              ┆                ┆ 23:22:08 CET  ┆               │
│ 14214163 ┆ Vítkov up ┆ Run            ┆ 118.2    ┆ … ┆ 102472       ┆ 10997          ┆ 2026-03-05    ┆ 0.117786      │
│          ┆ sprint    ┆                ┆          ┆   ┆              ┆                ┆ 23:22:21 CET  ┆               │
│ 14214163 ┆ Vítkov up ┆ Run            ┆ 118.2    ┆ … ┆ 102517       ┆ 11008          ┆ 2026-03-06    ┆ 0.117786      │
│          ┆ sprint    ┆                ┆          ┆   ┆              ┆                ┆ 23:22:01 CET  ┆               │
│ 14214163 ┆ Vítkov up ┆ Run            ┆ 118.2    ┆ … ┆ 102582       ┆ 11014          ┆ 2026-03-07    ┆ 0.117786      │
│          ┆ sprint    ┆                ┆          ┆   ┆              ┆                ┆ 23:38:31 CET  ┆               │
│ 14214163 ┆ Vítkov up ┆ Run            ┆ 118.2    ┆ … ┆ 102605       ┆ 11019          ┆ 2026-03-08    ┆ 0.117786      │
│          ┆ sprint    ┆                ┆          ┆   ┆              ┆                ┆ 23:05:36 CET  ┆               │
└──────────┴───────────┴────────────────┴──────────┴───┴──────────────┴────────────────┴───────────────┴───────────────┘

In [28]:
graf(weekly("Vítkov up sprint"))

alt.Chart(...)

In [29]:
segment("Risova studanka - od zavory")

shape: (398, 3)
┌─────────────────────────────────┬──────────────┬──────────────────┐
│ date                            ┆ effort_count ┆ daily_difference │
│ ---                             ┆ ---          ┆ ---              │
│ str                             ┆ i64          ┆ i64              │
╞═════════════════════════════════╪══════════════╪══════════════════╡
│ 2024-12-25 00:00:00.000000+01:… ┆ 41328        ┆ 2                │
│ 2024-12-26 00:00:00.000000+01:… ┆ 41336        ┆ 8                │
│ 2024-12-27 00:00:00.000000+01:… ┆ 41351        ┆ 15               │
│ 2024-12-28 00:00:00.000000+01:… ┆ 41360        ┆ 9                │
│ 2024-12-29 00:00:00.000000+01:… ┆ 41365        ┆ 5                │
│ …                               ┆ …            ┆ …                │
│ 2026-03-04 00:00:00.000000+01:… ┆ 47226        ┆ 13               │
│ 2026-03-05 00:00:00.000000+01:… ┆ 47249        ┆ 23               │
│ 2026-03-06 00:00:00.000000+01:… ┆ 47264        ┆ 15               │
│ 2026-03-07 00:00:00.000000+01:… ┆ 47287        ┆ 23               │
│ 2026-03-08 00:00:00.000000+01:… ┆ 47310        ┆ 23               │
└─────────────────────────────────┴──────────────┴──────────────────┘

alt.Chart(...)

In [30]:
segment("Sedýlko - Praděd climb")

shape: (348, 3)
┌─────────────────────────────────┬──────────────┬──────────────────┐
│ date                            ┆ effort_count ┆ daily_difference │
│ ---                             ┆ ---          ┆ ---              │
│ str                             ┆ i64          ┆ i64              │
╞═════════════════════════════════╪══════════════╪══════════════════╡
│ 2024-12-25 00:00:00.000000+01:… ┆ 31962        ┆ 0                │
│ 2024-12-26 00:00:00.000000+01:… ┆ 31964        ┆ 2                │
│ 2024-12-27 00:00:00.000000+01:… ┆ 31969        ┆ 5                │
│ 2024-12-28 00:00:00.000000+01:… ┆ 31976        ┆ 7                │
│ 2024-12-29 00:00:00.000000+01:… ┆ 31977        ┆ 1                │
│ …                               ┆ …            ┆ …                │
│ 2026-03-04 00:00:00.000000+01:… ┆ 36060        ┆ 0                │
│ 2026-03-05 00:00:00.000000+01:… ┆ 36062        ┆ 2                │
│ 2026-03-06 00:00:00.000000+01:… ┆ 36063        ┆ 1                │
│ 2026-03-07 00:00:00.000000+01:… ┆ 36065        ┆ 2                │
│ 2026-03-08 00:00:00.000000+01:… ┆ 36065        ┆ 0                │
└─────────────────────────────────┴──────────────┴──────────────────┘

alt.Chart(...)

In [31]:
segment("Malchor - Lysá Hora")

shape: (413, 3)
┌─────────────────────────────────┬──────────────┬──────────────────┐
│ date                            ┆ effort_count ┆ daily_difference │
│ ---                             ┆ ---          ┆ ---              │
│ str                             ┆ i64          ┆ i64              │
╞═════════════════════════════════╪══════════════╪══════════════════╡
│ 2024-12-26 00:00:00.000000+01:… ┆ 19801        ┆ 47               │
│ 2024-12-27 00:00:00.000000+01:… ┆ 19835        ┆ 34               │
│ 2024-12-28 00:00:00.000000+01:… ┆ 19870        ┆ 35               │
│ 2024-12-29 00:00:00.000000+01:… ┆ 19910        ┆ 40               │
│ 2024-12-30 00:00:00.000000+01:… ┆ 19952        ┆ 42               │
│ …                               ┆ …            ┆ …                │
│ 2026-03-04 00:00:00.000000+01:… ┆ 25563        ┆ 6                │
│ 2026-03-05 00:00:00.000000+01:… ┆ 25578        ┆ 15               │
│ 2026-03-06 00:00:00.000000+01:… ┆ 25589        ┆ 11               │
│ 2026-03-07 00:00:00.000000+01:… ┆ 25625        ┆ 36               │
│ 2026-03-08 00:00:00.000000+01:… ┆ 25647        ┆ 22               │
└─────────────────────────────────┴──────────────┴──────────────────┘

alt.Chart(...)

In [32]:
graf(weekly("Tyršák čtyřstofka"))

alt.Chart(...)

In [33]:
graf(weekly('Juliska 400 m'))

alt.Chart(...)

In [34]:
graf(weekly('Karlův most ONLY'))

alt.Chart(...)

In [35]:
segment("Ořešník")

shape: (392, 3)
┌─────────────────────────────────┬──────────────┬──────────────────┐
│ date                            ┆ effort_count ┆ daily_difference │
│ ---                             ┆ ---          ┆ ---              │
│ str                             ┆ i64          ┆ i64              │
╞═════════════════════════════════╪══════════════╪══════════════════╡
│ 2024-12-26 00:00:00.000000+01:… ┆ 1105         ┆ 1                │
│ 2024-12-27 00:00:00.000000+01:… ┆ 1105         ┆ 0                │
│ 2024-12-28 00:00:00.000000+01:… ┆ 1106         ┆ 1                │
│ 2024-12-30 00:00:00.000000+01:… ┆ 1105         ┆ 1                │
│ 2024-12-31 00:00:00.000000+01:… ┆ 1106         ┆ 1                │
│ …                               ┆ …            ┆ …                │
│ 2026-03-04 00:00:00.000000+01:… ┆ 1453         ┆ 0                │
│ 2026-03-05 00:00:00.000000+01:… ┆ 1453         ┆ 0                │
│ 2026-03-06 00:00:00.000000+01:… ┆ 1455         ┆ 2                │
│ 2026-03-07 00:00:00.000000+01:… ┆ 1456         ┆ 1                │
│ 2026-03-08 00:00:00.000000+01:… ┆ 1460         ┆ 4                │
└─────────────────────────────────┴──────────────┴──────────────────┘

alt.Chart(...)

In [36]:
df = pl.read_parquet("data_raw/segments/*.parquet")

df = df.with_columns(
    (pl.col("date").cast(pl.Int64) * 1000000).cast(pl.Datetime(time_zone='CET'))
)
df = df.filter(pl.col('date').dt.hour() > 22)
df = df.sort(by="date")

In [37]:
df.columns

['id',
 'resource_state',
 'name',
 'activity_type',
 'distance',
 'average_grade',
 'maximum_grade',
 'elevation_high',
 'elevation_low',
 'start_latlng',
 'end_latlng',
 'elevation_profile',
 'elevation_profiles',
 'climb_category',
 'city',
 'state',
 'country',
 'private',
 'hazardous',
 'starred',
 'created_at',
 'updated_at',
 'total_elevation_gain',
 'map',
 'effort_count',
 'athlete_count',
 'star_count',
 'athlete_segment_stats',
 'xoms',
 'local_legend',
 'date']

In [38]:
df.group_by_dynamic("date", by="name", every="1d").agg(pl.col("effort_count").max())

C:\Users\micha\AppData\Local\Temp\ipykernel_7020\3197359101.py:1: DeprecationWarning: the argument `by` for `DataFrame.group_by_dynamic` is deprecated. It was renamed to `group_by` in version 0.20.14.
  df.group_by_dynamic("date", by="name", every="1d").agg(pl.col("effort_count").max())

shape: (109_107, 3)
┌─────────────────────────────────┬─────────────────────────┬──────────────┐
│ name                            ┆ date                    ┆ effort_count │
│ ---                             ┆ ---                     ┆ ---          │
│ str                             ┆ datetime[μs, CET]       ┆ i64          │
╞═════════════════════════════════╪═════════════════════════╪══════════════╡
│ 400m                            ┆ 2024-12-26 00:00:00 CET ┆ 33521        │
│ 400m                            ┆ 2024-12-27 00:00:00 CET ┆ 33521        │
│ 400m                            ┆ 2024-12-28 00:00:00 CET ┆ 33518        │
│ 400m                            ┆ 2024-12-29 00:00:00 CET ┆ 33518        │
│ 400m                            ┆ 2024-12-30 00:00:00 CET ┆ 33518        │
│ …                               ┆ …                       ┆ …            │
│ Szlak czerwony, Schronisko Nad… ┆ 2026-01-20 00:00:00 CET ┆ 12321        │
│ Szlak czerwony, Schronisko Nad… ┆ 2026-01-21 00:00:00 CET ┆ 12321        │
│ Szlak czerwony, Schronisko Nad… ┆ 2026-01-22 00:00:00 CET ┆ 12322        │
│ Szlak czerwony, Schronisko Nad… ┆ 2026-01-23 00:00:00 CET ┆ 12322        │
│ Szlak czerwony, Schronisko Nad… ┆ 2026-01-24 00:00:00 CET ┆ 12322        │
└─────────────────────────────────┴─────────────────────────┴──────────────┘

In [39]:
df

shape: (109_629, 31)
┌──────────┬──────────────┬──────────────┬──────────────┬───┬──────────────┬──────────────┬──────────────┬─────────────┐
│ id       ┆ resource_sta ┆ name         ┆ activity_typ ┆ … ┆ athlete_segm ┆ xoms         ┆ local_legend ┆ date        │
│ ---      ┆ te           ┆ ---          ┆ e            ┆   ┆ ent_stats    ┆ ---          ┆ ---          ┆ ---         │
│ i64      ┆ ---          ┆ str          ┆ ---          ┆   ┆ ---          ┆ struct[4]    ┆ struct[7]    ┆ datetime[μs │
│          ┆ i64          ┆              ┆ str          ┆   ┆ struct[6]    ┆              ┆              ┆ , CET]      │
╞══════════╪══════════════╪══════════════╪══════════════╪═══╪══════════════╪══════════════╪══════════════╪═════════════╡
│ 7116683  ┆ 3            ┆ Risova       ┆ Ride         ┆ … ┆ {603,"2024-0 ┆ {"5:46","7:1 ┆ {6149474,"Ro ┆ 2024-12-24  │
│          ┆              ┆ studanka -   ┆              ┆   ┆ 9-08","every ┆ 8","5:46",{" ┆ bert Šmíd"," ┆ 23:05:01    │
│          ┆              ┆ od zavory    ┆              ┆   ┆ one",1…      ┆ strava…      ┆ https:…      ┆ CET         │
│ 21800746 ┆ 3            ┆ Bečva -      ┆ Ride         ┆ … ┆ {null,null,n ┆ {"24:16","29 ┆ {102711780," ┆ 2024-12-24  │
│          ┆              ┆ Pustevny     ┆              ┆   ┆ ull,null,nul ┆ :31","24:16" ┆ Jiri Plandor ┆ 23:05:02    │
│          ┆              ┆ Uphill       ┆              ┆   ┆ l,0}         ┆ ,{"str…      ┆ ","htt…      ┆ CET         │
│ 35697355 ┆ 3            ┆ Židlochovice ┆ Ride         ┆ … ┆ {null,null,n ┆ {"19:00","21 ┆ {66888801,"S ┆ 2024-12-24  │
│          ┆              ┆ -> Olympia   ┆              ┆   ┆ ull,null,nul ┆ :20","19:00" ┆ tanislav     ┆ 23:05:02    │
│          ┆              ┆              ┆              ┆   ┆ l,0}         ┆ ,{"str…      ┆ Núdzik","…   ┆ CET         │
│ 28445365 ┆ 3            ┆ Šup do parku ┆ Run          ┆ … ┆ {null,null,n ┆ {"1:19","1:3 ┆ {21845495,"L ┆ 2024-12-24  │
│          ┆              ┆              ┆              ┆   ┆ ull,null,nul ┆ 1","1:19",{" ┆ ukáš Šteky", ┆ 23:05:03    │
│          ┆              ┆              ┆              ┆   ┆ l,0}         ┆ strava…      ┆ "https…      ┆ CET         │
│ 13197258 ┆ 3            ┆ Pavlov -     ┆ Run          ┆ … ┆ {null,null,n ┆ {"6:01","8:4 ┆ {73652736,"O ┆ 2024-12-24  │
│          ┆              ┆ Dívčí hrad   ┆              ┆   ┆ ull,null,nul ┆ 1","6:01",{" ┆ ndřej Janás" ┆ 23:05:03    │
│          ┆              ┆ climb        ┆              ┆   ┆ l,0}         ┆ strava…      ┆ ,"http…      ┆ CET         │
│ …        ┆ …            ┆ …            ┆ …            ┆ … ┆ …            ┆ …            ┆ …            ┆ …           │
│ 12366202 ┆ 3            ┆ Jelenka -    ┆ Run          ┆ … ┆ {null,null,n ┆ {"19:41","23 ┆ {36771394,"H ┆ 2026-01-24  │
│          ┆              ┆ Sněžka       ┆              ┆   ┆ ull,null,nul ┆ :47","19:41" ┆ alina Markow ┆ 23:39:06    │
│          ┆              ┆              ┆              ┆   ┆ l,0}         ┆ ,{"str…      ┆ ska-Mi…      ┆ CET         │
│ 29588014 ┆ 3            ┆ Špindlerův   ┆ Hike         ┆ … ┆ {null,null,n ┆ {"3:07","4:3 ┆ {137667325," ┆ 2026-01-24  │
│          ┆              ┆ Mlýn -       ┆              ┆   ┆ ull,null,nul ┆ 8","3:07",{" ┆ Bartosz      ┆ 23:39:07    │
│          ┆              ┆ Školní       ┆              ┆   ┆ l,0}         ┆ strava…      ┆ Fur","ava…   ┆ CET         │
│ 26819487 ┆ 3            ┆ rovinka      ┆ Run          ┆ … ┆ {null,null,n ┆ {"2:27","3:3 ┆ {17518530,"R ┆ 2026-01-24  │
│          ┆              ┆ kolem Sázavy ┆              ┆   ┆ ull,null,nul ┆ 9","2:27",{" ┆ adek Stastny ┆ 23:39:08    │
│          ┆              ┆ :Plynovod-…  ┆              ┆   ┆ l,0}         ┆ strava…      ┆ ","htt…      ┆ CET         │
│ 27598407 ┆ 3            ┆ Starý Kolín  ┆ Ride         ┆ … ┆ {null,null,n ┆ {"2:45","3:4 ┆ {166012651," ┆ 2026-01-24  │
│          ┆              ┆ - Svatá      ┆              ┆   ┆ ull,null,nul ┆ 3","2:45",{" ┆ Veronika     ┆ 23:39:08    │
│          ┆              ┆ Kateřina     ┆              ┆   ┆ l,0}         ┆ strava…      ┆ Sigmundov…   ┆ CET         │
│ 12868527 ┆ 3            ┆ Malchor -    ┆ Hike         ┆ … ┆ {null,null,n ┆ {"6:06","7:1 ┆ {73696645,"J ┆ 2026-01-24  │
│          ┆              ┆ Lysá Hora    ┆              ┆   ┆ ull,null,nul ┆ 6","6:06",{" ┆ ana Kuncarov ┆ 23:39:08    │
│          ┆              ┆              ┆              ┆   ┆ l,0}         ┆ strava…      ┆ a","ht…      ┆ CET         │
└──────────┴──────────────┴──────────────┴──────────────┴───┴──────────────┴──────────────┴──────────────┴─────────────┘

In [40]:
segment('Lužánky rovinka')

shape: (375, 3)
┌─────────────────────────────────┬──────────────┬──────────────────┐
│ date                            ┆ effort_count ┆ daily_difference │
│ ---                             ┆ ---          ┆ ---              │
│ str                             ┆ i64          ┆ i64              │
╞═════════════════════════════════╪══════════════╪══════════════════╡
│ 2024-12-25 00:00:00.000000+01:… ┆ 179488       ┆ 40               │
│ 2024-12-26 00:00:00.000000+01:… ┆ 179527       ┆ 39               │
│ 2024-12-27 00:00:00.000000+01:… ┆ 179560       ┆ 33               │
│ 2024-12-28 00:00:00.000000+01:… ┆ 179584       ┆ 24               │
│ 2024-12-29 00:00:00.000000+01:… ┆ 179626       ┆ 42               │
│ …                               ┆ …            ┆ …                │
│ 2026-01-20 00:00:00.000000+01:… ┆ 213673       ┆ 73               │
│ 2026-01-21 00:00:00.000000+01:… ┆ 213738       ┆ 65               │
│ 2026-01-22 00:00:00.000000+01:… ┆ 213813       ┆ 75               │
│ 2026-01-23 00:00:00.000000+01:… ┆ 213890       ┆ 77               │
│ 2026-01-24 00:00:00.000000+01:… ┆ 213915       ┆ 25               │
└─────────────────────────────────┴──────────────┴──────────────────┘

alt.Chart(...)

In [41]:
segment('time trial at Svratka')

shape: (367, 3)
┌─────────────────────────────────┬──────────────┬──────────────────┐
│ date                            ┆ effort_count ┆ daily_difference │
│ ---                             ┆ ---          ┆ ---              │
│ str                             ┆ i64          ┆ i64              │
╞═════════════════════════════════╪══════════════╪══════════════════╡
│ 2024-12-25 00:00:00.000000+01:… ┆ 141661       ┆ 24               │
│ 2024-12-26 00:00:00.000000+01:… ┆ 141680       ┆ 19               │
│ 2024-12-27 00:00:00.000000+01:… ┆ 141706       ┆ 26               │
│ 2024-12-28 00:00:00.000000+01:… ┆ 141721       ┆ 15               │
│ 2024-12-29 00:00:00.000000+01:… ┆ 141735       ┆ 14               │
│ …                               ┆ …            ┆ …                │
│ 2026-01-20 00:00:00.000000+01:… ┆ 161855       ┆ 12               │
│ 2026-01-21 00:00:00.000000+01:… ┆ 161863       ┆ 8                │
│ 2026-01-22 00:00:00.000000+01:… ┆ 161876       ┆ 13               │
│ 2026-01-23 00:00:00.000000+01:… ┆ 161877       ┆ 1                │
│ 2026-01-24 00:00:00.000000+01:… ┆ 161902       ┆ 25               │
└─────────────────────────────────┴──────────────┴──────────────────┘

alt.Chart(...)

In [42]:
segment('Od posledního tunelu do Bílovic')

shape: (366, 3)
┌─────────────────────────────────┬──────────────┬──────────────────┐
│ date                            ┆ effort_count ┆ daily_difference │
│ ---                             ┆ ---          ┆ ---              │
│ str                             ┆ i64          ┆ i64              │
╞═════════════════════════════════╪══════════════╪══════════════════╡
│ 2024-12-26 00:00:00.000000+01:… ┆ 124240       ┆ 14               │
│ 2024-12-27 00:00:00.000000+01:… ┆ 124314       ┆ 74               │
│ 2024-12-29 00:00:00.000000+01:… ┆ 124308       ┆ 18               │
│ 2024-12-30 00:00:00.000000+01:… ┆ 124325       ┆ 17               │
│ 2024-12-31 00:00:00.000000+01:… ┆ 124334       ┆ 9                │
│ …                               ┆ …            ┆ …                │
│ 2026-01-20 00:00:00.000000+01:… ┆ 146546       ┆ 2                │
│ 2026-01-21 00:00:00.000000+01:… ┆ 146546       ┆ 0                │
│ 2026-01-22 00:00:00.000000+01:… ┆ 146549       ┆ 3                │
│ 2026-01-23 00:00:00.000000+01:… ┆ 146549       ┆ 0                │
│ 2026-01-24 00:00:00.000000+01:… ┆ 146553       ┆ 4                │
└─────────────────────────────────┴──────────────┴──────────────────┘

alt.Chart(...)

In [43]:
segment('Lužánky - Plochá dráha')

shape: (350, 3)
┌─────────────────────────────────┬──────────────┬──────────────────┐
│ date                            ┆ effort_count ┆ daily_difference │
│ ---                             ┆ ---          ┆ ---              │
│ str                             ┆ i64          ┆ i64              │
╞═════════════════════════════════╪══════════════╪══════════════════╡
│ 2024-12-27 00:00:00.000000+01:… ┆ 32752        ┆ 2                │
│ 2024-12-29 00:00:00.000000+01:… ┆ 32746        ┆ 0                │
│ 2024-12-30 00:00:00.000000+01:… ┆ 32763        ┆ 17               │
│ 2024-12-31 00:00:00.000000+01:… ┆ 32763        ┆ 0                │
│ 2025-01-02 00:00:00.000000+01:… ┆ 32762        ┆ 5                │
│ …                               ┆ …            ┆ …                │
│ 2026-01-20 00:00:00.000000+01:… ┆ 39759        ┆ 16               │
│ 2026-01-21 00:00:00.000000+01:… ┆ 39765        ┆ 6                │
│ 2026-01-22 00:00:00.000000+01:… ┆ 39765        ┆ 0                │
│ 2026-01-23 00:00:00.000000+01:… ┆ 39773        ┆ 8                │
│ 2026-01-24 00:00:00.000000+01:… ┆ 39792        ┆ 19               │
└─────────────────────────────────┴──────────────┴──────────────────┘

alt.Chart(...)

In [44]:
segment('Risova studanka - od zavory')

shape: (363, 3)
┌─────────────────────────────────┬──────────────┬──────────────────┐
│ date                            ┆ effort_count ┆ daily_difference │
│ ---                             ┆ ---          ┆ ---              │
│ str                             ┆ i64          ┆ i64              │
╞═════════════════════════════════╪══════════════╪══════════════════╡
│ 2024-12-25 00:00:00.000000+01:… ┆ 41328        ┆ 2                │
│ 2024-12-26 00:00:00.000000+01:… ┆ 41336        ┆ 8                │
│ 2024-12-27 00:00:00.000000+01:… ┆ 41351        ┆ 15               │
│ 2024-12-28 00:00:00.000000+01:… ┆ 41360        ┆ 9                │
│ 2024-12-29 00:00:00.000000+01:… ┆ 41365        ┆ 5                │
│ …                               ┆ …            ┆ …                │
│ 2026-01-20 00:00:00.000000+01:… ┆ 47051        ┆ 0                │
│ 2026-01-21 00:00:00.000000+01:… ┆ 47052        ┆ 1                │
│ 2026-01-22 00:00:00.000000+01:… ┆ 47052        ┆ 0                │
│ 2026-01-23 00:00:00.000000+01:… ┆ 47052        ┆ 0                │
│ 2026-01-24 00:00:00.000000+01:… ┆ 47055        ┆ 3                │
└─────────────────────────────────┴──────────────┴──────────────────┘

alt.Chart(...)

In [45]:
segment('Brno Circuit')

shape: (373, 3)
┌─────────────────────────────────┬──────────────┬──────────────────┐
│ date                            ┆ effort_count ┆ daily_difference │
│ ---                             ┆ ---          ┆ ---              │
│ str                             ┆ i64          ┆ i64              │
╞═════════════════════════════════╪══════════════╪══════════════════╡
│ 2024-12-28 00:00:00.000000+01:… ┆ 880          ┆ 0                │
│ 2024-12-29 00:00:00.000000+01:… ┆ 881          ┆ 1                │
│ 2024-12-30 00:00:00.000000+01:… ┆ 881          ┆ 0                │
│ 2024-12-31 00:00:00.000000+01:… ┆ 881          ┆ 0                │
│ 2025-01-01 00:00:00.000000+01:… ┆ 881          ┆ 0                │
│ …                               ┆ …            ┆ …                │
│ 2026-01-20 00:00:00.000000+01:… ┆ 1067         ┆ 0                │
│ 2026-01-21 00:00:00.000000+01:… ┆ 1067         ┆ 0                │
│ 2026-01-22 00:00:00.000000+01:… ┆ 1067         ┆ 0                │
│ 2026-01-23 00:00:00.000000+01:… ┆ 1067         ┆ 0                │
│ 2026-01-24 00:00:00.000000+01:… ┆ 1067         ┆ 0                │
└─────────────────────────────────┴──────────────┴──────────────────┘

alt.Chart(...)

In [46]:
df.filter(pl.col('country').str.contains('Cze')).filter(pl.col('activity_type') == 'Run').group_by("name").agg(pl.col('effort_count').cast(int).max()).sort(by='effort_count',descending=True)

shape: (117, 2)
┌──────────────────────────────┬──────────────┐
│ name                         ┆ effort_count │
│ ---                          ┆ ---          │
│ str                          ┆ i64          │
╞══════════════════════════════╪══════════════╡
│ Stadion Na Děkance           ┆ 252221       │
│ Lužánky rovinka              ┆ 213915       │
│ Šlechtovka - finální rovinka ┆ 195825       │
│ VUT horní dráha 400m         ┆ 146304       │
│ Strahovská dráha             ┆ 118571       │
│ …                            ┆ …            │
│ Valy                         ┆ 394          │
│ Podél tratě do Úval          ┆ 387          │
│ Kraličák Skyrace - 2. kopec  ┆ 379          │
│ Autodrom Most                ┆ 281          │
│ ČSFR RIP                     ┆ 42           │
└──────────────────────────────┴──────────────┘

In [47]:
set(pl.Series(df.filter((pl.col('activity_type') == 'Run') & (pl.col('city') == 'Ostrava')).select("name")).to_list())

{'Hradní lávka => Sýkorův most',
 'Opavska down 1/2',
 'Park 1',
 'Železniční most => Jez Vítkovice'}

In [48]:
segment('Pražačka 320')

shape: (348, 3)
┌─────────────────────────────────┬──────────────┬──────────────────┐
│ date                            ┆ effort_count ┆ daily_difference │
│ ---                             ┆ ---          ┆ ---              │
│ str                             ┆ i64          ┆ i64              │
╞═════════════════════════════════╪══════════════╪══════════════════╡
│ 2024-12-27 00:00:00.000000+01:… ┆ 74840        ┆ 23               │
│ 2024-12-29 00:00:00.000000+01:… ┆ 74919        ┆ 101              │
│ 2024-12-30 00:00:00.000000+01:… ┆ 74938        ┆ 19               │
│ 2024-12-31 00:00:00.000000+01:… ┆ 74961        ┆ 23               │
│ 2025-01-01 00:00:00.000000+01:… ┆ 75036        ┆ 75               │
│ …                               ┆ …            ┆ …                │
│ 2026-01-20 00:00:00.000000+01:… ┆ 103319       ┆ 106              │
│ 2026-01-21 00:00:00.000000+01:… ┆ 103437       ┆ 118              │
│ 2026-01-22 00:00:00.000000+01:… ┆ 103588       ┆ 151              │
│ 2026-01-23 00:00:00.000000+01:… ┆ 103669       ┆ 81               │
│ 2026-01-24 00:00:00.000000+01:… ┆ 103714       ┆ 45               │
└─────────────────────────────────┴──────────────┴──────────────────┘

alt.Chart(...)

In [49]:
segment("Pec - Sněžka (přes Obřák)")

shape: (366, 3)
┌─────────────────────────────────┬──────────────┬──────────────────┐
│ date                            ┆ effort_count ┆ daily_difference │
│ ---                             ┆ ---          ┆ ---              │
│ str                             ┆ i64          ┆ i64              │
╞═════════════════════════════════╪══════════════╪══════════════════╡
│ 2024-12-26 00:00:00.000000+01:… ┆ 3487         ┆ 1                │
│ 2024-12-27 00:00:00.000000+01:… ┆ 3491         ┆ 4                │
│ 2024-12-28 00:00:00.000000+01:… ┆ 3493         ┆ 2                │
│ 2024-12-29 00:00:00.000000+01:… ┆ 3501         ┆ 8                │
│ 2024-12-30 00:00:00.000000+01:… ┆ 3503         ┆ 2                │
│ …                               ┆ …            ┆ …                │
│ 2026-01-20 00:00:00.000000+01:… ┆ 4740         ┆ 0                │
│ 2026-01-21 00:00:00.000000+01:… ┆ 4740         ┆ 0                │
│ 2026-01-22 00:00:00.000000+01:… ┆ 4744         ┆ 4                │
│ 2026-01-23 00:00:00.000000+01:… ┆ 4744         ┆ 0                │
│ 2026-01-24 00:00:00.000000+01:… ┆ 4757         ┆ 13               │
└─────────────────────────────────┴──────────────┴──────────────────┘

alt.Chart(...)

In [50]:
segment('Park 1')

shape: (373, 3)
┌─────────────────────────────────┬──────────────┬──────────────────┐
│ date                            ┆ effort_count ┆ daily_difference │
│ ---                             ┆ ---          ┆ ---              │
│ str                             ┆ i64          ┆ i64              │
╞═════════════════════════════════╪══════════════╪══════════════════╡
│ 2024-12-25 00:00:00.000000+01:… ┆ 13566        ┆ 6                │
│ 2024-12-26 00:00:00.000000+01:… ┆ 13571        ┆ 5                │
│ 2024-12-27 00:00:00.000000+01:… ┆ 13571        ┆ 0                │
│ 2024-12-28 00:00:00.000000+01:… ┆ 13573        ┆ 2                │
│ 2024-12-29 00:00:00.000000+01:… ┆ 13576        ┆ 3                │
│ …                               ┆ …            ┆ …                │
│ 2026-01-20 00:00:00.000000+01:… ┆ 16616        ┆ 2                │
│ 2026-01-21 00:00:00.000000+01:… ┆ 16618        ┆ 2                │
│ 2026-01-22 00:00:00.000000+01:… ┆ 16622        ┆ 4                │
│ 2026-01-23 00:00:00.000000+01:… ┆ 16625        ┆ 3                │
│ 2026-01-24 00:00:00.000000+01:… ┆ 16627        ┆ 2                │
└─────────────────────────────────┴──────────────┴──────────────────┘

alt.Chart(...)

In [51]:
segment("Tuhnická lávka -Chebský most")

shape: (378, 3)
┌─────────────────────────────────┬──────────────┬──────────────────┐
│ date                            ┆ effort_count ┆ daily_difference │
│ ---                             ┆ ---          ┆ ---              │
│ str                             ┆ i64          ┆ i64              │
╞═════════════════════════════════╪══════════════╪══════════════════╡
│ 2024-12-25 00:00:00.000000+01:… ┆ 3902         ┆ 7                │
│ 2024-12-26 00:00:00.000000+01:… ┆ 3902         ┆ 0                │
│ 2024-12-27 00:00:00.000000+01:… ┆ 3907         ┆ 5                │
│ 2024-12-28 00:00:00.000000+01:… ┆ 3911         ┆ 4                │
│ 2024-12-29 00:00:00.000000+01:… ┆ 3913         ┆ 2                │
│ …                               ┆ …            ┆ …                │
│ 2026-01-20 00:00:00.000000+01:… ┆ 5271         ┆ 2                │
│ 2026-01-21 00:00:00.000000+01:… ┆ 5273         ┆ 2                │
│ 2026-01-22 00:00:00.000000+01:… ┆ 5274         ┆ 1                │
│ 2026-01-23 00:00:00.000000+01:… ┆ 5274         ┆ 0                │
│ 2026-01-24 00:00:00.000000+01:… ┆ 5274         ┆ 0                │
└─────────────────────────────────┴──────────────┴──────────────────┘

alt.Chart(...)

In [52]:
segment("START")

shape: (186, 3)
┌─────────────────────────────────┬──────────────┬──────────────────┐
│ date                            ┆ effort_count ┆ daily_difference │
│ ---                             ┆ ---          ┆ ---              │
│ str                             ┆ i64          ┆ i64              │
╞═════════════════════════════════╪══════════════╪══════════════════╡
│ 2025-06-19 00:00:00.000000+02:… ┆ 8706         ┆ 1                │
│ 2025-06-20 00:00:00.000000+02:… ┆ 8711         ┆ 5                │
│ 2025-06-21 00:00:00.000000+02:… ┆ 8711         ┆ 0                │
│ 2025-06-22 00:00:00.000000+02:… ┆ 8712         ┆ 1                │
│ 2025-06-23 00:00:00.000000+02:… ┆ 8716         ┆ 4                │
│ …                               ┆ …            ┆ …                │
│ 2026-01-20 00:00:00.000000+01:… ┆ 9017         ┆ 1                │
│ 2026-01-21 00:00:00.000000+01:… ┆ 9017         ┆ 0                │
│ 2026-01-22 00:00:00.000000+01:… ┆ 9018         ┆ 1                │
│ 2026-01-23 00:00:00.000000+01:… ┆ 9018         ┆ 0                │
│ 2026-01-24 00:00:00.000000+01:… ┆ 9018         ┆ 0                │
└─────────────────────────────────┴──────────────┴──────────────────┘

alt.Chart(...)

In [53]:
segment('Hradní lávka => Sýkorův most')

shape: (376, 3)
┌─────────────────────────────────┬──────────────┬──────────────────┐
│ date                            ┆ effort_count ┆ daily_difference │
│ ---                             ┆ ---          ┆ ---              │
│ str                             ┆ i64          ┆ i64              │
╞═════════════════════════════════╪══════════════╪══════════════════╡
│ 2024-12-26 00:00:00.000000+01:… ┆ 13983        ┆ 6                │
│ 2024-12-27 00:00:00.000000+01:… ┆ 13985        ┆ 2                │
│ 2024-12-28 00:00:00.000000+01:… ┆ 13987        ┆ 2                │
│ 2024-12-29 00:00:00.000000+01:… ┆ 13992        ┆ 5                │
│ 2024-12-30 00:00:00.000000+01:… ┆ 13998        ┆ 6                │
│ …                               ┆ …            ┆ …                │
│ 2026-01-20 00:00:00.000000+01:… ┆ 17644        ┆ 13               │
│ 2026-01-21 00:00:00.000000+01:… ┆ 17652        ┆ 8                │
│ 2026-01-22 00:00:00.000000+01:… ┆ 17661        ┆ 9                │
│ 2026-01-23 00:00:00.000000+01:… ┆ 17665        ┆ 4                │
│ 2026-01-24 00:00:00.000000+01:… ┆ 17667        ┆ 2                │
└─────────────────────────────────┴──────────────┴──────────────────┘

alt.Chart(...)

In [54]:
df.group_by_dynamic("date", by="name", every="1d").agg(pl.col("effort_count").max())

C:\Users\micha\AppData\Local\Temp\ipykernel_7020\3197359101.py:1: DeprecationWarning: the argument `by` for `DataFrame.group_by_dynamic` is deprecated. It was renamed to `group_by` in version 0.20.14.
  df.group_by_dynamic("date", by="name", every="1d").agg(pl.col("effort_count").max())

shape: (109_107, 3)
┌─────────────────────────────────┬─────────────────────────┬──────────────┐
│ name                            ┆ date                    ┆ effort_count │
│ ---                             ┆ ---                     ┆ ---          │
│ str                             ┆ datetime[μs, CET]       ┆ i64          │
╞═════════════════════════════════╪═════════════════════════╪══════════════╡
│ 400m                            ┆ 2024-12-26 00:00:00 CET ┆ 33521        │
│ 400m                            ┆ 2024-12-27 00:00:00 CET ┆ 33521        │
│ 400m                            ┆ 2024-12-28 00:00:00 CET ┆ 33518        │
│ 400m                            ┆ 2024-12-29 00:00:00 CET ┆ 33518        │
│ 400m                            ┆ 2024-12-30 00:00:00 CET ┆ 33518        │
│ …                               ┆ …                       ┆ …            │
│ Szlak czerwony, Schronisko Nad… ┆ 2026-01-20 00:00:00 CET ┆ 12321        │
│ Szlak czerwony, Schronisko Nad… ┆ 2026-01-21 00:00:00 CET ┆ 12321        │
│ Szlak czerwony, Schronisko Nad… ┆ 2026-01-22 00:00:00 CET ┆ 12322        │
│ Szlak czerwony, Schronisko Nad… ┆ 2026-01-23 00:00:00 CET ┆ 12322        │
│ Szlak czerwony, Schronisko Nad… ┆ 2026-01-24 00:00:00 CET ┆ 12322        │
└─────────────────────────────────┴─────────────────────────┴──────────────┘