In [87]:
import os
import polars as pl
import altair as alt

In [88]:
pl.Config(tbl_rows=100)
pl.Config(fmt_str_lengths=150)
alt.data_transformers.disable_max_rows()

DataTransformerRegistry.enable('default')

In [89]:
df = pl.read_parquet(
    "data/segments.parquet"
).sort(
    ["id", "date"]
).with_columns(
    days_diff = pl.col("date").diff().dt.total_days().over("id"),
    effort_diff = pl.col("effort_count").diff().over("id")
).with_columns(
    avg_daily_efforts = pl.col("effort_diff") / pl.col("days_diff")
).with_columns(
    pl.when(pl.col("city").str.contains("Praha") | pl.col("city").str.contains("Prague")).then(pl.lit('Praha')).when(pl.col('city').str.contains('Brno')).then(pl.lit('Brno')).otherwise(pl.col('city')).alias('city'),
    pl.when(pl.col("effort_diff") < 0).then(pl.lit(0)).otherwise(pl.col("effort_diff")).alias("effort_diff")
).with_columns(
    pl.col('date').dt.ordinal_day().alias('day'),
    pl.col('date').dt.week().alias('week'),
    pl.col('date').dt.year().alias('year')
)

## Rozsah dat

In [91]:
print(df.select(pl.col("date").min()).item())
print(df.select(pl.col("date").max()).item())

2024-12-24 23:05:01+01:00
2026-03-08 23:39:05+01:00

In [92]:
df.sample(1)

shape: (1, 23)
┌──────────┬───────────────────────────────┬───────────────┬──────────┬───┬───────────────────┬─────┬──────┬──────┐
│ id       ┆ name                          ┆ activity_type ┆ distance ┆ … ┆ avg_daily_efforts ┆ day ┆ week ┆ year │
│ ---      ┆ ---                           ┆ ---           ┆ ---      ┆   ┆ ---               ┆ --- ┆ ---  ┆ ---  │
│ i64      ┆ str                           ┆ str           ┆ f64      ┆   ┆ f64               ┆ i16 ┆ i8   ┆ i32  │
╞══════════╪═══════════════════════════════╪═══════════════╪══════════╪═══╪═══════════════════╪═════╪══════╪══════╡
│ 11655930 ┆ Mezi zábranama (proti proudu) ┆ Run           ┆ 1067.3   ┆ … ┆ 0.0               ┆ 1   ┆ 1    ┆ 2025 │
└──────────┴───────────────────────────────┴───────────────┴──────────┴───┴───────────────────┴─────┴──────┴──────┘

## Výběr segmentů ke sledování

In [94]:
zebricek = df.filter(
    pl.col("country") == "Czechia"
).group_by(
    ["name","city","activity_type","start_to_finish_distance"]
).agg(
    pl.col("effort_diff").quantile(0.8)
).sort(
    by="effort_diff", descending=True
)

zebricek.head(100)

shape: (100, 5)
┌────────────────────────────────────────────┬──────────────────────────────┬───────────────┬──────────────────────────┬─────────────┐
│ name                                       ┆ city                         ┆ activity_type ┆ start_to_finish_distance ┆ effort_diff │
│ ---                                        ┆ ---                          ┆ ---           ┆ ---                      ┆ ---         │
│ str                                        ┆ str                          ┆ str           ┆ f64                      ┆ f64         │
╞════════════════════════════════════════════╪══════════════════════════════╪═══════════════╪══════════════════════════╪═════════════╡
│ Die Eine Runde                             ┆ Brno                         ┆ Ride          ┆ 0.002446                 ┆ 414.0       │
│ VUT horní dráha 400m                       ┆ Brno                         ┆ Run           ┆ 0.011266                 ┆ 219.0       │
│ Opičí Časovka, Podolská vodárna - Dvorce   ┆ Praha                        ┆ Ride          ┆ 1.379737                 ┆ 210.0       │
│ Zweite hup u ZOO                           ┆ Praha                        ┆ Ride          ┆ 0.308372                 ┆ 188.0       │
│ Stadion Na Děkance                         ┆ Praha                        ┆ Run           ┆ 0.006087                 ┆ 187.0       │
│ Zbraslav - Komořany                        ┆ Zbraslav                     ┆ Ride          ┆ 2.258969                 ┆ 151.0       │
│ Pražačka 320                               ┆ Praha                        ┆ Run           ┆ 0.000925                 ┆ 140.0       │
│ Šlechtovka - finální rovinka               ┆ Praha                        ┆ Run           ┆ 0.222849                 ┆ 139.0       │
│ Lužánky rovinka                            ┆ Brno                         ┆ Run           ┆ 0.260571                 ┆ 124.0       │
│ Od posledního tunelu do Bílovic            ┆ Bílovice nad Svitavou        ┆ Ride          ┆ 0.647058                 ┆ 105.0       │
│ Třebešín-dráha K                           ┆ Praha                        ┆ Ride          ┆ 0.008769                 ┆ 96.0        │
│ time trial at Svratka                      ┆ Brno                         ┆ Ride          ┆ 1.300465                 ┆ 92.0        │
│ TJ Sokol okruh                             ┆ Praha                        ┆ Run           ┆ 0.009342                 ┆ 91.0        │
│ 400m-Liberec                               ┆ Liberec                      ┆ Run           ┆ 0.014369                 ┆ 74.0        │
│ Rokytka od myčky                           ┆ Praha                        ┆ Ride          ┆ 1.812742                 ┆ 66.0        │
│ Strahovská dráha                           ┆ Praha                        ┆ Run           ┆ 0.001716                 ┆ 66.0        │
│ Štvanická lávka (do Karlína)               ┆ Praha                        ┆ Run           ┆ 0.273856                 ┆ 64.0        │
│ Vítkov up sprint                           ┆ Praha                        ┆ Run           ┆ 0.117786                 ┆ 53.0        │
│ Kolo na stadionu v Třebíči                 ┆ Třebíč                       ┆ Run           ┆ 0.008266                 ┆ 52.0        │
│ Stezka do Zlina                            ┆ Zlin                         ┆ Ride          ┆ 1.265858                 ┆ 51.0        │
│ tenis 1K                                   ┆ Brno                         ┆ Run           ┆ 0.951894                 ┆ 45.0        │
│ Smetanovy reverse                          ┆ Olomouc                      ┆ Run           ┆ 0.631364                 ┆ 41.0        │
│ Sptint pod Býčí skálou                     ┆ Olomučany                    ┆ Ride          ┆ 0.711671                 ┆ 36.0        │
│ Most Legií (směr Kampa)                    ┆ Praha                        ┆ Run           ┆ 0.326026                 ┆ 34.0        │
│ Tyršák čtyřstofka                          ┆ Šumperk                      ┆ Run           ┆ 0.002828                 ┆ 34.0        │
│ 400 m - atletický okruh - Lokomotiva       ┆ Olomouc                      ┆ Run           ┆ 0.003459                 ┆ 33.0        │
│ Hvězda flat                                ┆ Praha                        ┆ Run           ┆ 0.995211                 ┆ 33.0        │
│ 400m                                       ┆ Pardubice V                  ┆ Run           ┆ 0.003456                 ┆ 32.0        │
│ Židlochovice -> Olympia                    ┆ Židlochovice                 ┆ Ride          ┆ 9.643392                 ┆ 32.0        │
│ Ovál ZŠ Štefánikova                        ┆ Hradec Králové               ┆ Run           ┆ 0.004506                 ┆ 31.0        │
│ Karlův most ONLY                           ┆ Praha                        ┆ Run           ┆ 0.283976                 ┆ 31.0        │
│ Stodůlecký - Nepomucký rybník              ┆ Praha                        ┆ Run           ┆ 0.529274                 ┆ 30.0        │
│ Kampa South                                ┆ Praha                        ┆ Run           ┆ 0.36887                  ┆ 29.0        │
│ Lužánky - Plochá dráha                     ┆ Brno                         ┆ Run           ┆ 0.001678                 ┆ 29.0        │
│ Srbsko - Hlásná Třebáň                     ┆ Srbsko                       ┆ Ride          ┆ 4.557374                 ┆ 29.0        │
│ Muglinovská→Hradní lávka (po pravém břehu) ┆ Ostrava                      ┆ Ride          ┆ 2.660781                 ┆ 28.0        │
│ Revnicak Eve                               ┆ Řevnice                      ┆ Ride          ┆ 3.429182                 ┆ 28.0        │
│ Junglepark                                 ┆ Brno                         ┆ Run           ┆ 0.298243                 ┆ 27.0        │
│ Risova studanka - od zavory                ┆ Brno                         ┆ Ride          ┆ 2.507177                 ┆ 26.0        │
│ 400 m (track num. 2)                       ┆ Benešov                      ┆ Run           ┆ 0.015573                 ┆ 25.0        │
│ Juliska 400 m                              ┆ Praha                        ┆ Run           ┆ 0.00286                  ┆ 25.0        │
│ Mestsky stadion Trutnov                    ┆ Trutnov                      ┆ Run           ┆ 0.001844                 ┆ 25.0        │
│ Novomlýnská 5: Věstonice-Strachotín        ┆ Dolní Věstonice              ┆ Ride          ┆ 1.215091                 ┆ 24.0        │
│ Tatran Třemošná                            ┆ Třemošná                     ┆ Run           ┆ 0.002124                 ┆ 24.0        │
│ Od dubu ke Gizele                          ┆ Praha                        ┆ Run           ┆ 0.370526                 ┆ 23.0        │
│ Stezka nábřeží                             ┆ Zlín                         ┆ Run           ┆ 0.577385                 ┆ 22.0        │
│ Malchor - Lysá Hora                        ┆ Krásná                       ┆ Hike          ┆ 0.568227                 ┆ 22.0        │
│ 400m - Sportovní areál Na Stoupách         ┆ Jihlava                      ┆ Run           ┆ 0.007687                 ┆ 22.0        │
│ Rullerovo nábřeží                          ┆ Brno                         ┆ Run           ┆ 0.940342                 ┆ 20.0        │
│ svadov—valtirov                            ┆ Ústí nad Labem-Neštěmice     ┆ Ride          ┆ 2.730017                 ┆ 20.0        │
│ Ještěd Finale konec před kostkami.         ┆ Světlá pod Ještědem          ┆ Ride          ┆ 0.191607                 ┆ 19.0        │
│ Jiráskovo nábřeží k Husovce                ┆ České Budějovice             ┆ Ride          ┆ 1.009863                 ┆ 19.0        │
│ TJ Znojmo Lap                              ┆ Znojmo                       ┆ Run           ┆ 0.003705                 ┆ 19.0        │
│ Total brikule 🚀                           ┆ Staré Město                  ┆ Ride          ┆ 0.551812                 ┆ 19.0        │
│ Stadion Čelákovice 400m (II.)              ┆ Čelákovice                   ┆ Run           ┆ 0.006626                 ┆ 19.0        │
│ Maslovice - Kralupy                        ┆ Máslovice                    ┆ Ride          ┆ 4.687004                 ┆ 18.0        │
│ Nová cyklostezka do Bosche  2              ┆ Jihlava                      ┆ Ride          ┆ 2.439248                 ┆ 18.0        │
│ Cyklostezka sprint směr Děčín              ┆ Hřensko                      ┆ Ride          ┆ 1.000775                 ┆ 18.0        │
│ stezka                                     ┆ České Budějovice             ┆ Run           ┆ 0.891633                 ┆ 17.0        │
│ Sprintík křižovatka/skalní mlýn            ┆ Blansko                      ┆ Ride          ┆ 2.099472                 ┆ 17.0        │
│ Adamaov climb                              ┆ Adamov                       ┆ Ride          ┆ 1.192579                 ┆ 17.0        │
│ Szpic Jested  last 3 km ( od rozc na Dub)  ┆ Liberec                      ┆ Ride          ┆ 1.348759                 ┆ 16.0        │
│ Benedikt - Parkoviště                      ┆ Most                         ┆ Run           ┆ 0.001136                 ┆ 16.0        │
│ Trinec-Tesin                               ┆ Třinec                       ┆ Ride          ┆ 4.360789                 ┆ 16.0        │
│ Transformator k Butorance (u studanky)     ┆ Ostravice                    ┆ Hike          ┆ 1.223649                 ┆ 15.0        │
│ Mutěnka - z Kyjova po odbočku na hraběcí   ┆ Kyjov                        ┆ Ride          ┆ 3.458919                 ┆ 15.0        │
│ Lysá hora - 5 km                           ┆ Staré Hamry                  ┆ Ride          ┆ 3.229545                 ┆ 15.0        │
│ Klinovec Top                               ┆ Jáchymov                     ┆ Ride          ┆ 0.774628                 ┆ 14.0        │
│ Hradní lávka => Sýkorův most               ┆ Ostrava                      ┆ Run           ┆ 0.958195                 ┆ 14.0        │
│ Údolí Svatý Jan                            ┆ Beroun                       ┆ Ride          ┆ 3.618147                 ┆ 14.0        │
│ Sedýlko - Praděd climb                     ┆ Loučná Nad Desnou            ┆ Ride          ┆ 0.660889                 ┆ 14.0        │
│ Decin - Bad Schandau Abzweig Radwg         ┆ Děčín                        ┆ Ride          ┆ 14.292023                ┆ 14.0        │
│ Tuhnice most-Drahovice most,stezka         ┆ Karlovy Vary                 ┆ Ride          ┆ 2.155936                 ┆ 13.0        │
│ Papezov - Prazmo                           ┆ Krásná                       ┆ Ride          ┆ 6.992833                 ┆ 13.0        │
│ Podle Radbuzy                              ┆ Pilsen                       ┆ Ride          ┆ 1.806575                 ┆ 13.0        │
│ 400m-Jičín                                 ┆ Jičín                        ┆ Run           ┆ 0.001068                 ┆ 13.0        │
│ Eurovie - nadjezd Rosice                   ┆ Pardubice II                 ┆ Ride          ┆ 1.294441                 ┆ 13.0        │
│ mezi mosty                                 ┆ Pardubice                    ┆ Run           ┆ 0.894894                 ┆ 13.0        │
│ Hradiště - čtyřstovka                      ┆ Uherské Hradiště             ┆ Run           ┆ 0.006289                 ┆ 13.0        │
│ Sedmička, Lipno {                          ┆ Přední Výtoň                 ┆ Ride          ┆ 3.651891                 ┆ 13.0        │
│ Kynšperský ATAK                            ┆ Kynšperk nad Ohří            ┆ Ride          ┆ 0.504788                 ┆ 12.0        │
│ Cyklostezka Náchod -> Velké Poříčí         ┆ Náchod                       ┆ Ride          ┆ 3.006125                 ┆ 12.0        │
│ Interval                                   ┆ Olomouc                      ┆ Run           ┆ 0.822266                 ┆ 11.0        │
│ MH - Klaster                               ┆ Klášter Hradiště nad Jizerou ┆ Ride          ┆ 1.227082                 ┆ 11.0        │
│ Rovinka Beranov                            ┆ Malý Beranov                 ┆ Ride          ┆ 0.841521                 ┆ 11.0        │
│ Výstup na Klínovec                         ┆ null                         ┆ Ride          ┆ 0.808138                 ┆ 11.0        │
│ Šárka Valley (short)                       ┆ Praha                        ┆ Run           ┆ 0.82043                  ┆ 11.0        │
│ Park 1                                     ┆ Ostrava                      ┆ Run           ┆ 0.699398                 ┆ 10.0        │
│ Z Lednice po silnici k odbocce na Janohrad ┆ Lednice                      ┆ Ride          ┆ 1.255294                 ┆ 10.0        │
│ Tři prameny - Pravčická brána              ┆ Hřensko                      ┆ Hike          ┆ 0.71009                  ┆ 10.0        │
│ LS - Park Boost                            ┆ Bruntál                      ┆ Run           ┆ 0.356353                 ┆ 10.0        │
│ Klobouky Viadukt                           ┆ Valašské Klobouky            ┆ Ride          ┆ 0.98949                  ┆ 10.0        │
│ Chrudim climb                              ┆ Chrudim                      ┆ Ride          ┆ 0.838854                 ┆ 10.0        │
│ most - Loket                               ┆ Staré Sedlo                  ┆ Ride          ┆ 2.137918                 ┆ 9.0         │
│ Do sedla Klínovce po silnici               ┆ Loučná pod Klínovcem         ┆ Ride          ┆ 2.318996                 ┆ 9.0         │
│ Vlevo dole jezero Most                     ┆ Most                         ┆ Ride          ┆ 3.698485                 ┆ 9.0         │
│ Dom Śląski Up Hill                         ┆ Pec pod Sněžkou              ┆ Hike          ┆ 1.811384                 ┆ 9.0         │
│ Daskabát flat                              ┆ Velký Újezd                  ┆ Ride          ┆ 1.853476                 ┆ 9.0         │
│ Šantovka - Kojeňák                         ┆ Olomouc                      ┆ Ride          ┆ 0.985026                 ┆ 8.0         │
│ Bunč climb                                 ┆ Kostelany                    ┆ Ride          ┆ 1.459622                 ┆ 8.0         │
└────────────────────────────────────────────┴──────────────────────────────┴───────────────┴──────────────────────────┴─────────────┘

In [95]:
celorepublika = zebricek.filter(
    (pl.col('activity_type') == 'Run') & (pl.col('start_to_finish_distance') > 0.5)
).unique(
    subset='city',keep='first'
).sort(
    by='effort_diff',descending=True
).head(
    20
).select(
    pl.col('name')
).to_series(
).to_list()

celorepublika

['tenis 1K',
 'Smetanovy reverse',
 'Hvězda flat',
 'Stezka nábřeží',
 'stezka',
 'Hradní lávka => Sýkorův most',
 'mezi mosty',
 'Panelovka-Tichá 800m',
 'Ku řopíku',
 'Od Sanusu ke gymplu',
 'Lípy (směrem do Jičína)',
 'od hráze až na konec přehrady - silnice',
 'U Jordánu do kopce',
 'Tuhnická lávka -Chebský most',
 'Nábřeží',
 'po cyklostezce',
 'Ciclo Via BNL -> K',
 'Dlouhá míle',
 'Kuželna - Splav 800m',
 'BK-nabrezi']

In [96]:
import yaml

In [97]:
with open("data_raw/behani_top_20.yaml", "w", encoding="utf-8") as f:
    yaml.dump(celorepublika, f, allow_unicode=True, default_flow_style=False)

In [98]:
celorepublika_kolo = zebricek.filter(
    (pl.col('activity_type') == 'Ride') & (pl.col('start_to_finish_distance') > 1)
).unique(
    subset='city',keep='first'
).sort(
    by='effort_diff',descending=True
).head(
    20
).select(
    pl.col('name')
).to_series(
).to_list()

celorepublika_kolo

['Opičí Časovka, Podolská vodárna - Dvorce',
 'Zbraslav - Komořany',
 'time trial at Svratka',
 'Stezka do Zlina',
 'Židlochovice -> Olympia',
 'Srbsko - Hlásná Třebáň',
 'Revnicak Eve',
 'Muglinovská→Hradní lávka (po pravém břehu)',
 'Novomlýnská 5: Věstonice-Strachotín',
 'svadov—valtirov',
 'Jiráskovo nábřeží k Husovce',
 'Cyklostezka sprint směr Děčín',
 'Nová cyklostezka do Bosche  2',
 'Maslovice - Kralupy',
 'Sprintík křižovatka/skalní mlýn',
 'Adamaov climb',
 'Trinec-Tesin',
 'Szpic Jested  last 3 km ( od rozc na Dub)',
 'Lysá hora - 5 km',
 'Mutěnka - z Kyjova po odbočku na hraběcí']

In [99]:
with open("data_raw/kolo_top_20.yaml", "w", encoding="utf-8") as f:
    yaml.dump(celorepublika_kolo, f, allow_unicode=True, default_flow_style=False)

In [100]:
df.filter(
    pl.col('name').is_in(celorepublika)
)

shape: (8_332, 23)
┌──────────┬───────────────────┬───────────────┬──────────┬───┬───────────────────┬─────┬──────┬──────┐
│ id       ┆ name              ┆ activity_type ┆ distance ┆ … ┆ avg_daily_efforts ┆ day ┆ week ┆ year │
│ ---      ┆ ---               ┆ ---           ┆ ---      ┆   ┆ ---               ┆ --- ┆ ---  ┆ ---  │
│ i64      ┆ str               ┆ str           ┆ f64      ┆   ┆ f64               ┆ i16 ┆ i8   ┆ i32  │
╞══════════╪═══════════════════╪═══════════════╪══════════╪═══╪═══════════════════╪═════╪══════╪══════╡
│ 2462668  ┆ Hvězda flat       ┆ Run           ┆ 1001.15  ┆ … ┆ null              ┆ 359 ┆ 52   ┆ 2024 │
│ 2462668  ┆ Hvězda flat       ┆ Run           ┆ 1001.15  ┆ … ┆ 9.0               ┆ 360 ┆ 52   ┆ 2024 │
│ 2462668  ┆ Hvězda flat       ┆ Run           ┆ 1001.15  ┆ … ┆ inf               ┆ 361 ┆ 52   ┆ 2024 │
│ 2462668  ┆ Hvězda flat       ┆ Run           ┆ 1001.15  ┆ … ┆ 11.0              ┆ 362 ┆ 52   ┆ 2024 │
│ 2462668  ┆ Hvězda flat       ┆ Run           ┆ 1001.15  ┆ … ┆ 19.0              ┆ 363 ┆ 52   ┆ 2024 │
│ 2462668  ┆ Hvězda flat       ┆ Run           ┆ 1001.15  ┆ … ┆ 16.0              ┆ 364 ┆ 52   ┆ 2024 │
│ 2462668  ┆ Hvězda flat       ┆ Run           ┆ 1001.15  ┆ … ┆ inf               ┆ 365 ┆ 1    ┆ 2024 │
│ 2462668  ┆ Hvězda flat       ┆ Run           ┆ 1001.15  ┆ … ┆ inf               ┆ 366 ┆ 1    ┆ 2024 │
│ 2462668  ┆ Hvězda flat       ┆ Run           ┆ 1001.15  ┆ … ┆ 39.0              ┆ 1   ┆ 1    ┆ 2025 │
│ 2462668  ┆ Hvězda flat       ┆ Run           ┆ 1001.15  ┆ … ┆ inf               ┆ 2   ┆ 1    ┆ 2025 │
│ 2462668  ┆ Hvězda flat       ┆ Run           ┆ 1001.15  ┆ … ┆ 12.0              ┆ 3   ┆ 1    ┆ 2025 │
│ 2462668  ┆ Hvězda flat       ┆ Run           ┆ 1001.15  ┆ … ┆ inf               ┆ 4   ┆ 1    ┆ 2025 │
│ 2462668  ┆ Hvězda flat       ┆ Run           ┆ 1001.15  ┆ … ┆ 24.0              ┆ 5   ┆ 1    ┆ 2025 │
│ 2462668  ┆ Hvězda flat       ┆ Run           ┆ 1001.15  ┆ … ┆ inf               ┆ 6   ┆ 2    ┆ 2025 │
│ 2462668  ┆ Hvězda flat       ┆ Run           ┆ 1001.15  ┆ … ┆ inf               ┆ 7   ┆ 2    ┆ 2025 │
│ 2462668  ┆ Hvězda flat       ┆ Run           ┆ 1001.15  ┆ … ┆ inf               ┆ 8   ┆ 2    ┆ 2025 │
│ 2462668  ┆ Hvězda flat       ┆ Run           ┆ 1001.15  ┆ … ┆ 11.0              ┆ 9   ┆ 2    ┆ 2025 │
│ 2462668  ┆ Hvězda flat       ┆ Run           ┆ 1001.15  ┆ … ┆ 8.0               ┆ 10  ┆ 2    ┆ 2025 │
│ 2462668  ┆ Hvězda flat       ┆ Run           ┆ 1001.15  ┆ … ┆ 16.0              ┆ 11  ┆ 2    ┆ 2025 │
│ 2462668  ┆ Hvězda flat       ┆ Run           ┆ 1001.15  ┆ … ┆ 25.0              ┆ 12  ┆ 2    ┆ 2025 │
│ 2462668  ┆ Hvězda flat       ┆ Run           ┆ 1001.15  ┆ … ┆ inf               ┆ 13  ┆ 3    ┆ 2025 │
│ 2462668  ┆ Hvězda flat       ┆ Run           ┆ 1001.15  ┆ … ┆ 8.0               ┆ 14  ┆ 3    ┆ 2025 │
│ 2462668  ┆ Hvězda flat       ┆ Run           ┆ 1001.15  ┆ … ┆ inf               ┆ 15  ┆ 3    ┆ 2025 │
│ 2462668  ┆ Hvězda flat       ┆ Run           ┆ 1001.15  ┆ … ┆ 23.0              ┆ 16  ┆ 3    ┆ 2025 │
│ 2462668  ┆ Hvězda flat       ┆ Run           ┆ 1001.15  ┆ … ┆ inf               ┆ 17  ┆ 3    ┆ 2025 │
│ 2462668  ┆ Hvězda flat       ┆ Run           ┆ 1001.15  ┆ … ┆ inf               ┆ 18  ┆ 3    ┆ 2025 │
│ 2462668  ┆ Hvězda flat       ┆ Run           ┆ 1001.15  ┆ … ┆ inf               ┆ 19  ┆ 3    ┆ 2025 │
│ 2462668  ┆ Hvězda flat       ┆ Run           ┆ 1001.15  ┆ … ┆ 7.0               ┆ 20  ┆ 4    ┆ 2025 │
│ 2462668  ┆ Hvězda flat       ┆ Run           ┆ 1001.15  ┆ … ┆ inf               ┆ 21  ┆ 4    ┆ 2025 │
│ 2462668  ┆ Hvězda flat       ┆ Run           ┆ 1001.15  ┆ … ┆ 4.0               ┆ 22  ┆ 4    ┆ 2025 │
│ 2462668  ┆ Hvězda flat       ┆ Run           ┆ 1001.15  ┆ … ┆ 74.0              ┆ 23  ┆ 4    ┆ 2025 │
│ 2462668  ┆ Hvězda flat       ┆ Run           ┆ 1001.15  ┆ … ┆ inf               ┆ 24  ┆ 4    ┆ 2025 │
│ 2462668  ┆ Hvězda flat       ┆ Run           ┆ 1001.15  ┆ … ┆ 18.0              ┆ 25  ┆ 4    ┆ 2025 │
│ 2462668  ┆ Hvězda flat       ┆ Run           ┆ 1001.15  ┆ … ┆ 22.0              ┆ 26  ┆ 4    ┆ 2025 │
│ 2462668  ┆ Hvězda flat       ┆ Run           ┆ 1001.15  ┆ … ┆ inf               ┆ 27  ┆ 5    ┆ 2025 │
│ 2462668  ┆ Hvězda flat       ┆ Run           ┆ 1001.15  ┆ … ┆ 14.0              ┆ 28  ┆ 5    ┆ 2025 │
│ 2462668  ┆ Hvězda flat       ┆ Run           ┆ 1001.15  ┆ … ┆ 22.0              ┆ 29  ┆ 5    ┆ 2025 │
│ 2462668  ┆ Hvězda flat       ┆ Run           ┆ 1001.15  ┆ … ┆ inf               ┆ 30  ┆ 5    ┆ 2025 │
│ 2462668  ┆ Hvězda flat       ┆ Run           ┆ 1001.15  ┆ … ┆ 27.0              ┆ 31  ┆ 5    ┆ 2025 │
│ 2462668  ┆ Hvězda flat       ┆ Run           ┆ 1001.15  ┆ … ┆ inf               ┆ 32  ┆ 5    ┆ 2025 │
│ 2462668  ┆ Hvězda flat       ┆ Run           ┆ 1001.15  ┆ … ┆ 24.0              ┆ 33  ┆ 5    ┆ 2025 │
│ 2462668  ┆ Hvězda flat       ┆ Run           ┆ 1001.15  ┆ … ┆ inf               ┆ 34  ┆ 6    ┆ 2025 │
│ 2462668  ┆ Hvězda flat       ┆ Run           ┆ 1001.15  ┆ … ┆ inf               ┆ 35  ┆ 6    ┆ 2025 │
│ 2462668  ┆ Hvězda flat       ┆ Run           ┆ 1001.15  ┆ … ┆ 18.0              ┆ 36  ┆ 6    ┆ 2025 │
│ 2462668  ┆ Hvězda flat       ┆ Run           ┆ 1001.15  ┆ … ┆ inf               ┆ 37  ┆ 6    ┆ 2025 │
│ 2462668  ┆ Hvězda flat       ┆ Run           ┆ 1001.15  ┆ … ┆ 7.0               ┆ 38  ┆ 6    ┆ 2025 │
│ 2462668  ┆ Hvězda flat       ┆ Run           ┆ 1001.15  ┆ … ┆ inf               ┆ 39  ┆ 6    ┆ 2025 │
│ 2462668  ┆ Hvězda flat       ┆ Run           ┆ 1001.15  ┆ … ┆ 32.0              ┆ 40  ┆ 6    ┆ 2025 │
│ 2462668  ┆ Hvězda flat       ┆ Run           ┆ 1001.15  ┆ … ┆ inf               ┆ 41  ┆ 7    ┆ 2025 │
│ 2462668  ┆ Hvězda flat       ┆ Run           ┆ 1001.15  ┆ … ┆ 15.0              ┆ 42  ┆ 7    ┆ 2025 │
│ …        ┆ …                 ┆ …             ┆ …        ┆ … ┆ …                 ┆ …   ┆ …    ┆ …    │
│ 33529195 ┆ Smetanovy reverse ┆ Run           ┆ 639.7    ┆ … ┆ 19.0              ┆ 11  ┆ 2    ┆ 2026 │
│ 33529195 ┆ Smetanovy reverse ┆ Run           ┆ 639.7    ┆ … ┆ 30.0              ┆ 12  ┆ 3    ┆ 2026 │
│ 33529195 ┆ Smetanovy reverse ┆ Run           ┆ 639.7    ┆ … ┆ inf               ┆ 13  ┆ 3    ┆ 2026 │
│ 33529195 ┆ Smetanovy reverse ┆ Run           ┆ 639.7    ┆ … ┆ 32.0              ┆ 14  ┆ 3    ┆ 2026 │
│ 33529195 ┆ Smetanovy reverse ┆ Run           ┆ 639.7    ┆ … ┆ 31.0              ┆ 15  ┆ 3    ┆ 2026 │
│ 33529195 ┆ Smetanovy reverse ┆ Run           ┆ 639.7    ┆ … ┆ 22.0              ┆ 16  ┆ 3    ┆ 2026 │
│ 33529195 ┆ Smetanovy reverse ┆ Run           ┆ 639.7    ┆ … ┆ 37.0              ┆ 17  ┆ 3    ┆ 2026 │
│ 33529195 ┆ Smetanovy reverse ┆ Run           ┆ 639.7    ┆ … ┆ inf               ┆ 18  ┆ 3    ┆ 2026 │
│ 33529195 ┆ Smetanovy reverse ┆ Run           ┆ 639.7    ┆ … ┆ inf               ┆ 19  ┆ 4    ┆ 2026 │
│ 33529195 ┆ Smetanovy reverse ┆ Run           ┆ 639.7    ┆ … ┆ 51.0              ┆ 20  ┆ 4    ┆ 2026 │
│ 33529195 ┆ Smetanovy reverse ┆ Run           ┆ 639.7    ┆ … ┆ 48.0              ┆ 21  ┆ 4    ┆ 2026 │
│ 33529195 ┆ Smetanovy reverse ┆ Run           ┆ 639.7    ┆ … ┆ 28.0              ┆ 22  ┆ 4    ┆ 2026 │
│ 33529195 ┆ Smetanovy reverse ┆ Run           ┆ 639.7    ┆ … ┆ inf               ┆ 23  ┆ 4    ┆ 2026 │
│ 33529195 ┆ Smetanovy reverse ┆ Run           ┆ 639.7    ┆ … ┆ 32.0              ┆ 24  ┆ 4    ┆ 2026 │
│ 33529195 ┆ Smetanovy reverse ┆ Run           ┆ 639.7    ┆ … ┆ -inf              ┆ 25  ┆ 4    ┆ 2026 │
│ 33529195 ┆ Smetanovy reverse ┆ Run           ┆ 639.7    ┆ … ┆ 34.0              ┆ 26  ┆ 5    ┆ 2026 │
│ 33529195 ┆ Smetanovy reverse ┆ Run           ┆ 639.7    ┆ … ┆ inf               ┆ 27  ┆ 5    ┆ 2026 │
│ 33529195 ┆ Smetanovy reverse ┆ Run           ┆ 639.7    ┆ … ┆ 56.0              ┆ 28  ┆ 5    ┆ 2026 │
│ 33529195 ┆ Smetanovy reverse ┆ Run           ┆ 639.7    ┆ … ┆ -25.0             ┆ 29  ┆ 5    ┆ 2026 │
│ 33529195 ┆ Smetanovy reverse ┆ Run           ┆ 639.7    ┆ … ┆ inf               ┆ 30  ┆ 5    ┆ 2026 │
│ 33529195 ┆ Smetanovy reverse ┆ Run           ┆ 639.7    ┆ … ┆ inf               ┆ 31  ┆ 5    ┆ 2026 │
│ 33529195 ┆ Smetanovy reverse ┆ Run           ┆ 639.7    ┆ … ┆ 38.0              ┆ 33  ┆ 6    ┆ 2026 │
│ 33529195 ┆ Smetanovy reverse ┆ Run           ┆ 639.7    ┆ … ┆ inf               ┆ 34  ┆ 6    ┆ 2026 │
│ 33529195 ┆ Smetanovy reverse ┆ Run           ┆ 639.7    ┆ … ┆ 46.0              ┆ 35  ┆ 6    ┆ 2026 │
│ 33529195 ┆ Smetanovy reverse ┆ Run           ┆ 639.7    ┆ … ┆ inf               ┆ 36  ┆ 6    ┆ 2026 │
│ 33529195 ┆ Smetanovy reverse ┆ Run           ┆ 639.7    ┆ … ┆ 20.0              ┆ 37  ┆ 6    ┆ 2026 │
│ 33529195 ┆ Smetanovy reverse ┆ Run           ┆ 639.7    ┆ … ┆ inf               ┆ 38  ┆ 6    ┆ 2026 │
│ 33529195 ┆ Smetanovy reverse ┆ Run           ┆ 639.7    ┆ … ┆ 39.0              ┆ 39  ┆ 6    ┆ 2026 │
│ 33529195 ┆ Smetanovy reverse ┆ Run           ┆ 639.7    ┆ … ┆ inf               ┆ 40  ┆ 7    ┆ 2026 │
│ 33529195 ┆ Smetanovy reverse ┆ Run           ┆ 639.7    ┆ … ┆ 33.0              ┆ 41  ┆ 7    ┆ 2026 │
│ 33529195 ┆ Smetanovy reverse ┆ Run           ┆ 639.7    ┆ … ┆ 34.5              ┆ 45  ┆ 7    ┆ 2026 │
│ 33529195 ┆ Smetanovy reverse ┆ Run           ┆ 639.7    ┆ … ┆ 26.0              ┆ 47  ┆ 8    ┆ 2026 │
│ 33529195 ┆ Smetanovy reverse ┆ Run           ┆ 639.7    ┆ … ┆ 16.0              ┆ 48  ┆ 8    ┆ 2026 │
│ 33529195 ┆ Smetanovy reverse ┆ Run           ┆ 639.7    ┆ … ┆ 57.0              ┆ 51  ┆ 8    ┆ 2026 │
│ 33529195 ┆ Smetanovy reverse ┆ Run           ┆ 639.7    ┆ … ┆ 46.0              ┆ 52  ┆ 8    ┆ 2026 │
│ 33529195 ┆ Smetanovy reverse ┆ Run           ┆ 639.7    ┆ … ┆ inf               ┆ 53  ┆ 8    ┆ 2026 │
│ 33529195 ┆ Smetanovy reverse ┆ Run           ┆ 639.7    ┆ … ┆ 37.0              ┆ 54  ┆ 9    ┆ 2026 │
│ 33529195 ┆ Smetanovy reverse ┆ Run           ┆ 639.7    ┆ … ┆ inf               ┆ 55  ┆ 9    ┆ 2026 │
│ 33529195 ┆ Smetanovy reverse ┆ Run           ┆ 639.7    ┆ … ┆ inf               ┆ 56  ┆ 9    ┆ 2026 │
│ 33529195 ┆ Smetanovy reverse ┆ Run           ┆ 639.7    ┆ … ┆ inf               ┆ 57  ┆ 9    ┆ 2026 │
│ 33529195 ┆ Smetanovy reverse ┆ Run           ┆ 639.7    ┆ … ┆ 27.0              ┆ 58  ┆ 9    ┆ 2026 │
│ 33529195 ┆ Smetanovy reverse ┆ Run           ┆ 639.7    ┆ … ┆ 37.0              ┆ 59  ┆ 9    ┆ 2026 │
│ 33529195 ┆ Smetanovy reverse ┆ Run           ┆ 639.7    ┆ … ┆ inf               ┆ 60  ┆ 9    ┆ 2026 │
│ 33529195 ┆ Smetanovy reverse ┆ Run           ┆ 639.7    ┆ … ┆ 30.0              ┆ 61  ┆ 10   ┆ 2026 │
│ 33529195 ┆ Smetanovy reverse ┆ Run           ┆ 639.7    ┆ … ┆ inf               ┆ 62  ┆ 10   ┆ 2026 │
│ 33529195 ┆ Smetanovy reverse ┆ Run           ┆ 639.7    ┆ … ┆ inf               ┆ 63  ┆ 10   ┆ 2026 │
│ 33529195 ┆ Smetanovy reverse ┆ Run           ┆ 639.7    ┆ … ┆ 49.0              ┆ 64  ┆ 10   ┆ 2026 │
│ 33529195 ┆ Smetanovy reverse ┆ Run           ┆ 639.7    ┆ … ┆ inf               ┆ 65  ┆ 10   ┆ 2026 │
│ 33529195 ┆ Smetanovy reverse ┆ Run           ┆ 639.7    ┆ … ┆ inf               ┆ 66  ┆ 10   ┆ 2026 │
│ 33529195 ┆ Smetanovy reverse ┆ Run           ┆ 639.7    ┆ … ┆ 20.0              ┆ 67  ┆ 10   ┆ 2026 │
└──────────┴───────────────────┴───────────────┴──────────┴───┴───────────────────┴─────┴──────┴──────┘

In [101]:
orez_extremu = df.filter(
    pl.col('name').is_in(celorepublika)
).select(
    pl.col('effort_diff')
).quantile(
    0.99
).item(
)

do_grafu_celorepublika = df.filter(
    pl.col('name').is_in(celorepublika)
).with_columns(
    pl.when(pl.col('effort_diff') >= orez_extremu).then(orez_extremu).otherwise(pl.col('effort_diff')).alias('effort_diff')
).group_by(
    ['year','week']
).agg(
    pl.col('effort_diff').sum()
).sort(
    by=['year','week']
).filter(
    pl.col('year') >= 2025
).with_columns(
    (pl.col('effort_diff') / pl.col('effort_diff').shift(1)).alias('trend')
)

do_grafu_celorepublika.filter(pl.col("trend") > 1.2)

shape: (6, 4)
┌──────┬──────┬─────────────┬──────────┐
│ year ┆ week ┆ effort_diff ┆ trend    │
│ ---  ┆ ---  ┆ ---         ┆ ---      │
│ i32  ┆ i8   ┆ f64         ┆ f64      │
╞══════╪══════╪═════════════╪══════════╡
│ 2025 ┆ 44   ┆ 1460.0      ┆ 1.418853 │
│ 2025 ┆ 47   ┆ 1615.0      ┆ 1.78453  │
│ 2026 ┆ 2    ┆ 1024.0      ┆ 1.410468 │
│ 2026 ┆ 6    ┆ 1348.0      ┆ 1.454153 │
│ 2026 ┆ 8    ┆ 1188.0      ┆ 1.346939 │
│ 2026 ┆ 9    ┆ 1589.0      ┆ 1.337542 │
└──────┴──────┴─────────────┴──────────┘

In [102]:
orez_extremu_kolo = df.filter(
    pl.col('name').is_in(celorepublika_kolo)
).select(
    pl.col('effort_diff')
).quantile(
    0.99
).item(
)

do_grafu_celorepublika_kolo = df.filter(
    pl.col('name').is_in(celorepublika_kolo)
).with_columns(
    pl.when(pl.col('effort_diff') >= orez_extremu_kolo).then(orez_extremu_kolo).otherwise(pl.col('effort_diff')).alias('effort_diff')
).group_by(
    ['year','week']
).agg(
    pl.col('effort_diff').sum()
).sort(
    by=['year','week']
).filter(
    pl.col('year') >= 2025
).with_columns(
    (pl.col('effort_diff') / pl.col('effort_diff').shift(1)).alias('trend')
)

do_grafu_celorepublika_kolo.filter(pl.col("trend") > 1.2)

do_grafu_celorepublika_kolo_2w = df.filter(
    pl.col('name').is_in(celorepublika_kolo)
).with_columns(
    pl.when(pl.col('effort_diff') >= orez_extremu_kolo).then(orez_extremu_kolo).otherwise(pl.col('effort_diff')).alias('effort_diff')
).sort(
    by="date"
).group_by_dynamic(
    index_column="date", every="2w"
).agg(
    pl.col('effort_diff').sum()
).sort(
    by="date"
).filter(
    pl.col('date').dt.year() >= 2025
).with_columns(
    (pl.col('effort_diff') / pl.col('effort_diff').shift(1)).alias('trend')
).with_columns(
    pl.col("date").dt.year().alias("year")
)

do_grafu_celorepublika_kolo.filter(pl.col("trend") > 1.2)

shape: (21, 4)
┌──────┬──────┬─────────────┬──────────┐
│ year ┆ week ┆ effort_diff ┆ trend    │
│ ---  ┆ ---  ┆ ---         ┆ ---      │
│ i32  ┆ i8   ┆ f64         ┆ f64      │
╞══════╪══════╪═════════════╪══════════╡
│ 2025 ┆ 3    ┆ 761.0       ┆ 1.206022 │
│ 2025 ┆ 4    ┆ 1419.0      ┆ 1.864652 │
│ 2025 ┆ 8    ┆ 1169.0      ┆ 1.562834 │
│ 2025 ┆ 9    ┆ 2075.0      ┆ 1.775021 │
│ 2025 ┆ 10   ┆ 3980.0      ┆ 1.918072 │
│ 2025 ┆ 12   ┆ 3192.0      ┆ 1.479833 │
│ 2025 ┆ 16   ┆ 4825.0      ┆ 1.204744 │
│ 2025 ┆ 22   ┆ 5643.0      ┆ 1.223282 │
│ 2025 ┆ 24   ┆ 6543.0      ┆ 1.456589 │
│ 2025 ┆ 29   ┆ 5783.0      ┆ 1.234102 │
│ 2025 ┆ 32   ┆ 6596.0      ┆ 1.333064 │
│ 2025 ┆ 38   ┆ 6095.0      ┆ 1.416125 │
│ 2025 ┆ 44   ┆ 2566.0      ┆ 1.542067 │
│ 2025 ┆ 47   ┆ 1536.0      ┆ 1.381295 │
│ 2025 ┆ 49   ┆ 1044.0      ┆ 1.633803 │
│ 2025 ┆ 50   ┆ 1422.0      ┆ 1.362069 │
│ 2026 ┆ 4    ┆ 485.0       ┆ 1.492308 │
│ 2026 ┆ 6    ┆ 597.0       ┆ 1.275641 │
│ 2026 ┆ 7    ┆ 834.0       ┆ 1.396985 │
│ 2026 ┆ 9    ┆ 3078.0      ┆ 4.204918 │
│ 2026 ┆ 10   ┆ 3845.0      ┆ 1.249188 │
└──────┴──────┴─────────────┴──────────┘

In [103]:
do_grafu_celorepublika.sort(by="effort_diff",descending=True).head(10)

shape: (10, 4)
┌──────┬──────┬─────────────┬──────────┐
│ year ┆ week ┆ effort_diff ┆ trend    │
│ ---  ┆ ---  ┆ ---         ┆ ---      │
│ i32  ┆ i8   ┆ f64         ┆ f64      │
╞══════╪══════╪═════════════╪══════════╡
│ 2026 ┆ 10   ┆ 1619.0      ┆ 1.01888  │
│ 2025 ┆ 47   ┆ 1615.0      ┆ 1.78453  │
│ 2026 ┆ 9    ┆ 1589.0      ┆ 1.337542 │
│ 2025 ┆ 36   ┆ 1462.0      ┆ 1.160317 │
│ 2025 ┆ 44   ┆ 1460.0      ┆ 1.418853 │
│ 2025 ┆ 22   ┆ 1433.0      ┆ 1.166938 │
│ 2025 ┆ 19   ┆ 1428.0      ┆ 1.088415 │
│ 2025 ┆ 50   ┆ 1423.0      ┆ 1.117832 │
│ 2025 ┆ 23   ┆ 1417.0      ┆ 0.988835 │
│ 2025 ┆ 13   ┆ 1371.0      ┆ 1.03785  │
└──────┴──────┴─────────────┴──────────┘

In [104]:
alt.Chart(
    do_grafu_celorepublika,
    width=500,
    height=300
).mark_line(
).encode(
    alt.X('week:Q'),
    alt.Y('trend:Q'),
    alt.Color('year:N')
)

alt.Chart(...)

In [105]:
alt.Chart(
    do_grafu_celorepublika_kolo,
    width=500,
    height=300
).mark_line(
).encode(
    alt.X('week:Q'),
    alt.Y('trend:Q'),
    alt.Color('year:N')
)

alt.Chart(...)

In [106]:
do_grafu_celorepublika_kolo_2w

shape: (31, 4)
┌──────────────────────────┬─────────────┬──────────┬──────┐
│ date                     ┆ effort_diff ┆ trend    ┆ year │
│ ---                      ┆ ---         ┆ ---      ┆ ---  │
│ datetime[μs, CET]        ┆ f64         ┆ f64      ┆ i32  │
╞══════════════════════════╪═════════════╪══════════╪══════╡
│ 2025-01-06 00:00:00 CET  ┆ 1392.0      ┆ null     ┆ 2025 │
│ 2025-01-20 00:00:00 CET  ┆ 3029.0      ┆ 2.176006 ┆ 2025 │
│ 2025-02-03 00:00:00 CET  ┆ 1961.0      ┆ 0.647408 ┆ 2025 │
│ 2025-02-17 00:00:00 CET  ┆ 3244.0      ┆ 1.654258 ┆ 2025 │
│ 2025-03-03 00:00:00 CET  ┆ 6137.0      ┆ 1.8918   ┆ 2025 │
│ 2025-03-17 00:00:00 CET  ┆ 6374.0      ┆ 1.038618 ┆ 2025 │
│ 2025-03-31 00:00:00 CEST ┆ 7801.0      ┆ 1.223878 ┆ 2025 │
│ 2025-04-14 00:00:00 CEST ┆ 9914.0      ┆ 1.270863 ┆ 2025 │
│ 2025-04-28 00:00:00 CEST ┆ 10756.0     ┆ 1.08493  ┆ 2025 │
│ 2025-05-12 00:00:00 CEST ┆ 8938.0      ┆ 0.830978 ┆ 2025 │
│ 2025-05-26 00:00:00 CEST ┆ 10135.0     ┆ 1.133923 ┆ 2025 │
│ 2025-06-09 00:00:00 CEST ┆ 12325.0     ┆ 1.216083 ┆ 2025 │
│ 2025-06-23 00:00:00 CEST ┆ 11688.0     ┆ 0.948316 ┆ 2025 │
│ 2025-07-07 00:00:00 CEST ┆ 10469.0     ┆ 0.895705 ┆ 2025 │
│ 2025-07-21 00:00:00 CEST ┆ 10295.0     ┆ 0.98338  ┆ 2025 │
│ 2025-08-04 00:00:00 CEST ┆ 13853.0     ┆ 1.345605 ┆ 2025 │
│ 2025-08-18 00:00:00 CEST ┆ 13078.0     ┆ 0.944055 ┆ 2025 │
│ 2025-09-01 00:00:00 CEST ┆ 10673.0     ┆ 0.816103 ┆ 2025 │
│ 2025-09-15 00:00:00 CEST ┆ 9125.0      ┆ 0.854961 ┆ 2025 │
│ 2025-09-29 00:00:00 CEST ┆ 5245.0      ┆ 0.574795 ┆ 2025 │
│ 2025-10-13 00:00:00 CEST ┆ 4145.0      ┆ 0.790276 ┆ 2025 │
│ 2025-10-27 00:00:00 CET  ┆ 4713.0      ┆ 1.137033 ┆ 2025 │
│ 2025-11-10 00:00:00 CET  ┆ 2648.0      ┆ 0.56185  ┆ 2025 │
│ 2025-11-24 00:00:00 CET  ┆ 1683.0      ┆ 0.635574 ┆ 2025 │
│ 2025-12-08 00:00:00 CET  ┆ 2294.0      ┆ 1.363042 ┆ 2025 │
│ 2025-12-22 00:00:00 CET  ┆ 1420.0      ┆ 0.619006 ┆ 2025 │
│ 2026-01-05 00:00:00 CET  ┆ 696.0       ┆ 0.490141 ┆ 2026 │
│ 2026-01-19 00:00:00 CET  ┆ 953.0       ┆ 1.369253 ┆ 2026 │
│ 2026-02-02 00:00:00 CET  ┆ 1431.0      ┆ 1.501574 ┆ 2026 │
│ 2026-02-16 00:00:00 CET  ┆ 3810.0      ┆ 2.662474 ┆ 2026 │
│ 2026-03-02 00:00:00 CET  ┆ 3845.0      ┆ 1.009186 ┆ 2026 │
└──────────────────────────┴─────────────┴──────────┴──────┘

In [107]:
alt.Chart(
    do_grafu_celorepublika_kolo_2w,
    width=500,
    height=300
).mark_line(
).encode(
    alt.X('date:T'),
    alt.Y('effort_diff:Q'),
    alt.Color('year:N')
)

alt.Chart(...)

In [108]:
alt.Chart(
    do_grafu_celorepublika,
    width=500,
    height=300
).mark_line(
).encode(
    alt.X('week:Q'),
    alt.Y('effort_diff:Q'),
    alt.Color('year:N')
)

alt.Chart(...)

In [109]:
do_grafu_celorepublika

shape: (62, 4)
┌──────┬──────┬─────────────┬──────────┐
│ year ┆ week ┆ effort_diff ┆ trend    │
│ ---  ┆ ---  ┆ ---         ┆ ---      │
│ i32  ┆ i8   ┆ f64         ┆ f64      │
╞══════╪══════╪═════════════╪══════════╡
│ 2025 ┆ 1    ┆ 1085.0      ┆ null     │
│ 2025 ┆ 2    ┆ 1179.0      ┆ 1.086636 │
│ 2025 ┆ 3    ┆ 1128.0      ┆ 0.956743 │
│ 2025 ┆ 4    ┆ 1250.0      ┆ 1.108156 │
│ 2025 ┆ 5    ┆ 1235.0      ┆ 0.988    │
│ 2025 ┆ 6    ┆ 1040.0      ┆ 0.842105 │
│ 2025 ┆ 7    ┆ 1053.0      ┆ 1.0125   │
│ 2025 ┆ 8    ┆ 1120.0      ┆ 1.063628 │
│ 2025 ┆ 9    ┆ 1170.0      ┆ 1.044643 │
│ 2025 ┆ 10   ┆ 1240.0      ┆ 1.059829 │
│ 2025 ┆ 11   ┆ 1251.0      ┆ 1.008871 │
│ 2025 ┆ 12   ┆ 1321.0      ┆ 1.055955 │
│ 2025 ┆ 13   ┆ 1371.0      ┆ 1.03785  │
│ 2025 ┆ 14   ┆ 1285.0      ┆ 0.937272 │
│ 2025 ┆ 15   ┆ 1351.0      ┆ 1.051362 │
│ 2025 ┆ 16   ┆ 1240.0      ┆ 0.917839 │
│ 2025 ┆ 17   ┆ 1269.0      ┆ 1.023387 │
│ 2025 ┆ 18   ┆ 1312.0      ┆ 1.033885 │
│ 2025 ┆ 19   ┆ 1428.0      ┆ 1.088415 │
│ 2025 ┆ 20   ┆ 1216.0      ┆ 0.851541 │
│ 2025 ┆ 21   ┆ 1228.0      ┆ 1.009868 │
│ 2025 ┆ 22   ┆ 1433.0      ┆ 1.166938 │
│ 2025 ┆ 23   ┆ 1417.0      ┆ 0.988835 │
│ 2025 ┆ 24   ┆ 1238.0      ┆ 0.873677 │
│ 2025 ┆ 25   ┆ 1202.0      ┆ 0.970921 │
│ 2025 ┆ 26   ┆ 1136.0      ┆ 0.945092 │
│ 2025 ┆ 27   ┆ 1189.0      ┆ 1.046655 │
│ 2025 ┆ 28   ┆ 1249.0      ┆ 1.050463 │
│ 2025 ┆ 29   ┆ 1106.0      ┆ 0.885508 │
│ 2025 ┆ 30   ┆ 1147.0      ┆ 1.037071 │
│ 2025 ┆ 31   ┆ 1294.0      ┆ 1.12816  │
│ 2025 ┆ 32   ┆ 1201.0      ┆ 0.92813  │
│ 2025 ┆ 33   ┆ 1262.0      ┆ 1.050791 │
│ 2025 ┆ 34   ┆ 1352.0      ┆ 1.071315 │
│ 2025 ┆ 35   ┆ 1260.0      ┆ 0.931953 │
│ 2025 ┆ 36   ┆ 1462.0      ┆ 1.160317 │
│ 2025 ┆ 37   ┆ 1313.0      ┆ 0.898085 │
│ 2025 ┆ 38   ┆ 1322.0      ┆ 1.006855 │
│ 2025 ┆ 39   ┆ 1340.0      ┆ 1.013616 │
│ 2025 ┆ 40   ┆ 1325.0      ┆ 0.988806 │
│ 2025 ┆ 41   ┆ 1304.0      ┆ 0.984151 │
│ 2025 ┆ 42   ┆ 1220.0      ┆ 0.935583 │
│ 2025 ┆ 43   ┆ 1029.0      ┆ 0.843443 │
│ 2025 ┆ 44   ┆ 1460.0      ┆ 1.418853 │
│ 2025 ┆ 45   ┆ 1304.0      ┆ 0.893151 │
│ 2025 ┆ 46   ┆ 905.0       ┆ 0.694018 │
│ 2025 ┆ 47   ┆ 1615.0      ┆ 1.78453  │
│ 2025 ┆ 48   ┆ 1121.0      ┆ 0.694118 │
│ 2025 ┆ 49   ┆ 1273.0      ┆ 1.135593 │
│ 2025 ┆ 50   ┆ 1423.0      ┆ 1.117832 │
│ 2025 ┆ 51   ┆ 1176.0      ┆ 0.826423 │
│ 2025 ┆ 52   ┆ 1065.0      ┆ 0.905612 │
│ 2026 ┆ 1    ┆ 726.0       ┆ 0.68169  │
│ 2026 ┆ 2    ┆ 1024.0      ┆ 1.410468 │
│ 2026 ┆ 3    ┆ 1015.0      ┆ 0.991211 │
│ 2026 ┆ 4    ┆ 1079.0      ┆ 1.063054 │
│ 2026 ┆ 5    ┆ 927.0       ┆ 0.859129 │
│ 2026 ┆ 6    ┆ 1348.0      ┆ 1.454153 │
│ 2026 ┆ 7    ┆ 882.0       ┆ 0.654303 │
│ 2026 ┆ 8    ┆ 1188.0      ┆ 1.346939 │
│ 2026 ┆ 9    ┆ 1589.0      ┆ 1.337542 │
│ 2026 ┆ 10   ┆ 1619.0      ┆ 1.01888  │
└──────┴──────┴─────────────┴──────────┘

In [177]:
alt.Chart(
    do_grafu_celorepublika,
    width=500,
    height=300
).mark_line(
).encode(
    alt.X('week:Q'),
    alt.Y('effort_diff:Q'),
    alt.Color('year:N')
)

alt.Chart(...)

In [181]:
do_grafu_celorepublika.drop("trend").write_json("data/graf_rok_behani.json")

In [110]:
alt.Chart(
    do_grafu_celorepublika_kolo,
    width=500,
    height=300
).mark_line(
).encode(
    alt.X('week:Q'),
    alt.Y('effort_diff:Q'),
    alt.Color('year:N')
)

alt.Chart(...)

In [183]:
do_grafu_celorepublika_kolo.drop("trend").write_json("data/graf_rok_cyklo.json")

In [111]:
df.filter(
    (pl.col("country") == "Czechia") & (pl.col("activity_type") == "Run")
).group_by(
    "city"
).agg(
    pl.col("name").unique().len()
).sort(
    by='name',descending=True
)

shape: (74, 2)
┌──────────────────────────────────┬──────┐
│ city                             ┆ name │
│ ---                              ┆ ---  │
│ str                              ┆ u32  │
╞══════════════════════════════════╪══════╡
│ Praha                            ┆ 16   │
│ Brno                             ┆ 12   │
│ Ostrava                          ┆ 4    │
│ Olomouc                          ┆ 3    │
│ Hradec Králové                   ┆ 3    │
│ Liberec                          ┆ 3    │
│ Jihlava                          ┆ 2    │
│ Klatovy                          ┆ 2    │
│ Sušice                           ┆ 2    │
│ Most                             ┆ 2    │
│ České Budějovice                 ┆ 2    │
│ Jičín                            ┆ 2    │
│ Karlovy Vary                     ┆ 2    │
│ Znojmo                           ┆ 2    │
│ Frýdek-Místek                    ┆ 1    │
│ Lednice                          ┆ 1    │
│ Bruntál                          ┆ 1    │
│ Vsetín                           ┆ 1    │
│ Blansko                          ┆ 1    │
│ Rakovník                         ┆ 1    │
│ Kolín                            ┆ 1    │
│ Pavlov                           ┆ 1    │
│ Vyšší Brod                       ┆ 1    │
│ Ostravice                        ┆ 1    │
│ Šumperk                          ┆ 1    │
│ Poděbrady                        ┆ 1    │
│ Pec pod Sněžkou                  ┆ 1    │
│ Horní Planá                      ┆ 1    │
│ Aš                               ┆ 1    │
│ Kroměříž                         ┆ 1    │
│ Pardubice V                      ┆ 1    │
│ Mostkovice                       ┆ 1    │
│ Humpolec                         ┆ 1    │
│ Tábor                            ┆ 1    │
│ Staré Město                      ┆ 1    │
│ Čelákovice                       ┆ 1    │
│ Brandýs nad Labem-Stará Boleslav ┆ 1    │
│ Deštné v Orlických horách        ┆ 1    │
│ Havířov                          ┆ 1    │
│ Ctiněves                         ┆ 1    │
│ Třebíč                           ┆ 1    │
│ Nové Město na Moravě             ┆ 1    │
│ Třemošná                         ┆ 1    │
│ Jaroměř                          ┆ 1    │
│ Krnov                            ┆ 1    │
│ Vlašim                           ┆ 1    │
│ Trutnov                          ┆ 1    │
│ Dačice                           ┆ 1    │
│ Benešov                          ┆ 1    │
│ Liberec - Horní Hanychov         ┆ 1    │
│ Děčín                            ┆ 1    │
│ Kadaň                            ┆ 1    │
│ Ústí nad Labem-Střekov           ┆ 1    │
│ Hrdlořezy                        ┆ 1    │
│ Jindřichův Hradec                ┆ 1    │
│ Babice nad Svitavou              ┆ 1    │
│ Opava                            ┆ 1    │
│ Beroun                           ┆ 1    │
│ Pardubice                        ┆ 1    │
│ Zlín                             ┆ 1    │
│ Břeclav                          ┆ 1    │
│ Čáslav                           ┆ 1    │
│ Plzeň 1                          ┆ 1    │
│ Domažlice                        ┆ 1    │
│ Litomyšl                         ┆ 1    │
│ Uherské Hradiště                 ┆ 1    │
│ Hořice                           ┆ 1    │
│ Samotišky                        ┆ 1    │
│ Náchod                           ┆ 1    │
│ Hradec Kralove                   ┆ 1    │
│ Trojanovice                      ┆ 1    │
│ Čtyřkoly                         ┆ 1    │
│ Lhotka                           ┆ 1    │
│ Chvalčov                         ┆ 1    │
└──────────────────────────────────┴──────┘

In [112]:
df.filter(
    (pl.col("country") == "Czechia") & (pl.col("activity_type") == "Ride") & (pl.col('start_to_finish_distance') > 1)
).group_by(
    ["name","city"]
).agg(
    pl.col("effort_diff").quantile(0.8)
).sort(
    by="effort_diff", descending=True
)

shape: (66, 3)
┌────────────────────────────────────────────────────┬──────────────────────────────┬─────────────┐
│ name                                               ┆ city                         ┆ effort_diff │
│ ---                                                ┆ ---                          ┆ ---         │
│ str                                                ┆ str                          ┆ f64         │
╞════════════════════════════════════════════════════╪══════════════════════════════╪═════════════╡
│ Opičí Časovka, Podolská vodárna - Dvorce           ┆ Praha                        ┆ 210.0       │
│ Zbraslav - Komořany                                ┆ Zbraslav                     ┆ 151.0       │
│ time trial at Svratka                              ┆ Brno                         ┆ 92.0        │
│ Rokytka od myčky                                   ┆ Praha                        ┆ 66.0        │
│ Stezka do Zlina                                    ┆ Zlin                         ┆ 51.0        │
│ Židlochovice -> Olympia                            ┆ Židlochovice                 ┆ 32.0        │
│ Srbsko - Hlásná Třebáň                             ┆ Srbsko                       ┆ 29.0        │
│ Revnicak Eve                                       ┆ Řevnice                      ┆ 28.0        │
│ Muglinovská→Hradní lávka (po pravém břehu)         ┆ Ostrava                      ┆ 28.0        │
│ Risova studanka - od zavory                        ┆ Brno                         ┆ 26.0        │
│ Novomlýnská 5: Věstonice-Strachotín                ┆ Dolní Věstonice              ┆ 24.0        │
│ svadov—valtirov                                    ┆ Ústí nad Labem-Neštěmice     ┆ 20.0        │
│ Jiráskovo nábřeží k Husovce                        ┆ České Budějovice             ┆ 19.0        │
│ Cyklostezka sprint směr Děčín                      ┆ Hřensko                      ┆ 18.0        │
│ Nová cyklostezka do Bosche  2                      ┆ Jihlava                      ┆ 18.0        │
│ Maslovice - Kralupy                                ┆ Máslovice                    ┆ 18.0        │
│ Adamaov climb                                      ┆ Adamov                       ┆ 17.0        │
│ Sprintík křižovatka/skalní mlýn                    ┆ Blansko                      ┆ 17.0        │
│ Trinec-Tesin                                       ┆ Třinec                       ┆ 16.0        │
│ Szpic Jested  last 3 km ( od rozc na Dub)          ┆ Liberec                      ┆ 16.0        │
│ Mutěnka - z Kyjova po odbočku na hraběcí           ┆ Kyjov                        ┆ 15.0        │
│ Lysá hora - 5 km                                   ┆ Staré Hamry                  ┆ 15.0        │
│ Údolí Svatý Jan                                    ┆ Beroun                       ┆ 14.0        │
│ Decin - Bad Schandau Abzweig Radwg                 ┆ Děčín                        ┆ 14.0        │
│ Papezov - Prazmo                                   ┆ Krásná                       ┆ 13.0        │
│ Tuhnice most-Drahovice most,stezka                 ┆ Karlovy Vary                 ┆ 13.0        │
│ Sedmička, Lipno {                                  ┆ Přední Výtoň                 ┆ 13.0        │
│ Podle Radbuzy                                      ┆ Pilsen                       ┆ 13.0        │
│ Eurovie - nadjezd Rosice                           ┆ Pardubice II                 ┆ 13.0        │
│ Cyklostezka Náchod -> Velké Poříčí                 ┆ Náchod                       ┆ 12.0        │
│ MH - Klaster                                       ┆ Klášter Hradiště nad Jizerou ┆ 11.0        │
│ Z Lednice po silnici k odbocce na Janohrad         ┆ Lednice                      ┆ 10.0        │
│ Vlevo dole jezero Most                             ┆ Most                         ┆ 9.0         │
│ Daskabát flat                                      ┆ Velký Újezd                  ┆ 9.0         │
│ Do sedla Klínovce po silnici                       ┆ Loučná pod Klínovcem         ┆ 9.0         │
│ most - Loket                                       ┆ Staré Sedlo                  ┆ 9.0         │
│ Bunč climb                                         ┆ Kostelany                    ┆ 8.0         │
│ Sprint Páteček - Santos                            ┆ Sušice                       ┆ 8.0         │
│ Šobes - sjezd                                      ┆ Podmolí                      ┆ 7.0         │
│ Kaufland - Popendorf                               ┆ Jičín                        ┆ 7.0         │
│ Hostyn-od.zastavky.po.znacku.P                     ┆ Bystřice Pod Hostýnem        ┆ 7.0         │
│ Plácky-soutok                                      ┆ Hradec Králové               ┆ 7.0         │
│ Kleť k vysílači - finále                           ┆ Kájov                        ┆ 7.0         │
│ Špindlerovka - část II. (od Černýho potoka nahoru) ┆ Špindlerův Mlýn              ┆ 6.0         │
│ Máchovo kritérium - přes bory kolem vrchu Borný    ┆ Doksy                        ┆ 6.0         │
│ Lednice - Bulhary                                  ┆ Lednice                      ┆ 6.0         │
│ Kerhartice-Choceň                                  ┆ Ústí nad Orlicí              ┆ 6.0         │
│ Starý Kolín - Svatá Kateřina                       ┆ Starý Kolín                  ┆ 5.0         │
│ Černý důl konec Hoffmanky                          ┆ Černý Důl                    ┆ 5.0         │
│ stupani k vetr. mlynu Kuzelov                      ┆ Javorník                     ┆ 4.0         │
│ Kvilda Bučina                                      ┆ Kvilda                       ┆ 4.0         │
│ Bečva - Pustevny Uphill                            ┆ Prostřední Bečva             ┆ 4.0         │
│ Dářská rašeliniště                                 ┆ Radostín                     ┆ 4.0         │
│ Nová cyklopěšina z Peřiny do HTčka                 ┆ Horšovský Týn                ┆ 4.0         │
│ Sjezd Blatno-Březenec                              ┆ Blatno                       ┆ 3.0         │
│ Červená voda - Suchý vrch                          ┆ Červená Voda                 ┆ 3.0         │
│ Výrovka - Modré Sedlo                              ┆ Pec pod Sněžkou              ┆ 3.0         │
│ Ruda -> Gerlovka                                   ┆ Železná Ruda                 ┆ 2.0         │
│ Podél dálnice                                      ┆ Nepřevázka                   ┆ 2.0         │
│ Jesenice-Blatno DH                                 ┆ Jesenice                     ┆ 2.0         │
│ 611 - Mstetice                                     ┆ Jirny                        ┆ 2.0         │
│ Le Grande Classico                                 ┆ Spálov                       ┆ 2.0         │
│ Pod Homoli Climb                                   ┆ Liberk                       ┆ 2.0         │
│ Červená podél Zlaté stoky do Třeboně               ┆ Třeboň                       ┆ 1.0         │
│ podle Labe do Týnce                                ┆ Kojice                       ┆ 1.0         │
│ Dlouhe Strane od Loucnej                           ┆ Loučná nad Desnou            ┆ 0.0         │
└────────────────────────────────────────────────────┴──────────────────────────────┴─────────────┘

In [113]:
df

shape: (120_064, 23)
┌──────────┬────────────────┬───────────────┬──────────┬───┬───────────────────┬─────┬──────┬──────┐
│ id       ┆ name           ┆ activity_type ┆ distance ┆ … ┆ avg_daily_efforts ┆ day ┆ week ┆ year │
│ ---      ┆ ---            ┆ ---           ┆ ---      ┆   ┆ ---               ┆ --- ┆ ---  ┆ ---  │
│ i64      ┆ str            ┆ str           ┆ f64      ┆   ┆ f64               ┆ i16 ┆ i8   ┆ i32  │
╞══════════╪════════════════╪═══════════════╪══════════╪═══╪═══════════════════╪═════╪══════╪══════╡
│ 652851   ┆ Alpe d'Huez    ┆ Ride          ┆ 12024.9  ┆ … ┆ null              ┆ 362 ┆ 52   ┆ 2024 │
│ 652851   ┆ Alpe d'Huez    ┆ Ride          ┆ 12024.9  ┆ … ┆ -13.0             ┆ 363 ┆ 52   ┆ 2024 │
│ 652851   ┆ Alpe d'Huez    ┆ Ride          ┆ 12024.9  ┆ … ┆ 4.0               ┆ 364 ┆ 52   ┆ 2024 │
│ 652851   ┆ Alpe d'Huez    ┆ Ride          ┆ 12024.9  ┆ … ┆ inf               ┆ 365 ┆ 1    ┆ 2024 │
│ 652851   ┆ Alpe d'Huez    ┆ Ride          ┆ 12024.9  ┆ … ┆ 5.0               ┆ 366 ┆ 1    ┆ 2024 │
│ 652851   ┆ Alpe d'Huez    ┆ Ride          ┆ 12024.9  ┆ … ┆ -17.0             ┆ 1   ┆ 1    ┆ 2025 │
│ 652851   ┆ Alpe d'Huez    ┆ Ride          ┆ 12024.9  ┆ … ┆ -1.0              ┆ 2   ┆ 1    ┆ 2025 │
│ 652851   ┆ Alpe d'Huez    ┆ Ride          ┆ 12024.9  ┆ … ┆ inf               ┆ 3   ┆ 1    ┆ 2025 │
│ 652851   ┆ Alpe d'Huez    ┆ Ride          ┆ 12024.9  ┆ … ┆ 8.0               ┆ 4   ┆ 1    ┆ 2025 │
│ 652851   ┆ Alpe d'Huez    ┆ Ride          ┆ 12024.9  ┆ … ┆ inf               ┆ 5   ┆ 1    ┆ 2025 │
│ 652851   ┆ Alpe d'Huez    ┆ Ride          ┆ 12024.9  ┆ … ┆ inf               ┆ 6   ┆ 2    ┆ 2025 │
│ 652851   ┆ Alpe d'Huez    ┆ Ride          ┆ 12024.9  ┆ … ┆ 2.0               ┆ 7   ┆ 2    ┆ 2025 │
│ 652851   ┆ Alpe d'Huez    ┆ Ride          ┆ 12024.9  ┆ … ┆ 1.0               ┆ 8   ┆ 2    ┆ 2025 │
│ 652851   ┆ Alpe d'Huez    ┆ Ride          ┆ 12024.9  ┆ … ┆ -9.0              ┆ 9   ┆ 2    ┆ 2025 │
│ 652851   ┆ Alpe d'Huez    ┆ Ride          ┆ 12024.9  ┆ … ┆ -inf              ┆ 10  ┆ 2    ┆ 2025 │
│ 652851   ┆ Alpe d'Huez    ┆ Ride          ┆ 12024.9  ┆ … ┆ -inf              ┆ 11  ┆ 2    ┆ 2025 │
│ 652851   ┆ Alpe d'Huez    ┆ Ride          ┆ 12024.9  ┆ … ┆ -inf              ┆ 12  ┆ 2    ┆ 2025 │
│ 652851   ┆ Alpe d'Huez    ┆ Ride          ┆ 12024.9  ┆ … ┆ 9.0               ┆ 13  ┆ 3    ┆ 2025 │
│ 652851   ┆ Alpe d'Huez    ┆ Ride          ┆ 12024.9  ┆ … ┆ -inf              ┆ 14  ┆ 3    ┆ 2025 │
│ 652851   ┆ Alpe d'Huez    ┆ Ride          ┆ 12024.9  ┆ … ┆ inf               ┆ 15  ┆ 3    ┆ 2025 │
│ 652851   ┆ Alpe d'Huez    ┆ Ride          ┆ 12024.9  ┆ … ┆ -11.0             ┆ 16  ┆ 3    ┆ 2025 │
│ 652851   ┆ Alpe d'Huez    ┆ Ride          ┆ 12024.9  ┆ … ┆ -inf              ┆ 17  ┆ 3    ┆ 2025 │
│ 652851   ┆ Alpe d'Huez    ┆ Ride          ┆ 12024.9  ┆ … ┆ 0.0               ┆ 18  ┆ 3    ┆ 2025 │
│ 652851   ┆ Alpe d'Huez    ┆ Ride          ┆ 12024.9  ┆ … ┆ inf               ┆ 19  ┆ 3    ┆ 2025 │
│ 652851   ┆ Alpe d'Huez    ┆ Ride          ┆ 12024.9  ┆ … ┆ 3.0               ┆ 20  ┆ 4    ┆ 2025 │
│ 652851   ┆ Alpe d'Huez    ┆ Ride          ┆ 12024.9  ┆ … ┆ -inf              ┆ 21  ┆ 4    ┆ 2025 │
│ 652851   ┆ Alpe d'Huez    ┆ Ride          ┆ 12024.9  ┆ … ┆ inf               ┆ 22  ┆ 4    ┆ 2025 │
│ 652851   ┆ Alpe d'Huez    ┆ Ride          ┆ 12024.9  ┆ … ┆ inf               ┆ 23  ┆ 4    ┆ 2025 │
│ 652851   ┆ Alpe d'Huez    ┆ Ride          ┆ 12024.9  ┆ … ┆ 0.0               ┆ 24  ┆ 4    ┆ 2025 │
│ 652851   ┆ Alpe d'Huez    ┆ Ride          ┆ 12024.9  ┆ … ┆ -inf              ┆ 25  ┆ 4    ┆ 2025 │
│ 652851   ┆ Alpe d'Huez    ┆ Ride          ┆ 12024.9  ┆ … ┆ -inf              ┆ 26  ┆ 4    ┆ 2025 │
│ 652851   ┆ Alpe d'Huez    ┆ Ride          ┆ 12024.9  ┆ … ┆ -5.0              ┆ 27  ┆ 5    ┆ 2025 │
│ 652851   ┆ Alpe d'Huez    ┆ Ride          ┆ 12024.9  ┆ … ┆ -inf              ┆ 28  ┆ 5    ┆ 2025 │
│ 652851   ┆ Alpe d'Huez    ┆ Ride          ┆ 12024.9  ┆ … ┆ inf               ┆ 29  ┆ 5    ┆ 2025 │
│ 652851   ┆ Alpe d'Huez    ┆ Ride          ┆ 12024.9  ┆ … ┆ -inf              ┆ 30  ┆ 5    ┆ 2025 │
│ 652851   ┆ Alpe d'Huez    ┆ Ride          ┆ 12024.9  ┆ … ┆ -1.0              ┆ 31  ┆ 5    ┆ 2025 │
│ 652851   ┆ Alpe d'Huez    ┆ Ride          ┆ 12024.9  ┆ … ┆ 11.0              ┆ 32  ┆ 5    ┆ 2025 │
│ 652851   ┆ Alpe d'Huez    ┆ Ride          ┆ 12024.9  ┆ … ┆ 6.0               ┆ 33  ┆ 5    ┆ 2025 │
│ 652851   ┆ Alpe d'Huez    ┆ Ride          ┆ 12024.9  ┆ … ┆ -inf              ┆ 34  ┆ 6    ┆ 2025 │
│ 652851   ┆ Alpe d'Huez    ┆ Ride          ┆ 12024.9  ┆ … ┆ 4.0               ┆ 35  ┆ 6    ┆ 2025 │
│ 652851   ┆ Alpe d'Huez    ┆ Ride          ┆ 12024.9  ┆ … ┆ inf               ┆ 36  ┆ 6    ┆ 2025 │
│ 652851   ┆ Alpe d'Huez    ┆ Ride          ┆ 12024.9  ┆ … ┆ 4.0               ┆ 37  ┆ 6    ┆ 2025 │
│ 652851   ┆ Alpe d'Huez    ┆ Ride          ┆ 12024.9  ┆ … ┆ 8.0               ┆ 39  ┆ 6    ┆ 2025 │
│ 652851   ┆ Alpe d'Huez    ┆ Ride          ┆ 12024.9  ┆ … ┆ -44.0             ┆ 40  ┆ 6    ┆ 2025 │
│ 652851   ┆ Alpe d'Huez    ┆ Ride          ┆ 12024.9  ┆ … ┆ 8.0               ┆ 41  ┆ 7    ┆ 2025 │
│ 652851   ┆ Alpe d'Huez    ┆ Ride          ┆ 12024.9  ┆ … ┆ 5.0               ┆ 42  ┆ 7    ┆ 2025 │
│ 652851   ┆ Alpe d'Huez    ┆ Ride          ┆ 12024.9  ┆ … ┆ NaN               ┆ 43  ┆ 7    ┆ 2025 │
│ 652851   ┆ Alpe d'Huez    ┆ Ride          ┆ 12024.9  ┆ … ┆ -1.0              ┆ 44  ┆ 7    ┆ 2025 │
│ 652851   ┆ Alpe d'Huez    ┆ Ride          ┆ 12024.9  ┆ … ┆ inf               ┆ 45  ┆ 7    ┆ 2025 │
│ 652851   ┆ Alpe d'Huez    ┆ Ride          ┆ 12024.9  ┆ … ┆ 2.0               ┆ 46  ┆ 7    ┆ 2025 │
│ …        ┆ …              ┆ …             ┆ …        ┆ … ┆ …                 ┆ …   ┆ …    ┆ …    │
│ 39018275 ┆ kolem kapličky ┆ Run           ┆ 695.8    ┆ … ┆ 5.0               ┆ 11  ┆ 2    ┆ 2026 │
│ 39018275 ┆ kolem kapličky ┆ Run           ┆ 695.8    ┆ … ┆ NaN               ┆ 12  ┆ 3    ┆ 2026 │
│ 39018275 ┆ kolem kapličky ┆ Run           ┆ 695.8    ┆ … ┆ 9.0               ┆ 13  ┆ 3    ┆ 2026 │
│ 39018275 ┆ kolem kapličky ┆ Run           ┆ 695.8    ┆ … ┆ inf               ┆ 14  ┆ 3    ┆ 2026 │
│ 39018275 ┆ kolem kapličky ┆ Run           ┆ 695.8    ┆ … ┆ inf               ┆ 15  ┆ 3    ┆ 2026 │
│ 39018275 ┆ kolem kapličky ┆ Run           ┆ 695.8    ┆ … ┆ inf               ┆ 16  ┆ 3    ┆ 2026 │
│ 39018275 ┆ kolem kapličky ┆ Run           ┆ 695.8    ┆ … ┆ 3.0               ┆ 17  ┆ 3    ┆ 2026 │
│ 39018275 ┆ kolem kapličky ┆ Run           ┆ 695.8    ┆ … ┆ inf               ┆ 18  ┆ 3    ┆ 2026 │
│ 39018275 ┆ kolem kapličky ┆ Run           ┆ 695.8    ┆ … ┆ inf               ┆ 19  ┆ 4    ┆ 2026 │
│ 39018275 ┆ kolem kapličky ┆ Run           ┆ 695.8    ┆ … ┆ 6.0               ┆ 20  ┆ 4    ┆ 2026 │
│ 39018275 ┆ kolem kapličky ┆ Run           ┆ 695.8    ┆ … ┆ 5.0               ┆ 21  ┆ 4    ┆ 2026 │
│ 39018275 ┆ kolem kapličky ┆ Run           ┆ 695.8    ┆ … ┆ inf               ┆ 22  ┆ 4    ┆ 2026 │
│ 39018275 ┆ kolem kapličky ┆ Run           ┆ 695.8    ┆ … ┆ 2.0               ┆ 23  ┆ 4    ┆ 2026 │
│ 39018275 ┆ kolem kapličky ┆ Run           ┆ 695.8    ┆ … ┆ inf               ┆ 24  ┆ 4    ┆ 2026 │
│ 39018275 ┆ kolem kapličky ┆ Run           ┆ 695.8    ┆ … ┆ 4.0               ┆ 25  ┆ 4    ┆ 2026 │
│ 39018275 ┆ kolem kapličky ┆ Run           ┆ 695.8    ┆ … ┆ inf               ┆ 26  ┆ 5    ┆ 2026 │
│ 39018275 ┆ kolem kapličky ┆ Run           ┆ 695.8    ┆ … ┆ 3.0               ┆ 27  ┆ 5    ┆ 2026 │
│ 39018275 ┆ kolem kapličky ┆ Run           ┆ 695.8    ┆ … ┆ inf               ┆ 28  ┆ 5    ┆ 2026 │
│ 39018275 ┆ kolem kapličky ┆ Run           ┆ 695.8    ┆ … ┆ 4.0               ┆ 29  ┆ 5    ┆ 2026 │
│ 39018275 ┆ kolem kapličky ┆ Run           ┆ 695.8    ┆ … ┆ inf               ┆ 30  ┆ 5    ┆ 2026 │
│ 39018275 ┆ kolem kapličky ┆ Run           ┆ 695.8    ┆ … ┆ 4.0               ┆ 31  ┆ 5    ┆ 2026 │
│ 39018275 ┆ kolem kapličky ┆ Run           ┆ 695.8    ┆ … ┆ 7.0               ┆ 33  ┆ 6    ┆ 2026 │
│ 39018275 ┆ kolem kapličky ┆ Run           ┆ 695.8    ┆ … ┆ -2.0              ┆ 34  ┆ 6    ┆ 2026 │
│ 39018275 ┆ kolem kapličky ┆ Run           ┆ 695.8    ┆ … ┆ 2.0               ┆ 35  ┆ 6    ┆ 2026 │
│ 39018275 ┆ kolem kapličky ┆ Run           ┆ 695.8    ┆ … ┆ inf               ┆ 36  ┆ 6    ┆ 2026 │
│ 39018275 ┆ kolem kapličky ┆ Run           ┆ 695.8    ┆ … ┆ inf               ┆ 37  ┆ 6    ┆ 2026 │
│ 39018275 ┆ kolem kapličky ┆ Run           ┆ 695.8    ┆ … ┆ inf               ┆ 38  ┆ 6    ┆ 2026 │
│ 39018275 ┆ kolem kapličky ┆ Run           ┆ 695.8    ┆ … ┆ 5.0               ┆ 39  ┆ 6    ┆ 2026 │
│ 39018275 ┆ kolem kapličky ┆ Run           ┆ 695.8    ┆ … ┆ inf               ┆ 40  ┆ 7    ┆ 2026 │
│ 39018275 ┆ kolem kapličky ┆ Run           ┆ 695.8    ┆ … ┆ -inf              ┆ 41  ┆ 7    ┆ 2026 │
│ 39018275 ┆ kolem kapličky ┆ Run           ┆ 695.8    ┆ … ┆ 5.25              ┆ 45  ┆ 7    ┆ 2026 │
│ 39018275 ┆ kolem kapličky ┆ Run           ┆ 695.8    ┆ … ┆ 7.0               ┆ 47  ┆ 8    ┆ 2026 │
│ 39018275 ┆ kolem kapličky ┆ Run           ┆ 695.8    ┆ … ┆ 2.0               ┆ 48  ┆ 8    ┆ 2026 │
│ 39018275 ┆ kolem kapličky ┆ Run           ┆ 695.8    ┆ … ┆ 3.0               ┆ 51  ┆ 8    ┆ 2026 │
│ 39018275 ┆ kolem kapličky ┆ Run           ┆ 695.8    ┆ … ┆ NaN               ┆ 52  ┆ 8    ┆ 2026 │
│ 39018275 ┆ kolem kapličky ┆ Run           ┆ 695.8    ┆ … ┆ inf               ┆ 53  ┆ 8    ┆ 2026 │
│ 39018275 ┆ kolem kapličky ┆ Run           ┆ 695.8    ┆ … ┆ 4.0               ┆ 54  ┆ 9    ┆ 2026 │
│ 39018275 ┆ kolem kapličky ┆ Run           ┆ 695.8    ┆ … ┆ 3.0               ┆ 55  ┆ 9    ┆ 2026 │
│ 39018275 ┆ kolem kapličky ┆ Run           ┆ 695.8    ┆ … ┆ inf               ┆ 56  ┆ 9    ┆ 2026 │
│ 39018275 ┆ kolem kapličky ┆ Run           ┆ 695.8    ┆ … ┆ 6.0               ┆ 57  ┆ 9    ┆ 2026 │
│ 39018275 ┆ kolem kapličky ┆ Run           ┆ 695.8    ┆ … ┆ inf               ┆ 58  ┆ 9    ┆ 2026 │
│ 39018275 ┆ kolem kapličky ┆ Run           ┆ 695.8    ┆ … ┆ inf               ┆ 59  ┆ 9    ┆ 2026 │
│ 39018275 ┆ kolem kapličky ┆ Run           ┆ 695.8    ┆ … ┆ 5.0               ┆ 60  ┆ 9    ┆ 2026 │
│ 39018275 ┆ kolem kapličky ┆ Run           ┆ 695.8    ┆ … ┆ 11.0              ┆ 61  ┆ 10   ┆ 2026 │
│ 39018275 ┆ kolem kapličky ┆ Run           ┆ 695.8    ┆ … ┆ inf               ┆ 62  ┆ 10   ┆ 2026 │
│ 39018275 ┆ kolem kapličky ┆ Run           ┆ 695.8    ┆ … ┆ inf               ┆ 63  ┆ 10   ┆ 2026 │
│ 39018275 ┆ kolem kapličky ┆ Run           ┆ 695.8    ┆ … ┆ 13.0              ┆ 64  ┆ 10   ┆ 2026 │
│ 39018275 ┆ kolem kapličky ┆ Run           ┆ 695.8    ┆ … ┆ inf               ┆ 65  ┆ 10   ┆ 2026 │
│ 39018275 ┆ kolem kapličky ┆ Run           ┆ 695.8    ┆ … ┆ inf               ┆ 66  ┆ 10   ┆ 2026 │
│ 39018275 ┆ kolem kapličky ┆ Run           ┆ 695.8    ┆ … ┆ 4.0               ┆ 67  ┆ 10   ┆ 2026 │
└──────────┴────────────────┴───────────────┴──────────┴───┴───────────────────┴─────┴──────┴──────┘

In [114]:
df.select("effort_diff").quantile(0.9)

shape: (1, 1)
┌─────────────┐
│ effort_diff │
│ ---         │
│ f64         │
╞═════════════╡
│ 28.0        │
└─────────────┘

In [115]:
df.filter(
    (pl.col("country") == "Czechia") & (pl.col("activity_type") == "Run") & (pl.col('start_to_finish_distance') < 0.5)
).group_by(
    ["name","city"]
).agg(
    pl.col("effort_diff").quantile(0.8)
).sort(
    by="effort_diff", descending=True
)

shape: (57, 3)
┌──────────────────────────────────────┬───────────────────┬─────────────┐
│ name                                 ┆ city              ┆ effort_diff │
│ ---                                  ┆ ---               ┆ ---         │
│ str                                  ┆ str               ┆ f64         │
╞══════════════════════════════════════╪═══════════════════╪═════════════╡
│ VUT horní dráha 400m                 ┆ Brno              ┆ 219.0       │
│ Stadion Na Děkance                   ┆ Praha             ┆ 187.0       │
│ Pražačka 320                         ┆ Praha             ┆ 140.0       │
│ Šlechtovka - finální rovinka         ┆ Praha             ┆ 139.0       │
│ Lužánky rovinka                      ┆ Brno              ┆ 124.0       │
│ TJ Sokol okruh                       ┆ Praha             ┆ 91.0        │
│ 400m-Liberec                         ┆ Liberec           ┆ 74.0        │
│ Strahovská dráha                     ┆ Praha             ┆ 66.0        │
│ Štvanická lávka (do Karlína)         ┆ Praha             ┆ 64.0        │
│ Vítkov up sprint                     ┆ Praha             ┆ 53.0        │
│ Kolo na stadionu v Třebíči           ┆ Třebíč            ┆ 52.0        │
│ Most Legií (směr Kampa)              ┆ Praha             ┆ 34.0        │
│ Tyršák čtyřstofka                    ┆ Šumperk           ┆ 34.0        │
│ 400 m - atletický okruh - Lokomotiva ┆ Olomouc           ┆ 33.0        │
│ 400m                                 ┆ Pardubice V       ┆ 32.0        │
│ Ovál ZŠ Štefánikova                  ┆ Hradec Králové    ┆ 31.0        │
│ Karlův most ONLY                     ┆ Praha             ┆ 31.0        │
│ Lužánky - Plochá dráha               ┆ Brno              ┆ 29.0        │
│ Kampa South                          ┆ Praha             ┆ 29.0        │
│ Junglepark                           ┆ Brno              ┆ 27.0        │
│ 400 m (track num. 2)                 ┆ Benešov           ┆ 25.0        │
│ Mestsky stadion Trutnov              ┆ Trutnov           ┆ 25.0        │
│ Juliska 400 m                        ┆ Praha             ┆ 25.0        │
│ Tatran Třemošná                      ┆ Třemošná          ┆ 24.0        │
│ Od dubu ke Gizele                    ┆ Praha             ┆ 23.0        │
│ 400m - Sportovní areál Na Stoupách   ┆ Jihlava           ┆ 22.0        │
│ Stadion Čelákovice 400m (II.)        ┆ Čelákovice        ┆ 19.0        │
│ TJ Znojmo Lap                        ┆ Znojmo            ┆ 19.0        │
│ Benedikt - Parkoviště                ┆ Most              ┆ 16.0        │
│ 400m-Jičín                           ┆ Jičín             ┆ 13.0        │
│ Hradiště - čtyřstovka                ┆ Uherské Hradiště  ┆ 13.0        │
│ LS - Park Boost                      ┆ Bruntál           ┆ 10.0        │
│ Čtyrák 800m                          ┆ České Budějovice  ┆ 8.0         │
│ Kolem stadionu                       ┆ Hradec Kralove    ┆ 8.0         │
│ Zatáčky Žabovřeská                   ┆ Brno              ┆ 7.0         │
│ Slezanský ovál                       ┆ Frýdek-Místek     ┆ 7.0         │
│ Vojenský ovál 400M                   ┆ Hradec Králové    ┆ 7.0         │
│ Od letňáku ke starému vchodu ZOO     ┆ Jihlava           ┆ 6.0         │
│ Lysa hora - jizni sjezdovka          ┆ Ostravice         ┆ 6.0         │
│ Kopec nářku                          ┆ Brno              ┆ 5.0         │
│ Od lávky k lávce                     ┆ Rakovník          ┆ 5.0         │
│ BRNĚNSKÁ SA CALOBRA                  ┆ Brno              ┆ 3.0         │
│ Track Domažlice                      ┆ Domažlice         ┆ 3.0         │
│ Jindrichohradecky 1/2 M petikilo     ┆ Jindřichův Hradec ┆ 2.0         │
│ Segment                              ┆ Ctiněves          ┆ 2.0         │
│ Koupaliště sprint                    ┆ Vlašim            ┆ 2.0         │
│ Rybnik                               ┆ Kroměříž          ┆ 2.0         │
│ Schody voda - Hostýn                 ┆ Chvalčov          ┆ 1.0         │
│ Bludička-Opavice                     ┆ Opava             ┆ 1.0         │
│ Berounka sprint                      ┆ Beroun            ┆ 1.0         │
│ Šup do parku                         ┆ Plzeň 1           ┆ 1.0         │
│ ČSFR RIP                             ┆ Brno              ┆ 0.0         │
│ Stadion - 400 m                      ┆ Dačice            ┆ 0.0         │
│ Autodrom Most                        ┆ Most              ┆ 0.0         │
│ Giro di Tyrš                         ┆ Aš                ┆ 0.0         │
│ Pavlov - Dívčí hrad climb            ┆ Pavlov            ┆ 0.0         │
│ 400 metrů, 44 120 diváků             ┆ Brno              ┆ 0.0         │
└──────────────────────────────────────┴───────────────────┴─────────────┘

In [116]:
df.filter(
    (pl.col("country") == "Czechia") & (pl.col("activity_type") == "Run") & (pl.col('start_to_finish_distance') > 0.5)
).group_by(
    ["name","city"]
).agg(
    pl.col("effort_diff").quantile(0.8)
).sort(
    by="effort_diff", descending=True
)

shape: (60, 3)
┌─────────────────────────────────────────────────────┬──────────────────────────────────┬─────────────┐
│ name                                                ┆ city                             ┆ effort_diff │
│ ---                                                 ┆ ---                              ┆ ---         │
│ str                                                 ┆ str                              ┆ f64         │
╞═════════════════════════════════════════════════════╪══════════════════════════════════╪═════════════╡
│ tenis 1K                                            ┆ Brno                             ┆ 45.0        │
│ Smetanovy reverse                                   ┆ Olomouc                          ┆ 41.0        │
│ Hvězda flat                                         ┆ Praha                            ┆ 33.0        │
│ Stodůlecký - Nepomucký rybník                       ┆ Praha                            ┆ 30.0        │
│ Stezka nábřeží                                      ┆ Zlín                             ┆ 22.0        │
│ Rullerovo nábřeží                                   ┆ Brno                             ┆ 20.0        │
│ stezka                                              ┆ České Budějovice                 ┆ 17.0        │
│ Hradní lávka => Sýkorův most                        ┆ Ostrava                          ┆ 14.0        │
│ mezi mosty                                          ┆ Pardubice                        ┆ 13.0        │
│ Šárka Valley (short)                                ┆ Praha                            ┆ 11.0        │
│ Interval                                            ┆ Olomouc                          ┆ 11.0        │
│ Park 1                                              ┆ Ostrava                          ┆ 10.0        │
│ Panelovka-Tichá 800m                                ┆ Mostkovice                       ┆ 8.0         │
│ Lípy (směrem do Jičína)                             ┆ Jičín                            ┆ 7.0         │
│ Ku řopíku                                           ┆ Děčín                            ┆ 7.0         │
│ Od Sanusu ke gymplu                                 ┆ Hradec Králové                   ┆ 7.0         │
│ kolem kapličky                                      ┆ Brno                             ┆ 6.0         │
│ od hráze až na konec přehrady - silnice             ┆ Liberec                          ┆ 6.0         │
│ U Jordánu do kopce                                  ┆ Tábor                            ┆ 5.0         │
│ Tuhnická lávka -Chebský most                        ┆ Karlovy Vary                     ┆ 5.0         │
│ Nábřeží                                             ┆ Kadaň                            ┆ 5.0         │
│ BK-nabrezi                                          ┆ Blansko                          ┆ 4.0         │
│ Železniční most => Jez Vítkovice                    ┆ Ostrava                          ┆ 4.0         │
│ Ciclo Via BNL -> K                                  ┆ Brandýs nad Labem-Stará Boleslav ┆ 4.0         │
│ Kuželna - Splav 800m                                ┆ Vsetín                           ┆ 4.0         │
│ po cyklostezce                                      ┆ Humpolec                         ┆ 4.0         │
│ Dlouhá míle                                         ┆ Sušice                           ┆ 4.0         │
│ JestedSkyrace - last uphill - middle part           ┆ Liberec                          ┆ 3.0         │
│ Kopeček - od kruháče k bazilice                     ┆ Samotišky                        ┆ 3.0         │
│ Gránické údolí - Central Part DOWN                  ┆ Znojmo                           ┆ 3.0         │
│ Luby end                                            ┆ Klatovy                          ┆ 3.0         │
│ Opavice od zatáčky                                  ┆ Krnov                            ┆ 3.0         │
│ START                                               ┆ Karlovy Vary                     ┆ 3.0         │
│ Rovinka od kruháče k bazénu                         ┆ Klatovy                          ┆ 3.0         │
│ Krásnohorské                                        ┆ Náchod                           ┆ 3.0         │
│ Javorník finish od Pinduly                          ┆ Trojanovice                      ┆ 3.0         │
│ Opavska down 1/2                                    ┆ Ostrava                          ┆ 3.0         │
│ #ULhalf - Strekovske Nabrezi                        ┆ Ústí nad Labem-Střekov           ┆ 2.0         │
│ rovinka kolem Sázavy:Plynovod-křižovatka u Mostu    ┆ Čtyřkoly                         ┆ 2.0         │
│ Ondřejník sedlo - Ondřejník vrchol                  ┆ Lhotka                           ┆ 2.0         │
│ Debř-Michalovice ☠                                  ┆ Hrdlořezy                        ┆ 2.0         │
│ BKJ - podél Labe                                    ┆ Poděbrady                        ┆ 2.0         │
│ Růžohorky - Růžová hora                             ┆ Pec pod Sněžkou                  ┆ 2.0         │
│ Tygří výzva, sklon 32% :)                           ┆ Liberec - Horní Hanychov         ┆ 2.0         │
│ Most - Most -> Břeclav                              ┆ Břeclav                          ┆ 2.0         │
│ Mezi zábranama (proti proudu)                       ┆ Jaroměř                          ┆ 2.0         │
│ Labe_po asfaltu                                     ┆ Kolín                            ┆ 1.0         │
│ Valy                                                ┆ Litomyšl                         ┆ 1.0         │
│ Z Doubravky k Josefu                                ┆ Hořice                           ┆ 1.0         │
│ Hlavní třídou nahoru                                ┆ Havířov                          ┆ 1.0         │
│ Pristaviste-Minaret                                 ┆ Lednice                          ┆ 1.0         │
│ podél Podměstského rybníku                          ┆ Čáslav                           ┆ 1.0         │
│ Okruhy Ochozou - Výběh na Harusák (0,76 km / 105 m) ┆ Nové Město na Moravě             ┆ 1.0         │
│ Po Šutrované od Alexandrovy rozhledny na kopec      ┆ Babice nad Svitavou              ┆ 1.0         │
│ Podél tratě do Úval                                 ┆ Praha                            ┆ 0.0         │
│ Kraličák Skyrace - 2. kopec                         ┆ Staré Město                      ┆ 0.0         │
│ Velká Deštná climb                                  ┆ Deštné v Orlických horách        ┆ 0.0         │
│ VR #11 finish                                       ┆ Vyšší Brod                       ┆ 0.0         │
│ BL Boletice - rovinka na hřebeni                    ┆ Horní Planá                      ┆ 0.0         │
│ Hadí stezka (Svatobor)                              ┆ Sušice                           ┆ 0.0         │
└─────────────────────────────────────────────────────┴──────────────────────────────────┴─────────────┘

In [117]:
alt.Chart(
    df.filter(
        pl.col('date').dt.year() >= 2025
    ).filter(
        pl.col('name').is_in(
            ["Opičí Časovka, Podolská vodárna - Dvorce","time trial at Svratka","Muglinovská→Hradní lávka (po pravém břehu)"	]
        )
    ).sort(
        by='date'
    ).group_by_dynamic(
        index_column='date',every='1mo'
    ).agg(
        pl.col('effort_diff').sum()
    ),
    width=800
).mark_bar(
).encode(
    alt.X("date:T"),
    alt.Y('effort_diff:Q')
    )

alt.Chart(...)

In [118]:
alt.Chart(
    df.filter(
        pl.col('date').dt.year() >= 2025
    ).filter(
        pl.col('name').is_in(
            ["Šlechtovka - finální rovinka","Lužánky rovinka","Smetanovy reverse","tenis 1K","Hvězda flat"]
        )
    ).sort(
        by='date'
    ).group_by_dynamic(
        index_column='date',every='1mo'
    ).agg(
        pl.col('effort_diff').sum()
    ),
    width=800
).mark_bar(
).encode(
    alt.X("date:T"),
    alt.Y('effort_diff:Q')
    )

alt.Chart(...)

In [119]:
alt.Chart(
    df.filter(
        pl.col('date').dt.year() >= 2025
    ).filter(
        pl.col('name').is_in(
            ["Die Eine Runde"	]
        )
    ).sort(
        by='date'
    ).group_by_dynamic(
        index_column='date',every='1mo'
    ).agg(
        pl.col('effort_diff').sum()
    ),
    width=800
).mark_bar(
).encode(
    alt.X("date:T"),
    alt.Y('effort_diff:Q')
    )

alt.Chart(...)

In [120]:
def ukaz_mesice(segmenty:list):
    return alt.Chart(
    df.filter(
        pl.col('date').dt.year() >= 2025
    ).filter(
        pl.col('name').is_in(
            segmenty
        )
    ).sort(
        by='date'
    ).group_by_dynamic(
        index_column='date',every='1mo'
    ).agg(
        pl.col('effort_diff').sum()
    ),
    width=800
).mark_bar(
).encode(
    alt.X("date:T"),
    alt.Y('effort_diff:Q')
    )

In [121]:
ukaz_mesice(
    ["Adamaov climb"	]
)

alt.Chart(...)

In [122]:
ukaz_mesice(["VUT horní dráha 400m","Stadion Na Děkance","TJ Sokol okruh","400m-Liberec","Kolo na stadionu v Třebíči"])

alt.Chart(...)

In [123]:
def ukaz_dny(segmenty:list):
    return alt.Chart(
    df.filter(
        pl.col('date').dt.year() >= 2025
    ).filter(
        pl.col('name').is_in(
            segmenty
        )
    ).sort(
        by='date'
    ).group_by(
        pl.col("date").dt.weekday()
    ).agg(
        pl.col('effort_diff').mean()
    ),
    width=800
).mark_bar(
).encode(
    alt.X("date:N"),
    alt.Y('effort_diff:Q')
    )

In [124]:
ukaz_dny(["Rullerovo nábřeží"])

alt.Chart(...)

In [125]:
ukaz_dny(["VUT horní dráha 400m","Stadion Na Děkance","TJ Sokol okruh","400m-Liberec","Kolo na stadionu v Třebíči"])

alt.Chart(...)

In [126]:
ukaz_dny(
    ["Kleť k vysílači - finále","Lednice - Bulhary","Máchovo kritérium - přes bory kolem vrchu Borný","Špindlerovka - část II. (od Černýho potoka nahoru)"]
)

alt.Chart(...)

In [127]:
sledujeme = [
    "Šlechtovka - finální rovinka","Štvanická lávka (do Karlína)","Most Legií (směr Kampa)","Vítkov up sprint","Hvězda flat","Šárka Valley (short)","Stodůlecký - Nepomucký rybník"
]

In [128]:
ukaz_dny(
    sledujeme
)

alt.Chart(...)

In [129]:
mezirocni_srovnani = df.filter(
    pl.col("name").is_in(sledujeme) & (pl.col('date').dt.year() >= 2025)
).with_columns(
    pl.col("date").dt.year().alias("rok"),
    pl.col("date").dt.ordinal_day().alias("den"),
    pl.col("date").dt.week().alias("tyden"),
).group_by(
    ['rok','tyden']
).agg(
    pl.col('effort_diff').sum()
).sort(
    by=['rok','tyden']
)

strop = mezirocni_srovnani.select(pl.col('effort_diff')).quantile(0.97).item()

mezirocni_srovnani = mezirocni_srovnani.with_columns(
    pl.when(pl.col('effort_diff') > strop).then(pl.lit(strop)).otherwise(pl.col('effort_diff')).alias('effort_diff')
)

In [130]:
alt.Chart(
    mezirocni_srovnani,
    width=900
).mark_line(
).encode(
    alt.X('tyden:Q'),
    alt.Y('effort_diff:Q'),
    alt.Color('rok:N')
)

alt.Chart(...)