V tomto sešitu najdeme nejfrekventovanější úseky napříč republikou (vždy jen 1 pro 1 město) a vyexportujeme je do souborů ```.yaml``` ve složce ```data```.

In [12]:
import os
import yaml
import polars as pl
import altair as alt

In [13]:
pl.Config(tbl_rows=100)
pl.Config(fmt_str_lengths=150)
alt.data_transformers.disable_max_rows()

DataTransformerRegistry.enable('default')

In [14]:
df = pl.read_parquet(
    "data/segments.parquet"
).sort(
    ["id", "date"]
).with_columns(
    days_diff = pl.col("date").diff().dt.total_days().over("id"),
    effort_diff = pl.col("effort_count").diff().over("id")
).with_columns(
    avg_daily_efforts = pl.col("effort_diff") / pl.col("days_diff")
).with_columns(
    pl.when(pl.col("city").str.contains("Praha") | pl.col("city").str.contains("Prague")).then(pl.lit('Praha')).when(pl.col('city').str.contains('Brno')).then(pl.lit('Brno')).otherwise(pl.col('city')).alias('city'),
    pl.when(pl.col("effort_diff") < 0).then(pl.lit(0)).otherwise(pl.col("effort_diff")).alias("effort_diff")
).with_columns(
    pl.col('date').dt.ordinal_day().alias('day'),
    pl.col('date').dt.week().alias('week'),
    pl.col('date').dt.year().alias('year')
)

## Rozsah dat

In [16]:
print(df.select(pl.col("date").min()).item())
print(df.select(pl.col("date").max()).item())

2024-12-24 23:05:01+01:00
2026-03-09 23:38:56+01:00

In [17]:
df.sample(1)

shape: (1, 23)
┌─────────┬─────────────────────────────────┬───────────────┬──────────┬───┬───────────────────┬─────┬──────┬──────┐
│ id      ┆ name                            ┆ activity_type ┆ distance ┆ … ┆ avg_daily_efforts ┆ day ┆ week ┆ year │
│ ---     ┆ ---                             ┆ ---           ┆ ---      ┆   ┆ ---               ┆ --- ┆ ---  ┆ ---  │
│ i64     ┆ str                             ┆ str           ┆ f64      ┆   ┆ f64               ┆ i16 ┆ i8   ┆ i32  │
╞═════════╪═════════════════════════════════╪═══════════════╪══════════╪═══╪═══════════════════╪═════╪══════╪══════╡
│ 8646352 ┆ Kopeček - od kruháče k bazilice ┆ Run           ┆ 776.1    ┆ … ┆ 1.0               ┆ 25  ┆ 4    ┆ 2026 │
└─────────┴─────────────────────────────────┴───────────────┴──────────┴───┴───────────────────┴─────┴──────┴──────┘

## Výběr segmentů ke sledování

### Nezávazný žebříček

In [20]:
zebricek = df.filter(
    pl.col("country") == "Czechia"
).group_by(
    ["name","city","activity_type","start_to_finish_distance"]
).agg(
    pl.col("effort_diff").quantile(0.8)
).sort(
    by="effort_diff", descending=True
)

zebricek.head(100)

shape: (100, 5)
┌──────────────────────────────┬──────────────────────────────┬───────────────┬──────────────────────────┬─────────────┐
│ name                         ┆ city                         ┆ activity_type ┆ start_to_finish_distance ┆ effort_diff │
│ ---                          ┆ ---                          ┆ ---           ┆ ---                      ┆ ---         │
│ str                          ┆ str                          ┆ str           ┆ f64                      ┆ f64         │
╞══════════════════════════════╪══════════════════════════════╪═══════════════╪══════════════════════════╪═════════════╡
│ Die Eine Runde               ┆ Brno                         ┆ Ride          ┆ 0.002446                 ┆ 419.0       │
│ VUT horní dráha 400m         ┆ Brno                         ┆ Run           ┆ 0.011266                 ┆ 219.0       │
│ Opičí Časovka, Podolská      ┆ Praha                        ┆ Ride          ┆ 1.379737                 ┆ 210.0       │
│ vodárna - Dvorce             ┆                              ┆               ┆                          ┆             │
│ Stadion Na Děkance           ┆ Praha                        ┆ Run           ┆ 0.006087                 ┆ 187.0       │
│ Zweite hup u ZOO             ┆ Praha                        ┆ Ride          ┆ 0.308372                 ┆ 184.0       │
│ Zbraslav - Komořany          ┆ Zbraslav                     ┆ Ride          ┆ 2.258969                 ┆ 151.0       │
│ Pražačka 320                 ┆ Praha                        ┆ Run           ┆ 0.000925                 ┆ 140.0       │
│ Šlechtovka - finální rovinka ┆ Praha                        ┆ Run           ┆ 0.222849                 ┆ 139.0       │
│ Lužánky rovinka              ┆ Brno                         ┆ Run           ┆ 0.260571                 ┆ 123.0       │
│ Od posledního tunelu do      ┆ Bílovice nad Svitavou        ┆ Ride          ┆ 0.647058                 ┆ 105.0       │
│ Bílovic                      ┆                              ┆               ┆                          ┆             │
│ Třebešín-dráha K             ┆ Praha                        ┆ Ride          ┆ 0.008769                 ┆ 96.0        │
│ time trial at Svratka        ┆ Brno                         ┆ Ride          ┆ 1.300465                 ┆ 92.0        │
│ TJ Sokol okruh               ┆ Praha                        ┆ Run           ┆ 0.009342                 ┆ 91.0        │
│ 400m-Liberec                 ┆ Liberec                      ┆ Run           ┆ 0.014369                 ┆ 74.0        │
│ Rokytka od myčky             ┆ Praha                        ┆ Ride          ┆ 1.812742                 ┆ 67.0        │
│ Strahovská dráha             ┆ Praha                        ┆ Run           ┆ 0.001716                 ┆ 66.0        │
│ Štvanická lávka (do Karlína) ┆ Praha                        ┆ Run           ┆ 0.273856                 ┆ 64.0        │
│ Vítkov up sprint             ┆ Praha                        ┆ Run           ┆ 0.117786                 ┆ 53.0        │
│ Kolo na stadionu v Třebíči   ┆ Třebíč                       ┆ Run           ┆ 0.008266                 ┆ 52.0        │
│ Stezka do Zlina              ┆ Zlin                         ┆ Ride          ┆ 1.265858                 ┆ 51.0        │
│ tenis 1K                     ┆ Brno                         ┆ Run           ┆ 0.951894                 ┆ 45.0        │
│ Smetanovy reverse            ┆ Olomouc                      ┆ Run           ┆ 0.631364                 ┆ 41.0        │
│ Sptint pod Býčí skálou       ┆ Olomučany                    ┆ Ride          ┆ 0.711671                 ┆ 36.0        │
│ Most Legií (směr Kampa)      ┆ Praha                        ┆ Run           ┆ 0.326026                 ┆ 34.0        │
│ Tyršák čtyřstofka            ┆ Šumperk                      ┆ Run           ┆ 0.002828                 ┆ 34.0        │
│ 400 m - atletický okruh -    ┆ Olomouc                      ┆ Run           ┆ 0.003459                 ┆ 33.0        │
│ Lokomotiva                   ┆                              ┆               ┆                          ┆             │
│ Hvězda flat                  ┆ Praha                        ┆ Run           ┆ 0.995211                 ┆ 33.0        │
│ 400m                         ┆ Pardubice V                  ┆ Run           ┆ 0.003456                 ┆ 32.0        │
│ Židlochovice -> Olympia      ┆ Židlochovice                 ┆ Ride          ┆ 9.643392                 ┆ 32.0        │
│ Ovál ZŠ Štefánikova          ┆ Hradec Králové               ┆ Run           ┆ 0.004506                 ┆ 31.0        │
│ Karlův most ONLY             ┆ Praha                        ┆ Run           ┆ 0.283976                 ┆ 31.0        │
│ Stodůlecký - Nepomucký       ┆ Praha                        ┆ Run           ┆ 0.529274                 ┆ 30.0        │
│ rybník                       ┆                              ┆               ┆                          ┆             │
│ Kampa South                  ┆ Praha                        ┆ Run           ┆ 0.36887                  ┆ 29.0        │
│ Srbsko - Hlásná Třebáň       ┆ Srbsko                       ┆ Ride          ┆ 4.557374                 ┆ 29.0        │
│ Lužánky - Plochá dráha       ┆ Brno                         ┆ Run           ┆ 0.001678                 ┆ 29.0        │
│ Revnicak Eve                 ┆ Řevnice                      ┆ Ride          ┆ 3.429182                 ┆ 28.0        │
│ Muglinovská→Hradní lávka (po ┆ Ostrava                      ┆ Ride          ┆ 2.660781                 ┆ 28.0        │
│ pravém břehu)                ┆                              ┆               ┆                          ┆             │
│ Junglepark                   ┆ Brno                         ┆ Run           ┆ 0.298243                 ┆ 27.0        │
│ Risova studanka - od zavory  ┆ Brno                         ┆ Ride          ┆ 2.507177                 ┆ 26.0        │
│ Mestsky stadion Trutnov      ┆ Trutnov                      ┆ Run           ┆ 0.001844                 ┆ 25.0        │
│ 400 m (track num. 2)         ┆ Benešov                      ┆ Run           ┆ 0.015573                 ┆ 25.0        │
│ Juliska 400 m                ┆ Praha                        ┆ Run           ┆ 0.00286                  ┆ 25.0        │
│ Novomlýnská 5:               ┆ Dolní Věstonice              ┆ Ride          ┆ 1.215091                 ┆ 24.0        │
│ Věstonice-Strachotín         ┆                              ┆               ┆                          ┆             │
│ Tatran Třemošná              ┆ Třemošná                     ┆ Run           ┆ 0.002124                 ┆ 24.0        │
│ Od dubu ke Gizele            ┆ Praha                        ┆ Run           ┆ 0.370526                 ┆ 23.0        │
│ Stezka nábřeží               ┆ Zlín                         ┆ Run           ┆ 0.577385                 ┆ 22.0        │
│ Malchor - Lysá Hora          ┆ Krásná                       ┆ Hike          ┆ 0.568227                 ┆ 22.0        │
│ 400m - Sportovní areál Na    ┆ Jihlava                      ┆ Run           ┆ 0.007687                 ┆ 22.0        │
│ Stoupách                     ┆                              ┆               ┆                          ┆             │
│ Rullerovo nábřeží            ┆ Brno                         ┆ Run           ┆ 0.940342                 ┆ 20.0        │
│ svadov—valtirov              ┆ Ústí nad Labem-Neštěmice     ┆ Ride          ┆ 2.730017                 ┆ 20.0        │
│ Total brikule 🚀             ┆ Staré Město                  ┆ Ride          ┆ 0.551812                 ┆ 19.0        │
│ Stadion Čelákovice 400m      ┆ Čelákovice                   ┆ Run           ┆ 0.006626                 ┆ 19.0        │
│ (II.)                        ┆                              ┆               ┆                          ┆             │
│ Jiráskovo nábřeží k Husovce  ┆ České Budějovice             ┆ Ride          ┆ 1.009863                 ┆ 19.0        │
│ TJ Znojmo Lap                ┆ Znojmo                       ┆ Run           ┆ 0.003705                 ┆ 19.0        │
│ Ještěd Finale konec před     ┆ Světlá pod Ještědem          ┆ Ride          ┆ 0.191607                 ┆ 19.0        │
│ kostkami.                    ┆                              ┆               ┆                          ┆             │
│ Maslovice - Kralupy          ┆ Máslovice                    ┆ Ride          ┆ 4.687004                 ┆ 18.0        │
│ Cyklostezka sprint směr      ┆ Hřensko                      ┆ Ride          ┆ 1.000775                 ┆ 18.0        │
│ Děčín                        ┆                              ┆               ┆                          ┆             │
│ Nová cyklostezka do Bosche   ┆ Jihlava                      ┆ Ride          ┆ 2.439248                 ┆ 18.0        │
│ 2                            ┆                              ┆               ┆                          ┆             │
│ Sprintík křižovatka/skalní   ┆ Blansko                      ┆ Ride          ┆ 2.099472                 ┆ 17.0        │
│ mlýn                         ┆                              ┆               ┆                          ┆             │
│ stezka                       ┆ České Budějovice             ┆ Run           ┆ 0.891633                 ┆ 17.0        │
│ Adamaov climb                ┆ Adamov                       ┆ Ride          ┆ 1.192579                 ┆ 17.0        │
│ Benedikt - Parkoviště        ┆ Most                         ┆ Run           ┆ 0.001136                 ┆ 16.0        │
│ Szpic Jested  last 3 km ( od ┆ Liberec                      ┆ Ride          ┆ 1.348759                 ┆ 16.0        │
│ rozc na Dub)                 ┆                              ┆               ┆                          ┆             │
│ Trinec-Tesin                 ┆ Třinec                       ┆ Ride          ┆ 4.360789                 ┆ 16.0        │
│ Transformator k Butorance (u ┆ Ostravice                    ┆ Hike          ┆ 1.223649                 ┆ 15.0        │
│ studanky)                    ┆                              ┆               ┆                          ┆             │
│ Mutěnka - z Kyjova po        ┆ Kyjov                        ┆ Ride          ┆ 3.458919                 ┆ 15.0        │
│ odbočku na hraběcí           ┆                              ┆               ┆                          ┆             │
│ Lysá hora - 5 km             ┆ Staré Hamry                  ┆ Ride          ┆ 3.229545                 ┆ 15.0        │
│ Hradní lávka => Sýkorův most ┆ Ostrava                      ┆ Run           ┆ 0.958195                 ┆ 14.0        │
│ Sedýlko - Praděd climb       ┆ Loučná Nad Desnou            ┆ Ride          ┆ 0.660889                 ┆ 14.0        │
│ Klinovec Top                 ┆ Jáchymov                     ┆ Ride          ┆ 0.774628                 ┆ 14.0        │
│ Decin - Bad Schandau Abzweig ┆ Děčín                        ┆ Ride          ┆ 14.292023                ┆ 14.0        │
│ Radwg                        ┆                              ┆               ┆                          ┆             │
│ Údolí Svatý Jan              ┆ Beroun                       ┆ Ride          ┆ 3.618147                 ┆ 14.0        │
│ Sedmička, Lipno {            ┆ Přední Výtoň                 ┆ Ride          ┆ 3.651891                 ┆ 13.0        │
│ Podle Radbuzy                ┆ Pilsen                       ┆ Ride          ┆ 1.806575                 ┆ 13.0        │
│ Papezov - Prazmo             ┆ Krásná                       ┆ Ride          ┆ 6.992833                 ┆ 13.0        │
│ 400m-Jičín                   ┆ Jičín                        ┆ Run           ┆ 0.001068                 ┆ 13.0        │
│ mezi mosty                   ┆ Pardubice                    ┆ Run           ┆ 0.894894                 ┆ 13.0        │
│ Hradiště - čtyřstovka        ┆ Uherské Hradiště             ┆ Run           ┆ 0.006289                 ┆ 13.0        │
│ Eurovie - nadjezd Rosice     ┆ Pardubice II                 ┆ Ride          ┆ 1.294441                 ┆ 13.0        │
│ Kynšperský ATAK              ┆ Kynšperk nad Ohří            ┆ Ride          ┆ 0.504788                 ┆ 12.0        │
│ Cyklostezka Náchod -> Velké  ┆ Náchod                       ┆ Ride          ┆ 3.006125                 ┆ 12.0        │
│ Poříčí                       ┆                              ┆               ┆                          ┆             │
│ Tuhnice most-Drahovice       ┆ Karlovy Vary                 ┆ Ride          ┆ 2.155936                 ┆ 12.0        │
│ most,stezka                  ┆                              ┆               ┆                          ┆             │
│ Výstup na Klínovec           ┆ null                         ┆ Ride          ┆ 0.808138                 ┆ 11.0        │
│ MH - Klaster                 ┆ Klášter Hradiště nad Jizerou ┆ Ride          ┆ 1.227082                 ┆ 11.0        │
│ Interval                     ┆ Olomouc                      ┆ Run           ┆ 0.822266                 ┆ 11.0        │
│ Z Lednice po silnici k       ┆ Lednice                      ┆ Ride          ┆ 1.255294                 ┆ 10.0        │
│ odbocce na Janohrad          ┆                              ┆               ┆                          ┆             │
│ Chrudim climb                ┆ Chrudim                      ┆ Ride          ┆ 0.838854                 ┆ 10.0        │
│ Šárka Valley (short)         ┆ Praha                        ┆ Run           ┆ 0.82043                  ┆ 10.0        │
│ LS - Park Boost              ┆ Bruntál                      ┆ Run           ┆ 0.356353                 ┆ 10.0        │
│ Klobouky Viadukt             ┆ Valašské Klobouky            ┆ Ride          ┆ 0.98949                  ┆ 10.0        │
│ Park 1                       ┆ Ostrava                      ┆ Run           ┆ 0.699398                 ┆ 10.0        │
│ Tři prameny - Pravčická      ┆ Hřensko                      ┆ Hike          ┆ 0.71009                  ┆ 10.0        │
│ brána                        ┆                              ┆               ┆                          ┆             │
│ Rovinka Beranov              ┆ Malý Beranov                 ┆ Ride          ┆ 0.841521                 ┆ 10.0        │
│ Do sedla Klínovce po silnici ┆ Loučná pod Klínovcem         ┆ Ride          ┆ 2.318996                 ┆ 9.0         │
│ most - Loket                 ┆ Staré Sedlo                  ┆ Ride          ┆ 2.137918                 ┆ 9.0         │
│ Daskabát flat                ┆ Velký Újezd                  ┆ Ride          ┆ 1.853476                 ┆ 9.0         │
│ Dom Śląski Up Hill           ┆ Pec pod Sněžkou              ┆ Hike          ┆ 1.811384                 ┆ 9.0         │
│ Vlevo dole jezero Most       ┆ Most                         ┆ Ride          ┆ 3.698485                 ┆ 9.0         │
│ Solan last km                ┆ Hutisko-Solanec              ┆ Ride          ┆ 0.855722                 ┆ 8.0         │
│ Bunč climb                   ┆ Kostelany                    ┆ Ride          ┆ 1.459622                 ┆ 8.0         │
└──────────────────────────────┴──────────────────────────────┴───────────────┴──────────────────────────┴─────────────┘

### Finální seznam: běh

In [22]:
celorepublika = zebricek.filter(
    (pl.col('activity_type') == 'Run') & (pl.col('start_to_finish_distance') > 0.5)
).unique(
    subset='city',keep='first'
).sort(
    by='effort_diff',descending=True
).head(
    20
)

print(celorepublika)

celorepublika = celorepublika.select(pl.col('name')).to_series().to_list()

with open("data/behani_top_20.yaml", "w", encoding="utf-8") as f:
    yaml.dump(celorepublika, f, allow_unicode=True, default_flow_style=False)

shape: (20, 5)
┌───────────────────────────────────┬─────────────────────────┬───────────────┬──────────────────────────┬─────────────┐
│ name                              ┆ city                    ┆ activity_type ┆ start_to_finish_distance ┆ effort_diff │
│ ---                               ┆ ---                     ┆ ---           ┆ ---                      ┆ ---         │
│ str                               ┆ str                     ┆ str           ┆ f64                      ┆ f64         │
╞═══════════════════════════════════╪═════════════════════════╪═══════════════╪══════════════════════════╪═════════════╡
│ tenis 1K                          ┆ Brno                    ┆ Run           ┆ 0.951894                 ┆ 45.0        │
│ Smetanovy reverse                 ┆ Olomouc                 ┆ Run           ┆ 0.631364                 ┆ 41.0        │
│ Hvězda flat                       ┆ Praha                   ┆ Run           ┆ 0.995211                 ┆ 33.0        │
│ Stezka nábřeží                    ┆ Zlín                    ┆ Run           ┆ 0.577385                 ┆ 22.0        │
│ stezka                            ┆ České Budějovice        ┆ Run           ┆ 0.891633                 ┆ 17.0        │
│ Hradní lávka => Sýkorův most      ┆ Ostrava                 ┆ Run           ┆ 0.958195                 ┆ 14.0        │
│ mezi mosty                        ┆ Pardubice               ┆ Run           ┆ 0.894894                 ┆ 13.0        │
│ Panelovka-Tichá 800m              ┆ Mostkovice              ┆ Run           ┆ 0.728498                 ┆ 8.0         │
│ Ku řopíku                         ┆ Děčín                   ┆ Run           ┆ 0.772301                 ┆ 7.0         │
│ Od Sanusu ke gymplu               ┆ Hradec Králové          ┆ Run           ┆ 0.546075                 ┆ 7.0         │
│ Lípy (směrem do Jičína)           ┆ Jičín                   ┆ Run           ┆ 1.710386                 ┆ 7.0         │
│ od hráze až na konec přehrady -   ┆ Liberec                 ┆ Run           ┆ 0.85032                  ┆ 6.0         │
│ silnice                           ┆                         ┆               ┆                          ┆             │
│ Tuhnická lávka -Chebský most      ┆ Karlovy Vary            ┆ Run           ┆ 1.053672                 ┆ 5.0         │
│ U Jordánu do kopce                ┆ Tábor                   ┆ Run           ┆ 0.759626                 ┆ 5.0         │
│ Nábřeží                           ┆ Kadaň                   ┆ Run           ┆ 1.209947                 ┆ 5.0         │
│ Dlouhá míle                       ┆ Sušice                  ┆ Run           ┆ 1.251162                 ┆ 4.0         │
│ po cyklostezce                    ┆ Humpolec                ┆ Run           ┆ 0.529263                 ┆ 4.0         │
│ Ciclo Via BNL -> K                ┆ Brandýs nad Labem-Stará ┆ Run           ┆ 1.022516                 ┆ 4.0         │
│                                   ┆ Boleslav                ┆               ┆                          ┆             │
│ Kuželna - Splav 800m              ┆ Vsetín                  ┆ Run           ┆ 0.802088                 ┆ 4.0         │
│ BK-nabrezi                        ┆ Blansko                 ┆ Run           ┆ 0.940444                 ┆ 4.0         │
└───────────────────────────────────┴─────────────────────────┴───────────────┴──────────────────────────┴─────────────┘

### Finální seznam: kolo

In [24]:
celorepublika_kolo = zebricek.filter(
    (pl.col('activity_type') == 'Ride') & (pl.col('start_to_finish_distance') > 1)
).unique(
    subset='city',keep='first'
).sort(
    by='effort_diff',descending=True
).head(
    20
)

print(celorepublika_kolo)

celorepublika_kolo = celorepublika_kolo.select(pl.col('name')).to_series().to_list()

with open("data/kolo_top_20.yaml", "w", encoding="utf-8") as f:
    yaml.dump(celorepublika_kolo, f, allow_unicode=True, default_flow_style=False)

shape: (20, 5)
┌──────────────────────────────────┬──────────────────────────┬───────────────┬──────────────────────────┬─────────────┐
│ name                             ┆ city                     ┆ activity_type ┆ start_to_finish_distance ┆ effort_diff │
│ ---                              ┆ ---                      ┆ ---           ┆ ---                      ┆ ---         │
│ str                              ┆ str                      ┆ str           ┆ f64                      ┆ f64         │
╞══════════════════════════════════╪══════════════════════════╪═══════════════╪══════════════════════════╪═════════════╡
│ Opičí Časovka, Podolská vodárna  ┆ Praha                    ┆ Ride          ┆ 1.379737                 ┆ 210.0       │
│ - Dvorce                         ┆                          ┆               ┆                          ┆             │
│ Zbraslav - Komořany              ┆ Zbraslav                 ┆ Ride          ┆ 2.258969                 ┆ 151.0       │
│ time trial at Svratka            ┆ Brno                     ┆ Ride          ┆ 1.300465                 ┆ 92.0        │
│ Stezka do Zlina                  ┆ Zlin                     ┆ Ride          ┆ 1.265858                 ┆ 51.0        │
│ Židlochovice -> Olympia          ┆ Židlochovice             ┆ Ride          ┆ 9.643392                 ┆ 32.0        │
│ Srbsko - Hlásná Třebáň           ┆ Srbsko                   ┆ Ride          ┆ 4.557374                 ┆ 29.0        │
│ Muglinovská→Hradní lávka (po     ┆ Ostrava                  ┆ Ride          ┆ 2.660781                 ┆ 28.0        │
│ pravém břehu)                    ┆                          ┆               ┆                          ┆             │
│ Revnicak Eve                     ┆ Řevnice                  ┆ Ride          ┆ 3.429182                 ┆ 28.0        │
│ Novomlýnská 5:                   ┆ Dolní Věstonice          ┆ Ride          ┆ 1.215091                 ┆ 24.0        │
│ Věstonice-Strachotín             ┆                          ┆               ┆                          ┆             │
│ svadov—valtirov                  ┆ Ústí nad Labem-Neštěmice ┆ Ride          ┆ 2.730017                 ┆ 20.0        │
│ Jiráskovo nábřeží k Husovce      ┆ České Budějovice         ┆ Ride          ┆ 1.009863                 ┆ 19.0        │
│ Nová cyklostezka do Bosche  2    ┆ Jihlava                  ┆ Ride          ┆ 2.439248                 ┆ 18.0        │
│ Cyklostezka sprint směr Děčín    ┆ Hřensko                  ┆ Ride          ┆ 1.000775                 ┆ 18.0        │
│ Maslovice - Kralupy              ┆ Máslovice                ┆ Ride          ┆ 4.687004                 ┆ 18.0        │
│ Adamaov climb                    ┆ Adamov                   ┆ Ride          ┆ 1.192579                 ┆ 17.0        │
│ Sprintík křižovatka/skalní mlýn  ┆ Blansko                  ┆ Ride          ┆ 2.099472                 ┆ 17.0        │
│ Trinec-Tesin                     ┆ Třinec                   ┆ Ride          ┆ 4.360789                 ┆ 16.0        │
│ Szpic Jested  last 3 km ( od     ┆ Liberec                  ┆ Ride          ┆ 1.348759                 ┆ 16.0        │
│ rozc na Dub)                     ┆                          ┆               ┆                          ┆             │
│ Mutěnka - z Kyjova po odbočku na ┆ Kyjov                    ┆ Ride          ┆ 3.458919                 ┆ 15.0        │
│ hraběcí                          ┆                          ┆               ┆                          ┆             │
│ Lysá hora - 5 km                 ┆ Staré Hamry              ┆ Ride          ┆ 3.229545                 ┆ 15.0        │
└──────────────────────────────────┴──────────────────────────┴───────────────┴──────────────────────────┴─────────────┘

In [25]:
celorepublika_kolo_30 = zebricek.filter(
    (pl.col('activity_type') == 'Ride') & (pl.col('start_to_finish_distance') > 1)
).unique(
    subset='city',keep='first'
).sort(
    by='effort_diff',descending=True
).head(
    30
)

print(celorepublika_kolo_30)

celorepublika_kolo_30 = celorepublika_kolo_30.select(pl.col('name')).to_series().to_list()

with open("data/kolo_top_30.yaml", "w", encoding="utf-8") as f:
    yaml.dump(celorepublika_kolo_30, f, allow_unicode=True, default_flow_style=False)

shape: (30, 5)
┌──────────────────────────────┬──────────────────────────────┬───────────────┬──────────────────────────┬─────────────┐
│ name                         ┆ city                         ┆ activity_type ┆ start_to_finish_distance ┆ effort_diff │
│ ---                          ┆ ---                          ┆ ---           ┆ ---                      ┆ ---         │
│ str                          ┆ str                          ┆ str           ┆ f64                      ┆ f64         │
╞══════════════════════════════╪══════════════════════════════╪═══════════════╪══════════════════════════╪═════════════╡
│ Opičí Časovka, Podolská      ┆ Praha                        ┆ Ride          ┆ 1.379737                 ┆ 210.0       │
│ vodárna - Dvorce             ┆                              ┆               ┆                          ┆             │
│ Zbraslav - Komořany          ┆ Zbraslav                     ┆ Ride          ┆ 2.258969                 ┆ 151.0       │
│ time trial at Svratka        ┆ Brno                         ┆ Ride          ┆ 1.300465                 ┆ 92.0        │
│ Stezka do Zlina              ┆ Zlin                         ┆ Ride          ┆ 1.265858                 ┆ 51.0        │
│ Židlochovice -> Olympia      ┆ Židlochovice                 ┆ Ride          ┆ 9.643392                 ┆ 32.0        │
│ Srbsko - Hlásná Třebáň       ┆ Srbsko                       ┆ Ride          ┆ 4.557374                 ┆ 29.0        │
│ Revnicak Eve                 ┆ Řevnice                      ┆ Ride          ┆ 3.429182                 ┆ 28.0        │
│ Muglinovská→Hradní lávka (po ┆ Ostrava                      ┆ Ride          ┆ 2.660781                 ┆ 28.0        │
│ pravém břehu)                ┆                              ┆               ┆                          ┆             │
│ Novomlýnská 5:               ┆ Dolní Věstonice              ┆ Ride          ┆ 1.215091                 ┆ 24.0        │
│ Věstonice-Strachotín         ┆                              ┆               ┆                          ┆             │
│ svadov—valtirov              ┆ Ústí nad Labem-Neštěmice     ┆ Ride          ┆ 2.730017                 ┆ 20.0        │
│ Jiráskovo nábřeží k Husovce  ┆ České Budějovice             ┆ Ride          ┆ 1.009863                 ┆ 19.0        │
│ Maslovice - Kralupy          ┆ Máslovice                    ┆ Ride          ┆ 4.687004                 ┆ 18.0        │
│ Cyklostezka sprint směr      ┆ Hřensko                      ┆ Ride          ┆ 1.000775                 ┆ 18.0        │
│ Děčín                        ┆                              ┆               ┆                          ┆             │
│ Nová cyklostezka do Bosche   ┆ Jihlava                      ┆ Ride          ┆ 2.439248                 ┆ 18.0        │
│ 2                            ┆                              ┆               ┆                          ┆             │
│ Sprintík křižovatka/skalní   ┆ Blansko                      ┆ Ride          ┆ 2.099472                 ┆ 17.0        │
│ mlýn                         ┆                              ┆               ┆                          ┆             │
│ Adamaov climb                ┆ Adamov                       ┆ Ride          ┆ 1.192579                 ┆ 17.0        │
│ Szpic Jested  last 3 km ( od ┆ Liberec                      ┆ Ride          ┆ 1.348759                 ┆ 16.0        │
│ rozc na Dub)                 ┆                              ┆               ┆                          ┆             │
│ Trinec-Tesin                 ┆ Třinec                       ┆ Ride          ┆ 4.360789                 ┆ 16.0        │
│ Lysá hora - 5 km             ┆ Staré Hamry                  ┆ Ride          ┆ 3.229545                 ┆ 15.0        │
│ Mutěnka - z Kyjova po        ┆ Kyjov                        ┆ Ride          ┆ 3.458919                 ┆ 15.0        │
│ odbočku na hraběcí           ┆                              ┆               ┆                          ┆             │
│ Údolí Svatý Jan              ┆ Beroun                       ┆ Ride          ┆ 3.618147                 ┆ 14.0        │
│ Decin - Bad Schandau Abzweig ┆ Děčín                        ┆ Ride          ┆ 14.292023                ┆ 14.0        │
│ Radwg                        ┆                              ┆               ┆                          ┆             │
│ Papezov - Prazmo             ┆ Krásná                       ┆ Ride          ┆ 6.992833                 ┆ 13.0        │
│ Podle Radbuzy                ┆ Pilsen                       ┆ Ride          ┆ 1.806575                 ┆ 13.0        │
│ Sedmička, Lipno {            ┆ Přední Výtoň                 ┆ Ride          ┆ 3.651891                 ┆ 13.0        │
│ Eurovie - nadjezd Rosice     ┆ Pardubice II                 ┆ Ride          ┆ 1.294441                 ┆ 13.0        │
│ Tuhnice most-Drahovice       ┆ Karlovy Vary                 ┆ Ride          ┆ 2.155936                 ┆ 12.0        │
│ most,stezka                  ┆                              ┆               ┆                          ┆             │
│ Cyklostezka Náchod -> Velké  ┆ Náchod                       ┆ Ride          ┆ 3.006125                 ┆ 12.0        │
│ Poříčí                       ┆                              ┆               ┆                          ┆             │
│ MH - Klaster                 ┆ Klášter Hradiště nad Jizerou ┆ Ride          ┆ 1.227082                 ┆ 11.0        │
│ Z Lednice po silnici k       ┆ Lednice                      ┆ Ride          ┆ 1.255294                 ┆ 10.0        │
│ odbocce na Janohrad          ┆                              ┆               ┆                          ┆             │
└──────────────────────────────┴──────────────────────────────┴───────────────┴──────────────────────────┴─────────────┘

### Finální seznam: běžecké ovály

In [27]:
ovaly = df.filter(
    (pl.col('country') == 'Czechia') & (pl.col('activity_type') == 'Run') & (pl.col('start_to_finish_distance') <= 0.02) & (pl.col('distance') < 450)
).group_by(
    ["name","start_to_finish_distance","distance"]
).agg(
    pl.col('effort_diff').mean()
).sort(
    by='effort_diff',descending=True
).filter(
    pl.col('effort_diff') > 7
)

print(ovaly)

ovaly = ovaly.select(pl.col('name')).to_series().to_list()

with open("data/ovaly.yaml", "w", encoding="utf-8") as f:
    yaml.dump(ovaly, f, allow_unicode=True, default_flow_style=False)

shape: (20, 4)
┌──────────────────────────────────────┬──────────────────────────┬──────────┬─────────────┐
│ name                                 ┆ start_to_finish_distance ┆ distance ┆ effort_diff │
│ ---                                  ┆ ---                      ┆ ---      ┆ ---         │
│ str                                  ┆ f64                      ┆ f64      ┆ f64         │
╞══════════════════════════════════════╪══════════════════════════╪══════════╪═════════════╡
│ Stadion Na Děkance                   ┆ 0.006087                 ┆ 420.9    ┆ 102.817308  │
│ VUT horní dráha 400m                 ┆ 0.011266                 ┆ 405.2    ┆ 98.302158   │
│ Pražačka 320                         ┆ 0.000925                 ┆ 343.3    ┆ 92.048077   │
│ TJ Sokol okruh                       ┆ 0.009342                 ┆ 418.8    ┆ 46.183771   │
│ 400m-Liberec                         ┆ 0.014369                 ┆ 408.0    ┆ 42.264851   │
│ Strahovská dráha                     ┆ 0.001716                 ┆ 413.7    ┆ 39.402469   │
│ Tyršák čtyřstofka                    ┆ 0.002828                 ┆ 426.5    ┆ 21.935096   │
│ 400 m - atletický okruh - Lokomotiva ┆ 0.003459                 ┆ 400.0    ┆ 21.194245   │
│ Juliska 400 m                        ┆ 0.00286                  ┆ 410.1    ┆ 20.422062   │
│ 400m                                 ┆ 0.003456                 ┆ 414.7    ┆ 19.863636   │
│ Lužánky - Plochá dráha               ┆ 0.001678                 ┆ 411.9    ┆ 18.928058   │
│ Ovál ZŠ Štefánikova                  ┆ 0.004506                 ┆ 269.6    ┆ 17.788969   │
│ 400m - Sportovní areál Na Stoupách   ┆ 0.007687                 ┆ 394.1    ┆ 16.232614   │
│ Mestsky stadion Trutnov              ┆ 0.001844                 ┆ 406.4    ┆ 13.915842   │
│ 400 m (track num. 2)                 ┆ 0.015573                 ┆ 406.8    ┆ 13.659472   │
│ TJ Znojmo Lap                        ┆ 0.003705                 ┆ 404.6    ┆ 13.551807   │
│ Tatran Třemošná                      ┆ 0.002124                 ┆ 421.5    ┆ 12.021583   │
│ Stadion Čelákovice 400m (II.)        ┆ 0.006626                 ┆ 403.4    ┆ 10.968825   │
│ 400m-Jičín                           ┆ 0.001068                 ┆ 401.7    ┆ 10.516827   │
│ Hradiště - čtyřstovka                ┆ 0.006289                 ┆ 437.7    ┆ 7.562201    │
└──────────────────────────────────────┴──────────────────────────┴──────────┴─────────────┘

### Finální seznam: cyklosegmenty nad 1000 m. n. m.

In [29]:
nad1000 = df.filter(
    (pl.col("activity_type") == "Ride") & (pl.col('country') == 'Czechia')
).group_by(
    "name"
).agg(
    pl.col("elevation_high").max(),
    pl.col("effort_diff").mean()
).sort(
    by="elevation_high",descending=True
).filter(
    pl.col('effort_diff') > 2
).filter(
    pl.col('elevation_high') >= 1000
)

print(nad1000)

nad1000 = nad1000.select(pl.col('name')).to_series().to_list()

with open("data/nad_1000_mnm.yaml", "w", encoding="utf-8") as f:
    yaml.dump(nad1000, f, allow_unicode=True, default_flow_style=False)

shape: (10, 3)
┌────────────────────────────────────────────────────┬────────────────┬─────────────┐
│ name                                               ┆ elevation_high ┆ effort_diff │
│ ---                                                ┆ ---            ┆ ---         │
│ str                                                ┆ f64            ┆ f64         │
╞════════════════════════════════════════════════════╪════════════════╪═════════════╡
│ Sedýlko - Praděd climb                             ┆ 1487.0         ┆ 10.327014   │
│ Zlaťák konec - smrt                                ┆ 1383.2         ┆ 4.07381     │
│ Lysá hora - 5 km                                   ┆ 1308.5         ┆ 9.175772    │
│ Výstup na Klínovec                                 ┆ 1241.8         ┆ 6.59375     │
│ Klinovec Top                                       ┆ 1238.8         ┆ 8.57619     │
│ Špindlerovka - část II. (od Černýho potoka nahoru) ┆ 1194.4         ┆ 3.593301    │
│ Do sedla Klínovce po silnici                       ┆ 1175.7         ┆ 5.580952    │
│ Kvilda Bučina                                      ┆ 1165.4         ┆ 2.007143    │
│ Kleť k vysílači - finále                           ┆ 1063.4         ┆ 3.595238    │
│ Bečva - Pustevny Uphill                            ┆ 1010.3         ┆ 2.751185    │
└────────────────────────────────────────────────────┴────────────────┴─────────────┘